### ISSUE TITLE
Next button does not work

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1]
Start here: https://newsite.com/packages

Then next button `>>` links to

    https://newsite.com/packages?page=0

expected

    https://newsite.com/packages?page=2

When you navigate to `https://newsite.com/packages?page=0` the next button keeps linking to `page=0`

**Comment by mkustermann** [comment]
Should be fixed by #04e3330c308aff07db6598c4d0332139d8f7ff18
