### ISSUE TITLE
Flutter logo color is wrong

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#1004]
Something happened to the Flutter logo on the pub site, the colors aren't correct.

Please see this screenshot:

![screen shot 2018-02-20 at 2 40 34 pm](https://user-images.githubusercontent.com/5479/36453191-1511cc5c-164c-11e8-9400-4446e0d1dbcf.png)

To get the official logos and assets: https://github.com/flutter/identity-assets

Thank you!

**Comment by kevmoo** [comment]
The logo went through a designers tool set – wondering if some color correction defaults got applied as it went through the loop...

**Comment by sethladd** [comment]
Maybe! I wonder if we can get this fixed before next week.
