### ISSUE TITLE
browser package is listed as a top flutter package

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#1009]
The browser package has nothing to do with Flutter. Can we remove it from the list of top Flutter packages?

Thanks!

**Comment by isoos** [comment]
@sethladd: I'm not sure: where do you see the `browser` package in the Flutter listings?

**Comment by sethladd** [comment]
Sorry, I forgot the link.

Here it is: https://pub.dartlang.org/flutter/packages?sort=popularity

**Comment by isoos** [comment]
We have two modes of 'flutter packages' (see the bottom of the [Flutter landing page](https://pub.dartlang.org/flutter)):
- [More Flutter packages...](https://pub.dartlang.org/flutter/packages) goes to "packages that you can use in Flutter apps (an may be other apps too)"
- [Flutter-specific packages...](https://pub.dartlang.org/packages?q=dependency%3Aflutter) goes to the "packages that depend on Flutter and can be used in Flutter-apps only".

If you look at the list in the later, it has no `browser` package (in any sort mode). Whether and how we should expose the later is a great question, but both modes are valid and should be supported.

**Comment by sethladd** [comment]
Thanks for the additional info.

In both of those lists "more flutter packages" and "flutter-specific packages", browser shouldn't belong.

browser is not a package that is useful or can be used by, in, or with a Flutter app.

I'm open to how to fix this, but the "bug" here is: "browser says it's related to Flutter, but it's not"

**Comment by isoos** [comment]
Ah, ok, the `browser` package is categorized as running everywhere, including Flutter. We have a whitelist for platform overrides, I can add this to that list and it will be web-only.

**Comment by sethladd** [comment]
Thanks!

Can a package author specify the whitelisting? If so, we can have the browser package specify "only for web". We control that package.

**Comment by isoos** [comment]
We haven't concluded on a mechanism to specify this by the package author, only doing it on the pub site. If there are similar packages, open an issue, it is easy to add the override.

**Comment by sethladd** [comment]
Thanks for the update!
