### ISSUE TITLE
Smart SEO for discontinued packages

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1011]
- [ ] Don't include them in the sitemap
- [ ] Consider excluding them robots.txt

**Comment by mit-mit** [comment]
cc @isoos @jakobr-google WDYT?

**Comment by isoos** [comment]
- Sitemap is easy (#1013 out for review).
- robots.txt is a bit tricky. If other pages link to it, it may still show up in search results. Instead, I'd rather use the `noindex` [meta header](https://support.google.com/webmasters/answer/93710?hl=en)

**Comment by kevmoo** [comment]
`noindex` SGTM – we want robots.txt to be fast.
