### ISSUE TITLE
[video_player] Video is not visible - but sound works

### ISSUE THREAD

**Issue by CrazyStaff** [dart-lang/pub-dartlang-dart#1022]
URL: https://pub.dartlang.org/packages/video_player

I have the issue that the video is not visible. However i can hear the sound.
Perhaps the height is zero? This video is running and also visible on my smartphone HTC 10, 
but when I use the android simulator with different sizes it doesnt work - only the sound is working.
I tested the simulator with different Android SDK 7.0 and less.

**Here is the log file** 
I dont know what the info warning means. 

D/NetworkSecurityConfig( 9393): No Network Security Config specified, using platform default
D/MediaPlayer( 9393): setSubtitleAnchor in MediaPlayer
D/MediaPlayer( 9393): setSubtitleAnchor in MediaPlayer
I/flutter ( 9393): height: 360.0 ## own test about height of video
I/flutter ( 9393): height: 360.0 ## own test about height of video
W/MediaPlayer( 9393): **info/warning (703, 0)**
W/MediaPlayer( 9393): info/warning (701, 0)
W/MediaPlayer( 9393): info/warning (703, 0)
W/MediaPlayer( 9393): info/warning (702, 0)
W/MediaPlayer( 9393): info/warning (703, 0)
W/MediaPlayer( 9393): info/warning (701, 0)
D/        ( 9393): HostConnection::get() New Host Connection established 0x8c770f00, tid 9487
W/MediaPlayer( 9393): info/warning (703, 0)
W/MediaPlayer( 9393): info/warning (702, 0)

**Comment by jakobr-google** [comment]
This repo is for the pub site itself. Please file issues with packages on the package's repo - in this case, flutter/plugins. I'll move this one.

**Comment by jakobr-google** [comment]
This issue was moved to flutter/flutter#14880
