### ISSUE TITLE
[analysis] outdated SDK used for scoring

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/pub-dartlang-dart#1027]
URL: https://pub.dartlang.org/packages/rxdart#-analysis-tab-

The pub scoring tool still runs on sdk 2.0.0-dev20
This is giving us a low score due to a compilation error.

Can you please update the tool?
Also, do I need to retrigger the scoring somehow after it is updated?

**Comment by isoos** [comment]
We are planning to release a new version with a newer SDK soon. Do you have any requirement for the minimal version?

**Comment by ypelud** [comment]
I thin k I have the same issue here ( https://pub.dartlang.org/packages/menu_swipe_helpers#-analysis-tab- ) and many packages with Flutter dependencies.  
May be sdk 2.0.0-dev23 will be a good start.

**Comment by frankpepermans** [comment]
@isoos Following the Flutter SDK version is good enough for me (which is the main reason that our lib was updated anyway, to keep being compatible with the Flutter latest)

**Comment by isoos** [comment]
These have been fixed in the latest release.
