### ISSUE TITLE
Sync to dartdoc 0.17.0 – SDK -dev.32

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1032]
...when it's published: https://github.com/dart-lang/dartdoc/pull/1616

the strong mode changes are awesome...

**Comment by isoos** [comment]
Auxiliary: We now rely on the `dartdoc` provided by the SDK. At minimum we'll need to switch to depend on it as package and runt `pub run dartdoc`.

**Comment by kevmoo** [comment]
In the short term, it'll be easier to just use what's in the SDK.

The update landed here: https://github.com/dart-lang/sdk/commit/7df5055b0679748e9800f73defb9ef3ff61ad3d9

Since we've already branched for -dev.31, this will almost certainly land in -dev.32

If ya'll end up looking at https://github.com/dart-lang/pub-dartlang-dart/issues/871 (which I think would rock) we'd have to look depending on the package directly – but that can wait.

**Comment by kevmoo** [comment]
FYI @isoos – the dev release w/ these updates has landed

**Comment by jakobr-google** [comment]
Fixed in #1062.
