### ISSUE TITLE
Analysis tab failure for flutter package

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/pub-dartlang-dart#1040]
Since yesterday, I notice my package remained in an `AWAITING` state

URL: https://pub.dartlang.org/packages/sqflite#-analysis-tab-

```
Detected platforms: unsure
Error(s) prevent platform classification.
E
RR: Invalid argument(s): Minimum version ("2.0.0-dev.23.0") must be less than maximum ("2.0.0-dev.16.0").
ERR: package:pub_semver/src/version_range.dart 59         new VersionRange
```

It seems to happen to many other packages (mainly flutter ones): 
* https://pub.dartlang.org/packages/flutter_cache_manager#-analysis-tab-
* https://pub.dartlang.org/packages/sqflite#-analysis-tab-
* https://pub.dartlang.org/packages/async#-analysis-tab-

**Comment by isoos** [comment]
Thanks for reporting! We are planning to release a new version soon with an updated SDK, and that should fix these issues.

**Comment by mit-mit** [comment]
@isoos separate from the roll-out resolving this systemic issue, why is the label for this case `AWAITING `? Shouldn't it be `FAILING` ?

**Comment by isoos** [comment]
It should be `[unidentified]` (which we can rename to failing, as they are semantically the same), I'm not sure why it is not like that.

**Comment by isoos** [comment]
This was fixed in the latest release.

**Comment by rajeshzmoke** [comment]
<img width="695" alt="screenshot 2018-10-26 at 2 03 51 am" src="https://user-images.githubusercontent.com/30038668/47528691-781a1e00-d8c3-11e8-94b6-459c1083fdcf.png">

my flutter package is unidentified
[flutter_date_picker](https://pub.dartlang.org/packages/flutter_date_picker)

how do i fix this?

**Comment by isoos** [comment]
@rajeshzmoke: this is tracked on #1728
