### ISSUE TITLE
How to re-authorize?

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/pub-dartlang-dart#1048]
During publish, pub asked me to authorize, but I accidentally selected a wrong email. Now publish is failing with "UnauthorizedAccess: ..." error. How can I re-authorize with the correct email?

I tried to add the email which I used to authorize as an uploader, but it failed with "unauthorized request'

**Comment by kzhdev** [comment]
Figured out remove ~/.pub-cache/credentials.json did the trick.

**Comment by jakobr-google** [comment]
Still a relevant issue - users shouldn't have to figure out some obscure file to delete to fix this problem.

It's on the pub client side, though. If we fix dart-lang/pub#1471, this use-case would be covered too.
