### ISSUE TITLE
Add Package.discontinuedMessage

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1055]
Why: let authors (or site maintainers) provide "Use this instead..." messaging without pushing a new version.

Then map `isDiscontinued` => `discontinuedMessage != null`

If there is no message, just store empty string...or something.

https://github.com/dart-lang/pub-dartlang-dart/blob/a5a1c03ab71ed70ae1dd3e859de38009a9215748/app/lib/frontend/models.dart#L53

**Comment by kevmoo** [comment]
CC @mit-mit

**Comment by mit-mit** [comment]
For now the recommendation is to update pubspec.yaml
