### ISSUE TITLE
Hi, I've got a problem with flutter_charts package! The chart's graphics can't be shown!

### ISSUE THREAD

**Issue by YugeCse** [dart-lang/pub-dartlang-dart#1059]
URL: https://pub.flutter-io.cn/packages/flutter_charts#-analysis-tab-

I write some code with flutter_charts, but the charts can't show in the mobile's UI. Would you pleause tell me how I can solve the problem? Thank You!
Then, next is my code.

import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter_charts/flutter_charts.dart';

class HeloPage extends StatefulWidget {

  @override
  State createState() => new _HeloPageState();

}

class _HeloPageState extends State<HeloPage> {

  ChartData _chartData;
  LineChartOptions _lineChartOptions;

  _HeloPageState();

  void _defineOptionsAndData() {
    _lineChartOptions = new LineChartOptions();
    _chartData = new RandomChartData(useUserProvidedYLabels: _lineChartOptions.useUserProvidedYLabels);
    _chartData.assignDataRowsDefaultColors();
  }

  @override
  Widget build(BuildContext context) {
    _defineOptionsAndData();
    MediaQueryData mediaQueryData = MediaQuery.of(context);
    LineChart lineChart = new LineChart(
      painter: new LineChartPainter(),
      layouter: new LineChartLayouter(
          chartArea: new ui.Size(
              mediaQueryData.size.width, mediaQueryData.size.height),
          chartData: _chartData,
          chartOptions: _lineChartOptions
      ),
    );
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Page 2'),
        centerTitle: true,
      ),
      body: new Column(
        children: <Widget>[
          new Text("This is page 2!"),
          lineChart,
        ],
      ),
    );
  }
}

**Comment by jakobr-google** [comment]
This is the issue tracker for the Pub server. We can't help with support for individual packages; you'll have to file an issue with the package itself.

See the package's 'homepage' link, which often points to its GitHub page where you can file the issue. In this case, here: https://github.com/mzimmerm/flutter_charts/
