### ISSUE TITLE
Remove 'feedback' link on Analysis tab

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/pub-dartlang-dart#1060]
A bunch of users seem to think it's for submitting feedback for the *package* that's being shown, instead of for the analysis feature.

cc @mit-mit

**Comment by isoos** [comment]
I'm not sure when we've deployed that analysis tab the first time, but it's online for more than two months at least, and those who cared would have seen it already.

On the other hand, the "Report an issue" link at the bottom of the page is the same, both follow the changes between tabs, and it is possible that users were clicking on the link in the footer.

How shall we change the label "More details: scoring."?

**Comment by jakobr-google** [comment]
True, I've seen issues from both the 'feedback' link, and the link at the bottom.

Maybe make it clearer that the bottom link is for issues with Pub, and remove the 'analysis feedback' link? (Hoping package authors are smart enough to find the link at the bottom if they have issues with the analysis...)
