### ISSUE TITLE
Ability to see number of packages failing analysis

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1073]
I would like page that shows the number of packages failing analysis. I'm thinking at least a daily update, and the ability to see last seven days.

The goal is to enable us to catch systemic analysis issues, as as the current issues on:
https://pub.dartlang.org/packages/url_launcher#-readme-tab-

```
Fix dependencies in pubspec.yaml.

Running flutter packages pub upgrade failed with the following output:

ERR: Invalid argument(s): Minimum version ("2.0.0-dev.23.0") must be less than maximum ("2.0.0-dev.16.0").
ERR: package:pub_semver/src/version_range.dart 59         new VersionRan
```

**Comment by isoos** [comment]
There are several reasons that old packages fail. If we are looking for alerting on mass-failures, I'd focus on two groups:
- packages that have new version published in the past X months (X = 6?)
- packages that are in the top N-th percentile wrt. popularity (N = 80?)

For the reporting part, I'm not yet sure if we can do this within the timeout limits of appengine (60 seconds to serve any request), but could start with a tool and refactor the code to a web page if it is fast enough.

**Comment by jakobr-google** [comment]
I think we just need to tighten up our logging, so we can easily grep for this. We should then be able to have Stackdriver generate the reports.

**Comment by isoos** [comment]
This may be lost in the noise of logging (e.g. we care much more of the analysis of the latest version than anything else, while the log may have much more failures). I'm putting together a small tool that will give us at least a minimal statistics.

**Comment by jakobr-google** [comment]
![Why don't we have both](http://i0.kym-cdn.com/photos/images/original/000/538/731/0fc.gif)

Having a tool to query this is a good idea, especially if it can provide a bit more insight.

Specifically for this, as you said, we're mostly interested in failures for the latest version of a package, so if we add a log line like:

```
Analysis failed for latest version of $package ($version): $error
```

then we can create a metric in Stackdriver, get a report showing the trends, and be alerted if we cross a set threshold. This should've alerted us to the issue @mit-mit is referring to.

Metrics for total number of analysis failures would also give us a clue if things go south.

**Comment by mit-mit** [comment]
Closing in favor of https://github.com/dart-lang/pub-dartlang-dart/issues/1122
