### ISSUE TITLE
Change the title: "Dart Packages"

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#108]
"Pub Package Manager" seems a weird title. We should have Dart right there – this is **the** site for Dart Packages.

Right?

**Comment by kevmoo** [comment]
...I'd like to discuss this a bit before running with it. Just brainstorming.

**Comment by isoos** [comment]
Related observations:
- Searching for "dart packages" gets https://pub.dartlang.org/packages as the first result, right before the domain root.
- Searching for "dart libraries" have many related results, but none of them is pub.dartlang.org on the first page (not sure if this is a concern, but I expected at least one first-page result).
- Search for "angular dart package" gets https://pub.dartlang.org/packages/angular as the first result, and presents angular2, Angular2_components, angular_ui... as they were sub-sections of it.
- The prior search has the page title: "angular 1.1.2+2 | Pub Package Manager - Dart Pub" - The "Pub" name is duplicated, and I'm not sure if it is beneficial to include the version there, e.g. "angular library | Pub - Dart Package Manager" could be better.

**Comment by mkustermann** [comment]
Should this issue closed, since https://github.com/isoos/pub-dartlang-dart/commit/1adda949cf75c0652d51e595b7b8468a881f41d7 has landed?
