### ISSUE TITLE
Forbid uploads of packages with homepage "example.com"

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1081]
URL: https://pub.dartlang.org/packages/json_api_document

Probably in a pubspec.yaml template somewhere?

**Comment by isoos** [comment]
Is this something that the pub client could warn/prevent as well? (Another thing that both projects should do with a shared validation?)

**Comment by kevmoo** [comment]
Agreed...

**Comment by isoos** [comment]
Further strange homepage examples:
- `...`
- `none`
- `later`
- `` (explicit empty string)
