### ISSUE TITLE
My package is not visible

### ISSUE THREAD

**Issue by zarub2k** [dart-lang/pub-dartlang-dart#1087]
URL: https://pub.dartlang.org/help#search

I published my sample package successfully and it is not visible in the pub.  See the output below from publish command,

Waiting for your authorization...
Authorization received, processing...
Successfully authorized.
Uploading...
Successfully uploaded package

Will take more time to be visible in the search?

**Comment by isoos** [comment]
@zarub2k what is the name of your package?
On the first publish, it may take a few minutes before it shows up in search.

**Comment by zarub2k** [comment]
@isoos Thanks for your confirmation. Now my package is visible in the search after some wait time :)

**Comment by electricMeterApp** [comment]
@zarub2k 
can you till me how many days take to see your first package

**Comment by StarTrooper08** [comment]
I'm facing the same problem!!
Is there any configuration we need to do?

**Comment by StarTrooper08** [comment]
https://pub.dev/packages/eos_icons_flutter
not showing in pub dev package even after searching

**Comment by isoos** [comment]
Please do not use old and closed issues, they are generally not monitored, and may be ignored.

@StarTrooper08: I've done a quick investigation, the package is in search, it shows up in the results, however, when you search for the package name, we don't give it enough priority. I've opened a new issue for that #6097.

**Comment by Blacktaler** [comment]
> @electricMeterApp: the package page should be available immediately, and the search index should pick it up in 15-30 minutes. do you have a package that takes longer?

Hi, my package is visible if it's searched through pub.dev, but I can't find it if I search it through google!
Does it require some time in order to be visible in google search? It has already been 7 days since I published the package

**Comment by isoos** [comment]
> Does it require some time in order to be visible in google search? It has already been 7 days since I published the package

Yes, it usually does take some time before it gets visible in Google search. Note: as an anti-spam measure, newly published packages won't get immediately exposed to Google for indexing (e.g. through sitemap or other metadata). After that, however, we have no influence when and how will Google search index or expose the package page.

**Comment by Blacktaler** [comment]
> > Does it require some time in order to be visible in google search? It has already been 7 days since I published the package
> 
> Yes, it usually does take some time before it gets visible in Google search. Note: as an anti-spam measure, newly published packages won't get immediately exposed to Google for indexing (e.g. through sitemap or other metadata). After that, however, we have no influence when and how will Google search index or expose the package page.

Okay, I got it, thanks.
