### ISSUE TITLE
Use <link rel=next> for search page, not <a href.. rel=next>

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1089]
Per https://support.google.com/webmasters/answer/1663744?hl=en

**Comment by isoos** [comment]
After https://github.com/dart-lang/pub-dartlang-dart/pull/1084 will get published we won't have the paginated pages in the search index, and this becomes irrelevant.

**Comment by isoos** [comment]
Closing this as ?page=2 and similar listing pages are now out of the google search index.
