### ISSUE TITLE
pub publish locally?

### ISSUE THREAD

**Issue by zarub2k** [dart-lang/pub-dartlang-dart#1090]
I am developing an Flutter plugin as a separate module which is being used in my Flutter application. Since both these projects are different, everytime I had to publish my package to the pub store and then I had to refer this my project.

Is there any possibility to publish locally and refer in my project? Once all my testing is done I can publish back to the global pub store. Is there any detailed document to have the best practice for pub package development?

**Comment by kevmoo** [comment]
See https://www.dartlang.org/tools/pub/dependencies#path-packages

Or you could push to GitHub and use git dependencies - https://www.dartlang.org/tools/pub/dependencies#git-packages

**Comment by zarub2k** [comment]
@kevmoo Thanks I missed this
