### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by GokulDharumar** [dart-lang/pub-dartlang-dart#1095]
URL: https://pub.dartlang.org/packages/flutter_webview_plugin
when i use PopupmenuButton with webviewscafold. the menus are not displayed on top of webview ... the webview kind of hides the menu

routes: {
        "/": (_) => new MyHomePage(title: "Flutter WebView Demo"),
        "/widget": (_) => new WebviewScaffold(
          url: selectedUrl,
          appBar: new AppBar(
            title: new Text("Test"),

            actions: <Widget>[
              new PopupMenuButton<Choice>( // overflow menu
                onSelected: _select,
                itemBuilder: (BuildContext context) {
                  return choices.skip(0).map((Choice choice) {
                    return new PopupMenuItem<Choice>(
                      value: choice,
                      child: new Icon(choice.icon),
                    );
                  }).toList();
                },
              ),

            ],
          ),

        )
      },

**Comment by isoos** [comment]
This issue was moved to dart-flitter/flutter_webview_plugin#44
