### ISSUE TITLE
Fatal package site error on opening Dart pub browse page

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pub-dartlang-dart#1098]
Opening https://pub.dartlang.org/packages

Fatal package site error
Please open an issue: https://github.com/dart-lang/pub-dartlang-dart/issues/new

Add these details to help us fix the issue:
Requested URL - https://pub.dartlang.org/packages
   Request ID - c3e05e15be80f435ef6bfc56a96a4940

**Comment by mit-mit** [comment]
Weird, works fine for me! Is it a consistent failure for you? Are others seeing it?

**Comment by mit-mit** [comment]
Cc @jakobr-google @isoos

**Comment by jakobr-google** [comment]
It was failing briefly due to issues with our search instances. Seems better now, so I’ll investigate further tomorrow.

**Comment by mit-mit** [comment]
Removing P0 as the site is back up. @jakobr-google did you investigate a bit what caused it?

**Comment by jakobr-google** [comment]
Our instances lost their connection to memcache, which led to an uncaught exception tearing down the isolates.

I have a fix in package:memcache, and will upgrade our dependency once it's published.
