### ISSUE TITLE
No package page for `flutter`

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1099]
I'm pretty sure https://pub.dartlang.org/packages/flutter used to serve the package page for the `flutter` package?

**Comment by mit-mit** [comment]
cc @isoos

**Comment by jakobr-google** [comment]
It did, but as requested in your email of 2/19, we’re now redirecting to flutter.io for that package instead, since Flutter isn’t using it.

**Comment by mit-mit** [comment]
Thanks for helping me remember my own actions :-)

The transition is a bit abrupt and unexpected. How about we redirect to https://pub.dartlang.org/flutter/ instead?

**Comment by jakobr-google** [comment]
:)

Sure, we can do that.
