### ISSUE TITLE
Code coloring not in the new version

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#11]
Pretty colors here: https://dartlang-pub.appspot.com/packages/path

:smile_cat: 

![screen shot 2015-04-22 at 12 58 38 pm](https://cloud.githubusercontent.com/assets/17034/7284004/56b1a390-e8ef-11e4-9f6e-16ebbaabfc05.png)

No pretty colors here: https://buildbot-dart-2015-04-22-dot-dartlang-pub.appspot.com/packages/path

:crying_cat_face: 

![screen shot 2015-04-22 at 12 59 11 pm](https://cloud.githubusercontent.com/assets/17034/7284014/6595ff0a-e8ef-11e4-85d0-1646eca505cd.png)

**Comment by sgjesse** [comment]
The syntax highlighting in the Python version is provided through the support for [Pygments](http://pygments.org/) in the Python markdown library.

Currently the Dart markdown package have no such thing.

**Comment by mkustermann** [comment]
Possible solutions:
- accept the worse display
- call pygments via an external process and cache the result
- make a "dart-plugin" to `package:mustache` which uses analyzer/... for coloring.

**Comment by mkustermann** [comment]
We went for option number 3.

**Comment by kevmoo** [comment]
:metal: awesome!
