### ISSUE TITLE
Catch all unhandled exceptions to prevent the entire service going down

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1101]
Follow-up to https://github.com/dart-lang/pub-dartlang-dart/issues/1098
- [x] frontend
- [x] analyzer
- [x] search
- [x] dartdoc

**Comment by isoos** [comment]
With #1148, the following parts are inside isolates that are automatically restarted on uncaught exceptions (after a 1-minute delay):
- `analyzer`'s job processing
- `search` (both the indexing and http serving)
- `dartdoc`'s job processing

1. Shall we put all the other http serving parts (`frontend`, `analyzer`, `dartdoc`) in a separate, restartable isolate?
2. How much delay should we use for http-serving isolate restarts (if at all)?

I think restartable isolates could provide a good catch-all handler, and if there is too many of them (e.g. 3+ in a minute), we could just abort/exit the DartVM and let AppEngine do its thing. WDYT @jakobr-google ?

**Comment by jakobr-google** [comment]
Running the http handlers in a separate isolate from the job runners sgtm. I don't think I'd put a delay on restarting the http handler isolate, at least not the first time - but maybe limit it to 1 restart per 10-20 seconds? And then abort completely on too many failures.

**Comment by isoos** [comment]
I was checking `package:isolate` if it can help us, but I don't think it is a good match for our use-case. Pinging @kevmoo as he contributed to that package to confirm that it is more for running short-lived tasks through a "main" controller than our "managed process" case.

**Comment by isoos** [comment]
Reopening, because local development didn't show frontend isolate error, and it was confusing what is happening.
