### ISSUE TITLE
Graceful service degradation

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1102]
We don't cache the results from search service, but we could introduce a network-first caching strategy for it:
- we query the service the same way as now
- we store the result in memcache (TTL = 1 hour)
- when the service is down, we fall back to the cached results

This would not have prevented https://github.com/dart-lang/pub-dartlang-dart/issues/1098 because its original cause was a memcache issue, but could be helpful in other cases, for short outages.

**Comment by jakobr-google** [comment]
We do need some kind of graceful degradation when search is down. At least show the static pages, and maybe a little "pub isn't feeling well" box where the top packages should be, if we can't reach search and memcache.

**Comment by isoos** [comment]
After the handler refactoring (with all the wrappers), if e.g. `search` is down and `SearchClient` throws an exception, we'd get something like this:

<img width="645" alt="screen shot 2018-04-12 at 14 30 14" src="https://user-images.githubusercontent.com/4778111/38677305-294d0756-3e5e-11e8-9f49-70ba3721da92.png">

@jakobr-google: I think some `search` caching (e.g. packages for the landing pages) would be useful, but it can go on with a different tracking issue and priority. wdyt?
