### ISSUE TITLE
Pub is unstable on CI, hard to download packages

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub-dartlang-dart#1105]
Cross-posting https://github.com/dart-lang/pub/issues/1826, because even though the pub CLI should probably use retries and other logic to make it sturdier, these problems might be more server related.

**Comment by mit-mit** [comment]
According to go/pub-uptime, we are running at least three 9s, most of the time four 9s. Are we sure this is n't due to networking issues on the CI provider?

**Comment by isoos** [comment]
It looks like that the referenced pub issue has been done (and reopened, and probably done again), closing it here.
