### ISSUE TITLE
Better, friendlier, "more fun" no package 404 page

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1115]
URL: https://pub.dartlang.org/packages/does_not_exist

When the target URL is clearly looking for a package, we could be better

1. Message that `does_not_exist` does not exist.
2. Link to search for `does_not_exist`

etc etc

**Comment by jakobr-google** [comment]
Agreed. We can have the search results (top 5 or 10) directly on the 404 page.

**Comment by mit-mit** [comment]
For inspiration: https://flutter.io/doesnexist
