### ISSUE TITLE
Report failure rates

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1122]
Metrics: 
* Pass analysis
* Dartdoc generation worked

Numbers to report:
* Failure rate for most recent package version that was updated within last 90d
* Failure rate for most recent package version
* Failure rate for all package versions

**Comment by isoos** [comment]
Unfortunately querying the entire `Job` table takes roughly 2 minutes (all the entries for both `analyzer` and `dartdoc`), which is roughly processing 400-500 entries per second, and it makes "real-time" queries infeasible. Couple of ways to work that around:
- concurrent request with different offsets,
- heavy filtering (last 90 days should be fast, latest stable ones could be under 10 seconds),
- pre-calculated rollups

The current one is to run a full query every 15 minutes (one per each instance, maybe it should be less frequent), and serve the aggregated results (all, latest stable, last 90 days) through the `/debug` url of the service. With #1135 it will serve the small subset of failed package names from the last 90 days, and I think that could be an "it is a start" version of serving these stats.

**Comment by mit-mit** [comment]
Every 15 mins sgtm! Please make sure the page prints somewhere when the data was generated.

**Comment by isoos** [comment]
> Please make sure the page prints somewhere when the data was generated.

Updated in #1135

**Comment by isoos** [comment]
This was merged, reporting is done in the form of polling the job status in every 15 minutes and displaying it as part of the `/debug` json.
