### ISSUE TITLE
Markdown rendering of fixed-width tables is way offf

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1125]
URL: https://pub.dartlang.org/packages/text_table

Vs https://github.com/desktop-dart/text_table

**Comment by isoos** [comment]
Hm, is this a style/font size issue? The actual text seems to be okay.

**Comment by kevmoo** [comment]
🤷‍♂️

**Comment by isoos** [comment]
Opened a PR for us and a matching issue for Dartdoc: https://github.com/dart-lang/dartdoc/issues/1644

If dartdoc lags behind we can still add it to our customization.

**Comment by kevmoo** [comment]
@srawlins – is this an issue w/ our markdown package?

**Comment by kevmoo** [comment]
pub site

![screen shot 2018-03-26 at 12 14 49 pm](https://user-images.githubusercontent.com/17034/37927581-5f6c6d94-30ef-11e8-8501-aee639260f24.png)

github

![screen shot 2018-03-26 at 12 15 07 pm](https://user-images.githubusercontent.com/17034/37927587-6379902e-30ef-11e8-9d5d-dca2e39985fb.png)

**Comment by srawlins** [comment]
This is a Kevin's computer problem :laughing: . They both render fine for me.
![ezebiucdddm](https://user-images.githubusercontent.com/103167/37928496-dfe83500-30f1-11e8-97ed-b0f24091843f.png)
![t2vucf27hmv](https://user-images.githubusercontent.com/103167/37928502-e16fb560-30f1-11e8-8a17-7b5c7983e5b5.png)

And Chrome DevTools says the font is "monospace" which it rendered with DejaVu Sans Mono.

**Comment by kevmoo** [comment]
Very weird!

Perhaps fixed in
https://github.com/dart-lang/pub-dartlang-dart/commit/c63edeefd1489c23118aa1861e9037968a962fd7
?

**Comment by isoos** [comment]
> Perhaps fixed in c63edee ?

Nope, that has not been deployed yet (but it fixes it, hence I still think it is a font-rendering issue).

**Comment by isoos** [comment]
Upon further investigation, only the "Menlo" font is needed from GitHub's font list, submitted `dartdoc` PR accordingly, and will update our codebase later when we are syncing to `dartdoc` css.
