### ISSUE TITLE
Add Google Analytics to generated docs

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1131]
Looking at https://staged_docs_host/documentation/test/0.12.32+2/

No analytics code there. It'd be great if we could track it!

**Comment by isoos** [comment]
Is there a different ID for it or the same as pub.dartlang.org?

**Comment by kevmoo** [comment]
If we're going to have a new domain, then yes – we should.

Or is everything going to be under pub.dartlang.org/documentation ?

**Comment by isoos** [comment]
p.d.o/documentation will be only temp for testing until the domain is redirected, but we may have it under p.d.o eventually (TBD).

**Comment by isoos** [comment]
The current dartlang.org has a tracking id `UA-51687523-1`. Shall we use that for now because we have access to it, or a different one?

**Comment by kevmoo** [comment]
We should have a seperate ID for each domain – if at all possible.

Analytics is tough to parse if it crosses domains...

**Comment by isoos** [comment]
Who will create the new analytics tracking account? @jakobr-google @mit-mit @kevmoo ?

**Comment by mit-mit** [comment]
Actually, we changed the plan so we will put the documentation permanently on p.d.o/documentation, and then have dartdocs.org redirect to that. With that, I assume we need no new IDs?

**Comment by kevmoo** [comment]
Correct! Use existing pub site id
