### ISSUE TITLE
Unable to publish because of detectedTypes

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#115]
@dam0vm3nt reported on gitter:

anyone having this problem with pub publish ?

````
 Uploading... (5.2s)
Invalid argument(s): Error while encoding entity (Bad state: Property validation failed for property detectedTypes while trying to serialize entity of kind PackageVersion. , #0      _ModelDescription._encodeProperty (package:gcloud/src/db/model_db_impl.dart:412:7)
#1      _ModelDescription.encodeModel.<anonymous closure> (package:gcloud/src/db/model_db_impl.dart:397:7)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:348)
#3      _ModelDescription.encodeModel (package:gcloud/src/db/model_db_impl.dart:396:34)
#4      _ExpandoModelDescription.encodeModel (package:gcloud/src/db/model_db_impl.dart:501:35)
````

The version number I'm using is absolutely legal : 2.0.0-rc.7
Tried also with 0.7.2 as a version number but it keeps giving me this error
It happens only with the pub.dartlang.org. Using pub publish with another server works.

/cc @mkustermann @kevmoo - shall we revert the new version until this is fixed?

**Comment by isoos** [comment]
Apparently serialization breaks when `detectedTypes=null`.

**Comment by mkustermann** [comment]
When deserializing from the datastore, the `CompatibleStringListProperyty` will convert non-existent properties to empty lists. When it will serialize the property it expects it to be a list.

The reason for this is that it is not possible with datastore to distinguish between `null` and an empty list (a property is just repeated 0 or more times)
