### ISSUE TITLE
`+` need not be encoded in URIs (unless it's in the query)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1156]
See
https://pub.dartlang.org/packages/angular/versions/5.0.0-alpha%2B8
vs
https://pub.dartlang.org/packages/angular/versions/5.0.0-alpha+8

and
https://pub.dartlang.org/documentation/angular/5.0.0-alpha%2B8/
vs
https://pub.dartlang.org/documentation/angular/5.0.0-alpha+8/

Reference: https://stackoverflow.com/a/1006074/39827

`+` is used in a lot of package versions – it'd be great if these URLs were prettier!

**Comment by isoos** [comment]
This should be coming along with https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/shared/urls.dart getting done.
