### ISSUE TITLE
Can't deep link to most recent api docs pages

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1168]
We already support linking to the latest version of api docs for a package, e.g.:
https://pub.dartlang.org/documentation/geolocation/0.1.1/
redirects to:
https://pub.dartlang.org/documentation/geolocation/0.1.1/

However, developers also need to link to the latest version api docs for more detailed pages, e.g.:
https://pub.dartlang.org/documentation/geolocation/geolocation/LocationResult-class.html
should redirect to:
https://pub.dartlang.org/documentation/geolocation/0.1.1/geolocation/LocationResult-class.html

**Comment by mit-mit** [comment]
cc @isoos

**Comment by isoos** [comment]
We've merged https://github.com/dart-lang/pub-dartlang-dart/pull/1167 today, which would support:
`/documentation/[pkg]/latest/whatever/path.html`, and package author could use `/documentation/[pkg]/latest` as the base reference.

Redirecting versionless link to versioned link would require us to check the first part of path parts whether they are versions or relative directories. It could be done by a lookup for the value or a lookup in a cache and fallback for db lookup. @mit-mit: Do you want to take that route, or are we good enough with the `/documentation/[pkg]/latest/[path]` handling?

**Comment by mit-mit** [comment]
Using `/latest/` is totally fine
