### ISSUE TITLE
Scroll position on initial load of pub.dartlang.org

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#1171]
![image](https://user-images.githubusercontent.com/405837/38349775-dd9b6cae-38a8-11e8-8205-6d4835d392ac.png)

Is this intentional that the page scrolls down on initial load to "Top Dart packages"?

I find this quite annoying. The "Top Dart packages" area is the least useful part of the pub.dartlang.org site to me. That's just my opinion of course and I understand that it might be interesting to newcomers. 

I only want to search for packages or see the last updates (which is a view that is quite cumbersome to navigate to).
Not scrolling down on initial load would be a good start to  have the search view immediately available and "Top Dart packages" would also be visible for people who don't know yet what to search for.

**Comment by isoos** [comment]
I'm unable to reproduce this on my Macbook with either Chrome, Safari or Firefox. What kind of extensions are you using?

**Comment by zoechi** [comment]
@isoos Thanks for the feedback. Good to hear that this is not intentional.
I had similar issues with an extension a while back that I'm not using since a while.
I'll experiment with my extensions then.
I guess we can close this and I'll reopen in case it turns out to not be on my end.
