### ISSUE TITLE
Discontinue carte-du-jour

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1178]
This is the old project from dartdocs.org

**Comment by isoos** [comment]
From @kevmoo: "https://dartdocs.org/ doesn't redirect to https://www.dartdocs.org/"

**Comment by mit-mit** [comment]
@isoos that should be unrelated to the carte-du-jour project by now; AFAIK we currently serve both domains from the new Pub server. @jakobr-google can we shut down carte-du-jour?

**Comment by kevmoo** [comment]
I think we can delete it. I was trying to dig in and see if there is any
activity, but the GCS logs say there has been no access since 2016 – which
I really don't believe.

**Comment by jakobr-google** [comment]
We've disabled public sharing on index files in the storage bucket as a scream test. Assuming no-one notices (which they really can't, since the domain points to the dartdoc service on AppEngine now, anyway), we'll delete the carte-du-jour project on Monday.

**Comment by mit-mit** [comment]
Deletion is underway

**Comment by mit-mit** [comment]
Project has been terminated
