### ISSUE TITLE
Docs for all packages are 404ing

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1181]
https://pub.dartlang.org/documentation/test_descriptor/1.0.3/
https://pub.dartlang.org/documentation/test_descriptor/1.0.3/index.html
https://pub.dartlang.org/documentation/test_descriptor/1.0.3

https://pub.dartlang.org/documentation/test_descriptor/latest redirects to https://pub.dartlang.org/documentation/test_descriptor/1.0.3/

**Comment by tvolkert** [comment]
https://pub.dartlang.org/documentation/path/1.5.1/ too.

I swear I've seen this before, and then seems to resolve itself.  Do we have monitoring set up to detect when this happens?

**Comment by kevmoo** [comment]
...we should!

**Comment by isoos** [comment]
I believe I know why this is happening: we have an ongoing deploy, which started to re-generate dartdocs for packages, and when one is ready, it cleans up the older versions from the storage bucket. The old dartdoc service is still active, and it is configured to not serve versions that are newer (for the reason to have a controlled upgrade).

@kevmoo @jakobr-google: for a quick fix, we shall migrate traffic to the new `dartdoc` service version right away, and I'll patch the old-version-cleanup logic for the next release.

**Comment by kevmoo** [comment]
Fixed w/ latest deployment...
