### ISSUE TITLE
markdown Table broken in Dart version

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#12]
https://buildbot-dart-2015-04-22-dot-dartlang-pub.appspot.com/packages/google_visualization_api

**Comment by sgjesse** [comment]
This is caused by the Dart markdown package currently not supporting tables, see https://github.com/dpeek/dart-markdown/issues/38.

**Comment by mkustermann** [comment]
We are not really using `package:markdown` but rather `package:mustache` which lives [here](https://github.com/xxgreg/mustache). But it has the same problem.

**Comment by sgjesse** [comment]
We are still inserting HTML generated by the markdown package into the mustache template.

https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/templates.dart#L140

**Comment by mkustermann** [comment]
You're absolutely right. I confused the server-side rendering of our html pages with `package:mustache` and the rendering of readme/changelog files with `package:markdown`.
