### ISSUE TITLE
Version links don't work

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1201]
The version links right under the package name heading don't seem to work, e.g. on https://pub.dartlang.org/packages/angular_components/versions/0.8.0

![image](https://user-images.githubusercontent.com/13644170/38722519-7461687c-3efe-11e8-94fa-fad9f66ab62b.png)

**Comment by mit-mit** [comment]
cc @isoos

**Comment by isoos** [comment]
Works for me (goes to the version pages). What's the expected behaviour?

**Comment by mit-mit** [comment]
Oh, yes they do work, not sure why I thought they did not
