### ISSUE TITLE
Adding plugin dependencies to Flutter app causes errors

### ISSUE THREAD

**Issue by Stoneman790** [dart-lang/pub-dartlang-dart#1203]
I am new to this so please be kind. I know this is a known issue and I have tried all of the suggestions, workarounds, etc. Nothing works. I can add Firebase podfiles to the project and the project runs on my iOS device and in the simulator. As soon as I add the dependencies in the pubspec.yaml file, and run the debugger it causes the error, "fatal error: 'firebase_auth/FirebaseAuthPlugin.h' file not found"

**Comment by isoos** [comment]
@Stoneman790: This repository is for issues with pub.dartlang.org, and not specific packages. Please use the Flutter repository if you have troubles using Flutter, I've moved your previous issue here: https://github.com/flutter/flutter/issues/16566
