### ISSUE TITLE
'connectivity/ConnectivityPlugin.h' file not found

### ISSUE THREAD

**Issue by prasant10050** [dart-lang/pub-dartlang-dart#1211]
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/prashant/IdeaProjects/job_posting/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'connectivity/ConnectivityPlugin.h' file not found
    #import <connectivity/ConnectivityPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by isoos** [comment]
@prasant10050 This repository is for the pub.dartlang.org site. For package-specific issues, please use the package's repository, e.g. if you are using the `connectivity` package, please use the Flutter repository to file a bug: https://github.com/flutter/flutter/issues/new

**Comment by prasant10050** [comment]
How to fix this error.

**Comment by amreniouinnovent** [comment]
My solution:
https://github.com/flutter/flutter/issues/21989#issuecomment-509193686

**Comment by papalardo** [comment]
I change this files 

pubspec.yaml -> connectivity: 0.4.4+1
Podfile -> platform :ios, '9.0'

```bash
flutter clean
flutter run
```
