### ISSUE TITLE
Make installing tab "smarter" about packages w/ binaries

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1213]
URL: https://pub.dartlang.org/packages/webdev#-installing-tab-

`webdev` has no libraries to use. It does have an executable defined in `pubspec.yaml`, though.

Consider adding `pub global activate` instructions for such packages.

See also
https://pub.dartlang.org/packages/peanut
https://pub.dartlang.org/packages/pubviz
https://pub.dartlang.org/packages/stagehand

**Comment by isoos** [comment]
This seemed to be a low-hanging fruit, but it turns out it has a lot of edge-cases, with the following parameters:

- with/without libraries
- with/without executables
- runs on Flutter/runs only on Flutter

How would you display the install tab when there are libraries and executables? What if it is Flutter-only?

**Comment by kevmoo** [comment]
> How would you display the install tab when there are libraries and executables? What if it is Flutter-only?

🤷‍♂️ 

Maybe just show both? (When we talk about executables, we mean packages with an `executables:` section in their pubspec, right?

**Comment by isoos** [comment]
> Maybe just show both?

Yeah, but what should be the wording? We already have a section of "depend on it", and also "install it", while global activate would be another installing, sometimes with library use, sometimes without it.

> When we talk about executables, we mean packages with an executables: section in their pubspec, right?

Yes.

**Comment by jakobr-google** [comment]
Maybe just show both, using sub-headings:

'Use this package as a library'

'Use this package as an executable'
