### ISSUE TITLE
Can't publish package!

### ISSUE THREAD

**Issue by wendux** [dart-lang/pub-dartlang-dart#1219]
I am in china, and I want to publish a  package  to pub, when i run `pub publish` , I receive some error:

```
Waiting for your authorization...
Authorization received, processing...
Connection failed (OS Error: No route to host, errno = 65), address = accounts.google.com, port = 443
```
and I run `curl accounts.google.com `
```                                                                                                          
<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://accounts.google.com/ManageAccount">here</A>.
</BODY>
</HTML>
```
I have used the shadowsocks to proxy my network, and still failed, but the google.com is available in browser.

any other ways to publish packages to pub ?

**Comment by isoos** [comment]
@wendux: were you able to resolve this?

**Comment by wendux** [comment]
yes I resolved by using  VPN.  sad......
