### ISSUE TITLE
Share still crashing on 0.4.0 on iPads

### ISSUE THREAD

**Issue by AppleEducate** [dart-lang/pub-dartlang-dart#1223]
URL: https://pub.dartlang.org/packages/share#-readme-tab-

After flutter clean and flutter upgrade,  when call share it loses the connection to the device and crashes.

**Comment by AppleEducate** [comment]
iOS 11.3, iPad Pro 10.5 256GB Flutter 0.2.8

**Comment by isoos** [comment]
This repository is for the pub site. The `share` package is created by the Flutter team, please check and/or open an issue in the Flutter repository: https://github.com/flutter/flutter/issues
