### ISSUE TITLE
Please update to (at least) Dart 2-dev.48

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1224]
We have a number of packages that are failing analysis

https://pub.dartlang.org/packages/build_modules
https://pub.dartlang.org/packages/build_web_compilers
https://pub.dartlang.org/packages/build_runner

https://pub.dartlang.org/packages/build_cli

**Comment by isoos** [comment]
I was not sure whether the `pana` upgrade is needed for this, but so far it looks like we can upgrade the runtime without waiting for the pana changes to land. Deploying it to staging to double-check.

**Comment by kevmoo** [comment]
Awesome

**Comment by kevmoo** [comment]
Please deploy docs! All of the packages listed above have broken dartdoc

https://pub.dartlang.org/documentation/build_modules/0.2.2+1/log.txt

**Comment by kevmoo** [comment]
ping @jakobr-google ?

**Comment by jakobr-google** [comment]
New versions of all apps with updated SDK deployed today.
