### ISSUE TITLE
Deployment time

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1233]
To enable troubleshooting, https://pub.dartlang.org/debug should contain a time stamp for when the current version was deployed.

**Comment by mkustermann** [comment]
There's 3 sources of information:

  * Environment variables (e.g. `GAE_VERSION`, ...) it's already used e.g. [here](https://github.com/dart-lang/appengine/blob/master/lib/src/appengine_internal.dart#L162)
  * Metadata server, see [doc](https://cloud.google.com/compute/docs/storing-retrieving-metadata) where you can get information about the GCP instance
  * The appengine API, see [source](https://github.com/dart-lang/googleapis/blob/master/generated/googleapis/lib/appengine/v1.dart#L1554) - (there's no longer dartdocs available for it :-/ )

**Comment by isoos** [comment]
Thanks for the pointers!
