### ISSUE TITLE
Why does the "documentation" link in a package page direct me to a non-useful logfile

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/pub-dartlang-dart#1234]
If I go to [package:googleapis](https://pub.dartlang.org/packages/googleapis) page and click the documentation link, it redirects the browser to [log.txt](https://pub.dartlang.org/documentation/googleapis/0.50.1/log.txt) instead of generated dartdoc html. Why is that?

**Comment by mkustermann** [comment]
At the same time the old dartdocs.org doesn't work anymore. This is really sub-optimal.

@mit-mit @isoos

**Comment by jakobr-google** [comment]
Because dartdoc generation failed: https://pub.dartlang.org/packages/googleapis#-versions-tab-

In this case, because it took too long:

```
Running dartdoc:
STDOUT:
Exceeded timeout of 0:10:00.000000
```

**Comment by mkustermann** [comment]
I think there needs to be an easy way to get to the documentation that's already available, even if it's from a previous version.

Maybe instead of redirecting to the logfile, which users don't care about, we should say: The dartdoc generation failed on this version, but you can see dartdocs of an earlier version here ...

**Comment by mit-mit** [comment]
Looks like almost 9% of all packages fail dartdoc (looking at https://dartdoc-dot-dartlang-pub.appspot.com/debug), so I agree that there is a UX issue we should resolve here.

**Comment by mit-mit** [comment]
Concrete easy suggesting for now: If the dartdocs failed for the most recent version, then link to the versions table. 

So in the concrete example the user would click 'documentation' from the googleapis frontpage, land on https://pub.dartlang.org/packages/googleapis#-versions-tab-, see it says `failed` under documentation for most recent version, but that there are doc links for older versions.

**Comment by isoos** [comment]
Redirecting to the versions tab looks good to me, however, maybe we should redirect to the "All versions" page (https://pub.dartlang.org/packages/googleapis/versions) instead, just in cast that the latest few versions don't have a valid documentation.

**Comment by mit-mit** [comment]
sgtm
