### ISSUE TITLE
Code snippets should be syntax highlighted for Java, ObjC, and Swift code

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/pub-dartlang-dart#124]
Code snippets in the README.md displayed on pub are not syntax highlighted making them hard to read.

Example: https://pub.dartlang.org/packages/firebase_messaging

The same readme looks much nicer when viewed on github: https://github.com/flutter/firebase_messaging/blob/master/README.md

**Comment by mit-mit** [comment]
Odd, the Dart code in https://pub.dartlang.org/packages/url_launcher is syntax highlighted.

**Comment by mit-mit** [comment]
@goderbauer can you clarify what parts you are not seeing highlighting for?

**Comment by isoos** [comment]
I think this page has an example, e.g. the objective-c block is not highlighted:
https://pub.dartlang.org/packages/firebase_messaging/versions/0.0.1+1
