### ISSUE TITLE
HTTP HEAD request results in 404 for valid doc URLs

### ISSUE THREAD

**Issue by chalin** [dart-lang/pub-dartlang-dart#1246]
Why does the following result in a 404?

```console
> curl -I https://pub.dartlang.org/documentation/http/latest/http/Client-class.html
HTTP/2 404 
...
```

My external link checker is getting a 404 as well, but the URL is valid AFAIK.

cc @kwalrath @kevmoo

**Comment by chalin** [comment]
Maybe HEAD isn't supported?

**Comment by kevmoo** [comment]
Perhaps? File an issue

**Comment by chalin** [comment]
Can't this count as the issue?

**Comment by kevmoo** [comment]
> Can't this count as the issue?

Ha! I suppose.

**Comment by isoos** [comment]
Yeah, we don't support `HEAD` anywhere on `pub.dartlang.org`. What's the use-case for it?

**Comment by isoos** [comment]
> Link checkers use HEAD by default (since it is quicker).

Is there a specific tool that needs this or just a nice-to-have? (assessing priorities)
