### ISSUE TITLE
Use --link-to-remote in dartdoc v0.19.0 to link packages together

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/pub-dartlang-dart#1254]
Dartdoc v0.19.0 is [out](https://pub.dartlang.org/packages/dartdoc) and has support for a new flag, --link-to-remote.  Pass this flag in when generating docs and Dartdoc will automatically link docs from different packages together with the Flutter/Dart SDKs and other pub packages.

**Comment by jcollins-g** [comment]
They are configurable but have reasonable defaults.  From dartdoc's --help:

```
    --link-to-hosted                              Specify URLs for hosted pub packages
                                                  (defaults to "pub.dartlang.org::https://pub.dartlang.org/documentation/%n%/%v%")

    --link-to-sdks                                Specify URLs for SDKs.
                                                  (defaults to "Dart::https://api.dartlang.org/%b%/%v%", "Flutter::https://docs.flutter.io/flutter")
```

The substitutions are the same as those for linkTo: url, [here](https://github.com/dart-lang/dartdoc#dartdoc_optionsyaml).  These strings, with the appropriate version substitution, will be inserted into hyperlinks automatically in a way that is hopefully completely bug free...

You'll notice that the Flutter SDK doesn't have version specifiers -- that's because their docs are not currently versioned.  https://github.com/flutter/flutter/issues/16811

**Comment by isoos** [comment]
Yeah, I was wondering if we could use `https://pub.dartlang.org/documentation/%n%/latest`?

**Comment by isoos** [comment]
Yeah, probably we should handle the rewrites anyway, because some of the dependent packages may be on their latest, some may be older, so it is a package-by-package basis. When `A` depends on `B`, and a new version of `B` is uploaded, we'll re-analyze and re-generate the docs anyway, updating the URLs at that time won't be a big issue.

**Comment by jcollins-g** [comment]
Is there something blocking the enabling of the flag at this point?

**Comment by isoos** [comment]
@jcollins-g: 

I'd think that the `Future` here would be linked to the SDK:
https://dartdoc-dot-dartlang-pub-dev.appspot.com/documentation/pool/latest/pool/Pool-class.html
Here is the log:
https://dartdoc-dot-dartlang-pub-dev.appspot.com/documentation/pool/latest/log.txt

Is this because we are excluding `dart:async` (among others)?

**Comment by jcollins-g** [comment]
@isoos It seems likely.  I'll look into this.  It would be really helpful if the logs included the command line parameters for dartdoc.

**Comment by jcollins-g** [comment]
@isoos  OK, tested this.  If you exclude dart:async, Future goes away, and if you exclude dart:core, hashCode and many of the other things go away.  --exclude used to be necessary for Flutter plugins if I remember right due to dart-lang/dartdoc#1431 but that's long fixed.  I would suggest stripping out any excludes and seeing if you get better results.

**Comment by jcollins-g** [comment]
In fact, the code is smart enough now to link to the Flutter version of the Dart SDK docs for dart:async and friends for flutter-plugins.

**Comment by isoos** [comment]
Tested with a few packages, and can confirm that we shall remove the excludes because they are no longer needed.

**Comment by isoos** [comment]
Closing this as the related code changes were merged (will take a while before the new pana version would take effect).
