### ISSUE TITLE
Why I couldn't search the package I uploaded today?

### ISSUE THREAD

**Issue by peng8350** [dart-lang/pub-dartlang-dart#1266]
I've uploaded a package this morning, https://pub.flutter-io.cn/packages/pull_to_refresh, why I can't search for my own uploads in it, such as this search, https://pub.flutter-io.cn/packages?Q=pull_to_refresh, is there a process of manual review?

**Comment by isoos** [comment]
There is no manual review, the search index should pick it up automatically, within a few (usually less than 10) minutes. I'll need to investigate why it had no happened yet.

**Comment by isoos** [comment]
I'm not sure yet why `search` did not pick up the package, while `dartdoc` and `analyzer` did it, there is nothing error-related in the logs. One notable difference is: `search` is polling `Package` and `Analysis`, while the others poll `PackageVersion`.

**Comment by peng8350** [comment]
Is there no way to solve this problem? Can you delete this library and let me upload it again?

**Comment by isoos** [comment]
@jakobr-google: Repeatedly checking the debug URL reveals that some instances have more packages in their index than others (e.g. +5). I'm not yet sure whether it is systemic issue or just a temp glitch, it is not clear from the logs. Could you please reboot the instances?

**Comment by jakobr-google** [comment]
I rebooted the instances. Took a little while for the package to show up in the index, but it's there now.

**Comment by isoos** [comment]
#1288 seems to have fixed this. Package updates are now picked up in ~10 minutes or so.
