### ISSUE TITLE
type '() => Future<dynamic>' is not a subtype of type '() => Future<Null>'<Summarize your issues here>

### ISSUE THREAD

**Issue by Arunva28** [dart-lang/pub-dartlang-dart#1267]
URL: https://pub.dartlang.org/packages/async_loader#-readme-tab-

I was using an older version of Dart where httpClient was in use. But when i updated dart, I had to shift to http package. But when I work with it, I am able to get a response but I am unable to load after I get the response. I see an error like 

type '() => Future<dynamic>' is not a subtype of type '() => Future<Null>'

Stack trace is 
I/flutter ( 3802): When the exception was thrown, this was the stack:
I/flutter ( 3802): #0      DetailPage._securityPage.<anonymous closure> (file:///Volumes/MEM/Flutter/virtualdoor/lib/main.dart:658:32)
I/flutter ( 3802): #1      AsyncLoaderState.build (package:async_loader/async_loader.dart:76:19)
I/flutter ( 3802): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
I/flutter ( 3802): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter ( 3802): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3802): #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter ( 3802): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 3802): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 3802): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 3802): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 3802): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 3802): #11     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 3802): #12     _drawFrame (dart:ui/hooks.dart:109:3)

**Comment by isoos** [comment]
@Arunva28:

1) Please specify the versions you are using, and double-check that you have strong mode enabled in your project and it has no analyzer warnings.

2) I'm the author of `package:http_client` [here](https://pub.dartlang.org/packages/http_client), and I've published 0.4 a few weeks ago. What was you issue of using it with the new Dart version?

**Comment by zoechi** [comment]
This kind of nonsensical type error is common if you have relative imports in `lib/main.dart` (imports where the path doesn't start with `'package:...'`

**Comment by eernstg** [comment]
PS: I just noted in passing that the type arguments in [the initial entry](https://github.com/dart-lang/pub-dartlang-dart/issues/1267#issue-320596397) got swallowed during rendering, which makes it look like the type relationship under consideration is `Future Function()` and `Future Function()`; it is actually `Future<dynamic> Function()` and `Future<Null> Function()`, just like it is in the title, and for those two types it is indeed true that there is no subtyping relationship. I'm not working on pub so I won't make any attempt to go futher, but I just thought that it would be useful to avoid that misunderstanding. ;-)

**Comment by isoos** [comment]
Not sure what's left to do here, closing.
