### ISSUE TITLE
Shared Preferences can't be renamed

### ISSUE THREAD

**Issue by rtyker** [dart-lang/pub-dartlang-dart#1272]
URL: https://pub.dartlang.org/packages/shared_preferences

There is no way to rename the SharedPreference internal file in Flutter like in old Java/Android way.
The generated name always = FlutterSharedPreferences.

**Comment by isoos** [comment]
@rtyker: this tracker is for the pub site. If you have issue with a package, please open an issue in the package's issue tracker, in this case, the Flutter team's one. I'm moving this over.

**Comment by isoos** [comment]
This issue was moved to flutter/flutter#17379
