### ISSUE TITLE
Kind column on package listing page

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/pub-dartlang-dart#128]
A UX review of Flutter plugins (https://flutter.io/platform-plugins/) found that it was difficult from the packages listing page (https://pub.dartlang.org/packages) to tell if they were Dart packages or Flutter plugins.

It would be helpful to add a 'kind' column that indicated this to the LHS of each row, probably with either the Dart or Flutter logo.

**Comment by lukechurch** [comment]
cc @mit-mit

**Comment by mkustermann** [comment]
There is now a [https://pub.dartlang.org/flutter/plugins](https://pub.dartlang.org/flutter/plugins) page.

@isoos Though I think we could for all package lists show the detectedType icon on the left side of the name (i.e. on `/packages`, `/`, ...). wdyt?

**Comment by mit-mit** [comment]
Yes, this would be a great addition for those cases where developers click away from the /flutter/plugins page and up on the regular packages pages.

**Comment by mit-mit** [comment]
@kevmoo would be even greater if we could detect 'web only' packages (maybe those that depend on dart:html?), and show a web icon for those?

**Comment by isoos** [comment]
@mkustermann I was thinking similarly, left side sounds good.

I think there is no need for a column header, because if there are no icons, we want that column to be thin/disappear.

**Comment by jhirth** [comment]
@isoos The icons vary in size on different pages thanks to the `img{max-width: 100%}` rule. See:

https://pub.dartlang.org/flutter/plugins?page=1
https://pub.dartlang.org/flutter/plugins?page=2

Easy fix: Add `.tablecol-icons-img { max-width: unset }`.
