### ISSUE TITLE
Flutter version

### ISSUE THREAD

**Issue by dnfield** [dart-lang/pub-dartlang-dart#1282]
The flutter version pub uses for Analysis appears to be 0.3.5.

This doesn't currently track with Beta, Dev, or Master.  

I have a few packages published that require 0.3.6 and would like to know when that will be used for analysis so my packages can be categorized and scored properly.

**Comment by isoos** [comment]
We are doing controlled version upgrades for all of the tools in the pipeline and test these in a staging environment. I've started to prepare an upgrade for Flutter 0.4.2 (among others), but it may be deployed only next week.

It is a crazy world when a 16-days old version is already considered as obsolete :)

**Comment by dnfield** [comment]
Appears to be using 4.4.0 now
