### ISSUE TITLE
Both &nbsp; and literal char code 160 (\u00A0) are shown as "&nbsp;"

### ISSUE THREAD

**Issue by gregko** [dart-lang/pub-dartlang-dart#1287]
URL: https://pub.dartlang.org/packages/flutter_html_view#-analysis-tab-

If the data string to show in HtmlView control contains "Some&amp;nbsp;text" or "Some_test", where underscore _ represents Unicode code point 160 '\00A0', the HtmlView shows literally:

`Some&nbsp;text
`

To avoid the issue I have to use code like:

`  s = s.replaceAll('\u00A0', ' ');
`
or 
`  s = s.replaceAll('&nbsp;', ' ');
`

**Comment by isoos** [comment]
@gregko: the current issue tracker is for the pub site, please use the package's repository for reporting issues.

**Comment by isoos** [comment]
This issue was moved to PonnamKarthik/FlutterHtmlView#5
