### ISSUE TITLE
Feature request: Use favicons for pub.dartlang.org pages

### ISSUE THREAD

**Issue by kasperl** [dart-lang/pub-dartlang-dart#129]
Could be used to distinguish between the different kind of packages for the package specific pages and the filtered views.

**Comment by mit-mit** [comment]
Yes, would be great if:

1. the individual package pages show a custom favicon when kind is flutter_plugin (use [favicon.png](https://github.com/flutter/website/blob/master/images/favicon.png))

2. the flutter specific pub pages -- currently just /flutter/plugins -- also show that favicon

**Comment by mit-mit** [comment]
cc @isoos this would be a fairly small change, right?

**Comment by isoos** [comment]
Right now we have only `detectedType=flutter_plugin`, but what happens in the future where we may have several types and a package could get two or more? In those cases, choosing the icon may not be straightforward (e.g. who gets the priority?).

It would be also nice if we could maintain some kind of consistency across the pages, e.g. the flutter-plugin-favicon is a combination of the Dart logo + the Flutter logo.

Another option would be to fetch the favicon from the package's homepage, although it will be usually the github icon, so I wouldn't see much value in that.

**Comment by mit-mit** [comment]
`detectedType` is meant to be exclusive, so not too worried about that part.

**Comment by isoos** [comment]
I'm not sure that `detectedType` is exclusive, and even if it is now, in the future there may be overlaps.
