### ISSUE TITLE
pre-submit tests are not running

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1294]
I have now two examples where missing updates to generated files were not caught by the `ensure_build_test.dart`.

**Comment by jakobr-google** [comment]
Looks like that test is being skipped on Travis.

**Comment by isoos** [comment]
I'm not sure if there is a Travis setting or environment variable for it. @kevmoo: any idea?

Worst case: we can disable the test annotation and run it every time.

**Comment by kevmoo** [comment]
Looking now...
