### ISSUE TITLE
flutter_sprites version not suitable for dart2

### ISSUE THREAD

**Issue by qiuguian** [dart-lang/pub-dartlang-dart#1304]
URL: https://pub.dartlang.org/packages/flutter_sprites/versions/0.0.15

flutter_sprites version not suitable for dart2, when it will be update,I look forward to it!!

**Comment by isoos** [comment]
@qiuguian: this is the issue tracker for the pub site, and individual package issues should be reported on their respective repositories. In this case, I'd suggest to reach out to the authors/uploaders (listed on the package page) or use the flutter repository to file an issue.
