### ISSUE TITLE
How to get pub to list package as compatible with Flutter

### ISSUE THREAD

**Issue by mythz** [dart-lang/pub-dartlang-dart#1308]
I have a package published on pub at:

https://pub.dartlang.org/packages/servicestack

Which contains Dart HTTP Client library with JSON serializeration support. Unfortunately pub is flagging it incorrectly that it only works in Dart **WEB**.

The library was primarily designed to work in flutter where there's a working example referencing it over at:

https://github.com/ServiceStackApps/HelloFlutter

The same package also contains a HTTP Client that also works in Dart Web / AngularDart where this is the only file that references 'package:http/browser_client.dart':

https://github.com/ServiceStack/servicestack-dart/blob/master/lib/web_client.dart

In flutter projects, the only file that's referenced is:

https://github.com/ServiceStack/servicestack-dart/blob/master/lib/client.dart

Which only contains references of packages that are available in Flutter. 

So it appears that the heuristics which only classifies it as compatible with Dart **WEB** is not accurately reporting the compatible platforms, as it should also report that it's compatible with Flutter. 

Is there anyway I can indicate to pub that this library works in Flutter, whilst being able to continue support Dart WEB projects in the same package? 
Ideally I'd like to keep having the same package support all Dart platforms, which it currently does, unfortunately it's not classified as such.

**Comment by isoos** [comment]
@mythz: for such multi-platform packages we support and recognize the following pattern: use a generic `lib/<package_name>.dart` file to define your common interface and the shared API methods, and use e.g. `lib/web_client.dart` for your web-specific code.

Otherwise the current analysis looks at the package, it sees 7 libraries in the lib/ directory and it won't be able to identify a single main library, so it just uses an overall impression of what the platform could be.

**Comment by isoos** [comment]
@mythz: I'm closing this as I don't see anything I can immediately fix or implement. Feel free to re-open if you still have questions related to the platform classification.

**Comment by mythz** [comment]
I've decided to workaround the pub conflicts by extracting the Dart Web Client into a separate [servicestack_web](https://pub.dartlang.org/packages/servicestack_web) package, which whilst inconvenient at least reports gets pub to report the correct platforms with the latest version of [servicestack](https://pub.dartlang.org/packages/servicestack) now says it supports `[FLUTTER] [OTHER]` and [servicestack_web](https://pub.dartlang.org/packages/servicestack_web) says it supports `[WEB]`.

IMO we should be able to override/specify which platforms our libraries support as the inference doesn't cover use-cases with multiple classes having different dependencies.

One issue resulting from splitting the classes into different packages is that I've chosen to use the same `client.dart` name which reads better as `client` library from the `servicestack` or `servicestack_web` package:

```dart
import 'package:servicestack/client.dart';
import 'package:servicestack_web/client.dart';
```

Pub is now giving me a warning every time I try to publish a change:

```
Suggestions:
* The name of "lib\client.dart", "client", should match the name of the package, "servicestack_web".
  This helps users know what library to import.

Package has 1 warning. Upload anyway (y/n)? 
```

As it wants you to use the convention of repeating the library name:

```dart
import 'package:servicestack/servicestack.dart';
import 'package:servicestack_web/servicestack_web.dart';
```

I would like to disable this warning as I have ample docs and examples showing how to use the library and I believe the above makes the code read worse. 

If Dart/Pub wanted to enforce the convention of repeating the library name it should IMO make the library easier to use by being able to reduce the unnecessary repetition and assume a default import so library users could be able to write:

```dart
import 'package:servicestack';
import 'package:servicestack_web';
```

If we could do this then I'd rename it back to using `servicestack.dart` and `servicestack_web.dart` to match the library names as there's a clear end user benefit in doing so, as at the moment the trade-off is having worse repetitive naming vs clearer naming + repeated warnings.

**Comment by isoos** [comment]
> If we could do this then I'd rename it back to using servicestack.dart and servicestack_web.dart to match the library names as there's a clear end user benefit in doing so, as at the moment the trade-off is having worse repetitive naming vs clearer naming + repeated warnings.

I fail to see the why this couldn't be handled by the following:

````
// Web client
import 'package:servicestack/servicestack.dart';
import 'package:servicestack/servicestack_web.dart';
````

````
// Console client
import 'package:servicestack/servicestack.dart';
import 'package:servicestack/servicestack_console.dart';
````
or

````
// Web client
import 'package:servicestack/servicestack.dart';
import 'package:servicestack/web_client.dart';
````

That way you have only a single package, with a pub-friendly naming, with platforms clearly separated. You can even omit the `package:servicestack/servicestack.dart` part if you export it from the platform-dependent libraries.

**Comment by mythz** [comment]
This issue is because the inference of supported platforms in the packages is broken, please read my previous issues. e.g. Renaming to `servicestack/servicestack.dart` made it even worse where it was being misidentified as `[UNIDENTIFIED]`.

So I decided to split it into the different packages which was the only way I could get it to report the correct platforms for each package.

The previous comment explained why I don't want to use `import 'package:servicestack/servicestack.dart';` over `import 'package:servicestack/client.dart';` which reads better as to what exactly is being imported.

**Comment by mythz** [comment]
Ok fantastic thanks, I've refactored it so:

  - [servicestack.dart](https://github.com/ServiceStack/servicestack-dart/blob/master/lib/servicestack.dart) Contains the platform agnostic interfaces and converters
 - [client.dart](https://github.com/ServiceStack/servicestack-dart/blob/master/lib/client.dart) Contains the concrete `dart:io` `JsonServiceClient`
 - [web_client.dart](https://github.com/ServiceStack/servicestack-dart/blob/master/lib/web_client.dart) contains the concrete `http/browser_client.dart` `JsonWebClient `

And now the [servicestack](https://pub.dartlang.org/packages/servicestack) Dart package is correctly importing `[FLUTTER] [WEB] [OTHER]` platforms! Which also works in both the [Flutter Example](https://github.com/ServiceStackApps/HelloFlutter) and [Angular Dart Example](https://github.com/ServiceStackApps/HelloAngularDart) applications.

To make it so users don't have to import 2 references I've re-exported the platform-agnostic `servicestack.dart` in both `client.dart` and `web_client.dart`. i.e:

```dart
import './servicestack.dart';
export './servicestack.dart';
```

There seems to be little info on what the side-effects of re-exporting the main library are but it seems to work where the generated DTOs need only reference the platform-agnostic library:

```dart
import 'package:servicestack/servicestack.dart';
``` 

Whilst users only need to import the concrete library depending on if they're referencing a web or non web client:

```dart
import 'package:servicestack/client.dart'; //for Flutter + Dart VM Apps

import 'package:servicestack/web_client.dart';  //for Dart Web Apps
```

Given there shouldn't be any Apps that should ever reference both `client.dart` and `web_client.dart` I think it should be ok to re-export `servicestack.dart` as there doesn't appear to be any conflicts from doing so yet.
