### ISSUE TITLE
bad analysis displayed for package that was uploaded after a new analyzer runtime is introduced but not fully deployed

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1310]
Current issue was reported for https://pub.dartlang.org/packages/get_it#-analysis-tab-

Analysis with `pana 0.11.1` was successful, but the old runtime on the frontend is still on `pana 0.10.6`, and there are no analysis results stored with `0.10.6`.

We shall not stop running the old analysis during such overlapping periods.

**Comment by jakobr-google** [comment]
Sure, coming up.

**Comment by jakobr-google** [comment]
New services deployed.

**Comment by isoos** [comment]
@jakobr-google: Thanks! 

Fixing this in the backend seems to be not that straightforward: we'll need to track new uploads outside of the job processing, which is tuned towards processing everything only once and only be the latest version. However I think there is a lot of shared code around it, and it should fix it for next time.
