### ISSUE TITLE
Update score docs related to strong mode

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1322]
Not sure this makes sense anymore in a Dart 2 world:

> _analysis_options.yaml:_ Best if this file is present, with strong mode enabled. For more information, see Customize Static Analysis.

https://pub.dartlang.org/help#scoring

**Comment by isoos** [comment]
How would you change the sentence there?

On the linked "Customize Static Analysis" page, there is this sentence: "The analyzer in the Dart SDK doesn’t yet use the latest Dart type system, by default."

I think as long as the default is it not the strong mode, we should still encourage people to turn it on, as we analyze the packages with strong mode anyway.
