### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by gregko** [dart-lang/pub-dartlang-dart#1327]
URL: https://pub.dartlang.org/packages/shared_preferences

Is this the correct way to report issues for Flutter plugins? On GitHub flutter/plugins there is no "Issues" tab...

I really have an enhancement request to shared_preferences plugin. On occasion the native side of a Flutter app (e.g. Java side on Android) needs to access shared preferences set in Flutter, or maybe set them for Flutter side as well. It is necessary for example when communicating with other native apps on a platform.

Currently what I have to do in Java to accomplish this is:

`SharedPreferences prefs = getSharedPreferences("FlutterSharedPreferences", MODE_PRIVATE);`

and later when I want to read e.g. "myValue" key, I have to add "flutter." prefix:

`String value = prefs.getString("flutter."+key, null);`

This does not feel right though, spying on package private values and using them elsewhere. A better way should be provided by the SharedPreferencesPlugin instead.

**Comment by jakobr-google** [comment]
This repo is for the Pub server.

As it says in the [README.md](https://github.com/flutter/plugins/blob/master/README.md) in the [flutter/plugins](https://github.com/flutter/plugins) repo,

> Please file any issues, bugs, or feature requests in the [main flutter repo](https://github.com/flutter/flutter/issues/new).
