### ISSUE TITLE
pub client could include CLI search

### ISSUE THREAD

**Issue by truepatch** [dart-lang/pub-dartlang-dart#1334]
I want to find the package through the console.
But I can not implement this, because there is no `search` function

**example**: `pub search <regexp|package_name|description>`

**output** must be list packages in each string: 
`name package`  `last version` - `description` 

**example**: `pub search <regexp|package_name|description> -v`

**output** must be list packages: 
`name package`  `last version` - `full description`

**Comment by isoos** [comment]
@truepatch: We may have most of this already as a JSON API:
- search: https://pub.dartlang.org/api/search?q=json
- package data: https://pub.dartlang.org/api/packages/json_serializable

We do lack a typed API for though...

**Comment by truepatch** [comment]
This functionality is necessary for a larger community growth, I hope the contributors implement it.

**Comment by isoos** [comment]
Moving this to pub client for consideration.

**Comment by isoos** [comment]
This issue was moved to dart-lang/pub#1940

**Comment by jingtuo** [comment]
> 
> 
> @truepatch: We may have most of this already as a JSON API:
> 
>     * search: https://pub.dartlang.org/api/search?q=json
> 
>     * package data: https://pub.dartlang.org/api/packages/json_serializable
> 
> 
> We do lack a typed API for though...

 Is there a document for such an API?

**Comment by shyndman** [comment]
I threw this together quickly: https://pub.dev/packages/pubx

It's base bones, and not carefully considered, but it works! Pull requests are welcome.

**Comment by jonasfj** [comment]
> Is there a document for JSON API?

The search API is not stable, we do not have documented API for this.

**Comment by shyndman** [comment]
I'll get a smoke test running on CI, and update as you do.
