### ISSUE TITLE
A few presentation changes for Flutter plugins

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#134]
Kindly request some small visual tweaks:

### Plugin page

For package pages for Flutter plugins -- for example https://pub.dartlang.org/packages/url_launcher  -- please change the text `Flutter plugin` after the flutter logo to be a hyperlink, `<a href="/flutter/plugins">Flutter plugin</a>`

### Plugins list

On the plugins list, https://pub.dartlang.org/flutter/plugins/, please add a link to Flutter plugin docs after the 'Flutter Plugins header' and before the actual list of plugins:

`<p><a href="https://flutter.io/platform-plugins/">Learn more about Flutter plugins<a></p>`

**Comment by mit-mit** [comment]
cc @isoos

**Comment by mit-mit** [comment]
One more item, pretty please:

### Front page

On the front page, inside the 'Mobile development' box, please add a second button labeled 'Flutter Plugins' which links to `/flutter/plugins/`

**Comment by mit-mit** [comment]
Thanks @isoos! I don't see this on the site, does it need to be published or something?

**Comment by isoos** [comment]
Yes, @mkustermann  or @kevmoo will publish it.

**Comment by mkustermann** [comment]
Had to make a smaller fix to the flutter page (wasn't rendering properly). Published now.
