### ISSUE TITLE
pub package page hijacks location

### ISSUE THREAD

**Issue by srawlins** [dart-lang/pub-dartlang-dart#1343]
Steps to recreate:

1. I want to share a link to the "Asynchronous Tests" section of [test's README](https://pub.dartlang.org/packages/test)
2. I click the link at the top, in the table of contents, the link to: https://pub.dartlang.org/packages/test#asynchronous-tests
3. I confirm, yes, this is the content I want to link.
4. I go to the location bar, expecting an anchor in the URL, but it is still just https://pub.dartlang.org/packages/test.

Expected result:

Like a normal website, the anchor should be in the URL. It should read: https://pub.dartlang.org/packages/test#asynchronous-tests

**Comment by isoos** [comment]
Yeah, looks like we'll need to either re-do the custom scrollTo, or update the location.hash. The later is easier, a PR is in the works.

**Comment by srawlins** [comment]
Thanks!
