### ISSUE TITLE
Log entry with size 277.4K exceeds maximum size of 110.0K

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1347]
I've noticed the following error in the `dartdoc` logs:

````
An error occured while writing log entries:
Error:GrpcError: "Log entry with size 277.4K exceeds maximum size of 110.0K" (code: 3)
#0      Client.invoke (package:appengine/src/grpc_api_impl/grpc.dart:216:9)
#1      Channel.invoke (package:appengine/src/grpc_api_impl/grpc.dart:45:19)
#2      LoggingServiceV2Api.writeLogEntries (package:appengine/src/grpc_api/dart/google/logging/v2/logging.pb.dart:393:20)
#3      SharedLoggingService.flush (package:appengine/src/grpc_api_impl/logging_impl.dart:302:17)
````

It looks like we have similar messages in `analyzer` logs, but none in the `app` and `search`. 

Reducing the number of log messages seems to be a good idea for now.

**Comment by sortie** [comment]
The error suggests to me it's a single log entry that's too large, if that's the case then doing fewer small log messages won't make a difference? Or perhaps this is after a bunch of log messages have been aggregated?

**Comment by isoos** [comment]
I think [this code](https://github.com/dart-lang/appengine/blob/master/lib/src/grpc_api_impl/logging_impl.dart#L298) prepares a store request for all the entries enqueued, and it seems that flush is called either after 3 seconds or reaching 25 items, whichever is first.

The text which we put inside the log messages are not long (should be under 1K), but I guess the appengine library stores additional meta-information there too, and 20+ of them could easily push it over the 110k limit.

Making our texts shorter may help, but I'd also use the opportunity to remove some of the debug information we don't need anymore.

**Comment by isoos** [comment]
An update: `dartdoc` service is still affected by this, and `analyzer` too for a lesser extent. `app` and `search` seems to be doing fine.

**Comment by isoos** [comment]
Update: both `dartdoc` and `analyzer` remains affected, but many log-affecting changes were merged after the current release.

**Comment by isoos** [comment]
It is still affecting the new release (`analyzer` and `dartdoc` services), and it seems that the frequency and the exceed amount has increased.

**Comment by isoos** [comment]
With the latest release `analyzer` seems to be ok, but `dartdoc` seems to be still affected. In the logs I've noticed a lot of `dart --version` requests, these look like a low-hanging fruit to be cached in `pana`. They are already cached for a single environment, but we create new environments for new cache directories. We can both re-use the environment on the service for a limited number of analysis, and also try to use a global cache for certain things in `pana`.

**Comment by isoos** [comment]
It looks like that the latest release doesn't have the issue.
