### ISSUE TITLE
Offer help/steps for all Suggestions in scoring

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1354]
Some of the suggestions listed on the score page are not easy for a developer to reproduce. As an example, consider this one:

`Running dartdoc failed.`

How does a Flutter developer actually do that? They have no Dart SDK in path.

We should create a page with documentation for all possible failures with steps listed for how to do them.

**Comment by mit-mit** [comment]
cc @isoos WDYT?

**Comment by isoos** [comment]
Yeah, agreed. I'd add a `helpCode` to the suggestion, and the pub site could decide how to link to the more detailed help page.

**Comment by isoos** [comment]
We have ~25 different kind of suggestions in `pana`, and I think we'll need to provide help articles to less than 10 of them.

**Comment by mit-mit** [comment]
Cool. If you go ahead with the `helpCode` part I an help with documentation!

**Comment by isoos** [comment]
Another angle: Is there a Flutter-specific command that generates the docs for the app? I can't find one, but if there is, we can also output the Flutter-specific command within the suggestion's text (similarly what we do for `dartfmt` and `dartanalyzer` if the package uses Flutter).

**Comment by mit-mit** [comment]
Remaining work: Write up documentation for each of the possible error codes.

**Comment by isoos** [comment]
Suggestions with updated wording had been updated in both pana and pub site, will be part of the next prod release.
