### ISSUE TITLE
Documentation failed to be generated

### ISSUE THREAD

**Issue by MaikuB** [dart-lang/pub-dartlang-dart#1356]
URL: https://pub.dartlang.org/packages/flutter_local_notifications#-versions-tab-

Errors have started to appear in generating the documentation recently. This isn't isolated to my own package but other ones that have been uploaded more recently are also effected e.g. https://pub.dartlang.org/packages/firebase_auth

**Comment by MaikuB** [comment]
Just noticed a similar issue was raised at https://github.com/dart-lang/dartdoc/issues/1705

**Comment by isoos** [comment]
Yeah, I believe this should be fixed once we have a new prod deploy, probably early next week. (cc @sortie)

**Comment by MaikuB** [comment]
Wiill part of the deployment process also involve fixing previously uploaded packages? Uploaded a new package today where the documentation got generated without issues

**Comment by isoos** [comment]
While the new deploy is not complete yet, I can see that all of your versions have proper documentation. Closing the issue.
