### ISSUE TITLE
Update search logging and re-indexing

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1363]
- ~[ ] The 200ms threshold is interesting only in periods where there is no parallel re-indexing running.~
- ~[ ] When re-indexing is running, it should be increased to 500ms.~
- [ ] Should consider lowering indexing batch size.
- [ ] Should consider package hash that would make re-indexing skip identical packages.

**Comment by sortie** [comment]
The log warning just contained the search URL. It should be prefixed with "Slow search" so it's more visible what it is at a glance without expanding it.

**Comment by isoos** [comment]
It turns out that the increased number of warnings did indicate a slowdown, making most if the task list obsolete. As #1366 fixes a huge chunk of the latency, I'm closing the rest, keeping the warning at 200ms seems reasonable, and it turned out to be useful for this time.

**Comment by isoos** [comment]
> Is there any monitoring of latency for different APIs, keeping track of different percentiles?

No, I think earlier the dashboard and tools that google cloud console provided were enough. I've added this to keep an eye on search internals, and we have another metric that exposes the event loop latency on the /debug url, but it is not monitored either.
