### ISSUE TITLE
Docs are failing to generate for packages that require 2.0.0-dev.62.0

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pub-dartlang-dart#1376]
Some failures:
https://pub.dartlang.org/documentation/path/1.6.1/log.txt
https://pub.dartlang.org/documentation/angular_components/0.9.0-alpha+15/log.txt

**Comment by kevmoo** [comment]
Looks like we need https://github.com/dart-lang/pub-dartlang-dart/commit/cd9b4058c196702f2c3044a83e28f3bdb0ae93ec to be published so we pick up the site with -dev.63

**Comment by isoos** [comment]
The new version has been deployed (mid-week) and migrated (today), I can see that dartdoc execution of `path/1.6.1` happened and ended with a successful status.

uuid:`274458d1-1191-4124-b728-6e43f871e933`
timestamp: around `2018-06-19 21:24:45.613 CEST`

We may have a bit too much caching going on, and unfortunately we may need to wait a full day until it clears. I'll check it later and update the status.

**Comment by isoos** [comment]
The cache cleared, the package docs are generated. Keeping this issue open until I submit a fix for better cache invalidation.
