### ISSUE TITLE
Here is the error im getting on running the example provided in the docs. Hope it helps.

### ISSUE THREAD

**Issue by saivamsid** [dart-lang/pub-dartlang-dart#1377]
URL: https://pub.dartlang.org/packages/qrcode_reader#-example-tab-

C:\flutter\.pub-cache\hosted\pub.dartlang.org\qrcode_reader-0.3.3\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java:42: error: cannot find symbol
public class QRCodeReaderPlugin implements MethodCallHandler, ActivityResultListener, PluginRegistry.RequestPermissionResultListener {
                                                                                                    ^
  symbol:   class RequestPermissionResultListener
  location: interface PluginRegistry
C:\flutter\.pub-cache\hosted\pub.dartlang.org\qrcode_reader-0.3.3\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java:63: error: incompatible types: QRCodeReaderPlugin cannot be converted to RequestPermissionsResultListener
            registrar.addRequestPermissionsResultListener(instance);
                                                          ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\qrcode_reader-0.3.3\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java:155: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\qrcode_reader-0.3.3\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qrcode_reader:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Finished with error: Gradle build failed: 1

**Comment by isoos** [comment]
@saivamsid: this repo is for the pub site only, you'll need to report the issue to the package's own repository. You can do that by looking at the homepage URL of the package. I'm moving the issue this time.

**Comment by isoos** [comment]
This issue was moved to bcko/flutter_qrcode_reader#14
