### ISSUE TITLE
Help users understand what packages won't work with Flutter due to Dart2

### ISSUE THREAD

**Issue by jacob314** [dart-lang/pub-dartlang-dart#1395]
Now that Flutter only works with Dart 2, users need a way to understand what packages will work with Flutter when using the pub website to avoid issues like https://github.com/flutter/flutter/issues/18634.

For example:
https://pub.dartlang.org/packages/bignum
on the surface looks like it works with flutter..
Right at the top of the page you see FLUTTER listed as one of the platforms for the package even though this code will never compile on Flutter as it doesn't support Dart 2.
![image](https://user-images.githubusercontent.com/1226812/41676891-acbaada2-747b-11e8-9f92-8559d60b14d8.png)

Nit: it would be nice if health issues impacted the score more drastically so users can be confident even if they only look at the overall score and not the sub scores.
The package's score is 42 doesn't make it clear to me  that anything is broken. Is the score 42/100 or 42/50? The colored background doesn't make it obvious I should watch out.
If you drill into the score you can see that health is 7/100. It would be nice if a low health score lead to a low overall score warning users that the package won't work. If the overall score was 7/100 and showed up in red then I would have understood what was going on if I imported the package a bit more quickly.

**Comment by isoos** [comment]
There are a couple of actionable items here:

- Review how overall scoring works. In this case popularity dominates over health and maintenance, and it feels not good as overall score. I'm not sure thought what score would as a correct one in such case...

- Override platform classification if health score is low: if there are too many issues with the package, we shall rather stick with "unidentified" and not state much about the platform.

- The linked issue re-emphasizes the need of runtime analysis.

/cc @mit-mit, @sortie, @kevmoo

**Comment by mraleph** [comment]
I suggest we go further - you should not be able to install a package that is incompatible (has compilation errors) according to Dart 2 analysis.

**Comment by mit-mit** [comment]
We changed the site so that the platform badges (flutter, web, other) are removed when the quality is below a certain threshold. If you look at bignum now, you should see that:
https://pub.dartlang.org/packages/bignum#-analysis-tab-

This also prevents it from showing up in the platform searches:
https://pub.dartlang.org/flutter/packages?q=bignum

In todays launch we will additionally mark the 'score circle' for these red.

**Comment by mit-mit** [comment]
New site is live, closing

![screen shot 2018-08-10 at 16 50 15](https://user-images.githubusercontent.com/13644170/43964602-7a0d1646-9cbd-11e8-956d-def44e7f64f8.png)
