### ISSUE TITLE
Please mark `analyzer_cli` package as discontinued.

### ISSUE THREAD

**Issue by pq** [dart-lang/pub-dartlang-dart#1399]
Follow-up from: https://github.com/dart-lang/sdk/issues/25128#issuecomment-399180848

**Comment by isoos** [comment]
@sortie: you can use the `flag.dart` in `app/bin/tools`: IIRC it should be `dart bin/tools/flag.dart analyzer_cli --discontinued set`

**Comment by sortie** [comment]
Done. It produced this output:

Package analyzer_cli: isDiscontinued=true doNotAdverise=null

I don't see any changes on the page, it's probably cached.

**Comment by isoos** [comment]
The flag setter schedules it to another analysis round, and that would mark it as discontinued. Ideally that should happen in <10 minutes, and then it would be picked up by `search`, and it will remove it from the index.

**Comment by isoos** [comment]
@sortie: it looks like that `analyzer` did not receive the notification from the discontinue marking, not sure why. Could you please run the `dart ./bin/tools/notify_service.dart analyzer analyzer_cli 1.1.2`?

**Comment by sortie** [comment]
Done.

**Comment by pq** [comment]
Thanks! Sorry I don't fully understand the process but when this has fully percolated through the system, will the page at https://pub.dartlang.org/packages/analyzer_cli get updated visually?

![image](https://user-images.githubusercontent.com/67586/41858899-d09c610c-784f-11e8-9136-dbe5542a4cda.png)

**Comment by isoos** [comment]
@pq: Normally it should have happened in <15 minutes, but we have a bug in our internal notifications, and it is not triggering the required processing (#1409).

The system will do the re-processing eventually (most likely in a few days, but old and failing packages like this are de-prioritized), or it will be done on our next release (next week at latest).

**Comment by pq** [comment]
Ah, cool.  Thanks @isoos !

**Comment by sortie** [comment]
This is now visible at https://pub.dartlang.org/packages/analyzer_cli

**Comment by pq** [comment]
Thanks for following up @sortie.  Oddly I'm not seeing anything different on the page?

![image](https://user-images.githubusercontent.com/67586/42695966-bcccca0c-866b-11e8-8604-dfa7d029e143.png)

**Comment by pq** [comment]
Thanks for the heads up!
