### ISSUE TITLE
Delete pub package "threejs_facade_test"

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/pub-dartlang-dart#1407]
_From @anders-sandholm on June 22, 2018 12:6_

_From @patlillis on June 21, 2018 17:35_

https://pub.dartlang.org/packages/threejs_facade_test

This was a temporary project that I was using to test some things. I didn't realize that there wouldn't be a way for me to delete it from pub.dartlang.org. There are no users, it's less than a week old, and clearly has the word "_test" in the name, so this shouldn't cause any problems.

I just found out about "publish_to: none" (https://stackoverflow.com/questions/25131100/how-to-prevent-accidental-publishing-of-a-private-pub-package), but alas it's too late :(

Thanks a lot for the help, much appreciated.

_Copied from original issue: dart-lang/sdk#33562_

_Copied from original issue: dart-lang/pub#1935_

**Comment by anders-sandholm** [comment]
_From @natebosch on June 22, 2018 17:44_

@anders-sandholm - for future reference `dart-lang/pub` is the client

@kevmoo - is  `dart-lang/pub-dartlang-dart` the appropriate repo for deletion requests?

**Comment by anders-sandholm** [comment]
_From @kevmoo on June 22, 2018 17:46_

>  is dart-lang/pub-dartlang-dart the appropriate repo for deletion requests?

Yup!

**Comment by anders-sandholm** [comment]
my bad... moving (again)

**Comment by isoos** [comment]
@sortie: there is a tool for it: `app/bin/tools/remove_package.dart`

**Comment by sortie** [comment]
Done. "dart app/bin/tools/remove_package.dart remove threejs_facade_test" was very slow but it eventually went through. It did complain about a missing local memcache.

It did say "WARNING: Please remember to clear the AppEngine memcache!" which I don't know how to do. It appears the page has been properly invalidated and no longer shows up. Does any further action need to be taken?

**Comment by isoos** [comment]
Removal LGTM.

There is a ["Memcache"](https://console.cloud.google.com/appengine/memcache) tab on the Google Cloud Console under the "App Engine" menu item, with a "Flush Cache" button. It nukes all the prod cache, but makes the serving consistent.

**Comment by sortie** [comment]
Should I do that now, then?

**Comment by isoos** [comment]
> Should I do that now, then?

Based on the requests I've checked, I think it may not be necessary, but it won't hurt either (except for a minimal perf hit for the subsequent few requests that won't hit cache and re-populate it).

**Comment by sortie** [comment]
Alright, done.
