### ISSUE TITLE
stagehand 3.0.0 defaults to snapshot 1.1 not 2

### ISSUE THREAD

**Issue by CarnivalRaid** [dart-lang/pub-dartlang-dart#1408]
URL: https://pub.dartlang.org/packages/stagehand#-versions-tab-

When dart2 dev sdk is installed, executing stagehand web-angular should use snapshot dart2.

Hello there. I have installed dart 2 64.1-1 and wanted to try angular 5. After doing a:
 "pub global activate stagehand" and "pub global activate webdev", i have errors on stagehand and webdev. I saw that errors appear because the script uses snapshots 1.1 from either two.
The error on stagehand web-angular command is: "..../.pub-cache/global_packages/stagehand/bin/stagehand.dart.snapshot:1:1: Error: Unable to decode bytes as UTF-8.
���ܶj "
The error in webdev is a bit more complicated for me to understand and way longer.
If I do manualy dart and pick the snapshots from bin that are ended with dart2 it works as expected.
I installed as indicated on the website in preview angular 5, dart2 sdk (dev).
OS: WattOS (it's a stripdown  version of Ubuntu 16.04.4 LTS -Xenial).

I want to appologise in advance. I am new to programming, github and reporting issues.(but i love what you are doing with dart and angular and flutter)
Great day, devs.

**Comment by isoos** [comment]
This issue was moved to dart-lang/stagehand#544
