### ISSUE TITLE
Track missing dev API documentation

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1417]
- [ ] version upgrades
- [ ] Job processing and notification

**Comment by mit-mit** [comment]
Can you clarify what this is?

**Comment by isoos** [comment]
> Can you clarify what this is?

During code reviews Jonas rightfully pointed out a few items that have no documentation and they are not evident from the code. I'll need to document either to process or change the code to make it clear what's happening there.
