### ISSUE TITLE
Roll to latest pana and dart sdk

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1427]

**Comment by isoos** [comment]
This is now blocked on at least two major issues:

- https://github.com/dart-lang/pana/issues/366: package analysis fails, which was not caught by the existing tests

- https://github.com/dart-lang/pub-dartlang-dart/pull/1423: can't get CI tests to pass. it fails at random points, sometimes with precompilation, sometimes a test times out, but so far never the same. locally it works great.
