### ISSUE TITLE
Users can't find packages to use with Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pub-dartlang-dart#143]
/flutter/plugins only shows packages which include iOS and Android code.

However users are interested in finding what packages they can use with Flutter, which is a much larger set.

My understanding is @kevmoo is working on a plan to find all of these, but in the short-term I think we can change /flutter/plugins to include all packages which have a direct dependency on sdk: flutter.

**Comment by isoos** [comment]
/cc @mkustermann 

I can detect `dependencies: / flutter: / sdk: flutter` the same way we do `flutter: / plugin: `, and `detectedTypes` could handle it similarly. Any considerations not to do it that way?

I'm not that familiar with the Flutter ecosystem, what is role of a published package that has the flutter dependency but does not define a plugin?

**Comment by eseidelGoogle** [comment]
I spoke with @mit-mit yesterday.  I suspect we should remove the packages/plugins distinction.  All Flutter plugins are dart packages.  Any "dart package" which does not depend on dart:html (or other dartium exports) likely "just works" in Flutter and could be considered a "flutter compatible package", however my understanding is that's difficult to determine statically from the pubspec.yaml alone (due to transitive dependencies).  So I think the simple solution here is to just broaden the definition of "flutter package" to include packages which explicitly depend on sdk/flutter, but don't need to require that they have ios or android code dependencies (i.e. they don't need flutter: plugin:).

**Comment by mit-mit** [comment]
@isoos would it be possible to generate a list of current packages in Pub that depends on just `flutter` (not flutter+plugin as we do currently)? I'd like to do a bit of manual inspection and validation before we go ahead and make the change on the site.

**Comment by isoos** [comment]
@mit-mit: #148 provides a script that gets you the list of the packages in question. (#146 is blocker for it though, that needs to be fixed too). @mkustermann or @kevmoo will be able to run it on prod data.

**Comment by mkustermann** [comment]
Running the script on production data produces the following stats:
```json
{
  "counters": {
    "total": 2602,
    "flutter": {
      "total": 23,
      "plugins": 15,
      "sdk": 22
    }
  },
  "flutter": {
    "plugins": [
      "battery",
      "firebase_analytics",
      "firebase_auth",
      "firebase_database",
      "firebase_messaging",
      "firebase_storage",
      "flutter_webview_plugin",
      "fullscreen_mode",
      "google_sign_in",
      "image_picker",
      "path_provider",
      "share",
      "shared_preferences",
      "url_launcher",
      "video_launcher"
    ],
    "sdk": [
      "Flutter_Nectar",
      "battery",
      "css_colors",
      "firebase_analytics",
      "firebase_auth",
      "firebase_database",
      "firebase_messaging",
      "firebase_storage",
      "fluro",
      "flutter_built_redux",
      "flutter_flux",
      "flutter_markdown",
      "flutter_stream_friends",
      "flutter_webview_plugin",
      "fullscreen_mode",
      "google_sign_in",
      "image_picker",
      "path_provider",
      "share",
      "shared_preferences",
      "url_launcher",
      "zoomable_image"
    ]
  }
}

```

**Comment by isoos** [comment]
It looks like the `video_launcher ` is the only package that depends on flutter, but does not specify `sdk: flutter` inside:
https://github.com/rxlabz/flutter_video_launcher/blob/master/pubspec.yaml

The SDK ones without being a plugin: 
- `Flutter_Nectar`
- `css_colors`
- `fluro`
- `flutter_built_redux`
- `flutter_flux`
- `flutter_markdown`
- `flutter_stream_friends`
- `zoomable_image`

**Comment by mit-mit** [comment]
I fixed `video_launcher` in https://github.com/rxlabz/flutter_video_launcher/commit/01f5579485fe7f98de4484e1dbd05a51c39bd86c#diff-fb2d52cd953afedcafc9fe7629c6f132

**Comment by mit-mit** [comment]
I suggest the following path forward short-term:

1. Go ahead and analyze `dependencies: / flutter: / sdk: flutter` and tag those as `flutter_package`. 

1. Keep current tagging for `flutter_plugin` intact; we will need this later for search

1. Create a new page https://pub.dartlang.org/flutter/packages. This should display all package tagged `flutter_package` or `flutter_plugin` (i.e. both flutter packages and plugins).

1. Redirect from https://pub.dartlang.org/flutter/packages to https://pub.dartlang.org/flutter/plugins

Longer-term these static lists should be replaced with a nice and comprehensive search interface that makes this all clearer, but we can deal with that in due time.

@kevmoo @sethladd WDYT?

**Comment by eseidelGoogle** [comment]
@mit-mit I think you meant from /plugins -> /packages in item 4.

**Comment by mit-mit** [comment]
I did, thanks, fixed!

**Comment by sethladd** [comment]
I agree that there should be a single list of all packages that work with Flutter. I'm willing to invest in the long-term solution. I'd like to ask @kevmoo to track all these requirements and update us on the plan soon.

**Comment by kevmoo** [comment]
@eseidelGoogle @mit-mit – let's coordinate in the design doc for this...

**Comment by sethladd** [comment]
Thanks!
