### ISSUE TITLE
Ugly dependency strings

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub-dartlang-dart#1430]
I'm updating the [shared packages tutorial](https://www.dartlang.org/tutorials/libraries/shared-pkgs#name-the-package-dependencies), and I happened to notice that the "Depend on it" example in pub.dartlang.org now uses double quotes with `^`. For example:

![image](https://user-images.githubusercontent.com/2164483/42249990-2d4cb94e-7ee3-11e8-8a0c-0d17c1f2d235.png)

This looks really ugly to me, and I don't think the quotes are necessary. (Did they used to be there?) So I fudged it in my doc, hoping you'd change:

![image](https://user-images.githubusercontent.com/2164483/42249972-140237d4-7ee3-11e8-8b35-777a645c054a.png)

So... how about it? Is there a good reason to have the quotation marks there? If so, could we at least make them single quotes, like all our other pubspec examples?

Thanks!

**Comment by isoos** [comment]
@kwalrath: there is no special reason for the double quotes, removing them in #1432.

**Comment by kwalrath** [comment]
Thanks, @isoos!
