### ISSUE TITLE
What if the name I want use for my package has been used

### ISSUE THREAD

**Issue by entronad** [dart-lang/pub-dartlang-dart#1433]
Is any one can publish a package freely according to [doc](https://www.dartlang.org/tools/pub/publishing) ?
If so, What will happen if the name I want use for my package has been used, since I find you just need to specify the name while using a public package:
```
dependencies:
  transmogrify: ^1.0.0
```
So do I need to publish an empty package with my favorite name in case others will use it?

**Comment by isoos** [comment]
> Is any one can publish a package freely according to doc ?

Yes.

> What will happen if the name I want use for my package has been used, since I find you just need to specify the name while using a public package.

You shall choose another name.

> So do I need to publish an empty package with my favorite name in case others will use it?

In this community people won't admire you for your empty packages, but they will admire your abilities to code: a package gets popular because it provides value, not because it is has a cool name. Please do not name-squat packages just because you think the name is cool, focus on the value a package can provide instead.

**Comment by isoos** [comment]
> often makes people confused

If you visit pub.dartlang.org, you will notice a circle + number in several places for the packages. We are using static analysis for code quality + popularity to get that number to the user, and it should solve a certain class of problems that you have mentioned, e.g. if there are two packages with similar names, the score should give you the indication for the more popular/better code quality one.

In other cases, people are using [package prefix](https://pub.dartlang.org/packages?q=package%3Ajaguar_) to collect all the related packages into a single namespace. This is an area that we are looking to improve, /cc @mit-mit for taking notes about the namespacing.

Another anecdote: I've seen a package that was not actively developed, and I was missing some features from it. Reaching out to the author allowed me to take it over completely. People are in general nice :)

**Comment by entronad** [comment]
I have noticed the score circle at the first glance on pub.dartlang.org, and find you can sort search results by it. It is a great idea!

The package prefix may have limited effects I'm afraid, for it seems people haven't know about this informal rule and like to use the prefix "flutter_" :)

So I'm very settled and glad to hear that your are looking to improve the namespace area. I personally believe that, although a little bit verbose, a well-designed and forcing namespace rule to specify the author is a good way to solve name-squat and conflict.

In the conversation with you, I find developers of dart community are really nice. But one day, when dart becomes widely used as  JS and big companies enter the pub.dartlang.org(I think such day will surely come), things may become complicated. So have a preparation is always a good idea.

Thanks, wish dart community more and more better!
