### ISSUE TITLE
Multiple examples

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/pub-dartlang-dart#1434]
I think the example/example.dart is always a really useful thing to see when checking out a package. For my package I have multiple examples however it didn't pick them up and I was advised to rename it to main.dart or example.dart.

If you had the following examples they could be displayed as sub-tabs? or as a tree menu? 

* `example/simple.dart`
* `example/kitchen_sink.dart`
* `example/specific_feature.dart`
* `example/really_cool_thing.dart`

Or if you want more control over specific examples how about listing anything that fits this pattern: `example/example_$name.dart`

For Angular, you could have `example_service.dart`, `example_directive.dart`, `example_component.dart` etc.

**Comment by mit-mit** [comment]
Triage discussion: Let's change our example logic to also look for a file `example/readme.md`. If this exists, show the contents of that in the Example tab on Pub. This would allow publishers to use that to enumerate their various examples.

**Comment by isoos** [comment]
I've checked, and once https://github.com/dart-lang/pana/pull/421 lands, we'll need to:
- re-run `bin/tools/backfill_examples.dart` (no further changes needed)
- the template rendering will pick it up (no further changes needed).

**Comment by sortie** [comment]
Yes, this change was part of pana 0.12.5 which is in pub production. @isoos I guess we'll want to run the script then? Are there any pages that show the wrong contents that we can look at before & after to verify it's working?

**Comment by isoos** [comment]
I believe @jonasfj started to run the backfill examples script. We should be able to close the issue once it is done.

**Comment by isoos** [comment]
@jimmyff: pub now recognizes `example/readme.md` and if you have it, it will be shown on the example tab.

As the backfill completed, I'm closing the issue. Thanks @jonasfj!
