### ISSUE TITLE
device_calendar not building in xcode 9

### ISSUE THREAD

**Issue by blaneyneil** [dart-lang/pub-dartlang-dart#1435]
URL: https://pub.dartlang.org/packages/device_calendar#-example-tab-

just a head's up:

The target “device_calendar” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

**Comment by isoos** [comment]
@blaneyneil: please file issues to the package's repository. You can check that on the package page, usually the homepage points to it. I'm moving this now.

**Comment by isoos** [comment]
This issue was moved to builttoroam/flutter_plugins#61
