### ISSUE TITLE
angular_cli v0.1.2 (2017-10-09) failed to precomp under Dart2

### ISSUE THREAD

**Issue by pet-ro** [dart-lang/pub-dartlang-dart#1441]
URL: https://pub.dartlang.org/packages/angular_cli

<Describe your issue or suggestion here>
I'm a newbie to Dart2. 
As angular_cli v0.1.2 (2017-10-09) is uploaded before Dart2 publishing date,
it must fail. Right?

Or are there other reasons for these errors:

Failed to precompile angular_cli:bin\ngdart:
file:///<my-path>/pub.dartlang.org/analyzer-0.30.0+4/lib/src/dart/element/element.dart:4968:5: Error: Declared type variables of 'GenericFunctionTypeElementIm
pl::accept' doesn't match those on overridden method 'Element::accept'.
  T accept<T>(ElementVisitor<T> visitor) {
    ^
file:///<my-path>/pub.dartlang.org/analyzer-0.30.0+4/lib/src/dart/element/element.dart:4968:33: Error: The parameter 'visitor' of the method 'GenericFunctionT
ypeElementImpl::accept' has type analyzer.dart.element.element::ElementVisitor<analyzer.src.dart.element.element::GenericFunctionTypeElementImpl::accept::T>, which does not match the corresponding
 type in the overridden method (analyzer.dart.element.element::ElementVisitor<dynamic>).
Change to a supertype of analyzer.dart.element.element::ElementVisitor<dynamic> (or, for a covariant parameter, a subtype).
  T accept<T>(ElementVisitor<T> visitor) {
                                ^
file:///<my-path>/pub.dartlang.org/analyzer-0.30.0+4/lib/src/cancelable_future.dart:255:17: Error: Declared type variables of '_CancelableCompleterFuture::the
n' doesn't match those on overridden method 'Future::then'.
  Future/*<S>*/ then/*<S>*/(FutureOr/*<S>*/ onValue(T value),
                ^
file:///<my-path>/pub.dartlang.org/analyzer-0.30.0+4/lib/src/cancelable_future.dart:255:17: Error: The return type of the method '_CancelableCompleterFuture::
then' is dart.async::Future<dynamic>, which does not match the return type of the overridden method (dart.async::Future<dart.async::Future::then::R>).
Change to a subtype of dart.async::Future<dart.async::Future::then::R>.
  Future/*<S>*/ then/*<S>*/(FutureOr/*<S>*/ onValue(T value),
                ^
file:///<my-path>/pub.dartlang.org/analyzer-0.30.0+4/lib/src/cancelable_future.dart:292:17: Error: Declared type variables of '_WrappedFuture::then' doesn't m
atch those on overridden method 'Future::then'.
  Future/*<S>*/ then/*<S>*/(FutureOr/*<S>*/ onValue(T value),
                ^
file:///<my-path>/pub.dartlang.org/analyzer-0.30.0+4/lib/src/cancelable_future.dart:292:17: Error: The return type of the method '_WrappedFuture::then' is dar
t.async::Future<dynamic>, which does not match the return type of the overridden method (dart.async::Future<dart.async::Future::then::R>).
Change to a subtype of dart.async::Future<dart.async::Future::then::R>.
  Future/*<S>*/ then/*<S>*/(FutureOr/*<S>*/ onValue(T value),
                ^
file:///<my-path>/pub.dartlang.org/front_end-0.1.0-alpha.4.1/lib/src/fasta/util/link.dart:117:19: Error: The parameter 'f' of the method 'Link::every' has typ
e (dynamic) â†’ dart.core::bool, which does not match the corresponding type in the overridden method ((fasta.util.link::Link::T) â†’ dart.core::bool).
Change to a supertype of (fasta.util.link::Link::T) â†’ dart.core::bool (or, for a covariant parameter, a subtype).
  bool every(bool f(T)) {
                  ^
file:///<my-path>/pub.dartlang.org/front_end-0.1.0-alpha.4.1/lib/src/fasta/util/link.dart:141:5: Error: The method 'Link::singleWhere' has fewer named argumen
ts than those of overridden method 'Iterable::singleWhere'.

**Comment by isoos** [comment]
@pet-ro: this repository is for issues with pub.dartlang.org, and not individual packages, please file the issues on the package's repository.

**Comment by isoos** [comment]
@pet-ro: I can't move the issue, please contact the authors directly.
