### ISSUE TITLE
Front page doesn't need to tell me the date a package was updated. :)

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pub-dartlang-dart#145]
The current front page gives a list of the most recently updated packages.  But the date column is always today, since packages are updated hourly.  Seems silly.

Probably the right way to resolve this is to do a redesign of the front page in general.

**Comment by filiph** [comment]
Hi Eric, Seth and Kevin and I are working on a full redesign, and Istvan is implementing it. Happy to give you details.

**Comment by eseidelGoogle** [comment]
@filiph yup!  I'm fully aware (and I think I have access to some of the details).  I was asked to better communicate (via issues) Flutter's needs from pub, so doing so. :) . Please always feel free to close my issues if they're not useful or tracked via other means!

**Comment by filiph** [comment]
No, this is great. I just wanted to make sure we're all on the same page.

This is definitely an issue to keep.

**Comment by kevmoo** [comment]
@mit-mit this is a like-to-have for @eseidelGoogle, but is not flutter-specific. Removed tag.

**Comment by isoos** [comment]
The V2 design solved this. Sorting in the updated time order will be available, but won't be the default.
