### ISSUE TITLE
Awaiting analysis taking quite some time

### ISSUE THREAD

**Issue by tiagojencmartins** [dart-lang/pub-dartlang-dart#1450]
URL: https://pub.dartlang.org/packages/unicorndial

The package is awaiting for the analysis to complete for ~2 hours. Any problem?

**Comment by isoos** [comment]
We are in the middle of a deploy that was suspended after partial deploy. Apologies, we expect to resume it tomorrow, until then it will probably stay like that (for the packages that are published in this period).
