### ISSUE TITLE
retrieveDynamicLink() is always null

### ISSUE THREAD

**Issue by blaneyneil** [dart-lang/pub-dartlang-dart#1451]
URL: https://pub.dartlang.org/packages/firebase_dynamic_links

i'm using version 0.0.5 and on iOS.  i haven't ever been able to use:

`
final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.retrieveDynamicLink();
`
and get a non-null value for that data var.  that includes clicking on links i've generated in the firebase console, and thru buildUrl() and/or manually.  it doesn't matter if the app is open in the bg, closed, or coming out of a hard reboot.  and i've used both the simulator and a real device, and clicked on the link from sms and email.

generating links works as expected, and clicking on the link(s) always opens the app as expected (everything is configured properly in firebase and xcode).  to make sure i wasn't missing anything i reduced my app to this entry point:

```
void main() async {

  final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.retrieveDynamicLink();
  print('main link = $data');

  runApp(MaterialApp(
    home: new LinksTest(data: data),
  ));

```

and rendered LinksTest like so:

```
import 'package:flutter/material.dart';

class LinksTest extends StatelessWidget {
  var data;
  LinksTest({this.data});

  @override
  Widget build(BuildContext context) {
    return new Center(
      child: new Text(data.toString(), style: new TextStyle(color: Colors.white, fontSize: 14.0)),
    );
  }
}
```

no matter what i do, the app always opens but data is always null.

**Comment by isoos** [comment]
@blaneyneil: please file such request to the package's repository, in this case flutter/flutter. I'm moving this now.

**Comment by isoos** [comment]
This issue was moved to flutter/flutter#19506
