### ISSUE TITLE
/api/packages/versions/newUploadFinish logs warning if package is already uploaded

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1456]
The /api/packages/versions/newUploadFinish API logs a warning if a package is already uploaded:

    pubserver.shelf_pubserver: An error occured while finishing upload
    
    Error:
        Exception: Version 0.6.0 of package exifdart already exists.

I don't believe this matters enough to us that we log a warning, the uploader gets the warning and can figure out the problem. Can we demote this case to an info? Of course, if any other unexpected upload error happens, we should log a error/warning.

**Comment by isoos** [comment]
I think the log event comes from `package:pub_server`, from [this line](https://github.com/dart-lang/pub_server/blob/master/lib/shelf_pubserver.dart#L334). There seem to be legitimate cases where this event warrants a logger.warning.

However, if there were special exception types for errors that are supposed to be corrected by the user, the same code block could differentiate between the log levels.
