### ISSUE TITLE
PUB package management for Angular is down?

### ISSUE THREAD

**Issue by fallenreaper** [dart-lang/pub-dartlang-dart#1457]
All, I am not sure what is going on with the pub package manager.  It seems that I can search for packages, but when I do `pub get` it was throwing an error:
```
HTTP error 500: Internal Server Error at https://pub.dartlang.org/api/packages/angular.
This is likely a transient error. Please try again later.
```
When I went to pub.dartlang.org it showed and I could search for angular, but when I try to access it, it will also return an error, printed below:

```
Pub is not feeling well
Fatal package site error.

Please open an issue: https://github.com/dart-lang/pub-dartlang-dart/issues/new

Add these details to help us fix the issue:

Requested URL: https://pub.dartlang.org/packages/angular
Request ID: 096000c837ab3e8ad16d58c8219407fc
```

**Comment by sortie** [comment]
Hello. There were a few issues with the latest version of the pub service and we had to roll it back. Thank you for letting us know. Our internal alerts went off and we're currently looking at the logs to understand what happened.

**Comment by fallenreaper** [comment]
Ah, that makes sense. I did see it came back up.  Thank you for following up.
