### ISSUE TITLE
Error in android devices

### ISSUE THREAD

**Issue by SaiKarthikMalyala** [dart-lang/pub-dartlang-dart#1461]
URL: https://pub.dartlang.org/packages/url_launcher

When I tried to open .pfd and .docx files in android devices it exist displaying the blank black screen.

The same files when I opened the Iphone they are opened.

**Comment by isoos** [comment]
@SaiKarthikMalyala This repository is for the pub site, please submit your issues to the package's issue tracker. I'm moving it this time.

**Comment by isoos** [comment]
This issue was moved to flutter/flutter#19413
