### ISSUE TITLE
Analysis does not complete

### ISSUE THREAD

**Issue by janmiga** [dart-lang/pub-dartlang-dart#1471]
Package: https://pub.dartlang.org/packages/platform_aware

I uploaded this package 3 hours ago. While documentation was generated forthe latest Version, the analysis does not complete with no indication of errors

**Comment by isoos** [comment]
@janmiga: I'm sorry, we are halfway through a new release, which has stability issues. Your package will get analyzed after the release is either finalized or reverted, but it is hard to tell when this will happen.

**Comment by janmiga** [comment]
Wow, thank you for the quick response, this resolves my issue already

Maybe you should put a maintenance indicator on the site
