### ISSUE TITLE
Mark pkg:browser as discontinued

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1475]
URL: https://pub.dartlang.org/packages/browser

Thanks!

**Comment by kevmoo** [comment]
CC @mit-mit

**Comment by sortie** [comment]
Done. The analyzer bots will soon reanalyze the package and update the website. Current refactoring work will make this change more instantaneous. Closing now and verifying later that it as indeed marked as discontinued.
