### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by lisabiya** [dart-lang/pub-dartlang-dart#1479]
URL: https://pub.dartlang.org/packages/video_player

<Describe your issue or suggestion here>
should be ：
_controller.value.isPlaying
              ? _controller.pause()
              : _controller.play(),

**Comment by isoos** [comment]
@lisabiya: this is an issue tracker for the pub site. Please file the issues to the package's repository, in this case you should use https://github.com/flutter/flutter

Another thing: please be more specific about the issue's context, I have no idea where this is applied.
