### ISSUE TITLE
Discontinue (delete) flutter_stripe

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1496]
URL: https://pub.dartlang.org/packages/flutter_stripe

Seems the author is not wanting this to stick around?

**Comment by isoos** [comment]
Maybe it was only a specific version that was the issue? @hkm-ricky-lau ?

**Comment by isoos** [comment]
https://github.com/dart-lang/pub-dartlang-dart/issues/1494
