### ISSUE TITLE
Mark old Flutter packages as discontinued

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1502]
The following packages are no longer relevant, and can be marked discontinued:

https://pub.dartlang.org/packages/playfair
https://pub.dartlang.org/packages/flx
https://pub.dartlang.org/packages/flutter_firebase
https://pub.dartlang.org/packages/sky
https://pub.dartlang.org/packages/sky_services
https://pub.dartlang.org/packages/sky_engine
https://pub.dartlang.org/packages/flutter_services
https://pub.dartlang.org/packages/sky_tools
https://pub.dartlang.org/packages/cassowary

**Comment by Hixie** [comment]
I think cassowary could still be useful if anyone wants to use it. The others are definitely obsolete.

**Comment by mit-mit** [comment]
cassowary looks very broken; it we are to keep it, we should fix it:
https://pub.dartlang.org/packages/cassowary#-analysis-tab-

**Comment by lukef** [comment]
I'm not sure if they're related or not but what about the `quiver_<some module>` packages? I know `quiver` seems quite active. Has it fully replaced those other ones? Seems so..

**Comment by sortie** [comment]
I marked all the packages (except cassowary) in the initial post as discontinued. The website will soon be automatically updated. Closing. Please reopen if any more packages needs to be discontinued.
