### ISSUE TITLE
Need to update SDK version where dartdoc is running

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pub-dartlang-dart#1504]
Generating docs for packages when they require an SDK version >2.0.0-dev.69.3

For example: https://pub.dartlang.org/documentation/angular_forms/latest/log.txt

cc @kevmoo

Related: https://github.com/dart-lang/pana/issues/384

**Comment by kevmoo** [comment]
@isoos @sortie @mit-mit – this is pretty critical. All of the angular packages have broken analysis!

**Comment by kevmoo** [comment]
See also 
https://pub.dartlang.org/packages/aqueduct/#-analysis-tab-

CC @timsneath

**Comment by mit-mit** [comment]
Istvan is on it. I suspect this is less likely to happen going forward with 2.0 now in stable? If not, we need to change our processes so that we can be more proactive about changes like this.

**Comment by mit-mit** [comment]
There are two separate issues here:

### 1: Packages that depend on dev.69.5

Pub is on dev.69.3. I'm not sure why these packages were pegged on 69.5, but these are the only ones that do that, and thus the only ones failing:

angular	>=2.0.0-dev.69.5 <3.0.0
angular_forms	>=2.0.0-dev.69.5 <3.0.0
angular_test	>=2.0.0-dev.69.5 <3.0.0
angular_compiler	>=2.0.0-dev.69.5 <3.0.0
angular_ast	>=2.0.0-dev.69.5 <3.0.0
tonic	>=2.0.0-dev.69.5 <3.0.0

This is a temporal issue, will be resolved by the issue below.

### 2: Packages that depend on 2.0 stable or later

There are 43 of these currently, but of course this number will grow rapidly.

I think the solution is two staged:

1) Change pub to 2.0 stable (issue #1505). Yes, this will trigger failures in packages that don't work in Dart 2, but we are generally looking pretty good in the top packages
2) Consider if we want to still have analysis for Dart 1, and if so run in a dual SDK setup

**Comment by kevmoo** [comment]
A crazy idea – sniff the pubspec before running `pub get`. If the pubspec requires an SDK after the current one, use `_PUB_SDK_ENVIRONMENT` – or whatever it is – to pretend to be a compatible SDK and run anyway?

**Comment by mit-mit** [comment]
This has been resolved:

https://pub.dartlang.org/packages/aqueduct#-analysis-tab-
https://pub.dartlang.org/packages/angular#-analysis-tab-
https://pub.dartlang.org/packages/tonic#-analysis-tab-
