### ISSUE TITLE
Ensure we have fresh data in the staging site

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1509]
Staging has an old set of packages. Can we move the latest data from production into staging? @isoos says it is done by exporting a large file and importing it in staging. Can this be automated in a reasonable / occasional manner?

@mkustermann Perhaps you know more?

**Comment by mkustermann** [comment]
It's up to you to decide how often you would like to do an export of the data (and import to -dev project). Not sure if it's necessary to have -dev beign always close to the prod version. The export/import can be done via the cloud console under datastore admin.

Regarding automating this process, it is recommended to follow the [instructions here](https://cloud.google.com/datastore/docs/export-import-entities).

**Comment by isoos** [comment]
We also have this: https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/bin/tools/copy_data.dart

@mkustermann: was this ever used for copying?

**Comment by mkustermann** [comment]
Yes, I think I did use it at some point.

**Comment by isoos** [comment]
@sigurdm: would it be possible (and easy) to automate the restore-from-backup procedure you did in staging last week?

**Comment by sigurdm** [comment]
I believe it should be possible - when we have implemented the backup-as-chron-job, it could run the restore-to-staging as part of the process.

**Comment by sigurdm** [comment]
Basically I was running a `gcloud datastore import` and a `gsutil -m cp -r` command. But with the staging site being my project.

**Comment by isoos** [comment]
@sigurdm: do you see any further work with this, or can we close the issue?

**Comment by sigurdm** [comment]
@jonasfj thinks we should only run restore-to-staging manually as the data model might be different between staging and production.
The playbook covers how to restore to staging.
So I guess we can close this.
