### ISSUE TITLE
Add an 'Issues' link below the 'Homepage' link

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1522]
Make it easier for package consumers to file issues.

Ideas for realization:
  * Add a new field to `pubspec.yaml`
  * If field is unset: Deduce the Issue tracker link for the case where we have a GitHub link

**Comment by sortie** [comment]
Aqueduct, for instance, is hosted on github but has its homepage set to its actual homepage. We should consider adding a 'Repository' field to the `pubspec.yaml` while we're doing this, so the issue tracker can be deduced in such cases.

**Comment by sortie** [comment]
The pub client could at upload time check if there is a git remote, if so, suggest the pubspec.yaml contains the right repository value.

**Comment by isoos** [comment]
One note for #1675: I've prepared the issue tracker link pointing to the list of issues, and not to the "new issue page". Both GitHub and GitLab would ask the user to authenticate, and I thought that it is better UX to point to a page that won't redirect immediately.

**Comment by isoos** [comment]
Known issue trackers are now exposed on the UI. However, IIRC, adding a new keyword to `pubspec.yaml` may require a bit more coordination. @nex3 @kevmoo: what's the process there?

**Comment by kevmoo** [comment]
We should create a (short) doc and socialize it a bit. We should be clear about what this field is for, valid values, etc

It requires updates to (at least) docs (cc @kwalrath ) and https://pub.dartlang.org/packages/pubspec_parse

We might want to consider some minimal validation in the pub client, too – at least during publish

@nex3 – can you think of any other place?

**Comment by nex3** [comment]
Not off the top of my head.

**Comment by kwalrath** [comment]
When do we want to update the docs?

**Comment by mit-mit** [comment]
Two new fields:

`repository`: Optional field to specify the source code repository of the package. Useful when a package has both a home page and a repository.

`report_issue`: Optional field to a web page where developers can report new issues.

**Comment by kwalrath** [comment]
I think I expected issue_tracker, not report_issue. Tha is, I expected a link to the issue tracker (e.g. https://github.com/dart-lang/angular/issues), not specifically a new-issue page (e.g. https://github.com/dart-lang/angular/issues/new).

**Comment by mit-mit** [comment]
Sure, but isn't the 'report' issue link/action pretty clear (and will do the redirect) once you have made it to the issue tracker?

**Comment by isoos** [comment]
Sure. On last thing to defend it on our page: 'Report an issue [with the package]' is more straightforward than 'issue tracker' for people that have issues using a package. This goes back to the mis-filed issues we did got on our issue tracker, because of the 'Report an issue' link in the footer (which should be extended with 'with the pub site') string soon.

**Comment by mit-mit** [comment]
I think we could consider using a link called 'View/report issues [with the package]' even if that just linked to the issue tracker

**Comment by isoos** [comment]
sgtm. I'll remove the extra one.

**Comment by isoos** [comment]
'View/report issues with the package' is a bit too long, we are hitting a word-wrap with it (see image):

<img width="292" alt="screen shot 2018-11-09 at 13 15 41" src="https://user-images.githubusercontent.com/4778111/48262124-ac442180-e421-11e8-8849-1070d07bc211.png">

Maybe just 'View issues with the package'?

**Comment by mit-mit** [comment]
Maybe just 'View/report issues' (the package part is kinda given in the box with the context)?

**Comment by isoos** [comment]
That looks good:

<img width="305" alt="screen shot 2018-11-09 at 13 39 28" src="https://user-images.githubusercontent.com/4778111/48263006-ee229700-e424-11e8-8e0b-8f39b6e8553f.png">

**Comment by kwalrath** [comment]
We should make the capitalization consistent. Sentence caps (instead of Title Caps) are all the rage: https://developers.google.com/style/capitalization

**Comment by isoos** [comment]
The two pending PRs will change the labels to:
- Homepage (or Repository if it is recognized as a GitHub or GitLab repo)
- View/report issues
- API reference

**Comment by isoos** [comment]
The change has been deployed. Back to the naming, how does this look (merged content from @mit-mit and @kwalrath and extended a bit):

- `repository`: Optional field to specify the source code repository of the package. Useful when a package has both a home page and a repository.

- `issue_tracker`: Optional field to a web page where developers can report new issues or view existing ones.

**Comment by isoos** [comment]
We've released a new pub site, which supports the value and also contains the `pana` checks for its existence.
