### ISSUE TITLE
difference between 'More Flutter packages' & 'Flutter-specific packages'? From main page ?!

### ISSUE THREAD

**Issue by slabo** [dart-lang/pub-dartlang-dart#1528]
If you follow the main page flutter.io >> click packages  >> https://pub.dartlang.org/flutter .. at the bottom, you have two links for more info.
**More Flutter packages...** or **Flutter-specific packages...**
![auto generated inline image 1 1](https://user-images.githubusercontent.com/419319/44033687-d5b70ce2-9f13-11e8-932f-39dc38044335.jpg)

I think that's a little confusing, especially for someone coming to read the documentation. I guess Flutter-specific packages just mean that it will be already included as part of the framework, core flutter packages that you don't specifically have to import. 
Those would be included just by the line:  **sdk: flutter** 

The other Flutter packages would be packages that work in the flutter framework but aren't mandatory. 

But I'm just guessing, really.

**Comment by mit-mit** [comment]
The former lists packages that we believe will work with Flutter (based on our analysis of their dependencies). The latter lists packages that depends on the Flutter SDK itself, and this will only work with Flutter (and not with AngularDart, Dart on the Server, Dart CLI  programs, etc.)

I discussed with a few, and we came up with these new strings. Would those be clearer?

* More Flutter-compatible packages
* More Flutter-only packages

**Comment by isoos** [comment]
@mit-mit: would this be specific to those Flutter links, or do we want to change the messaging on other places? Some examples:
- "Top Flutter packages" -> "Top Flutter-compatible packages"
- [on /web](https://pub.dartlang.org/web) : "More web packages" -> "More web-compatible packages"

**Comment by slabo** [comment]
how about 

- More Flutter-compatible packages
- More Flutter-**specific** packages

this way **Flutter-compatible** isn't limited to web technologies, since there's also server-side, and there might be more later.

**Comment by mit-mit** [comment]
@isoos, yes, this would be in general

@slabo our writers preferred the -only suffix over -specific as it more clearly explains that they will work with only Flutter. I'm not sure I understand your web/server comment; can you elaborate?

**Comment by slabo** [comment]
@mit-mit I think I'm misreading @isoos  comment. From what I understand, there are web, mobile, and server platforms built with Dart. For now, anything you write in flutter is only useful for mobile, but there might be web ports later. In which case, plugins could be useful there too.

**Comment by zoechi** [comment]
What about just merging them?
I don't see the benefit of having 2 different views for that.

**Comment by isoos** [comment]
> I don't see the benefit of having 2 different views for that.

Depends on the context of your search. Some searches are for a package or plugin that is specifically written for Flutter SDK, while other searches are looking for a XML/whatever library that happens to work on Flutter too. Both is a valid context and need to be addressed.

**Comment by zoechi** [comment]
No strong opinion, but 
why would I want to know if a package uses the Flutter SDK?
I want to know if I can use a package with specific features with my Flutter project,
but how the package implements the feature wouldn't concern me while searching.

**Comment by mit-mit** [comment]
> why would I want to know if a package uses the Flutter SDK

Because you are trying to create code shared among Flutter, Server, and/or Dart4Web; in that case you would not want to depend on Flutter-only, or Web-Only packages from the shared code, but Flutter-compatible, etc. code would be ok.

**Comment by zoechi** [comment]
> 'Flutter-compatible' is: doesn't require Flutter 

That sounds all but intuitive to me and not a way I would approach a search.
I would still need to do extra checks if it supports web and server.
