### ISSUE TITLE
Works in debug mode in Android phone but crashes in Release

### ISSUE THREAD

**Issue by sureshrr** [dart-lang/pub-dartlang-dart#1530]
URL: https://pub.dartlang.org/packages/pdf_viewer_plugin#-versions-tab-

Worked nicely in development in the virtual device as well as Android phone in debug mode. But when it is deployed in Google play, it installs but when launched,it crashes.
Commented all the code and then also it crashed in Google Play
Finally when it is completely uninstalled in flutter, it doesn't crash.
I love this plugin but why does it crash only on Release.

**Comment by sortie** [comment]
This issue was moved to lubritto/Flutter_Medias_Picker#3
