### ISSUE TITLE
<Summarize your issues here>Problem Inserting Data in a Table with Autoincrement id -postgresql2 0.5.1.

### ISSUE THREAD

**Issue by finsignaresv** [dart-lang/pub-dartlang-dart#1531]
URL: https://pub.dartlang.org/packages/postgresql2#-installing-tab-

There is an error when somebody try to insert data in a table that has an autoincrement id:

I/flutter ( 1922): Query error: pgpool9:30264:9 ERROR 23505 duplicate key value violates unique constraint "table_pkey".

Is possible to insert the first row in the table, but if you try to upload a second one you will have this error, because the id do not increase automatically.

I hope you can fix this error soon.

Best regards,

Francisco.

**Comment by sortie** [comment]
This issue was moved to tomyeh/postgresql#3
