### ISSUE TITLE
Split dartdoc generation from dartdoc serving

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1534]
Currently the same instances are both serving the dartdoc and generating the dartdoc. However, these are two very different tasks with different latency requirements. The dartdoc serving must be instantaneous, while the dartdoc generation can be preemptible and done in the background at whatever pleasurably pace we prefer. The current dartdoc service should be split into two, one that serves the dartdoc, and one that generates the dartdoc.

This will help us scale better. The dartdoc generation instances can be marked as preemptible, which makes them much cheaper, and we can have more during peak hours / when the whole dartdoc uncatalogued needs to be generated. They can't be marked preemptible as long as they are serving user requests, as we must always have at least one instance serving users.

This work (while optional) will help us accomplish #1521, as we can have more dartdoc instances when needed at the same cost.

**Comment by isoos** [comment]
Would you prefer to have the dartdoc serving as a separate `dartdoc-frontend` service, or make it as integral part of the `app` (frontend) instances?

**Comment by sortie** [comment]
Either could work. What drawbacks are there from putting it in the app instance?

**Comment by isoos** [comment]
> What drawbacks are there from putting it in the app instance?

Nothing much really, if by accident there were 20x dartdoc-related traffic, appengine should start new instances that would serve them.

**Comment by sortie** [comment]
I guess putting it in the app service makes sense then, avoids extra complexity and should scale just as well.

**Comment by isoos** [comment]
One thing that I've encountered and I'm not yet decided how to resolve: the `app` (frontend) service "sanitizes" the URLs (and in effect: removes the trailing `/` characters from the URLs), while the other services don't do such things. The documentation serving handler relies on that, and we'll need to modify one or the other.

**Comment by isoos** [comment]
I've deployed the new version to staging, including the `dispatch.yaml`, and verified that the default service (frontend) is now able to serve the dartdoc files.

**Comment by sortie** [comment]
Cool!

**Comment by sortie** [comment]
I have done nothing specific with `dispatch.yaml`. I've just deployed the four services as I've always done. Do I need to take any extra action regarding that file?

**Comment by isoos** [comment]
Yes, you'll need to deploy it:
```gcloud app deploy dispatch.yaml```

https://cloud.google.com/appengine/docs/standard/python/reference/dispatch-yaml

**Comment by sortie** [comment]
Done. It seems to work. We can close this issue then?

**Comment by isoos** [comment]
Thanks!
