### ISSUE TITLE
Increase cloud project quota

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1539]
If we are to speed up package analysis and dartdoc generation by having more machines, we will run out of quota. We should request more cloud quota so we can have a higher peak usage, while still using the same amount of CPU hours in total.

**Comment by sortie** [comment]
We can delay this to M10 if we're not investing in speeding up dartdoc/analysis.

**Comment by jonasfj** [comment]
I requested a quote increase, doubling the amount of resources we have...

We can easily ask for more if we need it, turn around was pretty quick.

**Comment by sortie** [comment]
Thanks Jonas, yeah it's pretty quick at least for projects this size
