### ISSUE TITLE
Error: the name image is defined in the libraries image.dat and image.dat

### ISSUE THREAD

**Issue by Erhie** [dart-lang/pub-dartlang-dart#1540]
if I declare
import 'package:flutter/material.dart';
import 'package:launcher_assist/launcher_assist.dart';
import 'dart:typed_data';
import '**package:image/image.dart**';

I get this error
on decloration
**Image xyz;**

How I can decide, **which library to use**,
if I declare an Image object?

Thank for advice
Erhy

**Comment by sortie** [comment]
This issue was moved to brendan-duncan/image#81
