### ISSUE TITLE
Get Error TwitterKit/TwitterKit.h file not found

### ISSUE THREAD

**Issue by lucyhoang** [dart-lang/pub-dartlang-dart#1542]
URL: https://pub.dartlang.org/packages/flutter_twitter_login

Hi, when i using this package with setting ios platform is 9, then i will get the error "TwitterKit/TwitterKit.h file not found".
It loaded TwitterKit v3.0 but the code logic using api of TwitterKit v2.8

**Comment by isoos** [comment]
This issue was moved to roughike/flutter_twitter_login#12
