### ISSUE TITLE
pub.utils: HTTP GET failed on https://dartdoc-dot-dartlang-pub.appspot.com/documentation/<...>/latest/pub-data.json (1 retry left) Error: TimeoutException after 0:00:10.000000

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1547]
I am seeing a lot of these errors for the search service in the logs. It seems to be for various packages, for instance, the below trace is for `navigate`. When I request the URL in question, it is slow. Should it be that slow?

<pre>
pub.utils: HTTP GET failed on https://dartdoc-dot-dartlang-pub.appspot.com/documentation/navigate/latest/pub-data.json (1 retry left)

Error:
    TimeoutException after 0:00:10.000000: Future not completed

Stack:
    #0      getUrlWithRetry (package:pub_dartlang_org/shared/utils.dart:333:16)
    <asynchronous suspension>
    #1      DartdocClient.getContentBytes (package:pub_dartlang_org/shared/dartdoc_client.dart:71:24)
    <asynchronous suspension>
    #2      SearchBackend.loadDocuments.<anonymous closure> (package:pub_dartlang_org/search/backend.dart:75:23)
    #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
    #4      ListIterator.moveNext (dart:_internal/iterable.dart:343)
    #5      Future.wait (dart:async/future.dart:385)
    #6      SearchBackend.loadDocuments (package:pub_dartlang_org/search/backend.dart:74:35)
    <asynchronous suspension>
    #7      BatchIndexUpdater._updateBatch (package:pub_dartlang_org/search/updater.dart:122:16)
    <asynchronous suspension>
    #8      BatchIndexUpdater.runTask.<anonymous closure> (package:pub_dartlang_org/search/updater.dart:91:9)
    #9      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #10     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #11     _rootRun (dart:async/zone.dart:1122)
    #12     _CustomZone.run (dart:async/zone.dart:1023)
    #13     _CustomZone.runGuarded (dart:async/zone.dart:925)
    #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
    #15     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #16     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #17     _rootRun (dart:async/zone.dart:1126)
    #18     _CustomZone.run (dart:async/zone.dart:1023)
    #19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
    #20     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
    #21     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
    #22     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
    #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
</pre>

**Comment by sortie** [comment]
Looks like 64 dartdoc instances are running, as I increased the upper limit as a test. I'll decrease it to 4 and see if that reduces the load.

**Comment by isoos** [comment]
yesterday I've profiled this a bit, and IIRC larger amount of the time was spent in listing the files int the directory of the entry files, e.g. `$packageName/$packageVersion/entry` on the dartdoc storage bucket. Not sure if it is because a storage issue or if they had more files there than usual.

**Comment by isoos** [comment]
May be unrelated, but I've also found this in the log files, printed on the stdout, and with that it is not showing up in the logs as error:

```
ERROR from frontend isolate #2: [type 'MemCacheError' is not a subtype of type 'String', package:memcache/src/memcache_native_connection.dart 749:11 MemCacheNativeConnection.onError
```

Not sure of the caller stack (hard to copy everything to here), but it seems it is related to `appengine` initialization:

```
package:memcache/src/memcache_native_connection.dart 711:41 MemCacheNativeConnection.connect
package:memcache/src/dialer.dart 58:57 Dialer._performSingleDial
===== asynchronous gap ===========================
[...]
package:appengine/src/appengine_internal.dart _initializeAppEngine
```

**Comment by sortie** [comment]
The search instances are hitting this a lot on https://dartdoc-dot-dartlang-pub.appspot.com/documentation/jaguar/latest/pub-data.json which takes 17 seconds.

**Comment by isoos** [comment]
I believe this can be closed:
- the original exception seems to be gone (there was a single entry in `search` in the past week)
- there are a few memcache errors, but not the cast error we had (mostly connect issues and too large content)
- accessing the pub-data.json above is much faster, and doc browsing feels faster
