### ISSUE TITLE
please delete test_barometer package

### ISSUE THREAD

**Issue by efortuna** [dart-lang/pub-dartlang-dart#1557]
I created a package over the weekend to test the package publishing workflow, but now I'd like to delete this package, so I don't pollute the package namespace. Can we please remove it? https://pub.dartlang.org/packages/test_barometer
Thank you!

**Comment by mit-mit** [comment]
@sortie can handle this!

**Comment by sortie** [comment]
It's a pub package removal, I know this!

Done!
