### ISSUE TITLE
My plugin still at awaiting status for along time

### ISSUE THREAD

**Issue by duytq94** [dart-lang/pub-dartlang-dart#1572]
URL: https://pub.dartlang.org/packages/intro_slider

Hello, first thanks for your time.
Yesterday I updated my plugin, but until now (more than 10 hours), it's still at [awating] status.
Is there something wrong with my plugin (previous, it just takes about 10 minutes).
Thanks!

**Comment by isoos** [comment]
Sorry for that, it is a known issue, but luckily: temporary.

We are upgrading the system to `pana` `0.12.0`, and it has a breaking change in the data format. In such breaking cases, we'll need to analyze all of the packages with the new format first, before switching the traffic to the new version, and unfortunately, this means that new uploads won't get analysis until then.

Your package will gets its analysis (chances are it already got it), but we'll need to make sure everything is ok before we switch the traffic.

**Comment by sortie** [comment]
I haven't switched the traffic yet for any of the services. Why is the existence of the new upcoming version having anything to do with the analysis of the existing version in production? Are they sharing a job queue? Can we make these wholly independent?

**Comment by isoos** [comment]
Yes, they are sharing the Job queue, and yes, there is a work in progress to make them independent (esp. their result needs to be independent, and that will be the ScoreCard model).

**Comment by AbdulRahmanAlHamali** [comment]
Thank you @isoos for the clarification. Is there an ETA for this to be done?

**Comment by Sh1d0w** [comment]
Hey guys. Same problem with my packages. Will the stats during the transition such as installs, updates etc count towards the overall rating after the transition? Also any ETA when it will be finished?

Thanks.

**Comment by isoos** [comment]
The stats are collected separately and won't be lost. The traffic will be migrated on Monday, until then we ask your patience.

**Comment by CaiJingLong** [comment]
It's Monday.
Any changed?

**Comment by AbdulRahmanAlHamali** [comment]
My package got analyzed successfully since yesterday, but I did push an upgrade to it, so that might be the reason why it worked

**Comment by CaiJingLong** [comment]
@AbdulRahmanAlHamali 
My package also publish on Sep 2, 2018. But the state is AWAITING.
I need changed version publish again?

**Comment by AbdulRahmanAlHamali** [comment]
I'm not sure actually, let's wait for the contributors' reply

**Comment by sortie** [comment]
Hi all. The deployment has happened and all your packages has been analyzed. As Istvan explained, we had an internal breaking change and this deployment was a little unusual. We're doing the internal refactoring so the new ongoing deployment doesn't interfere with the production system as we saw here. 

Please continue to let us if you experience any further issues, and I hope you enjoy using pub, dart & flutter.
