### ISSUE TITLE
does not display at sign on phone call

### ISSUE THREAD

**Issue by Fotima97** [dart-lang/pub-dartlang-dart#1573]
URL: https://pub.dartlang.org/packages/url_launcher#-readme-tab-

I am trying to call a number that contains # sign, but the dealer does not show # sign 
                    launch('tel:*150#');

**Comment by isoos** [comment]
@Fotima97: please file issues in the package's repositories, this tracker is for the pub site. I'm moving this now.

**Comment by isoos** [comment]
This issue was moved to flutter/flutter#21267
