### ISSUE TITLE
First search result has misaligned package score bubble in Firefox

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1579]
https://pub.dartlang.org/packages?q=test

When searching for a package in Firefox (tested on Linux: Firefox 52, and Firefox 61), it seems that the first package score bubble isn't properly aligned. The rest of them are properly aligned.

**Comment by isoos** [comment]
Mac+FF61 seems to be good. Could you please attach a screenshot?

**Comment by sortie** [comment]
![pub-dartlang-org-misaligned-score-bubble](https://user-images.githubusercontent.com/3636196/45077743-428c5c00-b0ee-11e8-946e-c1c82123b4ce.png)
