### ISSUE TITLE
Dart SDK version (2.1.0) is not supported by geolocation

### ISSUE THREAD

**Issue by markflarup** [dart-lang/pub-dartlang-dart#1580]
URL: https://pub.dartlang.org/packages/geolocation#-installing-tab-

I want to support geo location in an app, but after adding `geolocation: ^0.2.1` as a dependency the following error message is returned:

```
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because [APP] depends on geolocation >=0.1.1 which requires SDK version <2.0.0, version solving failed.
pub get failed (1)
```

Do you have a estimate for when it will be supported?

**Comment by isoos** [comment]
This issue was moved to loup-v/geolocation#44
