### ISSUE TITLE
Flutter image Crop crashes everytime on clicking crop icon

### ISSUE THREAD

**Issue by Shubham555** [dart-lang/pub-dartlang-dart#1584]
URL: https://pub.dartlang.org/

<Describe your issue or suggestion here>

**Comment by isoos** [comment]
@Shubham555 This repository is for issues with the pub site. If you have issue with a package, please go to the package's repository and file an issue there. Unfortunately I don't know which package you are referring to now, I can't move this issue, closing.

**Comment by Shubham555** [comment]
Sorry, my bad.
