### ISSUE TITLE
carousel is not working for upgraded flutter in my project.Do anyone can help me......?

### ISSUE THREAD

**Issue by ranjannisha** [dart-lang/pub-dartlang-dart#1593]
URL: https://pub.dartlang.org/packages/carousel
I upgraded my flutter today and got an issue 
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because breadfruit depends on carousel >=0.1.0 which requires SDK version <2.0.0, version solving failed.

**Comment by sortie** [comment]
This issue was moved to gbrvalerio/carousel#11
