### ISSUE TITLE
Improve the UX of filing an issue (pub site vs. package's issue tracker)

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1594]
We are about to land a change where the "Report an issue" link will ask a confirmation from the user that they want to report an issue agains the pub site, and not against a package. In the future, we'd like to provide a nicer, in-site dialog window that asks the same question in a more user-friendly way, and also redirects them to the package's issue tracker (if applicable).

**Comment by mit-mit** [comment]
Let's try to change the current 'Report an issue' link to 'Report an issue with this site', and no dialog box.
