### ISSUE TITLE
Expect search for BadKeyException would yield json_annotation towards the top

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1602]
URL: https://pub.dartlang.org/packages?q=BadKeyException

Do we take into account ClassCasing or memberCasing when sorting search results? Might be good to prioritize API search in these cases?

See https://pub.dartlang.org/documentation/json_annotation/latest/json_annotation/BadKeyException-class.html

**Comment by isoos** [comment]
@kevmoo: we've released a new version with the fix. Does this match your expectation?

**Comment by kevmoo** [comment]
Looks good!
