### ISSUE TITLE
dartdoc DetailedApiRequestError errors and warnings in the log

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1604]
I'm seeing a lot of these noisy warnings and errors in the dartdoc logs.

This one is common:

```
pub.job: dartdoc job error sequence_zip 0.8.5

Error:
    DetailedApiRequestError(status: 404, message: No such object: dartlang-pub--dartdoc-storage/sequence_zip/0.8.5/entry/22c1ab30-b612-45c3-ab76-dc8c65cc9243.json)
```

This one is rare:

```
pub.job: dartdoc job error browser 0.5.12

Error:
    DetailedApiRequestError(status: 500, message: Backend Error)
```

There's also this one, but that is an unrelated issue (can we avoid this race condition or silence it?)

```
pub.job: dartdoc job error overwrite 0.2.10

Error:
    The transaction was aborted.
```

**Comment by sortie** [comment]
`The transaction was aborted` also happens for the analyzer. If it's harmless, it shouldn't be an error. Should I make a separate issue about this error?

**Comment by isoos** [comment]
Slightly related, but since we no longer serve the dartdoc public content on the `dartdoc` service, the `search` service should be moved off of it too.

**Comment by isoos** [comment]
I think we can reduce the log level of the `The transaction was aborted` entries, but I'd keep the rest.

**Comment by isoos** [comment]
The 404 codes are now cleared from the logs, and only a few upload issues remained. Tracking the handling of those in https://github.com/dart-lang/pub-dartlang-dart/issues/1727.
