### ISSUE TITLE
pana/google_maps/3.3.2: `dartfmt` failed

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1605]
I'm seeing this recurring error in the analyzer logs:

```
pana/google_maps/3.3.2: `dartfmt` failed.
Exception: dartfmt on lib/ failed with exit code -15
Exceeded timeout of 0:02:00.000000

Error:
    Exception: dartfmt on lib/ failed with exit code -15
    Exceeded timeout of 0:02:00.000000
```

Seems this package is too big to format or it ran into some bad performance in dartfmt? Unclear how we should handle cases like this. It seems to be the only one.

**Comment by isoos** [comment]
Running `dartfmt` on that project takes about 1m 30s to complete on my Macbook with SSD, it is possible that it can exceed the 2-minutes timeout even on a slightly less powerful CPU or lower IOPS disk. I don't see a reason why we couldn't increase the timeout to eg. 5 minutes.

**Comment by isoos** [comment]
`google_maps` is now successful in the analysis, the `dartfmt` process was completed in 2 minutes 5 seconds.
