### ISSUE TITLE
Notes in markdown are rendered incorrectly

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#161]
The note just above 'Getting Started' rendered correctly on GitHub:
https://github.com/flutter/plugins/tree/master/packages/android_intent

But has some of the spaces missing on Pub:
https://pub.dartlang.org/packages/android_intent
![screen shot 2017-06-07 at 13 14 57](https://user-images.githubusercontent.com/13644170/26875720-85a48142-4b83-11e7-9407-647c3661548e.png)

**Comment by isoos** [comment]
Tracking markdown issues: https://github.com/dart-lang/markdown/issues/162

**Comment by kevmoo** [comment]
This fix has been deployed to the public site, @mit-mit

**Comment by mit-mit** [comment]
Looks good, thanks!
