### ISSUE TITLE
Could you public toMap() of Contact class

### ISSUE THREAD

**Issue by lucyhoang** [dart-lang/pub-dartlang-dart#1610]
URL: https://pub.dartlang.org/packages/contacts_service#-readme-tab-

Hi, could you public toMap function of Contact class?

**Comment by isoos** [comment]
@lucyhoang: this repository is for the pub site, please file issues to the package's repository. I'm moving this now.

**Comment by isoos** [comment]
This issue was moved to clovisnicolas/flutter_contacts#35
