### ISSUE TITLE
Pub help page links don't scroll to anchors

### ISSUE THREAD

**Issue by srawlins** [dart-lang/pub-dartlang-dart#1613]
Steps:

1. Visit https://pub.dartlang.org/packages/markdown#-analysis-tab-
2. Hover over "scoring" link. Chrome says this links to: https://pub.dartlang.org/help#scoring
3. Click link.

Expected:
* Browser should visit https://pub.dartlang.org/help and scroll to "#scoring."

Actual:
* Browser location reads: https://pub.dartlang.org/help#scoring; good I guess.
* But browser actually visits https://pub.dartlang.org/help, **staying at the top of the page.**

The anchor _does exist_; you can just reload (e.g. with CTRL+R) and you'll get the right scrolling behavior.

**Comment by sortie** [comment]
I can confirm that going straight to to <https://pub.dartlang.org/help#scoring> works, as well as reloading when on <https://pub.dartlang.org/help#scoring>. But as reported, following the link to the page doesn't scroll to the anchor.

**Comment by isoos** [comment]
Chrome on Mac: It is broken as described, however, if I click back and then forward, after 1 or 2 tries the scrolling usually works.

Firefox on Mac: works as expected.

Safari on Mac: works as expected.

**Comment by isoos** [comment]
It looks like this line prevents the scrolling:
https://github.com/dart-lang/pub-dartlang-dart/blob/master/static/js/script.dart#L231

On the first iteration it looks like the browser already scrolled to that position, our code returns, but the browser is still at the top.
