### ISSUE TITLE
Sort by on Flutter packages page doesn't work

### ISSUE THREAD

**Issue by Sly777** [dart-lang/pub-dartlang-dart#1626]
Requested URL: https://pub.dartlang.org/flutter/packages?q=map&sort=created
Request ID: 3db596e32b3f4b696ef67c8051b388e7

Hey all, I try to sort items by newest order but it always gives error somehow. I added the error details below.

**Comment by isoos** [comment]
It is not flutter specific, we have a NPE here:
https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/search/handlers.dart#L70

It occurs when there is a search query for text match, but the search is ordered by another dimension, e.g. created or updated timestamp.

**Comment by sortie** [comment]
I can reproduce the issue.

**Comment by sortie** [comment]
I've deployed the fix.
