### ISSUE TITLE
I will recieved data when come from firebase console

### ISSUE THREAD

**Issue by Pradipkoravi** [dart-lang/pub-dartlang-dart#1634]
URL: https://pub.dartlang.org/packages/firebase_messaging

{notification: {body: this is test notification.Run the following command to create the client for our notes app.This shou..., title: Test}, data: {ni: 1, text: notification, color: red, image: image ur, title: Test}}

but I need to get individual value from it

**Comment by isoos** [comment]
This issue was moved to flutter/flutter#22069
