### ISSUE TITLE
Search for "search" + recently updated returns an error.

### ISSUE THREAD

**Issue by derekdang** [dart-lang/pub-dartlang-dart#1635]
Requested URL: https://pub.dartlang.org/flutter/packages?q=search&sort=updated
Request ID: 5753385c5c2c4e1c9bfb007b8cebe91c

**Comment by isoos** [comment]
Thanks for filing it. Duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/1626, will be fixed once #1628 gets deployed (hopefully today).
