### ISSUE TITLE
First search result for "angular" is "dart:html" Why?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pub-dartlang-dart#1647]
URL: https://pub.dartlang.org/packages?q=angular

Seems like if you search for the package by name it should be the first result.

**Comment by isoos** [comment]
Note: (debugging with the PR#1631) I couldn't imagine why the `dart:html` would ever come up at all: the primary reason is the match on the word `rectangular` for the documentation of [CanvasRenderingContext2D](https://api.dartlang.org/stable/2.0.0/dart-html/CanvasRenderingContext2D/drawImageToRect.html). There are other matches on the word `angular` too (some method or field called `angularVelocity`).

**Comment by isoos** [comment]
Looks like #1631 won't help on this, as the SDK relevancy is high-enough that `dart:html` result won't go away, and because SDK matches are treated as priority and before the normal result, this will still show up.

SDK priority was done mostly on the assumption that results on SDK API methods are considered more relevant than a pub package. I'll need to re-do some of the ranking to merge the two result-set with proper scoring on relevancy match.

**Comment by jakemac53** [comment]
Ya I always see `dart:<core|async|io>` before even exact matches for packages. Definitely not what I was looking for ;).

I would argue an exact match for a package site should always be the first result.

**Comment by nshahan** [comment]
Another good example for this issue is searching for path: 
https://pub.dartlang.org/packages?q=path

**Comment by isoos** [comment]
This has been fixed and released.

**Comment by jakemac53** [comment]
Looks like the most general issue is resolved, I did try a search for `async` and was surprised to see `dart:svg` and `dart:html` appear above `dart:async`, but I don't know if it is worth trying to resolve that, as `async` is probably a special case (it probably appears in documentation a _lot_ for svg/html).

**Comment by isoos** [comment]
Good catch, it is worth to reopen the tracker.

**Comment by isoos** [comment]
The issue was that `dart:async` was not tokenized, and the package name was not matched. #1697 fixes that and also provides better results page.

**Comment by jakemac53** [comment]
great! I wonder if package:async or dart:async will show first now? I think either could be argued as valid so I don't know that it matters haha :D

**Comment by isoos** [comment]
The original issue got fixed, tracking some parts of `async` search in https://github.com/dart-lang/pub-dartlang-dart/issues/1726
