### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#1658]
https://stackoverflow.com/questions/52522252/show-hidden-package-on-pub?noredirect=1#comment91988656_52522252

**Comment by jifalops** [comment]
The packages are
https://pub.dartlang.org/packages/shared_theme and
https://pub.dartlang.org/packages/shared_theme_flutter.

**Comment by isoos** [comment]
@zoechi @jifalops: thanks for reporting, this looks like a bug in ranking/post-filtering. The search index picked up the package, but its overall rank is too low and it got removed from the search results even for the exact-package-name query. I'll take a look on it next week (I'm out for this week), please bear with us till then.

**Comment by jifalops** [comment]
This happened to another new package that had the max 50 rating. `pubspec_update`

**Comment by isoos** [comment]
It looks like the index didn't pick up the package, although there was an analysis for it.

**Comment by isoos** [comment]
Based on the logs and the debug URL, I think we have strong indication that the index update loop stopped.

**Comment by jifalops** [comment]
Package from about 12 hours ago still not showing up. https://pub.dartlang.org/packages/mdc_web

**Comment by isoos** [comment]
@jifalops Thanks for reporting it. I've checked the logs, and it seems that about two days ago we had exception in the indexing, and that could be related with this issue. The pending and some of the already merged PRs should help this, but we'll need to release a new version for the site. Hopefully it will be done in the following days.

**Comment by isoos** [comment]
I believe this got fixed in the past two release. Please open a new issue if this happens again.
