### ISSUE TITLE
Pub can't find code_transformers package versions

### ISSUE THREAD

**Issue by griggsrl** [dart-lang/pub-dartlang-dart#1660]
Original issue details: https://stackoverflow.com/questions/52541532/package-code-transformers-has-no-versions-that-match

I'm not sure what the issue is here with the code_transformers version detection but it appears that the pub query can't find the versions that my dependency needs. Looking at https://pub.dartlang.org/packages/code_transformers/versions the compatible versions do exist out there but may not be returning in the pub query. 

Is this potentially an issue with the index? Or another issue entirely? Any help is greatly appreciated.

Thanks,
Ryan

**Comment by isoos** [comment]
I think the pub site provides the correct version information:
https://pub.dartlang.org/api/packages/code_transformers

Moving this to pub client, as I suspect the issue might be there.

**Comment by isoos** [comment]
This issue was moved to dart-lang/pub#1988
