### ISSUE TITLE
Irrelevant search results at the top

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#1661]
It was mentioned that showing SDK entries in the pub search result was added recently.

I found myself several times with results like

![image](https://user-images.githubusercontent.com/405837/46197762-f4dccb00-c30a-11e8-85c0-27d7a0e2d294.png)

and do not understand what value the SDK results are supposed to provide here.

**Comment by isoos** [comment]
This will be improved once https://github.com/dart-lang/pub-dartlang-dart/pull/1653 and https://github.com/dart-lang/pub-dartlang-dart/pull/1631 lands. It is also similar to https://github.com/dart-lang/pub-dartlang-dart/issues/1658.

**Comment by zoechi** [comment]
Ok, I assumed it's work-in-progress. Just wanted to make sure it's known.

Another unrelated question:
Are there packages that aren't listed at all anymore in search results?
I was wondering a few times lately that searching for the exact name of a package didn't list it in the search result. It wasn't that important at that time and I moved on.
I think I saw a comment that packages with low reps aren't shown anymore. Is that true?

**Comment by isoos** [comment]
- discontinued packages are removed from the search index, those won't show up,
- otherwise, exact name match should show up, regardless of the score. If you encounter such, please file a bug about it.

**Comment by zoechi** [comment]
I think I saw this mentioned already, but don't remember details and Google didn't come up with anything useful.
How can a package be discontinued?

**Comment by isoos** [comment]
> How can a package be discontinued?

At the moment you'll need to open an issue here, and somebody will do it. We want to implement self-management (#1642) soon, which would also include the option where you can set this flag yourself.

**Comment by zoechi** [comment]
I see. Thanks. When I run into that again I'll report.

Just my experience. 
If I look up a package because I know it exists and then it doesn't show up in the result, I'd find that quite confusing.
I'd prefer discontinued packages still to be listed.
It might still be interesting to fork and update such a package if it turns out to be abandoned.

**Comment by isoos** [comment]
A new search backend has been deployed, and results should be more sane now.

@zoechi: I believe that the meaning of 'discontinued' is a strong indicator from the authors that they probably have a new package or the codebase is beyond hope. If you feel strong about getting those back in the index, please open a new issue, because I think it warrants a discussion before it gets done.

**Comment by zoechi** [comment]
@isoos looks much better now. 

>  the meaning of 'discontinued'

It was a bit annoying because I was not aware of that feature and didn't understand why it wasn't listed.
It doesn't seem too common to be worth a discussion now.
In case it becomes a real problem, I'll create an issue.

Thanks a lot for the fix and the information!
