### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by denchaihos** [dart-lang/pub-dartlang-dart#1673]
URL: https://pub.dartlang.org/packages/jwt#-versions-tab-
I  use sdk version >2
when use jwt   it conlick  below
Running "flutter packages get" in mobile-cockpit-ket-app...
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because kpi depends on jwt any which requires SDK version <2.0.0, version solving failed.
pub get failed (1)
Process finished with exit code 1

how to solve  thank.

**Comment by isoos** [comment]
@denchaihos: Unfortunately `package:jwt` seems to be not compatible with Dart 2. We'll have soon a release that will mark it as such.

I'm moving this to the repository of the package, and maybe the author could comment on his plans to update it.

**Comment by isoos** [comment]
This issue was moved to gmosx/dart-json_web_token#5
