### ISSUE TITLE
Backslashes from markdown files are missing

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/pub-dartlang-dart#169]
Markdown source:
https://github.com/dart-lang/path/blame/master/README.md#L100

[Rendered](https://pub.dartlang.org/packages/path):
![image](https://user-images.githubusercontent.com/3479527/27089366-347bdf30-506b-11e7-88bc-1553fbe393d8.png)

**Comment by kevmoo** [comment]
@srawlins Next time you're bored?

**Comment by kevmoo** [comment]
Actually, it looks like this is a bug in the path package markdown.

Even GitHub doesn't render this. https://github.com/dart-lang/path/blob/master/README.md#how-cross-platform-is-this
