### ISSUE TITLE
Review need for a rel='noopener noreferrer'

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#1692]
In particular for links with `target='_blank'`.

This would be a security concern. Enforcing all links have `rel='noopener'` might be a sane thing to do for added security.

This could also be mitigated by `disown-opener` in CSP headers (#1691), but that doesn't seem to be widely supported by browsers yet.

Regardless, so long as you can't login to the site this isn't critical yet, and so far most links I've seen don't have `target='_blank'`, but it would be neat harden security around these edges.

**Comment by isoos** [comment]
I've checked and we are using `target="_blank"` only at the navigation menu layout, linking to `flutter.io` and `www.dartlang.org`, and one additional landing blurb. It will be a quick change to fix these.

**Comment by jonasfj** [comment]
@isoos, can we file a new issue for figuring out how to prevent any new introductions of `target='_blank'` without `rel='noopener'` ?

I imagine that changes in dartdoc or analysis, or README.md's or markdown rendering, etc. could accidentally introduce this in the future. It would be a problem if the target of the link was controlled as it would give access to the page. In a future where people are logging into the pub site, that is a security risk.

Again, I'm more concerned with how can we prevent this from happening in the future, I don't think there is an immediate pants-on-fire security issue with this at the moment.

**Comment by isoos** [comment]
I've added a test to the pending PR that checks the template outputs on our internal test cases. As far as I can tell the `markdown` package does not generate `target="_blank"` links, and I'm not sure if any markdown processor would do it. (We do not take user-provided HTML snippets.)

Anyway, we could create either a template validation that happens each time we serve a page (or maybe, at some random subset of that), or do an external crawler/parser that check pages randomly. I think it is not that pressing concern, and would just put it in the backlog.

**Comment by jonasfj** [comment]
> I think it is not that pressing concern, and would just put it in the backlog

Absolutely, agree :)

But long term it might be something we could come back to and investigate. Like I said, I don't have solution to prevent this type of bug. Using `disown-opener` in CSP might be the best option, I assume browser will support that soon.
