### ISSUE TITLE
pub.analyzer_memcache: Couldn't set memcache entry for /keyclic_sdk_api/1.28.2/0.12.4

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1693]
The search instance logs are full of this warning.

```
pub.analyzer_memcache: Couldn't set memcache entry for /keyclic_sdk_api/1.28.2/0.12.4

Error:
    MemcacheError(status: Status(ERROR), message: Error storing item)

Stack:
    #0      MemCacheImpl.set.<anonymous closure>.<anonymous closure> (package:memcache/src/memcache_impl.dart:215:9)
```

What's happening? The root cause should be fixed, or if it's harmless, the warning should be silenced. It appears to happening twice every ten minutes (preventing search from idling I guess).

**Comment by isoos** [comment]
No idea, because the content that we are setting is certainly not null, and our code starts to set it on memcache. My best guess is that we are reaching the maximum cached value size of 1 MB.

**Comment by isoos** [comment]
Deployed and fixed with the release today.
