### ISSUE TITLE
Flutter_TTS issue..

### ISSUE THREAD

**Issue by osamasabir** [dart-lang/pub-dartlang-dart#1698]
URL: https://pub.dartlang.org/packages/flutter_tts#-analysis-tab-

hi,
its my first flutter app ... i don't know much about iOS and Flutter thats why i am asking here

why i am getting that error ??
i tried that package with Swift/C++ support option..
anyone help me out ??

attaching Picture:

![image](https://user-images.githubusercontent.com/17942396/46908713-5d998980-cf40-11e8-83f7-4bc7d36e6e7e.png)

**Comment by osamasabir** [comment]
Anyone ?? please !!!!

**Comment by isoos** [comment]
@osamasabir this tracker is for the pub site and not for individual packages. Please open an issue in the package's repository, in this case it would be https://github.com/dlutton/flutter_tts/issues
In addition to that, if you are new to Flutter, I strongly suggest to ask people on gitter (https://gitter.im/flutter/flutter) or on StackOverflow.

Closing this as it is unrelated to the pub site.
