### ISSUE TITLE
Use `flutter analyze` for flutter packages

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#170]
I guess it wires up their own lints, etc.

Blocked by https://github.com/dart-lang/pana/issues/32
Which is blocked by flutter bug https://github.com/flutter/flutter/issues/10704

**Comment by devoncarew** [comment]
Assuming you ran `flutter packages get` for the project, `flutter analyze` should return the same set of errors/warnings/hints/lints as `dartanalyze`. So, I don't think a a `--machine` flag for flutter analyze is strictly required here?

**Comment by kevmoo** [comment]
Good to know!

**Comment by kevmoo** [comment]
@devoncarew – so we can just run `dartanalyze` and we're good? Cool!

**Comment by kevmoo** [comment]
Closing as not-needed.

This would need to be built into pana.
