### ISSUE TITLE
Discontinue pkg:shelf_appengine

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1701]
URL: https://pub.dartlang.org/packages/shelf_appengine

Not maintained or used for Dart2

**Comment by cskau-g** [comment]
I thought the Pub site uses shelf and runs on AppEngine. But maybe I'm missing something?

**Comment by cskau-g** [comment]
Ah, I see pub-dartlang-dart depends on shelf and appengine, but not shelf_appengine.
It's probably safe to ignore.

https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/pubspec.yaml

**Comment by sortie** [comment]
Done.
