### ISSUE TITLE
discontinue built_viewmodel_*

### ISSUE THREAD

**Issue by the4thfloor** [dart-lang/pub-dartlang-dart#1723]
please mark the following packages as discontinued

https://pub.dartlang.org/packages/built_viewmodel
https://pub.dartlang.org/packages/built_viewmodel_generator
https://pub.dartlang.org/packages/built_viewmodel_flutter_redux
https://pub.dartlang.org/packages/built_viewmodel_flutter_built_redux

**Comment by sortie** [comment]
Done. It may take a little while before the site rescans the packages and adds the discontinued label. I'll keep the bug open until then.

**Comment by isoos** [comment]
There was an ongoing release, that's the reason it was delayed. They are now marked as discontinued.
