### ISSUE TITLE
A problem occurred configuring project ':fluttertoast'.

### ISSUE THREAD

**Issue by 1420965446** [dart-lang/pub-dartlang-dart#1731]
I just added a line :   fluttertoast: ^2.0.9

* Error running Gradle:
Exit code 1 from: /Users/edz/Desktop/flutter_app/android/gradlew app:properties:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fluttertoast'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by isoos** [comment]
This issue was moved to PonnamKarthik/FlutterToast#26
