### ISSUE TITLE
Uploaded package with wrong email

### ISSUE THREAD

**Issue by marcguilera** [dart-lang/pub-dartlang-dart#1732]
I uploaded a package yesterday with the wrong email. It's called `dependencies`. Can we delete it? Thanks.

**Comment by isoos** [comment]
@marcguilera: is it the `author` field in `pubspec.yaml`? You can easily fix that with uploading a new version. Pub site's search will index only the latest stable, so it won't come up when search for author emails.

Also: this is the only version of the package. Are you planning to release a new version of it? If you want to remove a specific version, it would be nicer if you already published a new one first.

**Comment by sortie** [comment]
I can delete the package if you'd like. I can also change the uploader to another email (you'll need to say which one) if you'd like. What do you prefer?

**Comment by marcguilera** [comment]
You may delete it. Thanks!

**Comment by sortie** [comment]
Alright, I've removed it. I hope you're enjoying dart & pub.

@jonasfj FYI, here's how you handle this kind of request in case you need to do it in the future:
* git checkout the source code matching production (correct `runtimeVersion`).
* `cd pub-dartlang-dart/app && GCLOUD_PROJECT=... dart bin/tools/remove_package.dart remove $package_name`
* Flush the memcache and verify the package URL is now a search page.
