### ISSUE TITLE
Packages with a minimum bound 2.1.0-dev.XX of the SDK fail on pub upgrade

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1738]
_From @nshahan on October 31, 2018 14:29_

See:
https://pub.dartlang.org/packages/angular_components#-analysis-tab-
https://pub.dartlang.org/packages/angular#-analysis-tab-
https://pub.dartlang.org/packages/angular_forms#-analysis-tab-

_Copied from original issue: dart-lang/pana#435_

**Comment by isoos** [comment]
IIRC a similar request came up with a package a few weeks ago, but it was resolved with a wider SDK constraint release. I think we need to decide: do we want to be on the latest stable SDK or do we want closely track the `-dev` SDKs, or somewhere in-between? Dart 2.0 was released almost 3 months ago...

/cc @mit-mit @sortie @jonasfj

**Comment by sortie** [comment]
This stuff happens all the time. We're always chasing the next Dart SDK which occasionally need urgent deployments to production to avoid breaking key packages.

Can we build a system where pub tries with the stable version. If that doesn't work, then it detects what the latest dev release is, and retries with that? That should solve the chase.

Alternatively, we can consider packages depending on dev releases newer than our stable release as pre-release versions of packages (at least until we bump our stable version). That is after all technically the case, customers will be using the stable dart sdk. But then there's flutter which imports the Dart SDK on their own schedule, so this might not work. Possibly we could use a similar approach to pull in new flutter SDKs and use those for analysis.

**Comment by isoos** [comment]
To complicate things, we have a lot of legacy packages that have dartdoc generated with an earlier version of runtime + dartdoc combination. They contain inlined script tags, which we are trying to remove for #1691 (content security policy). If we want to make sure nothing is broken, we should re-generate those docs with an older SDK+dartdoc setup too (even if our customizations are not applied), or decide that after a certain point we are decommissioning such old generated documentation too.

**Comment by mit-mit** [comment]
@matanlurey can you comment on why angular packages are pushed to pub in *stable* versions with bounds that depend on the SDK in *dev* versions? The current design assumes that package like that should be published as *pre-release* versions (i.e. contain a dash in their version).

**Comment by nshahan** [comment]
@mit-mit Not to answer for him but I believe the general issue is that Angular is developed on the dev SDK internally, then synced out to GitHub and published publicly.

Publishing stable versions that depend on the dev SDK allows them to choose when to publish a new version on their own schedule. They are not tied to the release cadence of the SDK.

**Comment by matanlurey** [comment]
Right, what @nshahan said.

Our `5.1.0` is stable, and will work with `2.1.0-dev` and the eventual `2.1.0` final. We wanted users who were on the dev SDK branch to be able to use it sooner, and for users that prefer to wait for the stable branch we didn't want to have to rev again just for that purpose.

**Comment by isoos** [comment]
> Our 5.1.0 is stable, and will work with 2.1.0-dev and the eventual 2.1.0 final.

Assuming that even if/when 2.1 stable is out, you will continue this practice, how shall we communicate the fact, that while it will be stable in a future release, it is not useable on the latest stable Dart SDK?

**Comment by nshahan** [comment]
@isoos Now that Dart 2.1 has been published has pana and the dartdoc generator been updated to use the new SDK? Is there a way I can trigger the analysis and docs to be generated without uploading a new version?

**Comment by isoos** [comment]
@nshahan We've deployed a new version of the pub site with the 2.1 SDK, and the analysis of the angular packages was re-done, score is up again.

I'm closing this issue now. If you keep releasing stable versions with SDK constraints to unstable SDKs, it is very likely you will have similar experience. Please open a new issue how we should communicate it - if there were a consistent way to do it, the dev-SDK analysis can be added to the pub site.
