### ISSUE TITLE
How to make sure analyzer and dartdoc don't fail?

### ISSUE THREAD

**Issue by letsar** [dart-lang/pub-dartlang-dart#1742]
I published this package (https://pub.dartlang.org/packages/flutter_sidekick) yesterday.
The `flutter analyze` and `dartdoc` failed and the package lost 30 points 😞 .
I don't think the package is responsible for this, because I ran the analysis and dartdoc before publishing and I got nothing wrong.

Also the descriptions of the issue don't help to understand why it's failing:

> Fix platform conflicts. (-20 points)
> Error(s) prevent platform classification:
> **Make sure flutter analyze runs.**

> Running dartdoc failed. (-10 points)
> **Make sure dartdoc runs without any issues.**

I'm not sure it's the right place for this issue, because it involves other parties as well. So don't hesitate to tell me if I have to create a separate issue for the other parties as well.

How can I reproduce the error within the same environment pub uses?
Is the analysis launched periodically or should I publish a new version to trigger it?

When I looked at the dartdoc logs, I saw that the analyzer failed for a specific class, but I don't know more. It's maybe related to https://github.com/dart-lang/sdk/issues/34873.

**Comment by isoos** [comment]
@letsar: What was the Flutter version you have used to develop the package?

The package page contains the version of Flutter we have used for the latest analysis (in this case: `0.10.1`). Did you tried running `flutter analyze` with that? If you want to reproduce the code analysis part, you can also use [`pana`](https://pub.dartlang.org/packages/pana).

As your code uses mixins, and their support changes in the dev versions, it is possible that it will report different errors in different VM versions (as they are changing). In case of `dartdoc` it may be even more complex, as we use a version that is independent of the Dart/Flutter SDK used for the analysis.

**Comment by isoos** [comment]
I've checked this package with different SDK versions:
- `2.0.0` run `dartanalyzer` successfully but reported errors
- `2.1.0-dev.5.0` and `2.1.0-dev.7.1` failed to run `dartanalyzer` on the sources.
- `2.1.0-dev.8.0` and `2.1.0-dev.9.1` was successful in running `dartanalyzer`, and reported no issues.

It looks like there was a bug in `dartanalyzer` which got fixed some time ago, but the Flutter version on pub does not use it yet.

@letsar: that also means your issue will go away once we upgrade the Flutter SDK on pub site to a version that uses at minimum `2.1.0-dev.8.0`. I've checked, and Flutter `0.10.2` uses that, so the upgrade timeline is up to the pub site. I'll prepare the upgrade alongside with a new changes in `pana`, and hopefully it can be deployed in the second half of the week. Thank you for being patient with us until then.

**Comment by letsar** [comment]
Hi @isoos ,

I used Flutter 0.9.4 to develop this package and analyze it, but I also analyzed it with the master branch (which was something like 0.10.3 I think).

Thank you for the great explanation 🙂. 
No problem I'll wait for the fix to be deployed on pub 🙂.

Should I publish a new version of my package to trigger a new analysis when the fix will be deployed?

**Comment by isoos** [comment]
> Should I publish a new version of my package to trigger a new analysis when the fix will be deployed?

There is no need to publish a new version, we will reanalyze the existing ones with the new runtime.

**Comment by isoos** [comment]
@letsar: the new release was deployed, and your package seems to be doing great!
