### ISSUE TITLE
email uploaders when a package is published

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#1749]
This can ensure people notice the analysis score, if we can get it to send email after analysis is done.

It's also a good to be aware of when packages your administrate are uploaded, as a security measure.

**Comment by isoos** [comment]
I think this is an easy win, but first we need to decide: which mail API should we use?

- AppEngine standard has an [E-mail API](https://cloud.google.com/appengine/docs/standard/java/mail/), but it is not clear whether we can invoke that from the flex environment.
- Both [AppEngine flex](https://cloud.google.com/appengine/docs/flexible/java/sending-emails-with-mailgun) and the [Compute Engine tutorials](https://cloud.google.com/compute/docs/tutorials/sending-mail/) suggest third-party services.
- We could possibly use a gsuite account's SMTP gateway. I remember that dartlang.org was a gsuite domain at one point.

**Comment by isoos** [comment]
Any update on which API should we use?

**Comment by jonasfj** [comment]
I need to talk to mit about this... I had an item in my calendar yesterday,
but circumstances.. I suspect we'll get an SMTP server we just connect to..

**Comment by jonasfj** [comment]
We can use: https://pub.dartlang.org/packages/mailer

While not pretty, I suggest we store gmail username/password in datastore, that way we can use a different account for the staging site...

**Comment by jonasfj** [comment]
Example of sending email:
```dart
import 'dart:io';
import 'package:mailer/mailer.dart';
import 'package:mailer/smtp_server/gmail.dart';

void main() async {
  final email = 'pub@dartlang.org';
  final pass = Platform.environment['PUB_EMAIL_PASSWORD'];

  final server = gmail(email, pass);

  final message = Message()
    ..from = Address(email, 'Pub Service')
    ..recipients.add('jonasfj@google.com')
    ..subject = 'Pub emails works!'
    ..text =
        'Hi,\nThis message is supposed to demonstrate that **emails work**.'
    ..html =
        'Hi,<br>This message is supposed to demonstrate that <b>emails work</b>.';
  final report = await send(message, server); // this won't throw exceptions
  assert(report.every((r) => r.sent), 'failed to send some message');
}
```

**Comment by isoos** [comment]
Agreed, I use this package in other projects.

> I suggest we store gmail username/password in datastore

We have `PrivateKey` entity for such use-cases.

> that way we can use a different account for the staging site

Not sure about this. I'd rather have the staging site only log the e-mail, but not actually send it.

**Comment by isoos** [comment]
> I'd rather have the staging site only log the e-mail, but not actually send it.

Or alternatively, overriding the recipients e-mail address could work too. I would like to prevent accidental e-mail sending.

**Comment by jonasfj** [comment]
>
> Not sure about this. I'd rather have the staging site only log the e-mail,
> but not actually send it.

That's a good idea :)

--
Regards Jonas Finnemann Jensen.
