### ISSUE TITLE
discontinue dart2_constant

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1760]
URL: https://pub.dartlang.org/packages/dart2_constant

No longer needed now that Dart2 has been out for a while.

**Comment by sigurdm** [comment]
Do we have a process for this?

Would landing a new version where the README is updated to say that this package is discontinued be sufficient?

**Comment by isoos** [comment]
We have a flag for this, that can be run via:
https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/bin/tools/flag.dart
```
dart bin/tools/flag.dart --discontinued set [pkg-name]
```

It is part of the `Package` entry:
https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/frontend/models.dart#L56

Its primary purpose is to mark the package with the red banner and to remove it from search results.

**Comment by sigurdm** [comment]
Great, thanks!
I'll look into it

**Comment by sigurdm** [comment]
Done
