### ISSUE TITLE
https://pub.dartlang.org/ isn't accessible

### ISSUE THREAD

**Issue by ukor** [dart-lang/pub-dartlang-dart#1767]
It has been weeks now and still can't access https://pub.dartlang.org/. I am not behind any proxy.
https://pub.dartlang.org/ Takes too long to load.

**Comment by isoos** [comment]
@ukor: could you please share us more details about your location, OS, and browser?
Maybe the output of `curl -v https://pub.dartlang.org/`?

**Comment by ukor** [comment]
@isoos 
Location:  Nigeria
OS: MacOS Sierra 10.12.6
Browser: Google chrome

## output of curl -v https://pub.dartlang.org/
`
 Immediate connect fail for 2a00:1450:4009:810::2013: No route to host
   Trying 2a00:1450:4009:810::2013...
 TCP_NODELAY set
 Immediate connect fail for 2a00:1450:4009:810::2013: No route to host
   Trying 2a00:1450:4009:810::2013...
 TCP_NODELAY set
 Immediate connect fail for 2a00:1450:4009:810::2013: No route to host
   Trying 2a00:1450:4009:810::2013...
 TCP_NODELAY set
 Immediate connect fail for 2a00:1450:4009:810::2013: No route to host
   Trying 2a00:1450:4009:810::2013...
 TCP_NODELAY set
`

**Comment by sortie** [comment]
It appears you are trying to connect over IPv6, with no IPv4 fallback. Does IPv6 work correctly for you?

What happens if you force IPv4, e.g.?

curl -v https://pub.dartlang.org -4
curl -v https://pub.dartlang.org --resolve 'pub.dartlang.org:443:172.217.14.211'

Does that help?

**Comment by ukor** [comment]
@sortie Yes, it did help. Thank you . Everything works fine now.
For learning purpose, can you tell me why that work and why was i connecting over IPv6. (Forgive my ignorance)

**Comment by ukor** [comment]
There is an issue with IPv6 from my end.  https://pub.dartlang.org has stop, I tried the solution above, it worked on the terminal but not in the browser.

**Comment by sortie** [comment]
You should be able to configure your browser to always use IPv4 in your network settings. Likewise there are also operating system level settings you can configure. If your OS believes IPv6 works, but it does not, you should possibly talk to your ISP to get your network properly configured.

**Comment by isoos** [comment]
I believe you can disable OS-level ipv6 with the following commands:

```
# If you are using wire:
networksetup -setv6off Ethernet
# if you are using wi-fi
networksetup -setv6off Wi-Fi
```

You will be prompted to enter your OS X administrator password.

If you wish to re-enable IPv6 on your device, the following ones should re-enable it:

```
# If you are using wire:
networksetup -setv6automatic Wi-Fi
# if you are using wi-fi
networksetup -setv6automatic Ethernet
```

Please note, however, that Chrome may skip the OS-level settings, so it could also be worth to try different browsers too.

**Comment by jonasfj** [comment]
This really shouldn't be a problem unique to `pub.dartlang.org`, are you also having trouble accessing other sites?

Can you reach? https://dartlang-pub-dev.appspot.com/

Or maybe this example app: https://server-auth-python-dot-ee-demos.appspot.com/ ?

**Comment by ukor** [comment]
@jonasfj , yes i can access other website fine, I was able to access  https://dartlang-pub-dev.appspot.com/ and this https://server-auth-python-dot-ee-demos.appspot.com/ 
`pub.dartlang.org` is the only site i can't access both on browser and terminal (I have tried it on chrome and mozilla firefox - developer edition) and i also can't access it on my phone.

**Comment by ukor** [comment]
@jonasfj  `dig pub.dartlang.org` returns
`
; <<>> DiG 9.8.3-P1 <<>> pub.dartlang.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59169
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 8

;; QUESTION SECTION:
;pub.dartlang.org.		IN	A

;; ANSWER SECTION:
pub.dartlang.org.	66329	IN	CNAME	ghs.googlehosted.com.
ghs.googlehosted.com.	119	IN	A	216.58.204.83

;; AUTHORITY SECTION:
googlehosted.com.	74049	IN	NS	ns3.google.com.
googlehosted.com.	74049	IN	NS	ns4.google.com.
googlehosted.com.	74049	IN	NS	ns2.google.com.
googlehosted.com.	74049	IN	NS	ns1.google.com.

;; ADDITIONAL SECTION:
ns2.google.com.		264981	IN	A	216.239.34.10
ns2.google.com.		179828	IN	AAAA	2001:4860:4802:34::a
ns1.google.com.		253050	IN	A	216.239.32.10
ns1.google.com.		179823	IN	AAAA	2001:4860:4802:32::a
ns3.google.com.		179823	IN	A	216.239.36.10
ns3.google.com.		113078	IN	AAAA	2001:4860:4802:36::a
ns4.google.com.		256147	IN	A	216.239.38.10
ns4.google.com.		179823	IN	AAAA	2001:4860:4802:38::a

;; Query time: 95 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Tue Nov 13 18:31:44 2018
;; MSG SIZE  rcvd: 339
`

**Comment by isoos** [comment]
@ukor Is this still an issue?

**Comment by ukor** [comment]
@isoos Yes it is

**Comment by isoos** [comment]
Can you please report if you can reach the following sites?
- https://dartlang-pub.appspot.com/ (FYI: this is the same site as pub.dartlang.org)
- https://www.dartlang.org/
- https://dartpad.dartlang.org/
- https://news.dartlang.org/

(I'm just trying to rule out some cases.)

**Comment by HemlockBane** [comment]
@ukor What ISP do you use? I've tried the site with MTN, Airtel and GLO. Excepting GLO, all of them work.

**Comment by ukor** [comment]
@HemlockBane I am using GLO and I just tried again, still no luck. I wouldn't have mind if i can't access it on the browser because i learnt that [ this https://dartlang-pub.appspot.com/](https://dartlang-pub.appspot.com/) and [this https://pub.dartlang.org  ](https://pub.dartlang.org) are the same but this issue  affects me from installing packages.

**Comment by isoos** [comment]
@ukor @HemlockBane: I suggest you to contact the ISP (GLO), describe the issue with the technical details, and ask them to fix it. It depends on the expertise of their IT service, but they may be able to fix it.

(Although don't get your hopes up: one otherwise competent ISP in Hungary can't fix their foreign SMS routing, and even though we report it every now and then, it remains unfixed for many years now.)

I'm closing the issue, as we are not able to do anything else on our side, but please update it if the situation changes.

**Comment by thedejifab** [comment]
> 
> 
> @ukor Exactly! It affects me too. Try using another ISP (maybe Airtel, Swift, Spectranet etc.). I still can't figure out why [dartlang-pub.appspot.com/](url) works when its twin link doesn't. When I'm chanced, I'll try to find out. Although, @sortie suggests that it has something to do with IPv6 and IPv4, trying it with IPv4 didn't work for me. If you have a deadline to meet, like I do, please, get yourself a better ISP. No offence, but GLO is terrible.

GLO is really doing bad with this. They've got a good internet connection and it's even over their 4G network, I don't know why they're having issues accessing pub.

**Comment by isoos** [comment]
An update: another user reported here that they were able to get it working by using Google's DNS servers:
https://github.com/dart-lang/pub/issues/2015#issuecomment-448242398
https://www.wiknix.com/how-to-fix-err_connection_timed_out-error/

**Comment by ukor** [comment]
@isoos Thanks for the follow up, weird tho, after seeing your comment i thought i should check pub.dartlang.org before changing my DNS settings and everything worked perfectly, I was able to install packages without any error.
@HemlockBane and @thedejifab Please confirm this.

**Comment by thedejifab** [comment]
@ukor, thanks! It works here too. I guess it was a problem with GLO or something.

**Comment by thedejifab** [comment]
Changing DNS to 1.1.1.1 fixes this so well!

**Comment by modaloda** [comment]
> @ukor: This seems to be a problem local to your system. Could you please share us more details about your location, OS, and browser?
> Maybe the output of `curl -v https://pub.dartlang.org/`?

*   Trying 172.217.18.51...
* TCP_NODELAY set
* Connected to pub.dartlang.org (172.217.18.51) port 443 (#0)
* schannel: SSL/TLS connection with pub.dartlang.org port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 181 bytes...
* schannel: sent initial handshake data: sent 181 bytes
* schannel: SSL/TLS connection with pub.dartlang.org port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with pub.dartlang.org port 443 (step 2/3)
* schannel: encrypted data got 2800
* schannel: encrypted data buffer: offset 2800 length 4096
* schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection 0
* schannel: shutting down SSL/TLS connection with pub.dartlang.org port 443
* schannel: clear security context handle
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

I've got the same issue "Got TLS error trying to find package cupertino_icons at https://pub.dartlang.org.

pub get failed (69) -- attempting retry 1 in 1 second...". Can anyone help me with that

**Comment by jonasfj** [comment]
@modaloda, 
Can you post using [code fencing](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) or paste the log into a gist and link to it, it's a little easier to read that way,.

In any event, you seem to have a very different error... This suggest that you OS has TLS issues, have you installed custom certificates, are you behind a proxy or something else that might interfere with TLS connections?

[Googling around](https://curl.haxx.se/mail/lib-2019-03/0004.html) suggests to me that maybe you have a man-in-the-middle-proxy or maybe you've just been fiddling with the CA trust store on your machine... Or (most likely) some security software you've installed is fiddling with your CA trust store..

I'm not a Windows expert, but this looks like your system has configuration issues.

**Comment by Thirdwrist** [comment]
I am having the exact same issues using Glo network and trying to access dartpad

**Comment by paooxide** [comment]
I recently had this issue on a Glo Network (ISP) too.  I resolved this by changing my DNS addresses to

Primary DNS :   199.85.126.10
Secondary DNS :  199.85.127.10

you can also download [public DNS server tool](https://www.trishtech.com/downloads/public_dns.zip) if you are using a Windows OS


I hope this resolves the issue for you

**Comment by Thirdwrist** [comment]
I don't use a windows. but I will find an alternative to the dns tailoring to your suggestion

**Comment by OladapoAjala** [comment]
@isoos I already tried all the suggested solutions here I still can get my flutter packages.

**Comment by ukor** [comment]
@OladapoAjala change your network provider. GLO seems to be the culprit here. I was able to access
https://pub.dev/ and also download packages using MTN Nigeria.

**Comment by OladapoAjala** [comment]
@ukor thanks a different ISP (MTN) actually solves this for me. Apparently GLO could not resolve the website https://pub.dartlang.org

**Comment by solomontu** [comment]
I have equally been stranded with updating my flutter for nearly 2 weeks,  flutter doctor was only showing "building flutter tool" without any further progress. I could not access pub.dartlang.org on my glo line which I was referred to by the failing process. It's seems that glo line is the root of the evil here in Nigeria, after having it done with other ISP.

**Comment by calistus** [comment]
For developers in Nigeria, use another ISP apart from GLO. This will solve your problem.

**Comment by babahmed** [comment]
> For developers in Nigeria, use another ISP apart from GLO. This will solve your problem.

God bless you brother

**Comment by studywithlawz** [comment]
> I recently had this issue on a Glo Network (ISP) too. I resolved this by changing my DNS addresses to
> 
> Primary DNS : 199.85.126.10
> Secondary DNS : 199.85.127.10
> 
> you can also download [public DNS server tool](https://www.trishtech.com/downloads/public_dns.zip) if you are using a Windows OS
> 
> I hope this resolves the issue for you

Thanks, I resolved the Issue with GLO after downloading DNS Server Tools from your link (i selected Cloud Flare)

**Comment by onimeshc-iprogrammer** [comment]
Same issue here from India.
I tried [https://github.com/dart-lang/pub-dev/issues/1767#issuecomment-437531730](url) this, it works on on the terminal and only once, the other flutter commands are not working yet.

Then I also tried the command below:
$ dig pub.dartlang.org

; <<>> DiG 9.10.6 <<>> pub.dartlang.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54880
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;pub.dartlang.org.		IN	A

;; ANSWER SECTION:
pub.dartlang.org.	21599	IN	CNAME	ghs.googlehosted.com.
ghs.googlehosted.com.	299	IN	A	172.217.26.243

;; Query time: 70 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Apr 21 18:10:30 IST 2020
;; MSG SIZE  rcvd: 95

Is this fine??

**Comment by foomoto** [comment]
This is a painful problem that seems to be a networking issue between where pub.dev is hosted and your network provider. My advice is if you have access to a proxy server like nginx you should be able to setup a reverse proxy connection. 

See below:

location  /dart {
      resolver 1.1.1.1;
      proxy_ssl_server_name on;
      proxy_pass https://pub.dev/;
      proxy_set_header X-Real-IP $remote_addr;
rewrite "/([0-9]{4})/([0-9]{2})/([0-9]{2})/(.*)" /blog/$4 permanent;
#rewrite /blog/(.*) /$1  break;
proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#proxy_set_header   Host $http_host;             
                proxy_set_header X-NginX-Proxy true;
    }

**Comment by solomontu** [comment]
Thanks so much. For now, it's working well hopefully it doesn't stop.

**Comment by Tarhex** [comment]
Try to see if you can reach https://dartlang-pub-dev.appspot.com/ in your browser

If it is accessible, declare PUB_HOSTED_URL as a system environment variable and give it the value https://dartlang-pub-dev.appspot.com/

Then exit and reopen your cmd window and try again.

**Comment by isoos** [comment]
IMPORTANT NOTE: `https://dartlang-pub-dev.appspot.com/` is **not** the `pub.dev` site, it is the staging site. The data there is stale, and does not reflect the real site. While your `pub` client may work, there is no guarantee that it serves the same (or even similar) content than https://pub.dev/

You may set `PUB_HOSTED_URL` to `https://dartlang-pub.appspot.com/` (note the missing `-dev` in the hostname), however, there is no guarantee that it won't change in the future. Please try to debug why you can't access pub.dev, and use the above fallback only as a last resort.

**Comment by fejiro-ariek** [comment]
For developers in Nigeria, use another ISP apart from GLO. This will solve your problem.
