### ISSUE TITLE
Support marking a package stale/deprecated

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#182]
Need a way of marking a package stale/deprecated. For now we have to resort to README editing to make this clear, but would like a more explicit approach + special treatment for these in search, etc.

**Comment by kevmoo** [comment]
We have a bigger conversation in a newer bug, so marking this one as

Duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/289

**Comment by kevmoo** [comment]
Duplicates https://github.com/dart-lang/pub-dartlang-dart/issues/289

**Comment by kevmoo** [comment]
Duplicate of #289
