### ISSUE TITLE
Allow specifying a package as "not publishable"

### ISSUE THREAD

**Issue by amirh** [dart-lang/pub-dartlang-dart#1824]
Following some cases of packages being published unintentionally (e.g https://github.com/dart-lang/pub-dartlang-dart/issues/1820 )

It would be nice to have a way to specify in `pubspec.yaml` that a package should not be published.

@jonasfj suggested adding:
```yaml
publish_to: none  # do not publish this package while under active development.
```

This does the job, but it also makes `pub publish --dry-run` fail (which at least for [flutter/plugins](https://github.com/flutter/plugins) we run on presubmit for all plugins).
Ideally I'd want to be able to run the `pub publish --dry-run`, have it do all the checks it is currently doing but not fail if the packages was explicitly marked unpublishable.

**Comment by isoos** [comment]
I think this issue belongs to the pub client.

**Comment by isoos** [comment]
This issue was moved to dart-lang/pub#2004
