### ISSUE TITLE
Enable flutter.io to support Pub searches through an API

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#183]
Provide an API enabling Flutter.io to initiate Pub searches

**Comment by isoos** [comment]
Could you provide some examples of the scope of this?

**Comment by mit-mit** [comment]
Basically the ability to launch a search on pub.dartlang.org from flutter.io. We would need the ability to pass over the actually search string + "works with flutter" as search params.

**Comment by mit-mit** [comment]
Pushing to M4

**Comment by mit-mit** [comment]
There is no current need for this; closing
