### ISSUE TITLE
Pub is not feeling well

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [dart-lang/pub-dartlang-dart#1831]
Requested URL: https://pub.dartlang.org/packages?q=firebase
Request ID: c67490dba16f7283c41ca128abebd466

**Comment by isoos** [comment]
```
Error:
    Exception: Service returned status code 502
```

Looks like the search service was not reachable for a minute or two, and we've got a few 500 on the the frontend.

**Comment by jonasfj** [comment]
from our alerts:
>alert start: Nov 29, 2018 at 7:13AM UTC (3 minutes ago)
>alert end:  Nov 29, 2018 at 7:13AM UTC (4 minutes ago)
>Alert firing lasted
>1 min 0 secs

**Comment by isoos** [comment]
We've got double-restarts (when two instances were starting within 5 minutes) this week at the following times on `search` service (listing only the first of the pairs):
- `2018-11-26 11:34:07.547 CET`
- `2018-11-26 22:07:23.757 CET`
- `2018-11-28 10:10:53.893 CET`
- `2018-11-29 07:04:38.704 CET`
- `2018-11-29 08:11:01.628 CET`

At the moment the p99 event loop latency is 1176 - 1241 ms, which means that the period sampling timer we occasionally start takes more than 1 second to respond in >1% of the cases.

Contrast that with the `frontend` service:
- `2018-11-26 11:07:46.899 CET`
- `2018-11-26 11:11:31.098 CET`

It also has <2ms p99 event loop latency.

My suspicion: AppEngine's default health check times out and triggers a service restart. I think we can override the default timeouts and reduce the number of restarts (while the long-term goal would be to make search more responsive my calculating less stuff on each search).

**Comment by isoos** [comment]
I suspect these are the settings we need to tune:
https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml#health_checks

**Comment by jonasfj** [comment]
> At the moment the p99 event loop latency is 1176 - 1241 ms

Isn't this basically a metric saying that our main thread is super busy?
So what we can do to make it less busy? Do we throw more instances at the problem?
Or is there some optimization we should be looking into?

**Comment by ThinkDigitalRepair** [comment]
Some sites were getting DDoSed yesterday. 3 that I use regularly. BBVA was
also facing issues. It's probably related.

**Comment by isoos** [comment]
> Isn't this basically a metric saying that our main thread is super busy?

`search` only has on thread (one frontend isolate), and it both serves the search requests, and the index building. 

> Do we throw more instances at the problem?

Actually, that may be the easiest handling of the situation, as it would spread the load, and the individual instances would be less busy with search requests.

> Or is there some optimization we should be looking into?

I'm playing with the idea of using bitmap index (`package:bit_array`) inside the current `TokenIndex`, which is now rather memory-heavy with all the maps and sets... But starting a few more instances would probably solve this much easier than rewriting the index.

**Comment by isoos** [comment]
Strengthening my theory about the service taking a long time: in the minutes before the restart, there were several requests taking more than 12-15 seconds each to serve. URLs like:

```
/search?q=dependency%3Acloud_firestore%27-function%28%29%7Bxssdetected%2833911%29%7D%28%29-%22%3E%5C%22%3E%3CscrIpt%3Exssdetected%2833911%29%3C%2FscrIpt%3E%3CaUdio+src%3Dx+oNerror%3Dxssdetected%2833911%29%3E%3C%22-%27-function%28%29%7Bxssdetected%2833911%29%7D%28%29&offset=0&limit=10

/search?q=%27-function%28%29%7Bxssdetected%2856911%29%7D%28%29-%22%3E%5C%22%3E%3CscrIpt%3Exssdetected%2856911%29%3C%2FscrIpt%3E%3CaUdio+src%3Dx+oNerror%3Dxssdetected%2856911%29%3E%3C%22-%27-function%28%29%7Bxssdetected%2856911%29%7D%28%29email%3Ajonahwilliams%40google.com&offset=0&limit=10
```

I'll debug it a bit more tomorrow, maybe there are wins here with (a) capping the length at shorter lengths and (b) splitting up such phrases into several async passes so that it won't block the health checks.

**Comment by jonasfj** [comment]
> (a) capping the length at shorter lengths 

I strongly support this :)

As for (b) I generally believe that if we're doing something so CPU intensive that we need to artificially insert awaits... then we should (i) optimize the code, (ii) fix the slow path in the VM, (iii) move the CPU intensive work to a background isolate.

**Comment by isoos** [comment]
I've narrowed the slow path down to:
- the API symbol index mostly (but API documentation index has its fair share too)
- the term lookup part, where we select candidates based on word-similarity,
- specifically the ngram-similarity part,
- more specifically the `Set.intersect` method call of that ngram-similarity function

The ~75% of the time is spent in the later method.

Looks like package APIs are both large is very similar to each other, as there are lots of candidates that need to be considered.

I guess (a) we can turn the similarity match off for the API index, and/or (b) rewrite parts of that e.g. to use only a Hamming-distance based similarity, which can be implemented with deleted characters and a simple lookup (assuming it is maximised in 1 or 2 character differences).

**Comment by jonasfj** [comment]
Long term isn't the idea that you wanted to use bitfields instead of `Set<String>` ?

It looks to me as if we compare stuff when there isn't a ngram match too... which confuses me..

**Comment by isoos** [comment]
> It looks to me as if we compare stuff when there isn't a ngram match too...

Yeah, it is wasteful. I'm now experimenting with different kind of reductions, e.g. keeping only candidates that are derived by deleting one character. The entire search speed that was 10+ seconds now is below 0.5 second, which is great, but the price is that we no longer find `geolocation` when the search term was `location`.

**Comment by isoos** [comment]
The changes have been deployed. I've checked, the offending long query now completes fast enough (probably under a second).
