### ISSUE TITLE
Package view for plugin: fix broken crossdart link

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#184]
Crossdart links are broken for many Flutter plugins, and doesn't include the android and ios code. 

Short term, if something is a plugin just remove the crossdart link, and if the homepage is a github page, show that as the package source link.

Longer term, do https://github.com/dart-lang/pub-dartlang-dart/issues/185.

**Comment by kevmoo** [comment]
Closed in

https://github.com/dart-lang/pub-dartlang-dart/commit/7f78d195002a5257b3236fac19b70cc72ba2702a
https://github.com/dart-lang/pub-dartlang-dart/commit/c1180b50007dd9d77030e571b1bfb81d03c7c9fd
