### ISSUE TITLE
Obsolete Flutter pub package is confusing and should be removed.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/pub-dartlang-dart#1840]
See the first result in [this query](https://pub.dartlang.org/packages?q=flutter).

It is the "flutter" package, but it has version 0.0.20, but when clicked on, it just takes you to the pub search again.  It's confusing to people, but also to programs that are trying to enumerate packages on pub (most notably "Dash" and "Zeal" who publish offline docs for pub packages).  Can we just remove the "flutter" package, or will the world break?  Barring that, can we give it some contents that make sense, like a current version number and a "Dart 2 compatible" label?

It appears to already have a redirect in place to send the user back to the search page if they try and click on it, but removing it from the results would be the next best thing to removing it entirely.

**Comment by mit-mit** [comment]
@isoos I thought we were surpressing it from search results?

**Comment by isoos** [comment]
I remember that we've removed it from the results at one point, not sure how it managed to come back. 

A shortlist to handle packages with redirects:
- [ ] removing from /api/packages and sitemap listings
- [ ] removing from `Job` entries
- [ ] removing from search index

**Comment by isoos** [comment]
We had [this line](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/shared/task_scheduler.dart#L62) to prevent it to be added to the search index, but it is possible that it was not properly removed from the search snapshot in the first place, and we happened to keep it in there ever since.

**Comment by isoos** [comment]
The change has been deployed, the search no longer lists `package:flutter`.
