### ISSUE TITLE
Hangs on flutter packages get

### ISSUE THREAD

**Issue by rohanray** [dart-lang/pub-dartlang-dart#1857]
`flutter packages get` doesn't run successfully all the time... Original issue was posted at https://github.com/flutter/flutter/issues/25133

**Comment by isoos** [comment]
Can you reach the sites mentioned in https://github.com/dart-lang/pub-dartlang-dart/issues/1767#issuecomment-442493817? (btw. that is a similar issue, where the ISP had issues reaching the site).

**Comment by rohanray** [comment]
@isoos - Thanks for having a look on this one. Tried below sites from chrome browser

https://www.dartlang.org/ - `yes`
https://dartlang-pub.appspot.com/ -`yes`
https://dartpad.dartlang.org/ - `no`
https://news.dartlang.org/ - `no`

Below are some other tests if it helps:

```
┗❯ ping dartpad.dartlang.org
PING ghs.google.com (172.217.26.243): 56 data bytes
64 bytes from 172.217.26.243: icmp_seq=0 ttl=56 time=5.083 ms
64 bytes from 172.217.26.243: icmp_seq=1 ttl=56 time=5.257 ms
```

```
┗❯ ping news.dartlang.org
PING ghs.google.com (172.217.26.243): 56 data bytes
64 bytes from 172.217.26.243: icmp_seq=0 ttl=56 time=5.223 ms
64 bytes from 172.217.26.243: icmp_seq=1 ttl=56 time=28.083 ms
```

```
┗❯ telnet news.dartlang.org 443
Trying 172.217.26.243...
telnet: connect to address 172.217.26.243: Operation timed out
Trying 2404:6800:4009:806::2013...
telnet: connect to address 2404:6800:4009:806::2013: No route to host
telnet: Unable to connect to remote host
```

**Comment by isoos** [comment]
Do you access the https://pub.dartlang.org/ site? I suspect not, and it seems that the ISP is to blame for it :/

**Comment by rohanray** [comment]
No, I cannot access  https://pub.dartlang.org/. I guess you can close the issue. I'll try on a different network (different  ISP) in a few hours from now. Will report back here. Thanks @isoos for quick help on this

**Comment by rohanray** [comment]
Just for logging  purpose:

```
┗❯ curl -v https://pub.dartlang.org/
*   Trying 172.217.26.243...
* TCP_NODELAY set
* Connection failed
* connect to 172.217.26.243 port 443 failed: Operation timed out
* Failed to connect to pub.dartlang.org port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to pub.dartlang.org port 443: Operation timed out
```

```
┗❯ dig pub.dartlang.org

; <<>> DiG 9.10.6 <<>> pub.dartlang.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34045
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pub.dartlang.org.		IN	A

;; ANSWER SECTION:
pub.dartlang.org.	21536	IN	CNAME	ghs.googlehosted.com.
ghs.googlehosted.com.	236	IN	A	172.217.26.243

;; Query time: 1 msec
;; SERVER: 192.168.100.1#53(192.168.100.1)
;; WHEN: Sun Dec 09 22:35:12 IST 2018
;; MSG SIZE  rcvd: 84
```

**Comment by jonasfj** [comment]
@rohanray, where are you located? who is your ISP? (I'm curious if there's something that correlates between different users reporting issues talking to pub)

**Comment by rohanray** [comment]
@jonasfj Apologies for the delayed response! Well, I haven't faced any issues since past 3-4 days. My ISP is a local broadband company in Pune, India : *Gazon wireless*
