### ISSUE TITLE
Package view: View the main example (/example/lib/<name>/)

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#186]
If a package has an `example` folder, and if that contains a `lib/main.dart`, show that code in a new top-level tab called 'example' located right before 'Installing'.

**Comment by isoos** [comment]
@mkustermann: shall we have a new field in `PackageVersion` for this? (e.g. `exampleContent`)

**Comment by mit-mit** [comment]
@mkustermann was this deployed?

**Comment by mit-mit** [comment]
@kevmoo do you know?

**Comment by kevmoo** [comment]
It was not. We could deploy it, though. Meeting w/ @isoos this morning. Stay tuned..
