### ISSUE TITLE
api page scrolling confusing

### ISSUE THREAD

**Issue by pedromorgan** [dart-lang/pub-dartlang-dart#1865]
lost scrolling...

on chrome browser, reading eg https://pub.dartlang.org/documentation/sqflite/latest/sqflite/sqflite-library.html

- i scroll down and click something near bottom..eg `OnDatabaseOpenFn`
- takes me new page
- clicking back... I am at top of page again... and have to scroll to bottom
- frustrating.. 
- as is having the content wrapped in an inner scroll.... making chrome scrolls redundant...
- argh!!!!

**Comment by isoos** [comment]
This is something the `dartdoc` templates should address, moving the issue.

**Comment by isoos** [comment]
This issue was moved to dart-lang/dartdoc#1870
