### ISSUE TITLE
dart namespace + security

### ISSUE THREAD

**Issue by pedromorgan** [dart-lang/pub-dartlang-dart#1867]
Is dart safe from the "npm debacle".. 

https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/

(does it have namespace and identical packages in different project etc)

**Comment by jonasfj** [comment]
We don't currently have namespaces or a form of organizations and teams. But these things are on the road map. There is already some basic logic to mitigate trivial namesquatting attacks.

I believe there is ongoing work to define moderation policies.
But generally, we don't let people remove published packages, as NPM used to do around the `left-pad` incident.

What is the concerns with identical packages in different project? It's possible that I'm not up-to-date with all the debacles.

I think pub gets some things right with versioning, in that it doesn't allow you to use multiple versions of package in the same project. This makes it important that packages are updated to be compatible with the latest version of their dependencies, but you are not going to have 5 versions of some utility package in your dependency tree :)

**Comment by mit-mit** [comment]
Closing as a duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/1503
