### ISSUE TITLE
Refactor README and write deployment docs

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#1878]
We should put deployment docs in `doc/deployment.md` and refactor the README...

 * document source code generation
 * document repository management with `mono_repo`
 * document the deployment process steps
 * document required services: SMTP, redis cache
 * document backup strategy

Test docs by creating a new staging site setup (and then delete it).

**Comment by isoos** [comment]
I think we only miss the backup strategy from the list above.

**Comment by jonasfj** [comment]
Backup strategy is in the internal playbook, so we don't need to document it here.. let's close :)
