### ISSUE TITLE
Don't expose Flutter developers to content not relevant to them

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#188]
Flutter(-only) developers are able to use the Pub site without stumbling into packages, documentation, etc. that is for AngularDart

Note: This may mostly be a design thing

**Comment by kevmoo** [comment]
Will be addressed as part of new design...

**Comment by isoos** [comment]
@mit-mit: does the new Flutter landing page address this concern? What additional requirement would you list for considering this issue closed?

**Comment by mit-mit** [comment]
Yes, it does! Thanks!
