### ISSUE TITLE
Delete package alert

### ISSUE THREAD

**Issue by jerolimov** [dart-lang/pub-dartlang-dart#1882]
Hello, it was my mistake to publish a flutter package under the generic name "[alert](https://pub.dartlang.org/packages/alert)".

I already published this small util package under "[flutter_alert](https://pub.dartlang.org/packages/flutter_alert)".

If its possible it would be great if you can remove the first one.

Sorry & thank you.

**Comment by sigurdm** [comment]
No problem - thanks for reaching out.
The package is deleted now
