### ISSUE TITLE
GitHub link doesn't work when it's "deep"

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1891]
For example, on https://pub.dartlang.org/packages/meta, the link is in [the pubspec](https://github.com/dart-lang/sdk/blob/master/pkg/meta/pubspec.yaml) is `https://github.com/dart-lang/sdk/tree/master/pkg/meta`, but the site removed the `/pkg/meta` part.

**Comment by isoos** [comment]
The current page has:
- the `Homepage` link: the original URL, which is deep into a repository
- the (inferred) `Repository` link: the actual repository root
- the (inferred) `Issue tracker` link: relative to the repository root

What would you expect instead? How would you like to see the distinction between the (now-Homepage) deep location and the repository root?

**Comment by mit-mit** [comment]
This works fine now we show an explicit Homepage link; closing
