### ISSUE TITLE
parsing issue with new pubspec_parse

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1898]
````
pub.package_graph: Bad state: Error while decoding entity (Unsupported value for `repository`.,
#0 new Pubspec.parse (package:pubspec_parse/src/pubspec.dart:139:7)
#1 new Pubspec (package:pub_dartlang_org/frontend/model_properties.dart:33:25)
#2 PubspecProperty.decodePrimitiveValue (package:pub_dartlang_org/frontend/model_properties.dart:157:18)
#3 _ModelDescription._decodeProperty (file:///root/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/model_db_impl.dart:438:22)
#4 _ModelDescription.decodeEntity.<anonymous closure> (file:///root/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/model_db_impl.dart:428:7) 
````

**Comment by kevmoo** [comment]
Should be an error w/ `pubspec_parse` package?

**Comment by isoos** [comment]
I wanted to identify the core issue on pub site, but it seems that it is breaking the listing process, and I can't really identify the specific package that has the offending value.

@kevmoo: what are our options here? do we need to revert to using String or can we use a more permitting parsing (that returns a null rather an exception)? It would be bad if every time something is added to the `pubspec_parse` we would need to worry about broken behaviour on pub.

**Comment by kevmoo** [comment]
One of the values of pubspec_parse (in my opinion) is that is throws with
bad inputs – so users can fix them.

We could add a permissive parsing mode which just populates `null`, I
guess...

**Comment by isoos** [comment]
> One of the values of pubspec_parse (in my opinion) is that is throws with bad inputs – so users can fix them.

That is a great value at upload time, but not that great when we are re-reading the `pubspec.yaml` at a later point, when the rules are changed and now we are throwing on values that nobody can fix.

> We could add a permissive parsing mode which just populates `null`, I guess...

Can we have two parsing there? One that has permissive mode with `null` populated values, and one for the upload-time strict checks that will throw when invalid value is provided?

**Comment by isoos** [comment]
Only one package has the parsing issue in staging: `angular2_authentication_sample`, with the following value:
```
"repository": {
  "url":"https://github.com/rwl/angular2-authentication-sample.git",
  "type":"git"
}
```

@jonasfj any preference on how to go ahead with this? A parse workaround is possible on pub site (until pubspec_parse has a new version), however, I think the more important question is how we want to have such semi-breaking changes handled going forward.

**Comment by jonasfj** [comment]
hmm... maybe `pubspec.yaml` should be versioned. I'm not actually suggesting that we do this :)
We could rely on the `sdk` version... but this is not a can of worms I'm looking to open.

I agree that we a permissive parsing mode seems like a good solution.

Or maybe we could forbid the presence of undefined properties in `pubspec.yaml` (https://github.com/dart-lang/pubspec_parse/issues/34).
That would prevent this sort of thing from happening in the future, right?

We could then scan all published packages and remove all undefined properties. Including the newly added properties such as `flutter`, `issue_tracker`, `publish_to`, and `repository`, as none of the currently published packages should have been able to define these.

**Comment by jonasfj** [comment]
Okay, I see it would definitely be a bad idea to remove usages of the `flutter` property :)

But would it not be fair to require that new properties be officially approved, [documented](https://www.dartlang.org/tools/pub/pubspec) and supported in `pubspec_parse`, before we allow packages using these properties to be uploaded to pub.dartlang.org?

If we wanted the flexibility of being able to experiment with properties, I suggest that we allow a `custom` property to contain arbitrary sub-properties, and serve as an experimental playground for new properties or custom properties introduced in `pubspec.yaml`. However, in general it seems most other things in the eco-system uses a separate yaml file for analyzer options, build_runner, etc.

Otherwise, it seems likely that any changes to the `pubspec.yaml` format will cause breaking surprises for people.

**Comment by isoos** [comment]
Here is the statistics from staging, keys used in `pubspec.yaml` and their counts:

````
name: 38464
version: 38464
description: 38464
homepage: 38452

author: 32377
authors: 6087
maintainer: 46
email: 45
uploader: 1

environment: 29058
environnment: 39
sdk: 15
enviroent: 9
language: 6

dependencies: 32667
dev_dependencies: 26181
dependency_overrides: 569
dev-dependencies: 56
test_dependencies: 15
dev_dependency_overrides: 14
devDependencies: 9
dev_dependency: 8
dependecies: 1

documentation: 4268
repository: 7
bugs: 1

flutter: 4457

transformers: 3445
dev_transformers: 2

executables: 2063
executable: 10
bin: 1
excutable: 1
scripts: 5

license: 8

web: 154

collection: 38

changelogname: 18

publish_to: 54

refit_http: 1

analyzer: 31

ghooks: 1

linter: 21
jaguar_http: 5
github: 1
plugin: 2
strong-mode: 7
````

Some strange parsing happened, because the tool also reported keys like `//  complex`, I've removed those from the above.

**Comment by isoos** [comment]
> But would it not be fair to require that new properties be officially approved, documented and supported in pubspec_parse, before we allow packages using these properties to be uploaded to `pub.dartlang.org`?

That's also a synchronisation problem:
- as everything happens in the open, people will be eager to set properties before they got finalized, or
- `pub.dartlang.org` may slightly lag behind (or accepting it upfront) in contrast to the official "timestamp of approval".

I'd rather see a process that is clear about what could be wrong, but it is self-correcting. For example if somebody uses an unknown key in `pubspec.yaml`:
- `pub publish` should warn about them.
- `pana` should add a penalty and lower the maintenance score if they are used.

As `pana` and pub site goes up-to-date following a new property, the penalty can go away.

---

However, the above still don't address the issue at hand: the current `pubspec_parse` version breaks the site, and we should address that and other future changes. E.g. `flutter:` property may be untyped now, may become typed, using the then-current Flutter config structure, but that may be different from past-published structures, and parsing it could also fail.

- `pub publish` (and pub's upload flow) requires strict mode, that's the main point.
- `pana` is fine with strict mode, because it is aiming to accept the latest standards.
- however, accessing the historical data doesn't work well with strict mode, we need a lenient mode (or should do the parsing ourselves).
