### ISSUE TITLE
Rebuild search index from scratch every 24 hours

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#1932]
Possibly using a cronjob.

Purpose:
 * Ensure we can generate the index from nothing.
 * Eliminate drift in case of bugs and temporary inconsistency in data.
 * Ensure eventual consistency, increasing robustness.

**Comment by jonasfj** [comment]
(only issue that we need to avoid having the updated snapshops overwrite a newly generated index snapshot)

**Comment by isoos** [comment]
I started considering to move the snapshot out of the frontend isolate altogether (loading it only at startup, discarding it after that, no updates to it, no saving), and doing the building and save in a background isolate.

However, we won't gain too much memory: as long as we keep the full PackageDocument instances (which we do, mostly for `"exact term"` search queries), most of the memory allocation will be there, regardless of the location of snapshot maintenance. Furthermore, we would duplicate the snapshot-related memory in the background isolate.

Creating a separate search-index-builder service seems to be an overkill, but it is another option to consider.

**Comment by jonasfj** [comment]
The motivation for this was to ensure eventual consistency... by forcing a complete rebuild of the search index, so if garbage somehow sneaks into the index then eventually it'll get purged.

If this comes at a memory cost that seems fine.. Well, that's a different issue we can discuss :) haha

**Comment by jonasfj** [comment]
The motivation for this was to ensure eventual consistency... by forcing a complete rebuild of the search index, so if garbage somehow sneaks into the index then eventually it'll get purged.

If this comes at a memory cost that seems fine.. Well, that's a different issue we can discuss :) haha

**Comment by isoos** [comment]
It seems to be feasible to start a separate isolate for the snapshot update, because the snapshot itself is about 200MB in memory. What I'm unsure about is what takes ~500-600 MB memory before the snapshot starts to load, that needs some debugging. (I've already ruled out SDK snapshot and popularity data).

We could also use this to restrict the number of initial updates: when the snapshot is loaded, we do a full-scan update, but it would be enough to do the scan after the snapshot-created timestamp.

**Comment by jonasfj** [comment]
If memory is a concern, we can just double the instance size.

**Comment by isoos** [comment]
I think the original goals are mostly matched, closing the issue.

> Ensure we can generate the index from nothing.

The same code path populates the snapshot as the index: at startup it will scan the Packages and create entries if they are not present.

> Eliminate drift in case of bugs and temporary inconsistency in data.
> Ensure eventual consistency, increasing robustness.

#1982 improved on this: we'll update the entries roughly once a day, making sure it is up-to-date. As a side-effect, it will also update the popularity score values inside the index.
