### ISSUE TITLE
Encourage HTTPS links to well known sites with HTTPS

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1933]
Some packages have set their homepage to a HTTP link when the homepage offers HTTPS. For instance, <https://pub.dartlang.org/packages/source_maps> links to <http://github.com/dart-lang/source_maps> over HTTP even though github has HTTPS.

I suggest the pub website helps turn these homepage links into HTTPS links.

* For well known sites like github with HTTP, either fix the protocol scheme when displaying the link, or at least issue a tiny score penalty telling the package owner to fix the link. Note that major sites tends to preload their certificates, so the browser would automatically redirect to HTTPS, but it could be the first time the user visits github.
* For unknown sites, we already scan whether the site is there when analyzing the package. We could check for whether the HTTPS port is active and has a valid certificate. There may be false positives when doing that as some sites has HTTPS but it's not set up right or have different content. In that case, the analyzer could suggest fixing the link, potentially with a small penalty.

What do you think?

**Comment by isoos** [comment]
Let's start with the minimal non-https penalty. I'd rather skip on rewriting the URLs if it is not necessary.

**Comment by sortie** [comment]
Well yes github does redirect to https but that's not secure unless the browser has the site already stored as a https site. It's a simple change to detect the most well known sites and simply change the schema but at least there's a warning now, although I imagine a number of packages will ignore those (but let's see). The stuff we do to detect the bug tracker is more complex.

**Comment by jonasfj** [comment]
Let's not add complex logic to rid ourselves of http links... This a complication that needs to be maintained and tested.

We have more pressing concerns wrt. hardening security.. improving trust model, publishing hashes, signing packages... Let's spend our energy on features that'll make an impact..

Most of the web is slowly moving away from HTTP anyways. A complete migration will take time, we need to enable it. Showing http links in analysis is a amazing, I'm not sure I would have gone that far..

Note we can discuss this in the meeting tomorrow. But my suggestion is that we spend our energy somewhere else..

@sortie, you could also scan all linked repositories for unnecessary HTTP links and file PRs against them that fixes the links to HTTPS :)
(I'm joking of course -- it's not obvious that automated PRs will br well received)

**Comment by isoos** [comment]
Discussed this again, and we've agreed on closing this. If people won't change the URLs after the analysis suggestion, we may reconsider, but let's just hope that they will update them.
