### ISSUE TITLE
Mark google_xxx api packages as discontinued

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1938]
Please mark the following packages as discontinued. They are not dart2 compatible, and have no usage. Further, they are all replaced by https://pub.dartlang.org/packages/googleapis.

google_adexchangebuyer_v1_1_api
google_adexchangebuyer_v1_2_api
google_adexchangebuyer_v1_3_api
google_adexchangebuyer_v1_api
google_adexchangeseller_v1_1_api
google_adexchangeseller_v1_api
google_adexchangeseller_v2_0_api
google_admin_directory_v1_api
google_admin_email_migration_v2_api
google_admin_reports_v1_api
google_adsense_v1_2_api
google_adsense_v1_3_api
google_adsense_v1_4_api
google_adsensehost_v4_1_api
google_analytics_v2_4_api
google_analytics_v3_api
google_androidpublisher_v1_1_api
google_androidpublisher_v1_api
google_androidpublisher_v2_api
google_appsactivity_v1_api
google_appstate_v1_api
google_audit_v1_api
google_autoscaler_v1beta2_api
google_bigquery_v2_api
google_blogger_v2_api
google_blogger_v3_api
google_books_v1_api
google_calendar_v3_api
google_civicinfo_us_v1_api
google_civicinfo_v1_api
google_cloudmonitoring_v2beta1_api
google_compute_v1_api
google_content_v2_api
google_coordinate_v1_api
google_customsearch_v1_api
google_datastore_v1beta1_api
google_datastore_v1beta2_api
google_dfareporting_v1_1_api
google_dfareporting_v1_2_api
google_dfareporting_v1_3_api
google_dfareporting_v1_api
google_discovery_v1_api
google_dns_v1beta1_api
google_doubleclickbidmanager_v1_api
google_doubleclicksearch_v2_api
google_drive_v1_api
google_drive_v2_api
google_freebase_v1_api
google_freebase_v1_sandbox_api
google_freebase_v1sandbox_api
google_fusiontables_v1_api
google_games_v1_api
google_gamesmanagement_v1management_api
google_gan_v1beta1_api
google_genomics_v1beta_api
google_gmail_v1_api
google_groupsmigration_v1_api
google_groupssettings_v1_api
google_identitytoolkit_v3_api
google_licensing_v1_api
google_manager_v1beta2_api
google_mapsengine_exp2_api
google_mapsengine_v1_api
google_mirror_v1_api
google_oauth2_v1_api
google_oauth2_v2_api
google_orkut_v2_api
google_pagespeedonline_v1_api
google_plus_v1_api
google_plusdomains_v1_api
google_prediction_v1_2_api
google_prediction_v1_3_api
google_prediction_v1_4_api
google_prediction_v1_5_api
google_prediction_v1_6_api
google_pubsub_v1beta1_api
google_qpxexpress_v1_api
google_replicapool_v1beta1_api
google_reseller_v1_api
google_reseller_v1sandbox_api
google_resourceviews_v1beta1_api
source_transformer
google_siteverification_v1_api
google_spectrum_v1explorer_api
google_sqladmin_v1beta1_api
google_sqladmin_v1beta3_api
google_storage_v1_api
google_storage_v1beta1_api
google_storage_v1beta2_api
google_taskqueue_v1beta1_api
google_taskqueue_v1beta2_api
google_tasks_v1_api
google_translate_v2_api
google_urlshortener_v1_api
google_webfonts_v1_api
google_webmasters_v3_api
google_youtube_v3_api
google_youtubeanalytics_v1_api
google_youtubeanalytics_v1beta1_api

**Comment by jonasfj** [comment]
done
