### ISSUE TITLE
Please mark the following Dart Team packages as discontinued

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1941]
Please mark the following Dart Team owned packages as discontinued:

build_compilers
lookup_map
sequence_zip
analysis_services
analysis_testing
bazel_ipc
browser_controller
cloud_datastore
collection_helpers
docgen
dummy_package_for_ssl_bug
minimal_serialization
minimal_serialization_example
notification
`_test_`

**Comment by jonasfj** [comment]
done
