### ISSUE TITLE
Make sure that SIGTERM triggers a quick shutdown.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1950]
- [ ] app
- [ ] analyzer
- [ ] dartdoc
- [ ] search

**Comment by isoos** [comment]
It looks like that DartVM by default handles the quick shutdown. If we don't bind handlers to the specific `ProcessSignal` events, it will just shut the VM down. Checked with `app`, `search`, and a very minimal `main() async { await Future.delayed(Duration(days: 1));}`.

**Comment by isoos** [comment]
I don't see any sign of binding in `appengine` or any of the libraries we are using. Let's close this?

**Comment by jonasfj** [comment]
Agreed, we should close this...

Ideally, the app should shutdown gracefully, instead of dropping active connections, but I'm okay ignoring that for now :)
