### ISSUE TITLE
Add scss as a supported language for syntax highlighting in documentation

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pub-dartlang-dart#1951]
We commonly document the usage of visual customizations for angular UI components with .scss code. Sometimes it will do an OK job with auto-detection but if you add the `scss` hint to a triple tick code block it doesn't work well.

scss is a supported language in the highlightjs docs:
https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases

**Comment by isoos** [comment]
Updated the related file, will be part of the next release.
