### ISSUE TITLE
Fix supportsOnlyLegacySdk to reflect required upper bound constraint

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#1952]
See: https://www.dartlang.org/dart-2 which says:

> Packages must have an upper constraint of <3.0.0 to work in Dart 2 stable and subsequent Dart 2 releases. Dart 2 dev builds before the stable release have lax upper constraint checking and can use packages that have no SDK constraints or an upper constraint of <2.0.0.

This should be fixed in:

https://github.com/dart-lang/pub-dartlang-dart/blob/1c41306575771c210de14b959232aaf0d5d03752/app/lib/frontend/model_properties.dart#L84-L87

**Comment by isoos** [comment]
#1977 fixed this
