### ISSUE TITLE
Handle pubspec parsing errors

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#1960]
We're not handling pubspec parsing issues:

![kfxj3no5tvy](https://user-images.githubusercontent.com/149732/51315190-de8d8300-1a51-11e9-90d8-c72b59ea002e.png)

This package had wrong `issue_tracker`:
https://github.com/akashMehta-STL/FlutterPaginationHelper/blob/001040c401dc2d2b26ffdbc4e6d39ad8203957e6/pubspec.yaml#L8-L9

**Comment by isoos** [comment]
Oh, it is from `ToolEnvironment.detectFlutterUse`. Yeah, that path uses strict parsing. Should pana be all-lenient, or do we have any case where pana should be strict? Or should we be all-lenient, be add a strict-check with penalty?

**Comment by jonasfj** [comment]
I'm okay with making pana all-lenient and then give a penalty :)

**Comment by isoos** [comment]
Fixed in staging, small PR out for not always providing reasonable message.
