### ISSUE TITLE
run dart bin/tools/remove_all_analysis.dart on prod

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#1961]
See: https://github.com/dart-lang/pub-dartlang-dart/pull/1959

@isoos, should we run this now, or wait for next release?

**Comment by jonasfj** [comment]
We still have old versions running..

(I just filed this so we don't forget to do it)

**Comment by isoos** [comment]
> We still have old versions running..

How many releases do we have since? Is it likely we will go back to them? Shall we just stop them?

**Comment by jonasfj** [comment]
We only have to versions running, so we're probably fine...

**Comment by jonasfj** [comment]
Done :)
```
...
Deleting 237 PackageVersionAnalysis (total: 42237)...
...
Deleting 468 Analysis (total: 351968)...
...
Deleting 64 PackageAnalysis (total: 5064)...
```
