### ISSUE TITLE
Review latency stats after switch to redis 

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#1971]

**Comment by isoos** [comment]
Using this issue to discuss the redis timeouts from the staging logs. Most of the entries are something like this:

````
Error:
    TimeoutException after 0:00:00.200000: Future not completed

Stack:
    #0      RedisCacheProvider._withRedis.<anonymous closure> (package:simple_cache/src/providers/redis.dart:84:21)
    <asynchronous suspension>
    #1      RetryOptions.retry (package:retry/retry.dart:109:24)
    <asynchronous suspension>
    #2      RedisCacheProvider._withRedis (package:simple_cache/src/providers/redis.dart:79:64)
    <asynchronous suspension>
    #3      RedisCacheProvider.get (package:simple_cache/src/providers/redis.dart:111:40)
    #4      _Entry.get (package:simple_cache/simple_cache.dart:162:38)
````

Note the above duration is 200ms. The timeouts are clustered and happen at the same time the index updates were happening. This aligns well with the theory that the timeouts happened because of the CPU-bound index handling.

**Comment by jonasfj** [comment]
200ms timeout might also be too low...

Ideally, background and foreground services should have different timeouts... But that seems overkill to configure. A simpler fix is probably to increase the timeout to 500ms, and reduce the batch size as you were talking about :)

**Comment by isoos** [comment]
> The timeouts are clustered and happen at the same time the index updates were happening. 

More precisely: the timeout happens while the search backend creates the `PackageDocument` instances, and loads the following:
- `Package` entity (Datastore, non-cached)
- `PackageVersion` entity (Datastore, non-cached)
- `ScoreCard` entity (Datastore, cached lookup(s))
- `pub-data.json` file: DartdocEntry (storage, cached lookup(s)) + storage.read (non-cached)

Of these, the `ScoreCard` has a little CPU-bound part, but most of the time is spent with the `pub-data.json` processing. Decoding the JSON and processing the structure is both synchronous and CPU-intensive, and very well could block the CPU for 200ms while the redis requests are waiting for the callback completition.

**Comment by isoos** [comment]
If I remove the batched update of the search index, the number of timeouts decrease significantly, but a few still occur. (The reduction in code complexity makes it worth doing anyway.)

With that change, the cache use of `PackageDocument` construction becomes a sequential async operation, but there are other processes that are running in the same VM:
- scanning of the Datastore (initial `Package` scan, regular `ScoreCard` scan)
- periodic check of the in-memory snapshot

The Datastore scanning part could be moved to a different isolate, and that should certainly help the event loop latencies (and the cache timeouts). At the same time, we could differentiate the logging requirements:
- for frontend-serving cache requests, we could continue to report timeouts
- for processing cache requests, we could increase the timeouts, and also ignore the log message if a timeout happens.

wdyt?

**Comment by jonasfj** [comment]
Reading this got me thinking (unrelated) that we should measure event loop latencies and show get those metrics in to stackdriver..

> for processing cache requests, we could increase the timeouts, and also ignore the log message if a timeout happens.

Catching an ignoring timeouts might be a good option... I'm not sure..

**Comment by isoos** [comment]
> Reading this got me thinking (unrelated) that we should measure event loop latencies and show get those metrics in to stackdriver..

We do measure them: `/debug`: `"vm"/"eventLoopLatencyMillis"`. Every 3 seconds we run a timer (with Duration.zero) and measure the difference, tracking the last 1000 measurements. How should we expose it to stackdriver?
