### ISSUE TITLE
Lint shows suggestion to add demo though project is already having that.

### ISSUE THREAD

**Issue by akashMehta-STL** [dart-lang/pub-dartlang-dart#1973]
I updated project as per lint suggestions and all other suggestions like to format file was resolved except this one 

> Maintain an example. (-10 points)
>
> Create a short demo in the example/ directory to show how to use this package. Common file name patterns include: main.dart, example.dart or you could also use flutter_pagination_helper.dart.

I tried to analyze code by running flutter analyze command but result was clean here.

please check this issue for this [library](https://pub.dartlang.org/packages/flutter_pagination_helper#-analysis-tab-)

You can check code from [here](https://github.com/akashMehta-STL/FlutterPaginationHelper/tree/feature/pub_dartland_project)

**Comment by jonasfj** [comment]
@isoos, I guess this is evidence that we should improve the text in our suggestions...
Maybe we should link to: https://www.dartlang.org/tools/pub/package-layout

@akashMehta-STL, if you read: https://www.dartlang.org/tools/pub/package-layout
does that help explain where the examples should be located in the package?

**Comment by isoos** [comment]
@akashMehta-STL: in addition to the patterns mentioned on https://www.dartlang.org/tools/pub/package-layout#examples, we also support a markdown-formatted `example/README.md` file, in which you can point to multiple projects or outline complex structures.

/cc @kwalrath: we should update the above page with the readme file support.

@jonasfj: updating `pana` suggestion with the link.
