### ISSUE TITLE
simple_permissions incompatible with Swift 4.2

### ISSUE THREAD

**Issue by superdev89** [dart-lang/pub-dartlang-dart#1994]
URL: https://pub.dartlang.org/packages/simple_permissions

=== BUILD TARGET gRPC-C++ OF PROJECT Pods WITH CONFIGURATION Debug ===
    /flutter/.pub-cache/hosted/pub.dartlang.org/simple_permissions-0.1.9/ios/Classes/SwiftSimplePermissionsPlugin.swift:51:38: error: 'UIApplicationOpenSettingsURLString' has been renamed to 'UIApplication.openSettingsURLString'
                if let url = URL(string: UIApplicationOpenSettingsURLString) {
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                         UIApplication.openSettingsURLString
    UIKit.UIApplicationOpenSettingsURLString:3:12: note: 'UIApplicationOpenSettingsURLString' was obsoleted in Swift 4.2
    public let UIApplicationOpenSettingsURLString: String

**Comment by isoos** [comment]
@superdev89: this repository is for the pub site, you should always contact the package author wrt. their package. In this case the author moved/deleted theirs, please contact them directly via e-mail.
