### ISSUE TITLE
Please delete package flutter_mvvm

### ISSUE THREAD

**Issue by dcov** [dart-lang/pub-dartlang-dart#1999]
I uploaded this package last May but never got around to developing it any further and don't plan to in the future. If there are people using it (which I highly doubt as it isn't even Dart 2 compatible, and is pretty much useless), I would be willing to transfer ownership. Otherwise I'd prefer if it was deleted.

Thanks.

**Comment by dcov** [comment]
Yeah that'll work too, but I think it qualifies as an almost-empty package/useless package. It's only one file, with around 50 lines, that exposes functionality that's already available in the framework.

I definitely should have taken more care before publishing so I do apologize for that. I'll be more careful in the future with publishing.

But yeah, as you said, in case it's being used I'm fine with marking it discontinued.

**Comment by jonasfj** [comment]
marked discontinued...
