### ISSUE TITLE
Can't change mail used to publish package due to e-mail suppression

### ISSUE THREAD

**Issue by thomas-doussin** [dart-lang/pub-dartlang-dart#2005]
URL: https://pub.dartlang.org/packages/ssl_pinning_plugin

Hi
We have uploaded our plugin with the following mail "s_ddg_numerique@macif.fr" in may 2018.
But, our company switched from a internal mailer to GSuite. And all old adresses linked to non-professionnal Gmail account were deleted (including this mail :( ). Thus, right now, we can't publish an update of our plugin. Neither publish a new one as dart-lang detect that is near the old one.

To be able update how to proceed to
- Grant access to other mails ? I haven't found a way to do so without having access to the account
- Or Remove the plugin to allow us to publish a new one

Thanks

**Comment by jonasfj** [comment]
@thomas-doussin, do you still have access to the email `s_ddg_numerique@macif.fr`, if so use `pub uploader add <email>` to add your new email as uploader, you'll need to login with a google account that has the email `s_ddg_numerique@macif.fr` email...

note. to logout of you current account in pub just delete `~/.pub-cache/credentials.json`... a feature to do this smarter should land in the SDK sometime soon too :)

**Comment by jonasfj** [comment]
resolved

**Comment by fatihbalsoy** [comment]
@jonasfj If we accidentally logged into the wrong email address to upload a package, how can we replace and remove our personal email from our package homepage to a professional email address?

**Comment by sigurdm** [comment]
* From the personal account run `pub uploader add prof@work.com` to add your professional address.
* Accept the email invite, and log in with the professional address (first log out by deleting ~/.pub-cache/credentials.json).
* Then remove the personal email-address: `pub uploader remove personal@gmail.com`.
