### ISSUE TITLE
Fail to use `pub get` install the Dart Sass 

### ISSUE THREAD

**Issue by zozoh** [dart-lang/pub-dartlang-dart#2006]
Hi, I am newcomer of Dart. I wanna build my sass file by [Dart-sass](https://sass-lang.com/dart-sass).
Following the [guide](https://sass-lang.com/dart-sass), I meet the issue:

```
...
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
```

It panic me, how should I do? how should I do?

-------------------------------------------------------------
### 1. make a folder, and create a `pubspec.yaml`

```yaml
name: my_project
dev_dependencies:
  sass: ^1.16.1
```

### 2. run the command `pub get`

```cmd
PS D:\workspace\git\github\roadz> dart --version
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
PS D:\workspace\git\github\roadz\practise\sass> pub get
Resolving dependencies...
+ args 1.5.1
+ async 2.0.8
+ charcode 1.1.2
+ cli_repl 0.2.0+1
+ collection 1.14.11
+ http 0.12.0+1
+ http_parser 3.1.3
+ js 0.6.1+1
+ matcher 0.12.4
+ meta 1.1.7
+ package_config 1.0.5
+ package_resolver 1.0.6
+ path 1.6.2
+ quiver 2.0.1
+ sass 1.16.1
+ source_maps 0.10.8
+ source_span 1.4.1 (1.5.4 available)
+ stack_trace 1.9.3
+ stream_transform 0.0.14+1
+ string_scanner 1.0.4
+ tuple 1.0.2
+ typed_data 1.1.6
+ watcher 0.9.7+10
Downloading sass 1.16.1...
Downloading source_span 1.4.1...
Downloading tuple 1.0.2...
Downloading path 1.6.2...
Downloading cli_repl 0.2.0+1...
Downloading js 0.6.1+1...
Downloading charcode 1.1.2...
Downloading source_maps 0.10.8...
Downloading string_scanner 1.0.4...
Downloading meta 1.1.7...
Downloading package_resolver 1.0.6...
Downloading args 1.5.1...
Downloading package_config 1.0.5...
Downloading watcher 0.9.7+10...
Downloading async 2.0.8...
Downloading stream_transform 0.0.14+1...
Downloading collection 1.14.11...
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
```

-------------------------------------------------------------
## About My ENV

- City : Beijing.China
- OS : Win10 Pro 17134.523
- Dart : 2.1.0

I d try to connected the net directly, or by proxies. In China as you known,
we had to switch proxy to access the service like google/twitter etc.
But the result was same:

```bash
...
Downloading collection 1.14.11...
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
PS D:\workspace\git\github\roadz\practise\sass>  # <- for a while, it quitted
```

-------------------------------------------------------------
## How should I do

I want to get some suggestion about how should I do next? 
Did there are any way to provide more useful information to you guys?
Did it is a bug of `pub.dartlang.org`? or maybe just I do something wrongly?

Thanks anywhy :)

**Comment by isoos** [comment]
There are a few community-run mirror/proxy sites that you can use to access pub. To use that you should set the `PUB_HOSTED_URL` environment variable to point to a new domain. In Unix and OSX you can use the following (sorry, not sure how to set it in your windows env):

````
export PUB_HOSTED_URL=https://pub.flutter-io.cn
````

The https://flutter.io/community/china site mentions another one: https://dart-pub.mirrors.sjtug.sjtu.edu.cn/

**Comment by zozoh** [comment]
@isoos  as I setup the env `PUB_HOSTED_URL=https://pub.flutter-io.cn` and run the `pub get` again, it worked. Thanks :)
