### ISSUE TITLE
Pub should display the license of a package

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#201]
Knowing what license a package uses is a major criteria when selecting whether to depend on something or not. Currently you have to manually click the license file to determine this. 

The present bug tracks making the license an actual field displayed alongside the other properties of the app. It would be good if we could infer the type for all commonly used open source licenses (similar to how github does it in the top "info band" on a repo page).

**Comment by isoos** [comment]
@kevmoo: I'd move this (issue | logic) into pana, because a package could have dependencies that are mutually exclusive wrt. their licenses. Thoughts?

**Comment by kevmoo** [comment]
Yeah, let's open a tracking bug in Pana for this.

Ugh...detecting this stuff will be fun!

**Comment by mit-mit** [comment]
GitHub's docs say this use this to detect the licenses: https://github.com/benbalter/licensee

**Comment by mit-mit** [comment]
> because a package could have dependencies

On that note: are we doing anything to display dependencies?

**Comment by isoos** [comment]
Tracking issue for basic license detection: https://github.com/dart-lang/pana/issues/37

**Comment by isoos** [comment]
> On that note: are we doing anything to display dependencies?

Pana detects dependencies and platform, we will soon deploy the analyzer service in staging, and then connect the package info page with that. If it goes well, deploying to prod is next.

**Comment by kevmoo** [comment]
> GitHub's docs say this use this to detect the licenses: https://github.com/benbalter/licensee

🔥 Hawt! Ruby is easy to add to a docker image...

**Comment by isoos** [comment]
Some licenses are now detected and displayed at the right side (e.g. BSD, GPL) for example [here](https://pub.dartlang.org/packages/pana).

More to come with upcoming `pana` version (e.g. Apache, MPL, LGPL).

**Comment by mit-mit** [comment]
Great!

Any chance we could make the license display link to the actual license file? For example,  in your example Pub detail page above `BSD` would be a link to `https://github.com/dart-lang/pana/blob/master/LICENSE`

**Comment by isoos** [comment]
Opened new issue for it: https://github.com/dart-lang/pub-dartlang-dart/issues/351
