### ISSUE TITLE
Weirdly blank analysis data for json_serializable

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#2011]
URL: https://pub.dartlang.org/packages/json_serializable#-analysis-tab-

![screen shot 2019-02-04 at 12 40 50 pm](https://user-images.githubusercontent.com/17034/52235858-2269f000-287a-11e9-9c60-477d45502a75.png)

CC @jonasfj @isoos

**Comment by jonasfj** [comment]
hmm, seems to me that this package was published while we did a release of pub.. so this is expected behavior, and indeed this has resolved itself by now... 2.0.2 was released `Feb 4, 2019`. 

@isoos, is it overkill to show that no analysis have been completed yet?

**Comment by isoos** [comment]
Analysis timestamp: 2019-02-04T22:04:06.577880Z
Dartdoc timestamp: 2019-02-04T20:28:23.780464Z
Issue timestamp: 2019-02-04 20:41 UTC

It looks like it took a while before the version was picked up for analysis (probably as we had the prod release that day), and in the meantime dartdoc was already completed. Before that we were showing the `ScoreCard` from the previous runtime, but at that point we created a `ScoreCard` with the dartdoc results only, and started to display that.

Reopening, as this needs to be fixed.
