### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by AakashGautam007** [dart-lang/pub-dartlang-dart#2051]
URL: https://pub.dartlang.org/packages/cloud_firestore#-readme-tab-

<Describe your issue or suggestion here>

.snapshop();    

this is not a function please use instead 
stream: Firestore.instance.collection('books').snapshots,

**Comment by isoos** [comment]
@AakashGautam007 this repository is for the pub site, for package issues, please file issues into the package's repository. I'm moving this issue now.

**Comment by isoos** [comment]
This issue was moved to flutter/flutter#27930
