### ISSUE TITLE
Skim through logs and fix 500s

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#2081]
Many of the 500s should probably 4xx...

**Comment by jonasfj** [comment]
Note. I know we can't remove all 500s, but maybe it's time to do some gardening and remove some of them... and then close this issue. We can open new bug next time we see a lot of 500s :)

**Comment by isoos** [comment]
While there are some odd ones like `GrpcError: "The service is temporarily unavailable." (code: 14)`, big percentage of it is `DetailedApiRequestError(status: 503, message: Backend Error)` related to storage-bucket access. I think #2084 will reduce the access of the storage buckets, and we'll see probably less of these on both `/api/documentation` and on `/documentation`.

**Comment by isoos** [comment]
Example 500s that are not related to dependent services:

A) `/https://pub.dartlang.org/` from a client agent of "Test Certificate Info". Seems to be an `package:appengine` or a `package:shelf` issue, as the exception stack trace is in the former, while the origin is in the later:

````
Error parsing request.
Invalid argument(s): handlerPath "null" and url "null" must combine to equal requestedUri path "/http://".
dart:_http                                                 _HttpServer.listen
package:appengine/src/server/server.dart 50:14             AppEngineHttpServer.run.<fn>
===== asynchronous gap ===========================
dart:async                                                 Future.then
package:appengine/src/server/server.dart 47:10             AppEngineHttpServer.run
package:appengine/src/appengine_internal.dart 55:21        runAppEngine.<fn>
package:appengine/src/appengine_internal.dart 110:20       _withAppEngineServicesInternal.<fn>
````

B) `/packages/sqflite#-readme-tab-` from IE9 (?) (or a proxy that sends the fragment to us).
I couldn't replicate it yet, as the modern HTTP clients already strip the `#fragment` part of the URL.

**Comment by isoos** [comment]
I think for both cases the lack of exception trace indicates that the root exception happens in `package:shelf`: https://github.com/dart-lang/shelf/blob/master/lib/src/request.dart#L172-L184

I was able to reach the `requestedUri.isAbsolute` exception with sending in the `#fragment` invoking the handler directly, but I couldn't get a real exception trace on the console. In such cases the parsing immediately goes to an error path:
https://github.com/dart-lang/shelf/blob/master/lib/shelf_io.dart#L74-L81

@jonasfj: any thought on how we should address this?

We could do a pre-parsing before passing it to `shelf`, but that kind of defeats the purpose, and also in the case of the `#fragmented` URL, we'd need to override the `requestedUri` somehow.

**Comment by isoos** [comment]
The original issues were addressed.
