### ISSUE TITLE
Wrong repository refered from pub package documentation.

### ISSUE THREAD

**Issue by rodrigogalhardo** [dart-lang/pub-dartlang-dart#2092]
URL: https://pub.dartlang.org/packages/back_button_interceptor#-readme-tab-

The github repository is redirecting to wrong git repo page, the correct repo about pub package is: https://github.com/marcglasberg/back_button_interceptor

:)

**Comment by isoos** [comment]
The author needs to fix it here: https://github.com/marcglasberg/back_button_interceptor/blob/master/pubspec.yaml#L5

Please file an issue or a PR in the package's repository.
