### ISSUE TITLE
how to remove a particular version from package uploaded to pub.dartlang

### ISSUE THREAD

**Issue by jaiswalshubham84** [dart-lang/pub-dartlang-dart#2099]
is there any way to remove a particular package version from pub.dartlang.
i have multiple version of the package with same functionalities, didn't find any option to remove the unwanted version.

**Comment by jonasfj** [comment]
You can file a request here.. then I'll confirm by email. But if it's been published for a long time it might be better to mark it discontinued... This way it won't show up in search, and you won't break people that depend on your package..

**Comment by jaiswalshubham84** [comment]
thanks @jonasfj
please remove all the version except 0.0.1
the package link is : https://pub.dartlang.org/packages/flutter_multi_carousel

**Comment by jonasfj** [comment]
I sent an email to confirm identity...

**Comment by jaiswalshubham84** [comment]
@jonasfj 
i have confirm the mail. 
please carry your step to remove all the version except 0.0.1.

**Comment by jonasfj** [comment]
I confirmed this request...

**Comment by jaiswalshubham84** [comment]
@jonasfj 
how much time it generally take to perform this delete task.

**Comment by jonasfj** [comment]
@jaiswalshubham84, looks like our tools doesn't support deleting the latest version... but if we want we can remove all versions, then you'll have to republish...

**Comment by jaiswalshubham84** [comment]
@jonasfj , ok, remove it all

**Comment by jaiswalshubham84** [comment]
@jason-simmons 
i somehow again pushed the wrong code from my end.
extremely sorry from end.
can you again delete all the versions of the package.
thanks in advance
Shubham Kumar

**Comment by jonasfj** [comment]
Removed the package, @jaiswalshubham84, you can publish now...

**Comment by jaiswalshubham84** [comment]
@jonasfj thanks🙂

**Comment by phillwiggins** [comment]
Hi

Please can you remove both of these versions? 
https://pub.dev/packages/parse_server_sdk_flutter/versions/1.0.28
https://pub.dev/packages/parse_server_sdk/versions/1.0.28

Thanks in advance.

**Comment by isoos** [comment]
@phillwiggins: please contact `support@pub.dev` as stated on the policy page: https://pub.dev/policy

**Comment by nvrr** [comment]
how to upgrade my package from 0.0.1 to 0.0.2,
when i doing, it shows 
Version 0.0.1 of package prompter_nvr already exists.
pub finished with exit code 1

**Comment by isoos** [comment]
@nvrr: you need to update the version in your `pubspec.yaml`. See https://dart.dev/tools/pub/pubspec for more info about it.

**Comment by nvrr** [comment]
> 
> 
> @nvrr: you need to update the version in your `pubspec.yaml`. See https://dart.dev/tools/pub/pubspec for more info about it.

thanks sir, now i got it

**Comment by nvrr** [comment]
> rretrerf

**Comment by nvrr** [comment]
- [ ]

**Comment by nvrr** [comment]
`void main() { 
  final options = [
    Option('I want red', '#f00'),
    Option('I want blue', '#00f')
  ];

 final prompter = Prompter();

 String colorCode = prompter.askMultiple('Select a color:', options);

 bool answer = prompter.askBinary('Do you like this lib?');

 print(colorCode);
 print(answer);
}`

**Comment by Donzo24** [comment]
Hi @jonasfj 

Please can you remove this version ?
https://pub.dev/packages/flutter_nimbas_sms/versions/1.0.0

Thanks in advance.

**Comment by isoos** [comment]
@Donzo24: please use the process described in https://pub.dev/policy.

**Comment by jonasfj** [comment]
Please refer to [pub.dev/policy](https://pub.dev/policy). Not we never allow republishing of the same version again!

Or use [retraction](https://dart.dev/tools/pub/publishing#retract) instead, it's much better for everybody.
