### ISSUE TITLE
Need to invalidate cached package pages when adding/removing uploaders

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/pub-dartlang-dart#21]
Adding an uploader via `pub uploaders add a@b.com` might only show up after the cache expiration. We should invalidate the **UI cache** after uploads.

**Comment by kevmoo** [comment]
+1

**Comment by mkustermann** [comment]
CL up for review: https://codereview.chromium.org/1267883004/
Though the expiration is just 1 hour or something like that.

**Comment by mkustermann** [comment]
Fixed.

**Comment by kevmoo** [comment]
Awesome! 0921c665d2638f416c68e9860f2c2206fa8478b8
