### ISSUE TITLE
Request to delete

### ISSUE THREAD

**Issue by fatihbalsoy** [dart-lang/pub-dartlang-dart#2102]
URL: https://pub.dartlang.org/packages/flutter_morse

Package name is misleading and I'd rather keep the package on GitHub.

**Comment by epireyn** [comment]
URL: https://pub.dartlang.org/packages/install_apk

I published it by mistake

**Comment by jonasfj** [comment]
I've sent uploaders an email, waiting for confirmation.

**Comment by jonasfj** [comment]
Request have been confirmed...

btw, I think it's a pretty cool project :)
Not that I have clue what to use it for... hehe.. maybe writing an app :)

**Comment by jonasfj** [comment]
package `flutter_morse` has been delete per request.

@epireyn, please file a issue bug for `install_apk`.
