### ISSUE TITLE
Packages with zero score should not show up in searches

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pub-dartlang-dart#2128]
Packages with zero score should not show up in searches (or in Google results), IMO.
example:
https://pub.dartlang.org/packages/date

**Comment by eseidelGoogle** [comment]
Looks like they're already hidden from pub searches:
<img width="994" alt="Screen Shot 2019-03-14 at 8 56 07 AM" src="https://user-images.githubusercontent.com/11857803/54371673-0acf1580-4637-11e9-9237-13dd64475677.png">
But not from Google searches (which might be harder):
<img width="663" alt="Screen Shot 2019-03-14 at 8 55 44 AM" src="https://user-images.githubusercontent.com/11857803/54371689-128eba00-4637-11e9-85a5-2e30cd6174dd.png">

**Comment by jonasfj** [comment]
We could probably just add `<meta name="robots" content="noindex">`
See: https://support.google.com/webmasters/answer/93710?hl=en
