### ISSUE TITLE
I think this plugin should be removed

### ISSUE THREAD

**Issue by taheralami** [dart-lang/pub-dartlang-dart#2130]
URL : https://pub.dartlang.org/packages/fuck#-versions-tab-

It is obviously a fake plugin sitting there for a month.

**Comment by jonasfj** [comment]
hehe, maybe we should define a policy and moderate useless content like this... But at the moment this seems pretty harmless :)

Note. I think we should be careful with establishing a policy for moderating useless packages.

-----
If someone wanted to use the package name for something else, I might feel differently about it... But I doubt this is one of those package names :) hehe

----
If you are the owner if this package, and would like it removed, please reopen this issue.
