### ISSUE TITLE
pkg:bloom_filter & pkg:bit_vector

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/pub-dartlang-dart#2135]
Hi, I'm currently using the [bloom_filter](https://pub.dartlang.org/packages/bloom_filter) package in a project I'm working on. This has a dependency on a package by the same author [bit_vector](https://pub.dartlang.org/packages/bit_vector) - this has dependencies on two testing packages: propcheck & enumerators. None of these packages support Dart 2. I've made a few small amends to the packages and removed the problematic dependencies from `bit_vector` (also had to sacrifice a couple of the tests that depend on those packages). 

I've reached out to the author (@kseo) of the packages on February 18th and provided my commits and asked if they would accept a PR. I've not had a response, I think the author may have moved on from Dart.

I've since added a few additional methods to the bloom_filter package to allow the objets be exported in to bits and restored from bits which allows me to store & index bloom_filters in Firestore.

I can keep either my either keep my changes local/private or could submit them under new package name(s)? 

If publishing the changes then maybe adding the `bit_vector` class into `bloom_filter` and not exposing it may be beneficial as the math behind bit_vector is beyond me and couldn't support anybody using it outside of the scope of the `bloom_filter` package?

The packages I'm currently using:
https://github.com/jimmyff/bloom_filter
https://github.com/jimmyff/bit_vector

**Comment by jonasfj** [comment]
I'm not sure exactly what you're asking :)

If you're wondering if you can publish the packages under a different package name the answer is: Yes, if the `LICENSE` permits it -- in your case the code looks BSD licensed, I'm no lawyer but read the license it's very short :)

----
Personally, I think it's good practice to reach out to the original author and ask if original author wants to accept contributions, or if the package appears unmaintained politely ask if they are open to transferring ownership to you. The email of the package author is listed on the package page on pub.

But if you've already tried to contact the original author, I suggest you just publish it under a different name like `jimmyff_bloom_filter` (or maybe you can come up with a better name).

**Comment by jimmyff** [comment]
@jonasfj okay, @kevmoo asked me to create an issue. I wasn't sure if we would be spammy having multiple packages in pub. I'll publish under a new name.

**Comment by jonasfj** [comment]
You could try to create an issue in the original authors repositories as a means of reaching out.

But we don't currently have a policy for transferring ownership of abandoned packages. The security implications of doing so seems non-trivial.

In general, I think we should be conservative about moderating packages, unless the content infringes on copyright, or the code contains backdoors, or is in some way clearly inappropriate.

Moderating packages based on personal preference seems unwise..

----
@kevmoo, curious, what do you think?
