### ISSUE TITLE
Update version in README

### ISSUE THREAD

**Issue by DigaoParceiro** [dart-lang/pub-dartlang-dart#2138]
URL: https://pub.dartlang.org/packages/flutter_url_image_load_fail

I forgot to update the current version of my package in the instructions of the README
Can you please update to `flutter_url_image_load_fail: ^0.0.3`

**Comment by jonasfj** [comment]
We generally avoid making changes to packages once published. We risk making the wrong judgement call and change something that breaks users of the package... there is a lot of concerns security for users...

I suggest you make the changes yourself and publish them as version `0.0.03+1`.
The `+1` is a build number.. it's often used if the only change in the newer version is packaging details, such as fixing a typo in a comment or the readme...

See https://semver.org/#spec-item-10

**Comment by DigaoParceiro** [comment]
Thank you!
