### ISSUE TITLE
I want to find a plugin for search packages.

### ISSUE THREAD

**Issue by jingtuo** [dart-lang/pub-dartlang-dart#2141]
This is my first time to write issues.  Please forgive me for my expressive ability. 
I'm learning flutter recently. 
In Android Studio, editing yaml is difficult, not support search packages. 
 So I want to find a plugin for the search packages.

**Comment by sigurdm** [comment]
Are you suggesting a tab-completion when editing pubspec.yaml? I don't think it exists currently.

It would be a cool feature, but it would be better filed as an issue for the android studio plugin: https://youtrack.jetbrains.com/issues/WEB?q=Subsystem:%20Dart

We do have a json search api for pub: https://pub.dartlang.org/api/search?q=keyword that could be used for implementing this.

I will close this now as this is outside the scope of this repo, but if I misunderstood you, please reopen.

**Comment by jonasfj** [comment]
I filed https://github.com/dart-lang/pub-dartlang-dart/issues/2142 to document the APIs, and make it clear what our stability expectations are...

**Comment by jingtuo** [comment]
> currently
You didn't misunderstand me.  

I didn't find it in JetBrains Plugins. Will you consider doing this plugin? 

Thank you very much for your answer.

**Comment by jingtuo** [comment]
> 
> 
> Are you suggesting a tab-completion when editing pubspec.yaml? I don't think it exists currently.
> 
> It would be a cool feature, but it would be better filed as an issue for the android studio plugin: https://youtrack.jetbrains.com/issues/WEB?q=Subsystem:%20Dart
> 
> We do have a json search api for pub: https://pub.dartlang.org/api/search?q=keyword that could be used for implementing this.
> 
> I will close this now as this is outside the scope of this repo, but if I misunderstood you, please reopen.


You didn't misunderstand me.  

I didn't find it in JetBrains Plugins. Will you consider doing this plugin? 

Thank you very much for your answer.

**Comment by jingtuo** [comment]
> 
> 
> I filed #2142 to document the APIs, and make it clear what our stability expectations are...

Thank you very much. I see.
