### ISSUE TITLE
Line break html code visible

### ISSUE THREAD

**Issue by Dirk-Sandberg** [dart-lang/pub-dartlang-dart#2153]
URL: https://pub.dartlang.org/packages/flutter_map

It looks like there is meant to be a line break in this documentation, but there was a typo.

Image here:

https://user-images.githubusercontent.com/37519914/55016761-a607a980-4fac-11e9-994d-cc59ba5c6063.png

**Comment by jonasfj** [comment]
Hmm, clearly we're not rendering markdown the same way github is... We should probably build a minimal example and file a bug upstream... Or declare that we don't support the same format as github and close this.

**Comment by isoos** [comment]
Looking at the [source file](https://raw.githubusercontent.com/johnpryan/flutter_map/master/README.md), it has a `<br>` typed into the document at that place. I believe by the Markdown spec this should not be converted to a newline.

**Comment by jonasfj** [comment]
@isoos, which markdown spec? :rofl:

**Comment by isoos** [comment]
> @isoos, which markdown spec? 🤣

- [GitHub's Markdown spec](https://github.github.com/gfm/)
- [CommonMark](https://spec.commonmark.org/0.28/)
- [DaringFireball](https://daringfireball.net/projects/markdown/syntax)

I don't see the `<br>` to `<br>` transformation in either of them, and would consider the source markdown file as not by the spec. I think we should close the issue with that.

**Comment by jonasfj** [comment]
It's actually present, here
 * https://github.github.com/gfm/#raw-html
 * https://spec.commonmark.org/0.28/#raw-html and 
 * https://daringfireball.net/projects/markdown/syntax#html

It's called inline HTML :)

In any event, @ESandberg, I think it would be better to file this upstream with a minimal example demonstrating the issue. Upstream would be: https://github.com/dart-lang/markdown

**Comment by isoos** [comment]
We are specifically removing the inline syntaxes: https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/shared/markdown.dart#L11

It is possible that we may not need to do that, or that we may add specific support e.g. for `<br/>` elements.

**Comment by jonasfj** [comment]
Oh, so we specifically modified the markdown library...
The spec says we should support inline HTML, but IMO this is one of the
scary parts of the spec, as failing to sanitize this correctly is a
security issue..

Maybe we should look at what GitHub does, and how much HTML they allow...

**Comment by isoos** [comment]
> The spec says we should support inline HTML, but IMO this is one of the
> scary parts of the spec, as failing to sanitize this correctly is a
> security issue..

I think we've disallowed inline templates for a long time now, and I think we shouldn't do it.

Given the simplicity of the current `package:markdown` implementation, I think we can add a special exception for `<br/>` tags, and maybe more if/when needed:
https://github.com/dart-lang/markdown/blob/master/lib/src/inline_parser.dart#L242-L244
