### ISSUE TITLE
Awaiting analysis to complete.

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/pub-dartlang-dart#2187]
I upgrade my plugin today.
Twenty minutes later, there is no score yet.

url: https://pub.dartlang.org/packages/flutter_ijkplayer#-analysis-tab-

**Comment by CaiJingLong** [comment]
It looks like document analysis takes too much time.
![image](https://user-images.githubusercontent.com/14145407/55863926-11a56580-5bae-11e9-8c23-c35a308cdef7.png)

**Comment by jonasfj** [comment]
Thanks for the report, @isoos, did we fix this by removing the old datastore entity?

**Comment by isoos** [comment]
The analysis was done at `2019-04-10T09:52:18.183947Z`. Do you recall at what time did you delete the record?

**Comment by jonasfj** [comment]
10.11 UTC, so this appears unrelated.

**Comment by isoos** [comment]
I may be unrelated to the fix, but I think it was related to the delay. If we hadn't had that entry, the analysis should have happened much sooner.

**Comment by isoos** [comment]
@CaiJingLong: Thanks for reporting it. Usually analysis can take anywhere from a few minutes to an hour, and in this case it took unusually longer. I'll add a few changes in the triggers to make it happen faster for new uploads.

**Comment by CaiJingLong** [comment]
Thx for work.
