### ISSUE TITLE
Request to remove 2 versions from package uploaded to pub.dartlang or remove all version, I will re-upload

### ISSUE THREAD

**Issue by Sacchid** [dart-lang/pub-dartlang-dart#2189]
Kindly remove version 1.0.1 and 1.0.2 from [Poly Package](https://pub.dartlang.org/packages/poly "Poly Package")
Version 1.0.1 & 1.0.2 added no new features - were just changes according to [suggestions form dart analysis](https://pub.dartlang.org/packages/poly#-analysis-tab- "Dart Pub Analysis")
I have a new version that I would like to upload.

**Comment by isoos** [comment]
@Sacchid: I don't see any harm to keep these versions around, especially if they happened for over a week now and people may depend on them. It is not uncommon that updates happen only to improve code quality or following suggestions.

Unless you have a pressing need to get these offline, I'd suggest you to rather just publish a new version and let your users upgrade on their own pace.

**Comment by jonasfj** [comment]
I suggest you just upload the new version :)

@Sacchid, please reopen if there is a pressing need to remove the package versions, or drop me a line if there is some sensitive reason (jonasfj@google.com).

**Comment by jonasfj** [comment]
@Sacchid, just to clarify, if you really want the packages gone for some reason we can make it happen, but we prefer not to, as it might break downstream consumers.

**Comment by Sacchid** [comment]
Ok, then I'll publish new version as v1.0.3

**Comment by jonasfj** [comment]
Awesome :)
