### ISSUE TITLE
My Package cannot use

### ISSUE THREAD

**Issue by htetwaiyan** [dart-lang/pub-dartlang-dart#2190]
> `error: cannot find symbol class MmsmsretrieverPlugin`

 show this error  every time

**Comment by jonasfj** [comment]
Please explain what you're trying to do?

Are you trying to use your own package (`mmsmsretriever`). If so what does the code using it look like... it seems to me that you might be missing an import statment or something.

It does look like the package was published correctly... I can't attest to whether or not the contents has bugs :)

**Comment by jonasfj** [comment]
Feel free to reopen, if you think this is related to the pub server.
