### ISSUE TITLE
Put a cache-control header on `static/`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#2194]
This is a simple win, we don't need a high cache expiration value to get a decent win...

5-10 minutes is better than nothing.

**Problem:** When updating the static content and deploying a new release, you might get new HTML with old static files from cache..

We could solve that by serving `/static/` with a prefix: `/static/<hash>/` where `<hash>` is computed from the contents of the files in `/static/`... We could also attach hash in the query string.. which I think we already do for some files.

**Comment by isoos** [comment]
> We could solve that by serving /static/ with a prefix: /static/<hash>/ where <hash> is computed from the contents of the files in /static/... We could also attach hash in the query string.. which I think we already do for some files.

This will solve it only if we store the old versions alongside the new ones, which would be either manually copying, or storing them as part of the deploy. With the current rate and scope of changes, I'm not sure if it is worth doing that.

**Comment by jonasfj** [comment]
For `https://pub.dartlang.org/static/img/dart-logo.svg` we currently use:
```
cache-control: max-age: 300
```
but we should be using:
```
cache-control: max-age=300
```

**Comment by jonasfj** [comment]
Let's also:
 A) Refuse to add a `cache-control` header to requests that don't have a `?hash=...` value,
 B) Set cache control to a week or something like that.

Note. we don't have to verify the hash value, if we do, we can just shout an error in logs when it's mismatching... we don't have to return 5xx...

**Comment by isoos** [comment]
> Refuse to add a cache-control header to requests that don't have a ?hash=... value,
> B) Set cache control to a week or something like that.
> [..] we don't have to verify the hash value

The current code checks the hash value, and if it matches the file's, it adds a 24-hours long cache age (barring the `:` vs `=`), otherwise 5-minutes of caching. I'll increase the long cache time to a week, and remove it otherwise, and increase the number of hashed assets.
