### ISSUE TITLE
Show pubspec.yaml next to CHANGELOG.md

### ISSUE THREAD

**Issue by srawlins** [dart-lang/pub-dartlang-dart#220]
I love our solution for showing the changelog (of the most recent version) in pub. Just render the markdown in a tab! beautiful!

What if we did the same thing for the pubspec.yaml of the most recent version of a package? Stupid simple alternative to #218 and #219. Or it could just be a stop-gap while they're implemented.

**Comment by kevmoo** [comment]
We go along way here show the dependencies, but we could show more.

https://pub.dartlang.org/experimental/packages/angular_router#-analysis-tab-

**Comment by mit-mit** [comment]
@218 was fixed, #219 was added to M4. With that we have no plans of showing pubspec.yaml, so won't fixing this.
