### ISSUE TITLE
Set HSTS headers

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#2206]
See: https://hstspreload.org/

Getting the domains preloaded is less important for now, we'll get there with the next domain for free.

Note. we should start with something like 1 hour, and later increase to a year, a decent header might be:
```
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
```

Note: we need to check that other properties on the `dartlang.org` are HTTPS, otherwise, this will break them.

**Comment by isoos** [comment]
> Note: we need to check that other properties on the dartlang.org are HTTPS, otherwise, this will break them.

Is there a simple way to test that?

**Comment by jonasfj** [comment]
CC, @mit-mit, @kevmoo, do any of you guys know about non-HTTPS properties? Do we have any under `dartlang.org`?

I haven't seen any, but it's also possible I'm not aware of all web properties :)

**Comment by kevmoo** [comment]
Everything should be HTTPS. Can't think of one that we haven't migrated.

CC @kwalrath

**Comment by kwalrath** [comment]
Everything's HTTPS, afaik.
