### ISSUE TITLE
Request to delete plugin

### ISSUE THREAD

**Issue by sarbagyastha** [dart-lang/pub-dartlang-dart#2211]
Plugin: https://pub.dartlang.org/packages/flutter_clipboard

Flutter framework provides built-in support for similar functionality, didn't knew about the built-in support in later versions of Flutter when publishing the plugin.

**Comment by isoos** [comment]
@sarbagyastha: the plugin is almost a months old and it has some use. If we were to remove it, it would break existing users who depend on it. Instead, I'd suggest the following: update the `README.md` with the description how Flutter supports the same functionality, make it clear that the plugin is no longer developed, and publish it as 1.0.2 (no code changes though).

Once that is out, we can mark the package as discontinued, and that would remove it from pub site search.

**Comment by jonasfj** [comment]
I sent an email to the uploader asking for confirmation to mark the package as discontinued.

**Comment by jonasfj** [comment]
I confirmed with author that we should mark the package as discontinued.

**Comment by sarbagyastha** [comment]
@isoos @jonasfj , updated the plugin to [1.0.2](https://pub.dartlang.org/packages/flutter_clipboard) as @isoos suggested.

**Comment by jonasfj** [comment]
Package has been flagged discontinued: https://pub.dartlang.org/packages/flutter_clipboard
