### ISSUE TITLE
Wrong config of provider in manifest

### ISSUE THREAD

**Issue by mrnodie** [dart-lang/pub-dartlang-dart#2214]
URL: https://pub.dartlang.org/packages/multi_image_picker/versions/2.2.61

the provider config in manifest 
`android:authorities="YOUR_PACKAGE_NAME_HERE.fileprovider"`
should be this
`android:authorities="YOUR_PACKAGE_NAME_HERE.multiimagepicker.fileprovider"`

**Comment by isoos** [comment]
@mrnodie this repository is for the pub site, for package-specific issues, please file them in the package's repository. In the case of `multi_image_picker` this should be the following: https://github.com/Sh1d0w/multi_image_picker
