### ISSUE TITLE
Help delete.

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/pub-dartlang-dart#2228]
URL:  https://pub.dartlang.org/packages/example_for_generator

An example was uploaded incorrectly.
Help delete.

I am the author and uploader of this library.

**Comment by jonasfj** [comment]
I sent an email to the author to confirm the deletion request.

**Comment by CaiJingLong** [comment]
@jonasfj 
I reply the email.
Thx.

**Comment by jonasfj** [comment]
Confirmed by email..

**Comment by jonasfj** [comment]
Done.
