### ISSUE TITLE
how to delete you own package cuz it is not working

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [dart-lang/pub-dartlang-dart#2245]
URL: https://pub.dartlang.org/

<Describe your issue or suggestion here>

**Comment by jonasfj** [comment]
You can't... You can file a request here if you really want to... But if it's just because you've published a broken version the recommendation is to fix the package and publish under a higher version number...

We strive to avoid deleting packages as it may break people depending on a package..

**Comment by jonasfj** [comment]
Please reopen if you have a specific request or concern... you can also just file a deletion request in this repository.
