### ISSUE TITLE
Line wrapping in package about box

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#2272]
URL: https://pub.dev/packages/protobuf

Hi, the 'About' description of the package has a long URL that doesn't line wrap and exceeds its container. 

```
Runtime library for protocol buffers support. Use https://pub.dartlang.org/packages/protoc_plugin to generate dart code for your '.proto' files.
```

It doesn't look pretty. Not sure what best can be done about it, whether CSS can do something reasonable, or if the package could include a markdown style link with a shorter title.

Seen on Version 74.0.3729.131 (Official Build) (64-bit) on x86_64 Linux.

**Comment by isoos** [comment]
It looks like there is a CSS style for that: `overflow-wrap: break-word;` will break it into the next line. Not pretty either, but maybe better. See attached screenshot. wdyt?

<img width="288" alt="Screen Shot 2019-05-08 at 17 37 32" src="https://user-images.githubusercontent.com/4778111/57388207-0565f580-71b8-11e9-9640-5ec7d3f4dd80.png">

**Comment by sortie** [comment]
It's not pretty but at least it's consistent, so I think it's preferable. But that's okay, I guess it's up to the package author to put some nice text in the box.
