### ISSUE TITLE
Mobile layout breaks with long package name

### ISSUE THREAD

**Issue by apaatsio** [dart-lang/pub-dartlang-dart#2276]
URL: https://pub.dev/packages/flutter_firestore_visual_query

Long package name doesn't wrap on mobile which breaks the layout.

Google Chrome: 74.0.3729.136 (Official Build) (32-bit)
OS: Android 8.0.0; F5321 Build/34.4.A.2.118

![Screenshot_20190512-090233](https://user-images.githubusercontent.com/195210/57578977-aba24b80-7495-11e9-8fb0-b0460f2535f9.png)

**Comment by isoos** [comment]
Thanks for reporting! Related to #2272.
