### ISSUE TITLE
"pub.dartlang.org" is down in Nigeria

### ISSUE THREAD

**Issue by OladapoAjala** [dart-lang/pub-dartlang-dart#2277]
I have been trying to get some packages from vs-code and all have been getting is:
Got socket error trying to find package english_words at https://pub.dartlang.org
I tried accessing the site from my browser and my browser was unable to resolve the link.
I used a VPN to access the site from Canada and I was able to get it.
Please fix this ASAP

**Comment by isoos** [comment]
@OladapoAjala: in Nigeria people have found that their access depends on their Internet Service Provider (ISP). Please check this thread if the same may apply to you too: https://github.com/dart-lang/pub-dartlang-dart/issues/1767

Unfortunately, if the ISP mishandles the IP routes, we can't really do much about it. To have a quick test on this, please check which of the hosts [here](https://github.com/dart-lang/pub-dartlang-dart/issues/1767#issuecomment-442493817) you are able to reach any.

**Comment by OladapoAjala** [comment]
@isoos I was able to reach the first two sites you provided:
https://dartlang-pub.appspot.com/
https://dart.dev/
Although I already changed my DNS server name to 1.1.1.1

**Comment by OladapoAjala** [comment]
@isoos I added 199.85.126.10, 199.85.127.10 to my DNS server name list and now I can access both sites but upon trying to do "flutter packages get" I still get the issue "pub get failed, Got socket error...."

**Comment by OladapoAjala** [comment]
I already got a solution from the other issue you redirected me to, the problem came from my ISP: GLO. When I used a different ISP (Internet Service Provider) I was able to download my flutter packages effectively. Thanks @isoos

**Comment by Omzlaw** [comment]
For GLO users in Nigeria, you can change your access point name to glosecure username: gprs and password: gprs

**Comment by niran2k2** [comment]
Changing APN to glosecure works. Thanks

**Comment by Milimeter** [comment]
Down again

**Comment by isoos** [comment]
@Milimeter: please do not comment on new issues on old bugs.

Also: please run this tool and report back with its output:
https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

**Comment by Milimeter** [comment]
<img width="1680" alt="Screenshot 2022-06-14 at 13 21 29" src="https://user-images.githubusercontent.com/44377998/173575886-b9438971-d453-481b-9132-174fc1737daa.png">
