### ISSUE TITLE
Request to remove versions of a published package

### ISSUE THREAD

**Issue by le0tan** [dart-lang/pub-dartlang-dart#2282]
I accidentally included my personal information in versions before 0.1.4, may I ask to remove the archives of those versions from pub? Thanks!

https://pub.dev/packages/luminus_api/versions/

**Comment by kevmoo** [comment]
CC @mit-mit @jonasfj

**Comment by mit-mit** [comment]
@le0tan I sent an email to the address listed on the package. Please confirm the request there.

**Comment by mit-mit** [comment]
Confirmed and approved.

**Comment by le0tan** [comment]
@mit-mit is @jonasfj going to remove the archives? Do I need further verification? Thanks!

**Comment by le0tan** [comment]
It's been 4 days since the approval, may I ask when can I get the versions
removed?

**Comment by isoos** [comment]
@le0tan: @jonasfj will do the package removal, but if I remember correctly he is/was traveling. He will do it once he is back in the office.

**Comment by jonasfj** [comment]
Versions prior to `0.1.4` have been removed.

(sorry, I was out of office last week, and jet lagged all weekend).
