### ISSUE TITLE
Capitalization sometimes changes result too much

### ISSUE THREAD

**Issue by parlough** [dart-lang/pub-dartlang-dart#2287]
For example when I search "analyzer", it comes first as expected:

<img width="1174" alt="Screen Shot 2019-05-17 at 14 57 06" src="https://user-images.githubusercontent.com/18372958/57952962-52328600-78b4-11e9-9a9e-2eb98da8f649.png">

But, when I search "Analyzer", it isn't first and is actually on the second page(possibly due to its low score?):

<img width="1089" alt="Screen Shot 2019-05-17 at 14 57 01" src="https://user-images.githubusercontent.com/18372958/57952978-66768300-78b4-11e9-8e30-bd7a60538135.png">

This happens with other capitalizations as well:

<img width="1152" alt="Screen Shot 2019-05-17 at 14 57 26" src="https://user-images.githubusercontent.com/18372958/57952982-6b3b3700-78b4-11e9-93d2-a2f3aeb3d690.png">

I feel like capitalization shouldn't affect results for exact matches, at least not this much, especially since a lot of mobile keyboards automatically capitalize your first character now.

**Comment by isoos** [comment]
For most part of search stack we are case-insensitive, but apparently for the package-exact match strings we are not. Should be easy to fix.
