### ISSUE TITLE
Support for getting live README data from repository instead of local copy

### ISSUE THREAD

**Issue by ShivamArora** [dart-lang/pub-dartlang-dart#2288]
There are times when we need to update the README file for a package to provide better info to the users.

This can go beyond version releases and we can't expect to release an update on the pub store just to update the content of README on the pub site.

So, I feel this is a feature request to display the current README content directly from the repository, if a repo is attached in the `pubspec.yaml` file.

And from the local copy if a repo is not attached with the pub project.

This would result in ease of updating the README without updating the deployed package itself.

Since, a README has nothing to do with the functionality of the package, it only acts as a source of information and documentation about the package. So it should be allowed to be updated independently when there is no change in the functionality itself.

**Comment by isoos** [comment]
Thanks for arguing for this, I think this is a good point, but I'd like to emphasize the counter-argument:

The package repository provides an immutable (and with that consistent, reliable and repeatable) version of the software. There is a great value in that, and a live repo view would only weaken that. You are arguing for the improvement part, but at there could be a similar move in the wrong direction: e.g. you could transfer the ownership of the repository, rename it, make it private or just delete it - either way, the pub site wouldn't be able to provide the same view anymore, and it is possible that the experience degrades.

I think improving the readme is in the same category as improving the code by formatting, refactoring or providing an example with the package: it represents a quality improvement, and there is no shame to publish a new version with only that.

**Comment by ShivamArora** [comment]
@isoos What about having something like a tabbed view of both a live README and the local README? 
That would facilitate both of our arguments.

The user has the choice to switch to either of them without leaving the pub package page.

**Comment by jonasfj** [comment]
I think we need to keep the service simple.

If anything it would be better to make it easier to publish from github..

Note. publishing as `x.y.z+1`, `x.y.z+2`, `x.y.z+3`...
