### ISSUE TITLE
Pub.dev does not support latest dev builds of Flutter

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/pub-dartlang-dart#2290]
https://pub.dev/packages/flutter_image_compress#-analysis-tab-

One problem is that I uploaded a new version of the package today.
I added a 1.5.9 constraint because a breaking change in flutter made my package unusable in version 1.5.9 or above, but it seems that the flutter SDK version of pub does not support version 1.5.9+. 
Now flutter dev channel is 1.6.0, so how should I do?

I get the info of pub:

![image](https://user-images.githubusercontent.com/14145407/57977368-ae6ae680-7a29-11e9-93fa-01c6c31f3f0e.png)

[fail log](https://pub.dev/documentation/flutter_image_compress/0.5.0/log.txt)

_Originally posted by @CaiJingLong in https://github.com/dart-lang/pub-dartlang-dart/issues/2283#issuecomment-493723811_

**Comment by CaiJingLong** [comment]
The breaking change is https://github.com/flutter/flutter/commit/63aa5b3647dbd912a02f7545fc0101003cb3adc4#diff-6ccbd4ed2d70bfa90b733f860afcbea6R230

**Comment by jonasfj** [comment]
I think we only support current stable version on pub.dev

That might change in some future... but for now that's what we support.
So if you publish packages for dev versions of flutter, you'll get a bad score, which will be fixed when the flutter version is released and deployed to pub.dev.

Notice, that users should also beware that your package requires a dev version, hence, a low score is not unfair.

----
Like I said, maybe this is something we change in the future, for now I wouldn't worry too much, the score will get fixed when newer flutter releases are deployed.

**Comment by CaiJingLong** [comment]
Understand and look forward to the advent of dev version analyzer in the future.

Now I decided to keep up with the flutter stable version by updating a new stable compatible version and waiting for stable to support the new flutter version before migrating incompatible code.
