### ISSUE TITLE
Typo in firebase_ml_vision

### ISSUE THREAD

**Issue by PabloHMartin** [dart-lang/pub-dartlang-dart#2291]
URL: https://pub.dev/packages/firebase_ml_vision#-readme-tab-

You can also configure all detectors, except TextRecognizer, with desired options.

final ImageLabeler labeler = FirebaseVision.instance.**imageLabler**(
  ImageLabelerOptions(confidenceThreshold: 0.75),
);

It should be:

    final ImageLabeler labeler = FirebaseVision.instance.**imageLabeler**(
      ImageLabelerOptions(confidenceThreshold: 0.75),
    );

cheers!

**Comment by isoos** [comment]
@PabloHMartin Thanks for reporting, but this repository is for the pub site. For individual packages, please use the packages's issue tracker to file issues. You can find the link with the "View/report issues" label on the right-side about box of the package. In this case, the following link can be used: https://github.com/flutter/flutter/issues

Closing it here.
