### ISSUE TITLE
Clicking badges opens wrong URL

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#24]
```
[![Build Status](https://travis-ci.org/dart-lang/coverage.svg?branch=master)](https://travis-ci.org/dart-lang/coverage)
[![Coverage Status](https://coveralls.io/repos/dart-lang/coverage/badge.svg?branch=master)](https://coveralls.io/r/dart-lang/coverage)
```

creates links to 
`https://travis-ci.org/dart-lang/coverage.svg?branch=master`,
`https://coveralls.io/repos/dart-lang/coverage/badge.svg?branch=master`
instead of 
`https://travis-ci.org/dart-lang/coverage`,
`https://coveralls.io/r/dart-lang/coverage`

Works fine on GitHub but not on pub.dartlang.org

**Comment by isoos** [comment]
AFAICT this is fixed: https://pub.dartlang.org/packages/coverage has the good links on it.

**Comment by mkustermann** [comment]
Closing the issue, since it seems to be fixed already.
