### ISSUE TITLE
Markdown nested lists no longer working

### ISSUE THREAD

**Issue by WillSquire** [dart-lang/pub-dartlang-dart#25]
I believe nested lists did work before with indentation/tabbing before adding the next list item in markdown. No longer appearing as it did previously on Pub

**Comment by srawlins** [comment]
Sorry for the late (really late) response! Can you give an example? I think we've maybe fixed this in a recent Markdown release.

**Comment by isoos** [comment]
Nested list seem to be working (e.g. https://pub.dartlang.org/packages/pwa has them). I think this can be closed.

**Comment by mkustermann** [comment]
@WillSquire Please re-open the issue if you find a case where this isn't working.

**Comment by WillSquire** [comment]
A year and a half @srawlins ;P . Ok, trust this is working now. Thank you
