### ISSUE TITLE
Multiple line comments in code blocks disappearing

### ISSUE THREAD

**Issue by WillSquire** [dart-lang/pub-dartlang-dart#26]
The code blocks generated by three back ticks in markdown are not allowing multiple single line comments to show past the first line ('//' lines after the first one are now invisible). No longer appearing as it did previously on Pub

**Comment by mkustermann** [comment]
This might be either a `package:markdown` issue or an issue with dart code syntax highlighting based on the analyzer package.

**Comment by mkustermann** [comment]
CL out for review: https://codereview.chromium.org/1410073003/

**Comment by mkustermann** [comment]
This was fixed in dbc4c7413889d5746f0dc13e958e2dc7f64f1e2d.

**Comment by nex3** [comment]
![celebration](https://cloud.githubusercontent.com/assets/188/10741374/b6413fcc-7be4-11e5-88ae-2c00a7e7e95f.gif)

**Comment by WillSquire** [comment]
Nice one. That only took 138 days to fix.
