### ISSUE TITLE
Line breaks in the md file that cause letters to overlap in documentation

### ISSUE THREAD

**Issue by WillSquire** [dart-lang/pub-dartlang-dart#27]
As the title says. It seems to be intermittent and corrects itself after a minute or so. When looking at my original readme.md it seems it is the last letter before a linebreak in the MD file and the first letter in the next line that overlap in Pub documentation on occasions.

**Comment by zoechi** [comment]
Sounds similar to #14

**Comment by WillSquire** [comment]
Yes, that's it! And it's cause by line breaks

**Comment by mkustermann** [comment]
Closing this as this seems the same as #14
