### ISSUE TITLE
Underscores causing an italics effect in documentation

### ISSUE THREAD

**Issue by WillSquire** [dart-lang/pub-dartlang-dart#28]
The default underscore replacement for spaces that automatically gets generated in the md file title from the project name now causes an italics effect on the site. It didn't previously.

**Comment by sethladd** [comment]
Thanks for the report. Can you link to an example?

**Comment by WillSquire** [comment]
Hi Seth, this is the same issue as the one you posted: https://github.com/dart-lang/pub-dartlang-dart/issues/32

Takes out spacing and adds italics

**Comment by sethladd** [comment]
The root issue was fixed in markdown. We've asked the maintainers of pub.dartlang.org to update the site. Thanks for the report!

**Comment by mkustermann** [comment]
We've updated to using version 0.8.0 of `package:markdown` in b7a701b77ef0c1eddc9a5f147cb5c21fe37e5d56 which should fix the issue.

**Comment by sethladd** [comment]
Thanks!
