### ISSUE TITLE
Analyzer dashboard

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#288]
How much is left? %
How fast is analysis going? (packages per time)

Really tough to tell

Should likely protect this somehow – even by Google connection

**Comment by isoos** [comment]
Work-in-progress update: It seemed easy to expose stats through the `/debug` url, until I realized that the analyzer instances are running inside an isolate, re-started dynamically. It took a while to realize why every metric stayed zero... :]
