### ISSUE TITLE
Allow marking a package as "discontinued"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub-dartlang-dart#289]
Pub currently ranks packages based on the `updated` column:

<img width="939" alt="screen shot 2017-08-08 at 8 32 43 am" src="https://user-images.githubusercontent.com/168174/29080258-2d8b3480-7c14-11e7-95f7-9336b2deb19e.png">

This works great, until it doesn't. For the `angular` package, there is a historic, unsupported/maintained `1.x` version that is presented instead of the newest `4.0.0-alpha` version:

<img width="936" alt="screen shot 2017-08-08 at 8 33 36 am" src="https://user-images.githubusercontent.com/168174/29080310-4fc56c14-7c14-11e7-8cd3-78eaaf579da7.png">
<img width="868" alt="screen shot 2017-08-08 at 8 33 42 am" src="https://user-images.githubusercontent.com/168174/29080311-4fcc6c26-7c14-11e7-92e6-25601d29bc64.png">

Under normal circumstances, this might be fine, i.e. ranking `stable` releases higher than `unstable` for viewing preference. However, package authors should be given an option (perhaps in an admin, or manually via a ticket system for the time being) to _deprecate_ a version range.

In this case, imagine the following metadata was attached to the `angular` package:

```json
{
  "deprecated": [
    "<4.0.0-alpha",
  ],
}
```

And the ranking was instead `stable` > `unstable` > `deprecated`.

**Comment by kwalrath** [comment]
Yes, please. This also affects https://pub.dartlang.org/packages/dev_compiler. See dart-lang/sdk#29911 for details.

**Comment by isoos** [comment]
Nit: What you are referring to is not the search ranking, it is the package index ordering.

I see a few conflicts with deprecated as it is proposed:
- version 2.0 could deprecate 1.0, but what if 2.1 un-deprecates everything?
- version 2.3 could deprecate 2.3, and it could be just as valid as not allowing it

I think at one point the package author needs to answer the question: what version do I want to be used by others? And if I want to use the newer, why don't I release it as stable?

If you deprecate everything that was `stable`, then what does it mean to be `unstable`?

**Comment by isoos** [comment]
Another thing is that we could consider is to use `discontinued` instead of `deprecated`, because deprecation is the intent of the original developer, but others using it may consider it just fine a keep going and use it. It also simplifies the tracking, because a package is discontinued if and only if the last published version (stable or otherwise) has this flag set to true.

If the developer changes their mind, publishes a new version without the flag, it is clear that they continue working on it, and we clear the flag, handle it as a normal package.

Deprecation and removal of an API, and introducing a new one (like in case of `angular`) and its incremental rollout should be handled by a new major semver, but that is unrelated to whether the package is considered `discontinued` (or it could be called `abandoned`).

**Comment by isoos** [comment]
Any comment on `discontinued`?

Another item for it: If a package has no recent release (e.g. in the past 2 years), it can be considered `discontinued`.

**Comment by kevmoo** [comment]
Added a new issue for the notion of a "broken" release - https://github.com/dart-lang/pub-dartlang-dart/issues/378

I think we should have separate concepts here...

**Comment by mit-mit** [comment]
Very-minimal solution discussed for now:

- Add a 'deprecated' flag in our backend
- Create a script we (the pub maintainers) can run to set/unset this for a package
- In package analysis, skip packages where this flag is set
- In pub searches, exclude packages where this flag is set
- in an pub package page, add a red DEPRECATED tag (placed right in front of the current platform tags)

Later work can expand on this, for example to add a `pub deprecate` command that uploaders could run.

**Comment by kevmoo** [comment]
SGTM!

**Comment by mit-mit** [comment]
Updating title to reflect that the present feature will allow marking a whole package (i.e., all versions of the package) as deprecated.

**Comment by mit-mit** [comment]
Updating to reflect we will be using the term 'discontinued' rather than 'deprecated'

**Comment by mit-mit** [comment]
This has landed!
