### ISSUE TITLE
Internal error for URLs with percent encoding

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/pub-dartlang-dart#29]
E.g.

  https://pub.dartlang.org/api/packages/http/versions/0.9.2+%40

gives 'Internal error'

whereas the "same" request

  https://pub.dartlang.org/api/packages/http/versions/0.9.2+A

gives 404

**Comment by mkustermann** [comment]
These are not the same urls since "%40" corresponds to "@".

The version "0.9.2+@" is not a valid semantic version, so we get an semantic version parsing exception.

I think an "Internal error" is not as bad as it sounds, but I can make an update to the API handling to return "400 Bad Request".

**Comment by mkustermann** [comment]
CL up for review for `package:pub_server`: https://codereview.chromium.org/1231753007/

**Comment by mkustermann** [comment]
The URL https://pub.dartlang.org/api/packages/http/versions/0.9.2+%40 will now return

```
{"error":{"message":"Version string \"0.9.2+@\" is not a valid semantic version."}}
```
