### ISSUE TITLE
Pub search results has flawed pagination logic

### ISSUE THREAD

**Issue by sandrobilbeisi** [dart-lang/pub-dartlang-dart#293]
Pub search results has flawed pagination logic; it displays a varying number of extra pages

![screen shot 2017-08-12 at 00 30 58](https://user-images.githubusercontent.com/755824/29234183-8da069ce-7ef5-11e7-9371-9f447a1df6fd.png)

in that particular example, clicking on any pagination button after ten returns the last result page ( equivalent to 10 )

I'll take a look at the code to see if I can fix this for you...

**Comment by isoos** [comment]
Ah, good catch there! You are welcome and encouraged to look at the code, this one was because we have recently migrated to a new search backend, and that provides more results than the previous did, and I forgot to update the pagination limiter.
