### ISSUE TITLE
analyzer: Flutter versions may diverge since we install during boot

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#296]
I forget if this has been discussed/addressed.

I could imagine a long running analyzer having an "old" version of flutter (against the alpha branch) and a new instance spinning up with a newer version.

I wonder if we should hard-wire the flutter version in the script or in an environment variable - something like https://github.com/dart-lang/pana/blob/474c0ed56c170c3b1efd25213443502a0623a46a/Dockerfile#L11

**Comment by kevmoo** [comment]
FYI issue related to sending environment variables to the builder – would allow us to include flutter in the analysis image only

https://issuetracker.google.com/issues/64424543

**Comment by kevmoo** [comment]
I guess we could teach `deploy.dart` to kick off a custom build and use that for the service - https://cloud.google.com/container-registry/docs/using-with-google-cloud-platform#deploying_to_app_engine

...should also make spinning up analyzer instances faster, since the flutter install would be baked in

**Comment by isoos** [comment]
We already hard-wire flutter version, and it is part of the stored analyzer version:
https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/script/setup-flutter.sh#L28
https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/analyzer/versions.dart#L12

We also have a test that makes sure these two are the same:
https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/test/analyzer/analyzer_version_test.dart

**Comment by isoos** [comment]
@kevmoo: are we happy with the current versions + tests (and close this issue), or do you expect something else?

**Comment by kevmoo** [comment]
All good...
