### ISSUE TITLE
Remove Custom Search support

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#297]
- [x] Remove template code that includes search fields
- [ ] Turn off the API

**Comment by isoos** [comment]
@kevmoo, @mkustermann: Do you want to have a milestone set before we turn it off / remove it? Either "our search must implement X" or "must live through a serious upgrade" or something, or shall I just go ahead and turn it off?

**Comment by mkustermann** [comment]
@isoos We still fall back to CSE if the normal search fails (any exception occurs) atm. As long as this code is in, we shouldn't turn off/disable the API.

@kevmoo should decide whether quality/speed/features of the new search are better than old one.

If the answer is yes, we should monitor the logs for some time, to ensure we never fall back to to CSE search in prod. Once that is established we can a) remove special cse html in our templates b) remove the fallback to CSE code c) turn off the API.

**Comment by mkustermann** [comment]
Are we still falling back to CSE? Can we remove all CSE related code support?

Once we have no CSE code left, please write it here and leave the issue open, so we can disable our CSE account / api service / ...

**Comment by isoos** [comment]
My ad-hoc and infrequent sampling of the `/debug` url showed no signs of fallback, ever, we did the searches from our service, and not from CSE.

If you are happy with the logs, I can start removing the CSE-related code any time.

**Comment by kevmoo** [comment]
Looks like we had **1** hit 15 days ago...

![screen shot 2017-09-22 at 9 09 30 am](https://user-images.githubusercontent.com/17034/30753968-cbc90684-9f75-11e7-9f8a-cc3404397241.png)

**Comment by isoos** [comment]
Can we correlate it with a log entry and reason?

**Comment by kevmoo** [comment]
> Can we correlate it with a log entry and reason?

Do I have to? 😄

**Comment by isoos** [comment]
Nope, not that important. I was just curious whether it was just a timeout, an error or something else. And it is also possible that it was used not by the prod up, but staging (if search was down there).

**Comment by kevmoo** [comment]
@isoos – are we ready to turn off the API?

**Comment by isoos** [comment]
Yeah, I think we can turn that off.

**Comment by kevmoo** [comment]
Done!
