### ISSUE TITLE
Add tests for the code which actually fills the templates.

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/pub-dartlang-dart#3]
There are no tests of the code which actually fills the templates. See https://github.com/dart-lang/pub-dartlang-dart/issues/2 for an issue.

**Comment by isoos** [comment]
In the absence of a simple code coverage for `pub test`, I've created a small script the summarizes the output of `dart_coveralls`. The big missing spots are the following:

- `colored_markdown.dart`: 0% coverage
- `templates.dart`: 4% coverage
- `upload_signer_service.dart`: 7% coverage
- `search_service.dart`: 12% coverage (+`keys.dart` with 0%, only used by this)
- `model_properties.dart`: 36% coverage
