### ISSUE TITLE
Some .yaml requests gives 'Internal error'

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/pub-dartlang-dart#30]
The request

  https://pub.dartlang.org/packages/csslib/versions/0.4.2%2B2.yaml

gives 'Internal error'

The "same" request

  https://pub.dartlang.org/packages/csslib/versions/0.4.2+2.yaml

does not.

**Comment by mkustermann** [comment]
CL is up for review: https://codereview.chromium.org/1225303003/
