### ISSUE TITLE
Double escaping code blocks when rendering markdown to HTML

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#31]
Text that is inside code blocks in markdown are getting double escaped.

Check out the page for https://pub.dartlang.org/packages/script_inliner

![screen shot 2015-07-07 at 6 05 42 pm](https://cloud.githubusercontent.com/assets/5479/8560978/02059782-24d3-11e5-8a50-8c73576bf823.png)

For example, instead of `&lt;head&gt;` I would expect `<head>`

Thanks for taking a look!

**Comment by sethladd** [comment]
I'm not 100% sure this is a markdown issue. I'm guessing that markdown is doing the right thing, and then a second level of encoding is applied to the entire results.

**Comment by mkustermann** [comment]
I agree with you. I will take a look at this one, since I implemented the dart code block coloring.

I'll just go ahead and rename the label from `package:markdown-issue` to `markdown-issue`, so it captures the actual intend.

**Comment by mkustermann** [comment]
CL is up for review: https://codereview.chromium.org/1225343002/

It was only handling code blocks via three backticks not via 4 space indents.

**Comment by sethladd** [comment]
Nice, thanks!
