### ISSUE TITLE
Markdown rendering of linked image broken

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#310]
https://pub.dartlang.org/packages/angular/versions/4.0.0-beta

Weird – could this be due to the version in the link?

**Comment by isoos** [comment]
Where is the markdown source? Markdown rendering is independent of the version in the link, so I would bet it is either the markdown source, or the markdown library.

**Comment by kevmoo** [comment]
https://github.com/dart-lang/angular/blob/master/angular/README.md

Closing this. I was confused because I was looking at the wrong readme.
