### ISSUE TITLE
Incorrect italics in markdown rendering

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#32]
Check out https://pub.dartlang.org/packages/dart_to_js_script_rewriter

The header is incorrectly rendered. It should look like "dart_to_js_script_rewriter", but instead it is "darttojsscriptrewriter"

![screen shot 2015-07-07 at 6 20 26 pm](https://cloud.githubusercontent.com/assets/5479/8561099/e8c17b72-24d4-11e5-9230-d82f420d5dff.png)

Thanks for taking a look!

**Comment by sethladd** [comment]
To see the correct rendering, check out https://github.com/sethladd/dart_to_js_script_rewriter

**Comment by mkustermann** [comment]
We are using [package:markdown](https://github.com/dpeek/dart-markdown) for this. @kevmoo has been doing a lot of work there.

@kevmoo Would you be interested in taking a look?

**Comment by sethladd** [comment]
Dupe of https://github.com/dart-lang/pub-dartlang-dart/issues/28
