### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by pauldemarco** [dart-lang/pub-dartlang-dart#326]
I'm using emojis to show a checked/unchecked table of progress.
Shows on github: https://github.com/pauldemarco/flutter_blue/
Does not show on pub: https://pub.dartlang.org/packages/flutter_blue

Any plans for supporting these?

**Comment by isoos** [comment]
In general I'd like the `markdown` package to support it (as it supports the github-flavored markdown syntax). If that takes long, we could add the few checked/unchecked emojis for the pub site.

**Comment by srawlins** [comment]
OK this is in markdown v1.1.1, in the `ExtensionSet.gitHubWeb`.

**Comment by isoos** [comment]
Awesome, thanks @srawlins, will integrate in pub site soon.

**Comment by kevmoo** [comment]
Deployed! https://pub.dartlang.org/packages/flutter_blue
