### ISSUE TITLE
Feature Request: Package Stats

### ISSUE THREAD

**Issue by brianegan** [dart-lang/pub-dartlang-dart#332]
Hello! Not sure if this is at all possible, but thought I'd throw my feature request in :)

I would like to see the number of times a package has been downloaded in the past day / week / month.

  - As a user, this allows me to determine the the size of the community around a package.
  - As an author, it helps me focus my effort on my most impactful projects.

An example of this can be seen on the npm package pages: https://www.npmjs.com/package/express

Thanks for listening to my feature request!

**Comment by mkustermann** [comment]
There is some infrastructure for processing the logs and generating popularity stats. It will be used for ranking in the search.

Exposing this data on the package pages should then also be possible.

/cc @isoos @kevmoo

**Comment by kevmoo** [comment]
Yup, @brianegan – we're doing a lot of plumbing right now. Collecting and using popularity stats is on our radar.

**Comment by isoos** [comment]
I think this can be closed now. We won't publish direct download counts (e.g. because they are skewed by the CIs that download them on every new change), but the popularity score is a huge part of the overall score.

**Comment by brianegan** [comment]
Yep, the popularity fulfills my use cases! Thanks for all the hard work :)
