### ISSUE TITLE
pub site should also show `changelog.md` (lowercase)

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#34]
See 
- https://pub.dartlang.org/packages/tuneup
- https://github.com/google/tuneup.dart/blob/master/changelog.md

**Comment by mkustermann** [comment]
It should do that already since fc8401095726aefabf9811a0326ba15c88cc54cd (see e.g.: https://pub.dartlang.org/packages/grinder)

We'll investigate this, thank you for the report.

**Comment by mkustermann** [comment]
So this was indeed fixed by fc84010 but we had traffic splitting enabled between the new version and an older one. This should be permanently fixed now.

**Comment by zoechi** [comment]
Thanks for checking. I assumed traffic splitting was long gone.

**Comment by mkustermann** [comment]
The traffic splitting was **not** between the old python version and the dart version. It was between 2 dart versions (we do that often if we make changes to the dart version).
