### ISSUE TITLE
Upgrade to latest pana

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#342]

**Comment by isoos** [comment]
@kevmoo @mkustermann: the code is merged, and I think let's not block this on [which way the services should depend on each other](https://github.com/dart-lang/pub-dartlang-dart/issues/341). Could you please deploy it in prod? It's been in staging in the past day or two, without issues.

**Comment by isoos** [comment]
Hm, please hold on, I've found that some flutter-related packages were not analyzed, while they are working with pana locally.

**Comment by isoos** [comment]
From the logs:
```
Error:
    FormatException: Unexpected character (at character 1)
    Downloading Dart SDK 1.25.0-dev.9.0...
    ^
Stack:
[...]
    #5      JsonCodec.decode (dart:convert/json.dart:125)
    #6      FlutterSdk.getVersion (package:pana/src/sdk_env.dart:112:17)
```

Maybe the flutter setup failed during the container init?

**Comment by isoos** [comment]
Yeah, that is it:

```
pub.analyzer: Failed to checkout flutter (exited with 1) stdout: Downloading Dart SDK 1.25.0-dev.9.0... % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 13 60.3M 13 8208k 0 0 21.9M 0 0:00:02 --:--:-- 0:00:02 21.9M 100 60.3M 100 60.3M 0 0 115M 0 --:--:-- --:--:-- --:--:-- 115M It appears that the downloaded file is corrupt; please try the operation again later. If this problem persists, please report the problem at https://github.com/flutter/flutter/issues/new stderr: Cloning into '/flutter'... Note: checking out 'b156a0f0549a3ad3e1134638f26f472427c379be'. You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by performing another checkout. If you want to create a new branch to retain commits you create, you may do so (now or later) by using -b with the checkout command again. Example: git checkout -b new_branch_name /flutter/bin/internal/update_dart_sdk.sh: line 64: unzip: command not found
```

**Comment by isoos** [comment]
This PR remove it (along the memcache): https://github.com/dart-lang/pub-dartlang-dart/pull/338/files#diff-3254677a7917c6c01f55212f86c57fbfL3

**Comment by isoos** [comment]
Deployed https://github.com/dart-lang/pub-dartlang-dart/pull/354 to staging, it looks OK. After merging that, the prod deployment can go ahead.

**Comment by isoos** [comment]
Merged, deploy to prod is OK.

**Comment by mkustermann** [comment]
There was a deployment on Friday, so I assume that this has been deployed to prod as well now.

**Comment by isoos** [comment]
Yeah, I can confirm that it did succeed, and data served is the latest and correct version.
