### ISSUE TITLE
Remove detectedTypes and use search in frontend for more features

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#348]
Now that we have proper platform classification from `pana`, using `detectedTypes` is no longer preferred (in `Package`, `PackageVersion` and throughout in `frontend`). The change requires a few things:
- [x] `search` to:
  - [x] support list of packages in reverse update order
  - [x] accept a query as valid without text or package prefix
  - [x] ~return more info (incl. platform information as part of the result for displaying the icon)~
  - [x] strip of extra info from search results
- [x] `fronend` to:
  - [x] use `search` to query `/packages` and `/flutter/packages`, because that is the quickest way to support all kinds of queries (e.g. later filtering on popularity, health, maintenance...)
  - [x] display icons in `search` from the `analyzer` service, using memcache
  - [x] `AnalysisView` to render flutter icon on package show page

- [ ] cleanup `detectedTypes` in Datastore

**Comment by isoos** [comment]
@kevmoo @mkustermann: I don't see the `detectedType` property in staging Datastore anymore. Did you remove it from there and from prod too?

**Comment by isoos** [comment]
Ah, I've realized that the datastore console did hide the column from me, maybe because the field hasn't been accessed in a while?

**Comment by kevmoo** [comment]
I didn't touch it. 🤷‍♂️
