### ISSUE TITLE
Shorthand reference links are not rendered.

### ISSUE THREAD

**Issue by dikmax** [dart-lang/pub-dartlang-dart#35]
Example:

``` markdown
[test].

[test]: http://test.com/
```

GitHub displays these links correctly.

**Comment by mkustermann** [comment]
We're using [package:markdown](https://github.com/dart-lang/markdown) and since we're not changing the parsing/rendering (except for syntax highlighting dart code), it's probably a missing feature from `package:markdown`.

**Comment by srawlins** [comment]
This markdown works in the latest markdown:

```none
$ dart bin/markdown.dart --version
0.11.1
$ dart bin/markdown.dart issue-35.md
<p><a href="http://test.com/">test</a>.</p>

```

**Comment by isoos** [comment]
AFAICT this works not on pub.
