### ISSUE TITLE
Simple cleanup: Get rid of withCorrectDatastore, we no longer need work-around for mac

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/pub-dartlang-dart#350]
The `withCorrectDatastore` workaround for MacOS is no longer needed since https://github.com/dart-lang/appengine/issues/63 (aka https://github.com/dart-lang/sdk/issues/29240) was fixed (i.e. we have proper ALPN support in the SSL implementation of the DartVM on MacOS).

**Comment by isoos** [comment]
Does this require 1.25 or should it work on 1.24.2 too? Either that, or the lack of local memcache, but it is not working for me yet.

**Comment by kevmoo** [comment]
Requires at least the first release of 1.25 -
https://github.com/dart-lang/sdk/commit/644862bf966e6c079460258807ab3364b7e3759a

**Comment by mkustermann** [comment]
Fixed in a7442c048f610d7670320eda0ee9bcbd56a8d263
