### ISSUE TITLE
Unexpected results: Search for "game"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub-dartlang-dart#358]
URL: https://pub.dartlang.org/search?q=game

Only the first 5 packages have the term "game" in them. Am I missing something?

**Comment by kevmoo** [comment]
Plenty of room to tweak the algorithm – thanks!

**Comment by isoos** [comment]
Yeah, agreed. So what would be your expectation here? Cut off everything that has no "game" in it (either in the package name or in the description/readme)?

**Comment by mkustermann** [comment]
The main reason why this happens is due to the use of character n-gram indexing, I guess?

We could move more to a word-level approach, but as long as the correct search results appear on the top of the list, this seems like not the most important thing atm. Furthermore in the mid-term we might have the option of using a hosted solution.

**Comment by isoos** [comment]
> The main reason why this happens is due to the use of character n-gram indexing, I guess?

That is correct. One way to fix this **and** preserve the ability for returning results with typos (either in the query or the indexed source): we could use only the longest-matching n-grams. E.g. in this case we find a 4-gram sequence, so we can drop 3-grams, 2-grams and 1-grams. If there were no match for the 4-gram sequence, we fall back to 3-grams etc. (Or alternatively just decreasing their weight in such cases.)

**Comment by mkustermann** [comment]
That would be one approach.

Though using a word-level approach **can still handle typos**. There's several possibilities for this. e.g. using DWT (or something similar) to go from search word to closest indexed words and then using these words for search. It would also allow "spelling-correction" suggestions ...

But again, getting popularity scores automatically into the system and other things are probably higher priority.

**Comment by kevmoo** [comment]
@matanlurey – better? https://pub.dartlang.org/search?q=game
