### ISSUE TITLE
Create a debugging database

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub-dartlang-dart#36]
Long ago, when I was first working on `pub publish`, I set up the application to use a separate staging namespace when deployed with a version name other than `preview`, `coming-soon`, or a number (see [`appengine_config.py`](https://github.com/dart-lang/pub-dartlang/blob/master/app/appengine_config.py)). As far as I can tell this was lost in the translation to Dart; it would be really useful to have it back for testing publish and related issues with a live server.

It would be great to have this soon so we can debug issues like dart-lang/pub#1321.

**Comment by mkustermann** [comment]
> As far as I can tell this was lost in the translation to Dart

We made sure this continues works - although it's not used often. It just requires deploying a staging instance as described in the [README](https://github.com/dart-lang/pub-dartlang-dart) file. I've just deployed it, so you can use it via:
```
$ export PUB_HOSTED_URL=https://staging-dot-dartlang-pub.appspot.com
$ pub publish
```

**Comment by nex3** [comment]
Thanks!
