### ISSUE TITLE
Search doesn't find my library

### ISSUE THREAD

**Issue by adaojunior** [dart-lang/pub-dartlang-dart#38]
I've built this library https://pub.dartlang.org/packages/pusher and it has been on pub for a few days, but when I search for it https://pub.dartlang.org/search?q=pusher pub doesnt find it.
```
Search Results for “pusher”
Search for “pusher” did not match any packages.
```

Am I missing something ?

**Comment by mkustermann** [comment]
The result is showing up now. The delay until a newly uploaded package shows up can be long.
