### ISSUE TITLE
Categorize Packages according to target Dart environment

### ISSUE THREAD

**Issue by daftspaniel** [dart-lang/pub-dartlang-dart#39]
I was browsing through pub today and was finding it hard to see what was regular Dart and what was Flutter etc.

So, for example, if I am looking for some web widgets, it would be useful to be able to filter out all packages to do with mobile.

Without this pub will get more difficult to use, particularly for newer Dart programmers.

**Comment by kevmoo** [comment]
@isoos – lot's of overlap with https://github.com/dart-lang/pub-dartlang-dart/issues/92

What concrete work is left here?

**Comment by isoos** [comment]
This is done in pana and V2 design exposes it.
