### ISSUE TITLE
Update pub.dartlang.org with latest markdown

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#40]
Hi,

The markdown package was updated, and fixed a bug relevant to pub.dartlang.org. Specifically: https://github.com/dart-lang/markdown/issues/41

It will fix https://github.com/dart-lang/pub-dartlang-dart/issues/28

Thanks for the help!

**Comment by mkustermann** [comment]
Fixed in b7a701b77ef0c1eddc9a5f147cb5c21fe37e5d56, updated to version 0.8.0 of `package:markdown`.
