### ISSUE TITLE
Critical flaw? Pub search does not look inside README content while searching

### ISSUE THREAD

**Issue by yeradis** [dart-lang/pub-dartlang-dart#404]
The search option at https://pub.dartlang.org/
offer the same functionality as no having 
cause it does not help in discoverability of existing packages

Its not searching inside the packages README or other useful places like the code itself

For example if you search for `haversine` 

https://pub.dartlang.org/search?q=haversine

there should appear at least 3 repositories that contains that word, two of those are published by myself, for example:

- https://pub.dartlang.org/packages/latlong  (not mine)
- https://pub.dartlang.org/packages/haversine
- https://pub.dartlang.org/packages/great_circle_distance

same if you search for `vicenty`

https://pub.dartlang.org/search?q=vincenty

once again one of my package should appear, and `latlong` too
but those are not at the result list

this is a a *critical flaw*, there is no discoverability of existing packages 
leading to think that its a missing option

in the best of cases you end writing new libs for offering those functionality thinking there is nothing like that, but you are wrong, exists but the search result says NO,

This is my case, and i ended up publishing new packages instead of using the one published by @MikeMitterer https://github.com/MikeMitterer/dart-latlong

The real issue here is that maybe you are studying the current mature of Dart to check if a viable option for you next project searching for existing libraries, packages, etc so you don't have to start from scratch... well i think you understand my point

**Comment by isoos** [comment]
Thanks for the detailed report!

A quick analysis: we do index the *first* part of the readme, but:
- only a limited number of characters,
- with a much lower weight than the package name,
- and with a TF-IDF-like scoring, which reduces the term weight even more

So the results you have mentioned show up in the prepared list, but we do also score clipping, meaning we remove the values with a relatively low score. In the first case, the `haversine` package dominates the relevancy score so much, the others don't really stand a chance for showing up.

On the plus side: this is a really helpful description and we can both tune the weights, and also construct tests around it to make sure the mentioned packages do get the proper expose. Thanks for reporting it!

**Comment by MikeMitterer** [comment]
How many characters do you index and why don't you index the whole README?
Or let me ask different: Please index the whole README.

**Comment by isoos** [comment]
> How many characters do you index and why don't you index the whole README?

More background info:
- At the moment we are using an in-memory search index, and we'd like to limit the memory use. For example, if a few packages decide to have a 1MB+ README, we'll be soon out of memory, therefore we have limited it to the first 1000 characters.
- We do index N-grams (vs. not whole words), which provides typo-resistance for the search and surfaces results with word invariants.
- Indexing more content doesn't necessarily help the way you think it should, because TF-IDF scoring will render the matches in the longer text less relevant.

> Or let me ask different: Please index the whole README.

I'm doing the tuning for the search index weights, and it looks like both of the missing packages will show up if that fix lands.

**Comment by isoos** [comment]
@kevmoo @mkustermann: can we deploy the new version of search service to prod?

**Comment by kevmoo** [comment]
Can I do so in isolation? Happy to do it now...as long as it won't bork anything else...

**Comment by isoos** [comment]
> Can I do so in isolation?

Yeah, it should not break anything.

**Comment by kevmoo** [comment]
@yeradis – we're live - https://pub.dartlang.org/search?q=haversine

**Comment by yeradis** [comment]
@kevmoo thanks for mentioning, @isoos thanks to you too
@MikeMitterer look xD

**Comment by yeradis** [comment]
@isoos thanks for addressing this out, @kevmoo thanks for the mention
@MikeMitterer look xD
