### ISSUE TITLE
meta description tag in html package page should be the package description

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/pub-dartlang-dart#41]
When sharing a package page such as https://pub.dartlang.org/packages/test (on slack, facebook), the title is correct (i.e. it is the package title), but the description is always "Pub is a package manager for the Dart programming language."

````html
<title>test 0.12.5 | Pub Package Manager</title>
<meta name="description"
  content="Pub is a package manager for the Dart programming language.">
````

The description should be updated to be the package description such as

````html
<title>test 0.12.5 | Pub Package Manager</title>
<meta name="description"
  content="test provides a standard way of writing and running tests in Dart.">
````

Sharing (on slack and others) would be definitely better!

**Comment by sethladd** [comment]
Good call. Patches welcome!
