### ISSUE TITLE
Issue rendering markdown images + link

### ISSUE THREAD

**Issue by yeradis** [dart-lang/pub-dartlang-dart#422]
Right now at my README file i have a coverage status image +  link

At github this appears without problem, see next:

<img width="492" alt="screen shot 2017-10-11 at 18 47 47" src="https://user-images.githubusercontent.com/666944/31454127-b2274102-aeb4-11e7-901a-45102bba5c03.png">

but at the package home, there are rendering issues, see the next image:

<img width="662" alt="screen shot 2017-10-11 at 18 43 29" src="https://user-images.githubusercontent.com/666944/31454103-9b968e20-aeb4-11e7-9fac-83b8b901d7ff.png">

Also at the bottom you can see:
<img width="724" alt="screen shot 2017-10-11 at 18 50 19" src="https://user-images.githubusercontent.com/666944/31454347-702945ec-aeb5-11e7-8c81-dc501f673428.png">

The markdown used is this one:

```md
[![Coverage Status][coverage_status]][coverage_page]
.....

[coverage_page]:https://coveralls.io/github/yeradis/stay_points.dart?branch=master
[coverage_status]: https://coveralls.io/repos/github/yeradis/stay_points.dart/badge.svg?branch=master
```

**Comment by kevmoo** [comment]
Add a space between `:` and the url for coverage_page

We have a number of nitty issues w/ our markdown code. You can always play with it here: https://dart-lang.github.io/markdown/

**Comment by yeradis** [comment]
FIX: The problem is that there is no space after the colon punctuation `:` at `[coverage_page]:http://`

<img width="505" alt="screen shot 2017-10-11 at 18 57 10" src="https://user-images.githubusercontent.com/666944/31454530-0477b576-aeb6-11e7-8e87-2edec68808f1.png">

**Comment by yeradis** [comment]
@kevmoo oh thanks your response arrived before finishing mine xD

**Comment by kevmoo** [comment]
😄

**Comment by yeradis** [comment]
@kevmoo i should close this one, have you an issue regarding those king of markdown issues? btw thanks for the link

**Comment by kevmoo** [comment]
Requires a fix here https://github.com/dart-lang/markdown/issues/176

**Comment by kevmoo** [comment]
Leave it here – will close when we upgrade pkg/markdown to latest

**Comment by kevmoo** [comment]
Will be resolved when https://github.com/dart-lang/pub-dartlang-dart/issues/508 is fixed and landed

**Comment by kevmoo** [comment]
Fixed in latest release
