### ISSUE TITLE
code blocks have trailing blank lines

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/pub-dartlang-dart#43]
See this screenshot:

![pubbug](https://cloud.githubusercontent.com/assets/1961493/10500943/6efbaa32-7291-11e5-985e-05d9df5cc848.png)

there are blank lines in code blocks that use the triple-backtick syntax

**Comment by sethladd** [comment]
Is this really an issue with the markdown package?

cc @srawlins who has been helping work on markdown

**Comment by mkustermann** [comment]
This should be fixed by 4321be8c8415d424a23a447f1cbbcd2c81a6848e
