### ISSUE TITLE
disallow new package uploads w/ capital letters in their names

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#446]
We've been pretty clear on our naming guidelines here...

Don't do anything about this yet. Need to create a thread internally first...

**Comment by kevmoo** [comment]
This is only for NEW packages.

We should also make sure we don't allow publishing a package that conflicts w/ any existing packages based on case.

**Comment by isoos** [comment]
I believe this has been deployed and we no longer allow publishing new packages with capital letters.
