### ISSUE TITLE
Weird sorting w/ pkg/angular w/ latest search

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#451]
Deployed search @ 6a5ced8 – https://20171019t120511-dot-search-dot-dartlang-pub.appspot.com/

No search https://20171019t120511-dot-search-dot-dartlang-pub.appspot.com/search? – `angular` comes up as the most popular package. Awesome.

Actually search for `angular` https://20171019t120511-dot-search-dot-dartlang-pub.appspot.com/search?q=angular – `angular_ui` comes up first

Weird!

**Comment by isoos** [comment]
The `angular` package's description doesn't contain the world `angular`, while `angular_ui` does have it in the description. Because we are adding up the weights, it ends up behind `angular_ui`. Using `max` instead should fix it, I want to change the addition of the scoring anyway.

**Comment by kevmoo** [comment]
Cool!

**Comment by kevmoo** [comment]
Search is hard!

**Comment by kevmoo** [comment]
Seems fixed with deploy 20171028t171525
