### ISSUE TITLE
built_redux should show web and Flutter icon

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#455]
https://pub.dartlang.org/search?q=built_redux

Any idea why it doesn't?

**Comment by matanlurey** [comment]
It looks like it has a dependency on `source_gen`, which is CLI only:
https://pub.dartlang.org/packages/source_gen

Moving the generator to another package, like `built_value_generator`, would "fix" this.

(Or pub could be smarter, but that might be out of scope of this bug)

**Comment by kevmoo** [comment]
We did the same this w/ `json_annotation` and `json_serializable`

**Comment by zoechi** [comment]
Thanks for the info.
Seems to be cumbersome though.

**Comment by kevmoo** [comment]
> Seems to be cumbersome though.

Understood. Categorizing packages is really tough. We plan to evolve the logic, so feedback is great.

**Comment by isoos** [comment]
Ah, got it:
- `lib/built_redux.dart` works everywhere
- `lib/generator.dart` works only on the server

Our package-level classification looks at it, and sees that most libraries work everywhere, except for one, the `lib/generator.dart`, and it makes it the platform-level classification.

**Comment by kevmoo** [comment]
This will be fixed when we roll `pana` 0.5.0 to the package site.
