### ISSUE TITLE
Search results should show latest dev release as well as prod release?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub-dartlang-dart#46]
Related to https://github.com/dart-lang/pub-dartlang-dart/issues/44, if you search for [polymer](https://pub.dartlang.org/search?q=polymer) for instance you will see the version `0.16.3+3`. The latest version is actually `1.0.0-rc.7` (and that is what you see if you click through to the package).

![old](https://cloud.githubusercontent.com/assets/984921/11476274/a8df504a-9736-11e5-8bd1-8300c3c25e61.png)

I would suggest listing dev release versions next to the current prod version (if available). For instance something like the following would be sufficient:

![new](https://cloud.githubusercontent.com/assets/984921/11476277/abeb0f86-9736-11e5-8d2d-4fa62084f7aa.png)

**Comment by isoos** [comment]
This is the same issue as #47 and should be closed too.
