### ISSUE TITLE
Searches are incomplete

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#460]
For example, searching for the [two words 'firebase' and 'database'](https://pub.dartlang.org/experimental/search?q=firebase+database&platforms=flutter ) doesn't return the [firebase_database](https://pub.dartlang.org/experimental/packages/firebase_database) plugin despite this containing those words in [it's description](https://github.com/flutter/plugins/blob/master/packages/firebase_database/pubspec.yaml).

**Comment by isoos** [comment]
The analysis of `firebase_database` failed, because `pub upgrade` was not completed in the one-minute timeout. Because of that it has no platform classification, and the platform filter you've added doesn't yield it as a result. If you remove the platform filter, it is in the results.

**Comment by mit-mit** [comment]
Why do we run `pub upgrade`?

**Comment by mkustermann** [comment]
For search (i.e. text indexing of package name, description, readme/changelog) itself I don't think we need to involve pub. Maybe we can avoid involving pub if we do.

For checking whether a package has warnings/errors and ranking it lower if it has (what we can analysis), we need to involve pub. Maybe we can just increase the timeout, since 1 minute doesn't cut it: Even I have `pub get`s which take much longer, in particular with an empty PUB_CACHE.

@isoos This brings up an interesting point: It would be nice if we could get notified about failed analysis runs. I guess it should show up in the logs as warnings, but usually we only log at the last few days. Maybe we should add a script, which checks the DB for failed analysis runs and we can investigate them?

**Comment by isoos** [comment]
Btw. the timeout could be increased, but I'm not sure what kind of limit we would like to enforce. I remember that at some point it was way over 5 minutes.

The same long processing affects the end-users as well, and I think addressing [this](https://github.com/dart-lang/pub/issues/1702), which is a special case of [this](https://github.com/dart-lang/pub/issues/912) would yield improvements not only for us, but for every developer.

**Comment by mit-mit** [comment]
I just ran `flutter packages upgrade` against `/plugins/packages/firebase_database` on my MacBook, and that tool 7.9 seconds. Why is it timing out on the bot?

**Comment by isoos** [comment]
> I just ran flutter packages upgrade against /plugins/packages/firebase_database on my MacBook, and that took 7.9 seconds. Why is it timing out on the bot?

Similar experience here in local env. I've got two theories:
- It is possible that one of the dependencies was upgraded with a new set of constraints which makes the resolution faster.
- We may have had a transient network problem, and we should retry it.

@kevmoo / @mkustermann: could you please re-schedule it for analysis? This needs to be run in the prod environment:
```
dart bin/tools/notify_service.dart analyzer firebase_database 0.1.2
```

**Comment by kevmoo** [comment]
Done! (I think...that tool should print some sort of status...)

**Comment by kevmoo** [comment]
That's better: https://pub.dartlang.org/experimental/search?q=firebase+database

**Comment by isoos** [comment]
Yeah, it looks like it was a transient issue.

**Comment by kevmoo** [comment]
@isoos – anything else we should do here?

**Comment by mit-mit** [comment]
Shouldn't we consider having automated retries for transient failures?

**Comment by isoos** [comment]
> Shouldn't we consider having automated retries for transient failures?

We do, see #484 (immediately after the failure) and #485 (~ a day later).

**Comment by mit-mit** [comment]
Great, thanks

**Comment by isoos** [comment]
Most of this has been deployed, and the recent merges will increase stability, closing.

**Comment by mit-mit** [comment]
Thanks!
