### ISSUE TITLE
Search rankings don't seem to take filtered platform (enough) into account

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#461]
For example, search for firebase support for flutter:
https://pub.dartlang.org/experimental/search?q=firebase&platforms=flutter

The second (`firebase_rest`) and third (`firebase_dart`) hits are fairly irrelevant for Flutter. As a mobile developer you really want the mobile specific ones ([i.e., these six](https://github.com/flutter/plugins/blob/master/FlutterFire.md)).

**Comment by isoos** [comment]
So, you can't have both ways: it is either "exclusively flutter", or "everything that runs on flutter (among others)". I've pinged @kevmoo a lot about this question, and the latest was that we have chosen "everything that runs on X" (X=flutter in this case).

The best thing we can do is to introduce an extra checkbox somewhere, that turns into "exlusive on X".

**Comment by kevmoo** [comment]
Discussing our options internally

**Comment by mit-mit** [comment]
I'm looking for neither "exclusively flutter" nor "everything that runs on flutter (among others)".

I'm looking for "everything that works for flutter" *sorted* with "best for flutter first".

**Comment by mkustermann** [comment]
At least if the package's `pubspec.yaml` has a `flutter_plugin:` section (or whatever it was called), it's a **big sign** that this is **more related to flutter** as a package which just has platform independent libraries (which run on flutter). Another sign is if there are **flutter-only** libraries in a package (i.e. a exposed library which transitively imports flutter core libraries).

So why not having an additional ranking signal for these?

**Comment by isoos** [comment]
> sorted with "best for flutter first".

We could use the single-platform classification as a signal, e.g. if something is Flutter-only (or web-only), than it is relevant among the given platform. However, commonly used (~~ popular) packages that are cross-platform also bear a significance, and at one point we need to decide a weight between those. Any guesstimate how these should be related to each other?
