### ISSUE TITLE
To discuss: highlight "exact matches" in search

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#465]
See https://crates.io/search?q=winapi

If the search string exactly matches a package, highlight it on top

Wondering if this would be useful?

**Comment by isoos** [comment]
I find the crates.io highlight a bit confusing: its title, description, links and its download counts are not aligned with the rest of the results, and when I try to scan the page for further result, it has a "something is wrong" feeling.

Highlighting the background of the first match may work though.

**Comment by isoos** [comment]
The consensus was that it is too busy.
