### ISSUE TITLE
`installing` tab should include flutter instructions

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#490]
See `https://pub.dartlang.org/experimental/packages/pana#pub-tab-installing`

We should discuss the design here, but it's clear we should tell folks to use `flutter packages get`

**Comment by kevmoo** [comment]
CC @mit-mit

**Comment by isoos** [comment]
We do tell folks to use `flutter packages get`:
- v1: https://pub.dartlang.org/packages/cloud_firestore#pub-pkg-tab-installing
- v2: https://pub.dartlang.org/experimental/packages/cloud_firestore#pub-tab-installing

**Comment by kevmoo** [comment]
For flutter-only packages, which is great!

But what about packages that work on flutter, but aren't flutter-only? Like pkg/collection, pkg/async, etc...

**Comment by isoos** [comment]
Ah... so we want to display both if the package is multi-platform?

**Comment by kevmoo** [comment]
Or provide a toggle or something?

Let's discuss...just wanted it tracked...
