### ISSUE TITLE
Update flutter landing page graphic: "[LOGO] Flutter Packages"

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#510]
Blocked: waiting to get graphics from our design folks

**Comment by kevmoo** [comment]
CC @sethladd @mit-mit

**Comment by mit-mit** [comment]
Isn't this the regular Flutter logo?

**Comment by kevmoo** [comment]
The site layout uses SVG – which is great for keeping assets small.

We can just use the PNG if we get no traction w/ design

**Comment by kevmoo** [comment]
[Flutter-Packages.png.zip](https://github.com/dart-lang/pub-dartlang-dart/files/1483890/Flutter-Packages.png.zip)

@isoos – will want to resize this before we put it on the site 😄
