### ISSUE TITLE
Error when performing pub publish

### ISSUE THREAD

**Issue by jorishermans** [dart-lang/pub-dartlang-dart#52]
I got on dart version 1.17 when performing a 'pub publish'

Uploading...
Class 'AppEnginePackageMemcache' has no instance method '_packageUIKey with matching arguments.

NoSuchMethodError: incorrect number of arguments passed to method named '_packageUIKey'
Receiver: Instance of 'AppEnginePackageMemcache'
Tried calling: _packageUIKey("MyPackage")
Found: _packageUIKey(package, version)

**Comment by mkustermann** [comment]
Should be fixed.

**Comment by jorishermans** [comment]
Thanks, it is fixed :)
