### ISSUE TITLE
Never store an "invalid error" in memcache

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#525]
...for search/analyzer results

**Comment by isoos** [comment]
I think we never did that:
- `AnalyzerClient` checks for `statusCode==200` ([link](https://github.com/isoos/pub-dartlang-dart/blob/master/app/lib/shared/analyzer_client.dart#L83))
- `SearchMemcache` only stores the generated HTML pages

**Comment by mkustermann** [comment]
This turned out to be not storing into memcache but still being returned from memcache. The bug in package:memcache was should be fixed in https://github.com/dart-lang/memcache/commit/a6357481876c8379cca3080a81943e8153778d3d
