### ISSUE TITLE
Handle memcache going down during an active deployment

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#526]
Related to https://github.com/dart-lang/pub-dartlang-dart/issues/524

**Comment by isoos** [comment]
All of the memcache access is in try-catch block, and https://github.com/dart-lang/pub-dartlang-dart/pull/528 adds timeout handling too. What else could we do to handle memcache failures?

**Comment by mkustermann** [comment]
Agreed, closing.

**Comment by natebosch** [comment]
I think I saw some reports that we were still serving 200 OK responses despite the fact that the content was an error - are we correctly using a non-success error code now?

**Comment by mkustermann** [comment]
Our memcache implementation gave us bad data on lookups - which were then served. Now it reports an error.

So, yes it should be fixed
