### ISSUE TITLE
Platform not working well in search filtering

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#527]
With latest deployment f3492d6 - 20171106t103021-default,search,analyzer

Compare https://search-dot-dartlang-pub.appspot.com/search?q=angular&platform=web

to 

https://search-dot-dartlang-pub.appspot.com/search?q=angular

**Comment by isoos** [comment]
This may be the aftermath of the memcache issue, wrong analysis data stored in cache and/or in search index. Could you please restart the search instances too?

**Comment by isoos** [comment]
AFAICT the situation got better. @kevmoo: Can you please confirm that there was a restart?

**Comment by isoos** [comment]
I believe this can be closed now.
