### ISSUE TITLE
Unable to load popularity data

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#530]
```
 Unable to load popularity data: gs://dartlang-pub--popularity/popularity-latest.json.gz
Error: NoSuchMethodError: Class 'int' has no instance getter 'isEmpty'. Receiver: 0 Tried calling: isEmpty
Stack:
#0 Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1 int.parse (dart:core-patch/dart:core/integers_patch.dart:53)
#2 PopularityStorage._updateLatest (package:pub_dartlang_org/search/backend.dart:193:32)
#3 PopularityStorage.fetch (package:pub_dartlang_org/search/backend.dart:179:7) <asynchronous suspension>
#4 PopularityStorage.init.<anonymous closure> (package:pub_dartlang_org/search/backend.dart:166:7) 
```

**Comment by isoos** [comment]
@mkustermann: could you please check the content of the bucket? I remember Kevin making a change that mentioned versions in the file name, maybe we haven't updated the code for that?

**Comment by mkustermann** [comment]
Yes, for breaking format changes they are put into a new directory, for same format but new data they are overridden:

```
% gsutil ls gs://dartlang-pub--popularity/
gs://dartlang-pub--popularity/popularity-latest.json
gs://dartlang-pub--popularity/popularity-latest.json.gz
gs://dartlang-pub--popularity/v2/
gs://dartlang-pub--popularity/v3/
% gsutil ls gs://dartlang-pub--popularity/v2
gs://dartlang-pub--popularity/v2/popularity.json.gz
% gsutil ls gs://dartlang-pub--popularity/v3
gs://dartlang-pub--popularity/v3/popularity.json.gz

```

**Comment by mkustermann** [comment]
Let's keep this issue open until: a) prod can load the files b) it's safe to delete the legacy files.

**Comment by isoos** [comment]
Looks like we have the correct code in more than 7+ days: [link](https://github.com/dart-lang/pub-dartlang-dart/pull/486/files#diff-1f8d03fa608d13be3724a66a6c9ce73fR158). Maybe we have an older version running that fails to load and still logs it?

**Comment by kevmoo** [comment]
I was hoping having the version info would make this a non-issue.

**Comment by isoos** [comment]
> I was hoping having the version info would make this a non-issue.

And I believe it did, we may just have an older version around?

**Comment by kevmoo** [comment]
The older version should be grabbing it from the older location – I haven't deleted anything...

**Comment by kevmoo** [comment]
Any more thoughts here?

**Comment by isoos** [comment]
Old release versions running explain the exception, I wouldn't worry much for now.

**Comment by isoos** [comment]
The error is absent in the past week, probably because new releases are reading the correct values.
