### ISSUE TITLE
Formatting issues in CHANGELOG.md

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub-dartlang-dart#54]
In the CHANGELOG.md tab of https://pub.dartlang.org/packages/angular2, the comment `<!-- ### Breaking changes -->` is visible. Just below that, the continuation of the "API changes" section's bulleted item _should_ be indented, but isn't.

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/2164483/17312911/b149eb50-580b-11e6-92b5-79a0f9837d24.png)

That screenshot reflects the version at https://github.com/dart-lang/angular2/blob/be587bebc0af23053f84d3a6ed93d4cfb110d96a/CHANGELOG.md (which formats correctly in github).

I'll submit a workaround for this, but it'd be much better to have the markdown behave correctly and/or a way to preview how it'll look on pub.dartlang.org.

**Comment by mkustermann** [comment]
We are just using [package:markdown](https://github.com/dart-lang/markdown) for rendering this.

@munificent Do you know how is maintaining the markdown package at the moment?

**Comment by munificent** [comment]
@srawlins is doing a lot of work on it these days.

**Comment by srawlins** [comment]
This package is also on a pretty old version of package:markdown. I'd try bumping it. Our HTML support has gotten better. I think that should work.

**Comment by mkustermann** [comment]
I've updated now to the newest version of `package:markdown` (i.e. 0.10.1), but support for comments in markdown files seem to be still rendered.

For this issue I've filed an issue now (and also for having a simple way of seeing rendered output):
[markdown/issues/114: Support comments in markdown files](https://github.com/dart-lang/markdown/issues/114)
[markdown/issues/115: Simple way of showing markdown output](https://github.com/dart-lang/markdown/issues/115)

**Comment by mkustermann** [comment]
@srawlins Any chance you would have the time to look at these?

**Comment by srawlins** [comment]
@mkustermann definitely. And I think 0.10.1 has fixed your issue, right? The `<!-- comment -->` is in the output, but not escaped (`&lt;!-- comment --&gt;`), so it no longer shows up in your output.

**Comment by mkustermann** [comment]
We upgraded to a newer `package:markdown`.
