### ISSUE TITLE
Searching with multiple terms seems to not work?

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#547]
I could be totally missing something, but looks like multi-word searches don't `AND` the terms together?

For example, https://pub.dartlang.org/experimental/packages?q=firebase+flutter, seems to give lots of results that don't have `firebase` in them?

**Comment by isoos** [comment]
Yeah, that is correct. Currently we will look for each substring and try to weight them independently from their word separators.

I was planning to implement something along these lines for a while:
- try to match the longest sequence of text, and
- if we have match for that, we don't look for shorter character substrings.

However, that wouldn't really do good for your example either. It seems to be fair to say that the default expectation is to do an implicit `AND` between the words, I'll make sure it is handled that way.

**Comment by mit-mit** [comment]
Yes, my expectation is that all terms are `AND`'ed, and that if you want multi-word terms, you quote them.

For example, `"cloud storage"` is match the full term `cloud storage`.

And `"cloud storage" database` is `"cloud storage" AND database`

I believe this is consistent with google.com and other major search engines.

**Comment by mit-mit** [comment]
cc @kevmoo

**Comment by kevmoo** [comment]
@isoos – is this fixed?

**Comment by isoos** [comment]
Pending PR
