### ISSUE TITLE
When doing HTTP RPCs to services, do better logging

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#551]
1. Log the full URL we're hitting before the request goes out. Allows us to understand why hitting User URL X -> search URL Y
2. If possible, it'd be great to log the version of the search service that was hit – should be in the reply headers – if at all possible, it'd be great to get the request ID, too...so we can debug a full round-trip

**Comment by isoos** [comment]
@mkustermann: is there an API to query the currently running instance's version in the appengine?

**Comment by mkustermann** [comment]
There is an [package:googleapis/appengine/v1.dart](https://www.dartdocs.org/documentation/googleapis/0.47.0/googleapis.appengine.v1/AppsServicesVersionsResourceApi-class.html) api, it requires special IAM permission, i.e. the default service account the deployed service is using needs to have been added to the right IAM roles iirc.

**Comment by isoos** [comment]
I'm pretty sure it would not be that hard to use that API, but maybe we could use a simpler version, e.g. the last modified time of the `.packages` file? That should be set at the time we build the image, and could be used without much risk of exposing internal details.

**Comment by kevmoo** [comment]
The response header of the request should have the version in it...I think...

**Comment by isoos** [comment]
> The response header of the request should have the version in it...I think...

Headers from the `analyzer` service, via `curl`:

````
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 21 Nov 2017 16:37:46 GMT
< Content-Type: application/json; charset="utf-8"
< Content-Length: 219
< Vary: Accept-Encoding
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< Via: 1.1 google
< Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
````

Version may be exposed, but because we are using the public URLs they are stripped off?

**Comment by kevmoo** [comment]
Huh...maybe.

Wonder if there is another URL...hrm...
