### ISSUE TITLE
Have all platform icons always there and "grey out" platform icons which are not supported

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/pub-dartlang-dart#554]
The package listing pages look slightly weired to me since we only show the platform icons for the platforms which are supported. So for example they are not aligned below each other in columns but stacked from the left, so sometimes the html5 icon is left-most sometimes right-most.

Suggestion: Always show all icons and grey out (i.e. black/white versions of the normal icons) the ones which are not supported. 

@kevmoo @isoos  wdyt?

**Comment by isoos** [comment]
I agree. However, in the v2 design there won't be icons around, and the listing page won't have a platform-specific column, so I wouldn't put much effort into this, until that is finalized.

**Comment by mkustermann** [comment]
Then let's close it, since v2 is around the corner.
