### ISSUE TITLE
Hyperlinks to sections in readme don't work in pub.dartlang.org

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub-dartlang-dart#56]
If you load this page:

https://pub.dartlang.org/packages/test

The top part of the readme is a bunch of links that are supposed to link down the page. They don't work.

My guess is that GitHub adds names to the headings but whatever is doing the markdown here does not. Possibly you could blame the package, but since this is a Dart Team package and it seems like very useful functionality it might be worth investigating if it can be made to work?

**Comment by mkustermann** [comment]
This seems to work now with the newest version of the markdown package.

**Comment by DanTup** [comment]
Yep, works now. Though the floating black bar means the heading that it scrolls to is obscured (a common issue with floating headers like this!).
