### ISSUE TITLE
Fix resize on load for homepage – related to header image size

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#561]
Likely tricky, I know...but it looks pretty bad when navigating between pages

![ezgif-4-6135945d9d](https://user-images.githubusercontent.com/17034/32679361-106a877e-c61b-11e7-8d52-23707b670b1e.gif)

You can also see it just clicking around here - https://pub.dartlang.org/experimental

**Comment by isoos** [comment]
Tricky indeed! I've tried a few trivial changes (e.g. setting fixed width and height for the images), but these didn't yield much.

**Comment by isoos** [comment]
In their isolation, none of the HTML element, SVG images, background-image styles or CSS styles are responsible for the paint glitch (I've removed blocks from each of these, reloaded, checked if it is still working.

I have now a strong feeling that the root cause is in caching: we may see the repaint of the images because the browser thinks it has received new images. We don't set any cache headers when serving these...

**Comment by isoos** [comment]
I've got a definite improvement using `shelf_static`, but looking at the source code, they are using `*Sync` methods all over the place, and I wouldn't want the VM to block other requests on it. (https://github.com/dart-lang/shelf_static/issues/25)

**Comment by kevmoo** [comment]
See the notes from @nex3 – the actual file write is done async, which is likely the biggest bottleneck.

Let's try it out w/out changes and see how the perf is.

Also: is this shelf_static vs the default file handling that's in the appengine package?

**Comment by isoos** [comment]
We are using a custom static file serving, not the one from appengine (not sure what is there). I'm preparing  PR to adapt the cache headers into it.

Wrt. async vs sync: my experience differs, and I'll put together a benchmark if that is what this gets through. Or fork :).

**Comment by kevmoo** [comment]
If we have benchmarks on shelf_static, I'm sure we'll be willing to evolve...

**Comment by isoos** [comment]
Besides the pending open PR, I've found that the loading of the survey has also an effect on the flickering of the paint. Both of these solves it:
- removing it
- changing it to synchronously loaded (removing both `async` and `defer` attributes)

@kevmoo: what's the plan around that?

**Comment by kevmoo** [comment]
I think it looks great now. Closing.
