### ISSUE TITLE
New Flutter page lists packages, but it's unclear what those packages are

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#565]
![pub__dart_package_manager](https://user-images.githubusercontent.com/5479/32749853-90a4d6ae-c875-11e7-8afc-9ddf66a19f66.png)

**Comment by kevmoo** [comment]
Will ponder UX work required here...

**Comment by isoos** [comment]
I'm wondering if we could just put a `h2` header there in the center: "Top [platform | Dart] packages"?
