### ISSUE TITLE
Versions tab sometimes not rendering in browser

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/pub-dartlang-dart#57]
The following pages don't render correctly:
- https://pub.dartlang.org/packages/polymer_expressions#versions
- https://pub.dartlang.org/packages/core_elements#versions

Instead of showing the "Versions" tab, they just show the "README.md" tab.

```
Google Chrome   54.0.2840.41 (Official Build) beta (64-bit)
Revision    aeb8895aa4becddb1526af10d1e67495713b6c1a-refs/branch-heads/2840@{#557}
OS  Mac OS X 
JavaScript  V8 5.4.500.31
Flash   23.0.0.185
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.41 Safari/537.36
```

**Comment by kevmoo** [comment]
CC @mkustermann

**Comment by mkustermann** [comment]
This was due to inline html in the markdown files. Should be fixed now.
