### ISSUE TITLE
pkg/built_json download information does not render

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#58]
See https://pub.dartlang.org/packages/built_json

**Comment by srawlins** [comment]
Do you mean the links? Whitespace is not allowed between the `]` and the `(`.

**Comment by mkustermann** [comment]
As @srawlins says, this is due to the whitespace between link text and href (which github apparently seems to accept, see: https://github.com/google/built_json.dart)

**Comment by isoos** [comment]
This is the same as issue #72.
