### ISSUE TITLE
Should pub.dartlang.org render arbitrary html like <input> from READMEs?

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub-dartlang-dart#59]
This page:

https://pub.dartlang.org/packages/backy

has a random input box in the middle of it. This is because the README contains `<input>`. It doesn't render properly on GitHub either (it's just missing), but I wonder whether this is expected. I haven't done any testing, but it makes me wonder if other tags (like `<script>`) might also get through.

![screenshot 2016-11-10 at 19 27 03](https://cloud.githubusercontent.com/assets/1078012/20191098/07b9a4de-a77c-11e6-8108-9529906f64bf.png)

**Comment by mkustermann** [comment]
This is certainly not expected. Might this be a bug in [package:markdown](https://pub.dartlang.org/packages/markdown) ?

**Comment by DanTup** [comment]
AFAIK it is completely valid for markdown to include HTML. But, if you're displaying content from a third party you probably want to restrict what tags are allowed. So.. I'm not sure if this is really a bug in the Markdown library or just some missing restrictions for how the pub site is using it?

**Comment by mkustermann** [comment]
The `package:markdown` author explained on the issue that it's now possible to enable/disable specific syntax flavors. Should be fixed now.

**Comment by DanTup** [comment]
LGTM on the site now 👍
