### ISSUE TITLE
Provide AngularDart -> Angular alias for search.

### ISSUE THREAD

**Issue by ferhatb** [dart-lang/pub-dartlang-dart#595]
* Please include a link to the page in question
* Please check existing bug to see if your issue has already been filed

**Comment by isoos** [comment]
What's wrong with that? It has a description: "Router for AngularDart." which makes it relevant for the query, and also its readme has in the beginning: "The AngularDart router enables..."

**Comment by kevmoo** [comment]
Ignoring the implementation, we often refer to our flavor of Angular (and friends) as `AngularDart`.

We may want to ponder some hard-wired aliases for this and similar cases

**Comment by isoos** [comment]
I think the most transparent change here would be to include the `AngularDart` term in the description of the `angular` package, and publish a patch release. Is there something against that?

Either that, or we shall re-visit #602 as the hard-wired solution.

**Comment by kevmoo** [comment]
We should add `AngularDart` to the readme. We can check to see if `AngularDart` is a common search term. I'd rather not add a special case here unless we're sure it's needed.

Keeping open to track general issues related to extra metadata

**Comment by isoos** [comment]
`AngularDart` was added to the readme, it is still not showing up in the search, but it should. Investigating, but I'll need a fresh search snapshot (/cc @kevmoo).

**Comment by isoos** [comment]
Fixed with the latest release.
