### ISSUE TITLE
Make sure the scores are explained

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#596]
It should be easy for folks to understand why a package got the score it did...

**Comment by isoos** [comment]
Any specific suggestion and measurable goals we can list here? How much detail do we want to expose? Some examples:

- We don't provide exact download numbers, and the current popularity is kind of hard to grasp. Maybe if it were percentile based, popularity = 80 would be that the package is more popular than the 80% of the packages (technically it would be 79.5+).

- All files contribute to the health score, and listing everything is likely too much for the analysis tab.

**Comment by daniel-v** [comment]
Browsing the new site, that was exactly my first question: "what the hack are these scores?`

If nothing else, I'd put a link next to Scores header `what are these scores?` that link a wiki page or an MD in this repo.

**Comment by filiph** [comment]
I propose adding a new "Suggestion" that triggers when your popularity is below 100. This suggestion will give a short explanation and a link to more. We can be hand-wavy. The important part is to explain what exactly Popularity even means. How exactly it's computed can be secret sauce.

Same goes with Health.

**Comment by isoos** [comment]
PTAL on the site. Is it better now? What would you do differently?

**Comment by kevmoo** [comment]
Lot's of content added for this now. Closing.
