### ISSUE TITLE
miscategorized dart_to_js_script_rewriter

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub-dartlang-dart#598]
[dart_to_js_script_rewriter](https://pub.dartlang.org/experimental/packages/dart_to_js_script_rewriter) is categorized as flutter/server, but should be web.

**Comment by kevmoo** [comment]
Background: platform categories are based on the code. `dart_to_js_script_rewriter` uses transformers – which ends up using `dart:io`.

So it's allowed for flutter/server (yes, flutter here is also weird) and excluded on web.

Still need to fix, but that's the background.

**Comment by isoos** [comment]
Not sure what to fix here: the library's code is not usable in a web app, and we shouldn't state otherwise. We could classify it as build-helper though, but not sure if that provides enough value to do it (everything that is server could be part of a build)

**Comment by matanlurey** [comment]
Would be interesting to have @jakemac53 and @natebosch weigh in here.

**Comment by jakemac53** [comment]
It might make sense for an override in the pubspec for packages like this?

**Comment by mit-mit** [comment]
Yeah, some kind of override would be good. This currently shows up as a top Flutter package, which will definitely cause developer confusion: https://pub.dartlang.org/experimental/flutter

**Comment by isoos** [comment]
Maybe we should revisit the `category:` metadata request: https://github.com/dart-lang/pub-dartlang-dart/issues/367. If `dart_to_js_script_rewriter` were to be categorized as an `asset-transformer` (or something similar build-related), then we would know that it is (a) generic, and (b) wouldn't rank it high for the platform-specific pages.

**Comment by mit-mit** [comment]
We should also consider a short-term solution of having a manual 'override' list for re-categorizing packages manually.
