### ISSUE TITLE
Feature request - view number of imports for a package

### ISSUE THREAD

**Issue by gedw99** [dart-lang/pub-dartlang-dart#60]
When looking at a package it would be helpful to be able to see what packages import the respective package.

Why ?
So I can see examples of the package being used.

So I can see how popular a package is.

The same functionality exists in golang with godoc, and I feel it's worthwhile.

I would prefer this to be implemented at the web GUI level.

Please let me know if there are any questions.

**Comment by isoos** [comment]
You can use `dependency:pkg_name` in the search field to list/search the packages that depend on the package. (soon a change will be deployed: `dependecy*:` will list all of the transient dependents, while `dependency:` will list only the ones directly referenced in `pubspec.yaml`).
