### ISSUE TITLE
Sort on `server` page should not prioritize server-only packages

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/pub-dartlang-dart#600]
Context: https://pub.dartlang.org/experimental/server/packages

![image](https://user-images.githubusercontent.com/24210656/32969907-ab6df014-cb9b-11e7-943a-8fe130566971.png)

**Comment by isoos** [comment]
Couple of things at play:
- there is always a single score that is displayed, regardless of text search match relevance or ordering (try `?sort=updated` at the end of the url)
- platform-lists are ranked with an additional score that is the specificity to the given platform. eg. packages that are server-only rank a bit more than packages that run on 2 or 3 platforms.

I'm not sure if and how this later part should be spelled out on the UI. Maybe we shall say it is ordered by `magic`? :)

**Comment by kevmoo** [comment]
@isoos – wondering if the platform-exclusive sorting we use for `flutter` makes sense for `server`.

Down-ranking mixed packages when looking at flutter makes sense. I don't think it applies when looking at server packages, though. We end up giving priority for packages that use mirrors, then.

**Comment by isoos** [comment]
We don't do platform-exclusive sort. We do have platform-specificity, which prefers single platform over two-platforms over three platforms, and it is applied to all of the platforms, symmetrically.

**Comment by kevmoo** [comment]
My thought: flutter is the only case where we want to prefer flutter-only to multi-platform.

For Web/Server – don't be fancy.

Reasonable?

**Comment by isoos** [comment]
If you look at the `All`'s top 15, 8 of them are all-platform, and if we don't do platform-specificity there, these 8 will be present at both `Server` and `Web` and `All`. With the specificity, we are showing a much larger variety, more tailored to the platform. We could tune down the weight of it in non-Flutter platforms, but I wouldn't remove it entirely, I think it provides a good value.
