### ISSUE TITLE
[team review] Align labels in addition to package titles?

### ISSUE THREAD

**Issue by kasperl** [dart-lang/pub-dartlang-dart#612]
Front page (https://pub.dartlang.org/experimental/) looks a bit messy to me because of the lack of horizontal alignment of the labels (FLUTTER WEB SERVER) across the different packages.

Right now, we show: 
```
collection                                          url_launcher
Collections and utilities functions and             A Flutter plugin for launching a URL.
classes related to collections.                     |FLUTTER|
|FLUTTER| |SERVER |WEB|
```

but maybe moving the labels up right after the title would make the page look less "jumpy"?

**Comment by isoos** [comment]
I agree, that works better. We'll need to figure out whether the landing page and the subsequent package listing page (e.g. search) should be different (right now on the listing page the metadata is below the description).
