### ISSUE TITLE
Flutter tag links to incorrect page

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#620]
The individual package pages show a tag for the package type, e.g. 'FLUTTER' here:
https://pub.dartlang.org/experimental/packages/url_launcher#-readme-tab-

For flutter packages this currently links to https://pub.dartlang.org/flutter/packages. I think it should link to https://pub.dartlang.org/experimental/flutter.

**Comment by mit-mit** [comment]
cc @isoos

**Comment by isoos** [comment]
This is fixed in code, but not deployed yet.

**Comment by mit-mit** [comment]
Great, thanks

**Comment by kevmoo** [comment]
Deployed!
