### ISSUE TITLE
Consider making the Analysis tab say "Score (98)" instead of just "(98)"

### ISSUE THREAD

**Issue by filiph** [dart-lang/pub-dartlang-dart#626]
Example link: https://pub.dartlang.org/experimental/packages/xml

<img width="728" alt="screen shot 2017-11-22 at 15 14 44" src="https://user-images.githubusercontent.com/919717/33153659-f22e6ed4-cf97-11e7-94d5-857acfefd1b8.png">

That "(98)" in a circle is kind of mysterious and it isn't obvious that it's just another tab (i.e. it's clickable). Maybe adding "Score:" or "Analysis:" to it would help.

Downside: some of the more feature-complete packages (like [chartjs](https://pub.dartlang.org/experimental/packages/chartjs)) don't have the screen real estate.

**Comment by kevmoo** [comment]
We could certainly add a hover-over title/tooltip to be more clear.

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/pub-dartlang-dart/issues/631

**Comment by isoos** [comment]
Yeah, screen estate is the issue here. We've had a version where we had the 'Analysis' label below the score, and another one where it was beside it. I believe if we link to the analysis from multiple places it will be auto-discovered by the visitors

**Comment by kevmoo** [comment]
I think the info we have here is pretty good. Don't want to take up the real estate.

https://pub.dartlang.org/experimental/packages/collection#-analysis-tab-
