### ISSUE TITLE
[team review] Don't fail people for not including .dart files in `bin`

### ISSUE THREAD

**Issue by filiph** [dart-lang/pub-dartlang-dart#627]
Link: https://pub.dartlang.org/experimental/packages/jsonp#-analysis-tab-

The jsonp package gets its score downgraded because "No dart files found at: bin". Although that might mean that the package structure doesn't conform to pub standards, I think it could be only a tiny detracting signal

Right now it looks like this prevented the scoring algorithm to continue.

**Comment by isoos** [comment]
This will be fixed with https://github.com/dart-lang/pana/pull/141 (in the next `pana` patch release)
