### ISSUE TITLE
Provide a 'report issues with analysis' link at the top of the analysis tab

### ISSUE THREAD

**Issue by filiph** [dart-lang/pub-dartlang-dart#628]
Example page: https://pub.dartlang.org/experimental/packages/jsonp#-analysis-tab-

We should be very humble about the automated test.

* Put a visible "experimental feature" flag at the top of each analysis tab
* Add something like "give feedback" right next to it

**Comment by kevmoo** [comment]
@filiph – I wouldn't call our analysis "experimental" anymore. But it's absolutely open for refinement. Updated the title.

**Comment by filiph** [comment]
Maybe "experimental" is a strong wording but I say let's be humble and safe. This is a new feature and will inevitably have some issues at first ([exhibit A](https://github.com/dart-lang/pub-dartlang-dart/issues/633)). This is us scoring someone's work.

Maybe say "This feature is new. We welcome feedback."
