### ISSUE TITLE
Promote Angular2 in the front page

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/pub-dartlang-dart#63]
We have been getting consistent feedback that finding the right AngularDart package on pub is confusing. As a stop-gap until we have better lists (e.g. most used or most viewed packages), I suggest we introduce something like the following, e.g., in a box, on the [front page](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/views/index.mustache).
  "Writing a web app in Dart? Check out the [AngularDart](https://pub.dartlang.org/packages/angular2) package". 

Similarly, we could have "Writing a mobile app in Dart? Check out [Flutter](https://flutter.io/)".

@mkustermann, WDYT?

**Comment by mkustermann** [comment]
CL is up: https://codereview.chromium.org/2560433002/
