### ISSUE TITLE
Explain `[UNSURE]` on click

### ISSUE THREAD

**Issue by filiph** [dart-lang/pub-dartlang-dart#630]
Link: https://pub.dartlang.org/experimental/packages/jsonp#-readme-tab-

* Clicking `[UNSURE]` should lead the user to a page / section explaining why that particular package is marked as UNSURE (or generally, why some packages are marked so).

**Comment by isoos** [comment]
Usually we are unsure because the package has some errors, and the best page for it is it's analysis with the errors.

**Comment by kevmoo** [comment]
> Usually we are unsure because the package has some errors, and the best page for it is it's analysis with the errors.

Just linking there would be helpful, I think
