### ISSUE TITLE
Add sort option to package page to make it easy to see recently uploaded packages

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub-dartlang-dart#635]
This was there at some point... now I just see "top".

**Comment by isoos** [comment]
The UI design part is pending, but until then, you can add `?sort=updated` to the URL. Also try `created`, `popularity`, `health`, `maintenance`

**Comment by kevmoo** [comment]
Coming later, but planned...

**Comment by matanlurey** [comment]
@kevmoo But this is a regression from the existing site.

**Comment by kevmoo** [comment]
> @kevmoo But this is a regression from the existing site.

Yup. We decided to prioritize top packages over updated. We have plans to get this back, but we wanted to focus on the most important user flow first.

**Comment by matanlurey** [comment]
Alright, but aren't people going to wonder when they upload their package and don't see anything?

**Comment by kevmoo** [comment]
> Alright, but aren't people going to wonder when they upload their package and don't see anything?

They can always go to the package page, right?

I absolutely want to get this feature back. Just need to work out the UI.

For most users, seeing the best packages first is the most useful thing.

**Comment by kevmoo** [comment]
Changes title to make this about exposing this in the UI

In the mean time: https://pub.dartlang.org/experimental/flutter/packages?sort=updated

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/pub-dartlang-dart/commit/66cedd624834b3280c83748c1aed5cb1b89b7d51

Will be deployed shortly...
