### ISSUE TITLE
[Team] Top packages show questionable packages

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub-dartlang-dart#636]
For example, I really doubt the following packages are "top":

* string_scanner
* yaml
* crypto

**Comment by kevmoo** [comment]
Please include the link you're looking at that shows these?

I think in some cases, these guys are using in common bootstrap apps for
flutter, which is why they show up so much...

**Comment by matanlurey** [comment]
It's just the homepage for me.

**Comment by isoos** [comment]
Did a bit of digging, and from the data in staging (which is 7+ months old):
- `string_scanner` is in ~20 packages as direct, and 800+ packages as transitive dependency
- `yaml` and `crypto` is in ~100 packages as direct and 500-600 packages as transitive dependency

Not sure whether we need to do something about it though... For example, `crypto` is certainly an enabler. And if you have built a service client library with it, and that library gets popular, does this mean `crypto` doesn't deserve the credit for it?

Side note: I think it will be a great value to expose the dependencies through search.

**Comment by matanlurey** [comment]
I don't know. I'm looking at it through the lense of a prospective Dart (or Flutter) user. The top suggested packages sometimes have little practical use for anyone that isn't a developer _on_ the Dart team already (`string_scanner`, for example).

**Comment by isoos** [comment]
@kevmoo: could the popularity data import script distinguish between direct downloads and transitive dependency downloads? If it can, we can tune it easily, if not, we could do some compensation on our side, but there is no straightforward solution.

**Comment by mkustermann** [comment]
Isn't that exactly what [VoteData.direct_votes](https://github.com/dart-lang/pub-dartlang-dart/blob/master/pkg/_popularity/lib/popularity.dart#L58) is for?

**Comment by isoos** [comment]
> Isn't that exactly what VoteData.direct_votes is for?

There is no transitive there, only direct and dev, which leaves it ambiguous.

**Comment by kevmoo** [comment]
`score` doesn't even weigh tho `total` value, which includes transitive usages.

https://github.com/dart-lang/pub-dartlang-dart/blob/c81422c8eb67dac4fd37c14ed3f3d97e8942e4d5/pkg/_popularity/lib/popularity.dart#L76

**Comment by isoos** [comment]
`string_scanner` has a huge direct vote count in the flutter context. any idea why that would be?

**Comment by kevmoo** [comment]
Nope. I'd have to dig...

**Comment by matanlurey** [comment]
Probably something tooling related

**Comment by isoos** [comment]
> string_scanner has a huge direct vote count in the flutter context.

I guess this is it:
https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml#L53

While there is a comment in that file about being a transitive dependency, it is specified and therefore direct.

I think we don't have a bug here, shall we close this?

**Comment by matanlurey** [comment]
But that's a transitive dependency.

**Comment by matanlurey** [comment]
Right what I mean though is people depend on Flutter, they don't depend on
string_scanner.

**Comment by kevmoo** [comment]
Changed the title. transitive dependencies aren't counted at all. Digging now to understand why barback, etc is showing up so high...

**Comment by matanlurey** [comment]
Thanks!

**Comment by mit-mit** [comment]
Yes, specifically for flutter we are now seeing several (e.g. barback, glob, html, and dart_style) "unexplainable" top-pages on https://pub.dartlang.org/experimental/flutter. Two weeks ago there was just a single non-flutter only package there, so something seems to have changed.

I think this is a launch blocker.

**Comment by isoos** [comment]
@mit-mit: any comment on https://github.com/dart-lang/pub-dartlang-dart/issues/636#issuecomment-348242778? Some of the top packages there are marked as transitive deps of `flutter`, yet because it is specified in the `pubspec.yaml`, they are treated as they were direct dependencies. Is there any reason not to fix the versions in `pubspec.lock`?

**Comment by kevmoo** [comment]
Turns out there is some funky behavior w/ flutter and dependencies.

Discussions are ongoing. Nothing left to do in the context of the pub site.

The popularity score data has been updated. I think we're looking better now.

**Comment by mit-mit** [comment]
@kevmoo I still see barback, intl_translation, and html here?
https://pub.dartlang.org/experimental/flutter

**Comment by mit-mit** [comment]
re-opening until we get this figured out

**Comment by isoos** [comment]
@mit-mit: #700 should fix this (platform-specific specificity scores).

**Comment by kevmoo** [comment]
@mit-mit https://github.com/dart-lang/pub-dartlang-dart/pull/700 is deployed – https://pub.dartlang.org/experimental/flutter looks much better now

**Comment by mit-mit** [comment]
It does, yes!!
