### ISSUE TITLE
"More" and "top" should be explained as definitions

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub-dartlang-dart#637]
I don't understand what order I'm looking at here and how to obtain a higher ranking:

<img width="975" alt="screen shot 2017-11-22 at 7 15 40 pm" src="https://user-images.githubusercontent.com/168174/33157809-95d80ab0-cfb9-11e7-908f-9e86fd489e70.png">

**Comment by kevmoo** [comment]
@matanlurey – what page are you looking at here?

**Comment by kevmoo** [comment]
> @matanlurey – what page are you looking at here?

Ah! https://pub.dartlang.org/experimental/packages

**Comment by kevmoo** [comment]
This will get a lot cleaner once https://github.com/dart-lang/pub-dartlang-dart/issues/661 is complete

**Comment by kevmoo** [comment]
Added implementation details here: https://github.com/dart-lang/pub-dartlang-dart/issues/681 @isoos

**Comment by kevmoo** [comment]
Closed via https://github.com/dart-lang/pub-dartlang-dart/commit/2ab4de315dbb030b9b78692eeff659ba2bd3fb93
