### ISSUE TITLE
Package search list should be better sorted

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#64]
Search results don't seem to be sorted by any user focused metric. We should sort according to some usage metrics (e.g. downloads, stars, imports).

**Comment by mcmahonjohn** [comment]
I would include by author, recently updated, SDK version.

In fact, a lot can be learned from [npmjs.com's search options](https://www.npmjs.com/search?q=).

Though they don't have sorting and I would definitely recommend sorting as well as filtering options.

**Comment by kevmoo** [comment]
https://github.com/dart-lang/pana/blob/c0a64026bdd658601b2ba13147f3fe52f6abd47b/lib/src/scoring.dart#L65

Oh, I know. We're working on it 😄

**Comment by mcmahonjohn** [comment]
@kevmoo Stop worrying about releasing Dart 2.0 and do this! 😛

**Comment by kevmoo** [comment]
@mcmahonjohn – I'm spending more time on this than Dart 2, I promise 😄

**Comment by mcmahonjohn** [comment]
Understood. Thanks!

**Comment by isoos** [comment]
V2 design and overall ranking addresses this.
