### ISSUE TITLE
Remove package fastchemail

### ISSUE THREAD

**Issue by tredoe** [dart-lang/pub-dartlang-dart#65]
Please remove package [fastchemail](https://pub.dartlang.org/packages/fastchemail) since it has been renamed to [fast_chemail](https://pub.dartlang.org/packages/fast_chemail).

Thanks in advance!

**Comment by kevmoo** [comment]
@tredoe – in general, we don't remove packages unless they are fundamentally broken – or if they are VERY new.

Recommendation: publish fastchemail w/ v0.9.2+1 and be clear that it's no longer supported – and point folks to the new package

See https://pub.dartlang.org/packages/scheduled_test for an example

We do have plans to support marking packages as deprecated/unsupported. See https://github.com/dart-lang/pub-dartlang-dart/issues/289
