### ISSUE TITLE
Alphabetical index of packages

### ISSUE THREAD

**Issue by mehaase** [dart-lang/pub-dartlang-dart#66]
The [list of packages](https://pub.dartlang.org/packages) is sorted by updated date. It would be nice if there was an index of packages that is sorted alphabetically and indexed by first letter. E.g. if I want to browse all the ng_* packages, I could click on "N" and scroll down to the `ng_` items.

**Comment by isoos** [comment]
The search feature is available via putting `package:ng_` in the search query.

Soon we'll have sort not only by updated time, but also overall ranking, and maybe other values will be surfaced on the UI. At this point it is not hard at all to add alphabetical sorting, but unless a compelling reason comes up for it, I'd pass. The closest thing for it is dartdoc's package listing, but even that can be done in another way.
