### ISSUE TITLE
Cleanup platform details on landing and platform pages

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#661]
Discusses changes to 
- the landing page: https://pub.dartlang.org/experimental/
- the platform page: https://pub.dartlang.org/experimental/packages

Follow-up to https://github.com/dart-lang/pub-dartlang-dart/pull/660

- [x] Header in main content (both pages)
  - H2
  - color: gray
  - font-weight: 500
  - See image at bottom

- [x] Header in main content (both pages)
  - Add "pretty" hover-over behavior to explain these are all packages sorted by score.
  - With link to help page

- [x] Header on 'platform page' should match the header on the landing page.

- [x] Platform page: remove the "Learn more about using packages with Flutter." link. Duplicates content in the menu.

![screen shot 2017-11-28 at 2 27 00 pm](https://user-images.githubusercontent.com/17034/33348119-ea899fbc-d449-11e7-9b6e-3c88b8204317.png)

**Comment by isoos** [comment]
I was planning to put the same landing blurb on the platform pages (when there is no active search). WDYT?
