### ISSUE TITLE
pub's install tab is broken

### ISSUE THREAD

**Issue by Scorpiion** [dart-lang/pub-dartlang-dart#69]
Hi,

The "**1. Depend on it**" section (after clicking on "Installing") has stopped being rendered. I was just going to show a guy that it was an easy way to get a good default value to put in his `pubspec.yaml` file. He had put `stagexl:     ` without any version and `pub get` got stuck in an infinite loop...

Has this been removed on purpose or is it simply broken? I think it was a very good feature, would be great if it could be fixed!

Cheers, Robert

**Comment by kevmoo** [comment]
Hey @Scorpiion – for which package?

There may be some funking markdown escaping stuff that only breaks for certain packages. Would love to understand which...

**Comment by Scorpiion** [comment]
Hi Kevin, it's not just some package, it's every single package on pub as far as I know... :) To illustrate, let's take the [markdown package](https://pub.dartlang.org/packages/markdown) (on the "Installing" tab). 

This part:
```
dependencies:
  markdown: 
```

Used to look something like this:
```
dependencies:
  angular2: '0.11.2'
```

Or maybe like this:
```
dependencies:
  angular2: '^0.11.2'
```

Not sure exactly how pub determined what version/syntax, but right now it does not list any version at all and it can be very confusing for beginners.
