### ISSUE TITLE
Switching package type loses search term

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub-dartlang-dart#691]
https://pub.dartlang.org/experimental

The first thing on the page is a search box so it seems natural to type into it before clicking the package type buttons. If you do, and then click on (for example) Flutter, you end up losing your search term.

Clicking the search button first (or selecting package type before typing) works as expected, but I think it'd be nice if clicking the different types didn't lose your term (to be honest, I think it'd be better if it really was a client-side switch - that's how it looks - rather than navigating to other pages).

**Comment by kevmoo** [comment]
We'd have to turn button clicks on that page to update the content in-place instead of navigating. Agreed, it's annoying.

**Comment by isoos** [comment]
Content update in-place itself wouldn't solve the issue. As a first step we could catch the click event, and amend the URL with the search expression typed into the field.

**Comment by DanTup** [comment]
The new behaviour is much better, though it wasn't really what I expected. Clicking the buttons with no text in the box just reloads the same page with a different graphic but when there is text it performs the search. It feels slightly weird that it looks like a tab/switcher control but functions like a "do search" button (at least, when there's text).

It's possible my expectation is somewhat skewed by this multi-lang textbox we have in our product though..

<img width="465" alt="screen shot 2017-12-06 at 18 04 08" src="https://user-images.githubusercontent.com/1078012/33677223-f45a5efc-daaf-11e7-9f11-735ed7eb6176.png">

.. so don't feel you need to act on this, I'm just providing it as feedback :-)

**Comment by isoos** [comment]
>  Clicking the buttons with no text in the box just reloads the same page with a different graphic but when there is text it performs the search. 

@DanTup: could you make a screenshot of this. I suspect that the "Top X packages" headline and the list of packages is below the fold on your screen, can you confirm that?

@kevmoo: maybe this needs a refinement somehow?

**Comment by kevmoo** [comment]
> maybe this needs a refinement somehow?

Happy to discuss...

**Comment by DanTup** [comment]
Sorry if I wasn't clear. When I'm on a page without a search, eg:

https://pub.dartlang.org/flutter

If I just click on the "Web" button (for ex) without entering anything, it takes me to a page that looks the same, except is now filtered to Web:

https://pub.dartlang.org/web

(eg. it still shows the Top xxx packages).

However, if I type into the box and then click on one of those buttons, it performs the search. eg. if I type "test" in the box then click "Server" I end up here:

https://pub.dartlang.org/server/packages?q=test

I guess this is because the presence of the querystring results in the search being run, but my initial expectation was that I would just end up on the server page showing top packages but with the input box pre-filled.

I don't feel strongly about changing this, it was just unexpected. It also functioned as expected when I already have search results on the screen.

**Comment by isoos** [comment]
Ah, yeah. We have a conflicting requirement here: people also expect that when they type something in the search box and click on the 'server', then at minimum the typed text is not lost, and more often they expect that we execute the search on that query.

We can't have both, and I'd err on the side that when something was typed into the search box, we'll execute the search. Switching to the platform-specific landing page without executing the search would also look weird.

Does this explain the behavior?

**Comment by DanTup** [comment]
Yeah, I understood what was going on, it just wasn't what I expected - but as shown above - where I work we have a similar looking control that just switches client-side so my expectations where somewhat based on that.

I think the current behaviour is reasonable and don't really have any ideas to make it better.. except maybe make it faster...

Here, clicking a platform type (with no search term) results in 20 HTTP requests and 870ms. It feels a little slow for loading a page that's almost identical (I'm not sure why there are 20 requests or why some are so slow - eg. script.dart.js is 49KB, took 672ms and also nothing seems to be being cached).

**Comment by isoos** [comment]
Added an extra caching header, this switch between platforms should be smoother now.

**Comment by DanTup** [comment]
Looking much better; majority of requests served from cache :-)

On first load, there's still a nasty content shuffle caused by the images/logos not having width/heights so the page quickly collapses, then the content gets pushed down once the image loads. Once cached this doesn't happen though. If you can add width/height attributes without affecting any size-responsiveness, I think it'd improve the first visit experience :-)
