### ISSUE TITLE
Be clear which lint rules affect health

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub-dartlang-dart#692]
https://pub.dartlang.org/experimental/help#health

> **How can you improve your health score?**
> 
> Use strong-mode checks and some linter rules, and make sure you fix all the warnings and errors before publishing."

It's not clear from this description which lint rules contribute towards the health score. People will naturally want to make sure they're following all the rules that will result in higher listings, but turning them all on is probably overkill (and some are rather subjective).

**Comment by DanTup** [comment]
Also - that page has the URL of the lint rules page on it in the sample file, but no clickable-link!

**Comment by kevmoo** [comment]
The lints come from here: https://github.com/dart-lang/pana/blob/master/lib/src/analysis_options.dart

we should improve the link to this, agreed!

**Comment by DanTup** [comment]
Aha; I did see mention of `pana` though it's in the maintenance score section but not the health section.

**Comment by mit-mit** [comment]
Can we simplify this make it more concrete; for example:

**How can you improve your health score?**

For Flutter packages, run `flutter analyze` and resolve any errors or warnings shown.

For Dart packages, run `tbd` and ....

**Comment by isoos** [comment]
Update: with the latest pana 0.9.1 release:
- previous health penalties were moved to the maintenance score,
- code health is based only on `dartanalyzer`,
- `dartanalyzer` errors are displayed in the suggestions block,

Still missing:
- `dartanalyzer` warnings and hints are not displayed in the suggestions sections, (postponed after the platform update),
- updating health page.
