### ISSUE TITLE
Sorting of package versions could be more clear

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub-dartlang-dart#693]
https://pub.dartlang.org/experimental/packages/test/versions

This doesn't seem to be sorted as expected either by the date or the version:

<img width="873" alt="screen shot 2017-12-01 at 18 52 52" src="https://user-images.githubusercontent.com/1078012/33498360-f478823c-d6c8-11e7-834e-cc5e3a5fcac9.png">

**Comment by isoos** [comment]
This is the same as the old page: https://pub.dartlang.org/packages/test/versions
We are sorting the stable versions first in descending version order, then the dev versions. @mkustermann may be able to recall the original reason for it.

**Comment by DanTup** [comment]
Yeah, I thought it might've been old - I think it's confused me in the past but not sure if I ever understood it.

If the sorting isn't by version/date I think it'd be good to allow the user to sort by those and/or have some ability to see stable versus all releases.

**Comment by isoos** [comment]
As a first step, separating the versions and giving a separate header for the dev versions would do a lot to reduce confusion. I'm not sure if freeform sorting would add too much, maybe it would help a bit.

**Comment by DanTup** [comment]
Oh, I may have misunderstood thinking there were more than two groupings (from the screenshot I thought that stable/dev/rc/betas where all being individually grouped). If it's just stable in one list then all others in the other, then I'd agree that adding a heading is probably sufficient :-)

**Comment by kevmoo** [comment]
We had a few packages (angular, analyzer) where there were a LOT of alpha/beta releases making it hard to see what the last stable one was.

Brainstorm (not design): I think a better solution would be to show only stable releases, but have a checkbox to show/hide pre-release versions.
