### ISSUE TITLE
Add link to all packages by an author

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub-dartlang-dart#694]
https://pub.dartlang.org/experimental/packages/test/versions/0.12.2

This is more of a request for something new than just feedback, but it surprised me when I clicked "Dart Team" on that page that it was an email link. I think it'd be useful to have a link to a page for that author that lists all of their packages.

It's also slightly strange (ironic?) that the email addresses further down the page (which you might expect to be mailto links) are not clickable (it also seems a little strange to list email addresses with no names).

**Comment by isoos** [comment]
This is now done and deployed.

**Comment by DanTup** [comment]
LGTM! 👍
