### ISSUE TITLE
[experimental] weird search result 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#705]
![image](https://user-images.githubusercontent.com/405837/33572899-9eee4b8a-d934-11e7-946d-acb2e4d35a55.png)

- It doesn't look like it is sorted by relevance
- it's unclear how the results are related to my search term

**Comment by kevmoo** [comment]
@zoechi – in the future, use "send feedback" link at the bottom of the page. We'll capture the URL you hit.

(although in this case, I think we can figure it out)

**Comment by zoechi** [comment]
@kevmoo thanks for the hint, will do

**Comment by zoechi** [comment]
Big improvement overall!
Seems like it was a lot of work.
