### ISSUE TITLE
Search should index the entire readme.md content

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#706]
Searches don't seem to work for package readme.md files?

For example:
https://pub.dartlang.org/experimental/flutter/packages?q=sms

Doesn't include the most common way of sending SMS/text messages on Flutter:
https://pub.dartlang.org/experimental/packages/url_launcher

**Comment by kevmoo** [comment]
We only index the first ~100 characters from the readme.

https://github.com/dart-lang/pub-dartlang-dart/blob/8ae285f2b846b0e3bf1098162318f6c52eff5776/app/lib/search/text_utils.dart#L21

We need to move to better search infra to be able to handle big text searches.

**Comment by isoos** [comment]
I believe we can increase that limit. According my tests on staging, increasing the limit to 5k increased the memory use only ~10% (~45MB), which is something we can afford now.
