### ISSUE TITLE
Add structured data to site

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#708]
See https://search.google.com/structured-data/testing-tool#url=github.com%2Fdart-lang%2Ftest as an example

For packages, we could populate: http://schema.org/SoftwareSourceCode
A bunch of easy things here

For the main site:
https://search.google.com/structured-data/testing-tool#url=npms.io

Wiring up the search action - http://schema.org/SearchAction – would be goodness to give folks access to our search engine

**Comment by kevmoo** [comment]
@isoos per SearchAction – missing something https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fpub.dartlang.org%2F

**Comment by isoos** [comment]
While the Google Search page doesn't show the sitemap's searchbar yet, Chrome does use the autocompletion (type pub.dartlang.org and hit tab, it will switch to search mode and will use the `/packages?q=` url.
