### ISSUE TITLE
Packages which depend on NodeJS runtime are categorized under Web

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/pub-dartlang-dart#709]
URL: https://pub.dartlang.org/experimental/packages/node_interop

This package can not be used in a Web browser so current classification is a bit misleading.
It should really in the Server category.

**Comment by isoos** [comment]
To highlight what is happening: the project depends on `dart:js` and `dart:js_util`, all of which are designed for the browser. We see that during analysis and classify it as "this is only for the web".

@pulyaevskiy: I haven't checked it, can this library be run in a normal Dart VM server app?

**Comment by pulyaevskiy** [comment]
@isoos 

This library defines bindings for Node-specific APIs (like IO and FS) so it can't even run in a browser, only in Node.

If the way categorization works is by checking dependencies then I'd suggest to look for dependency on [node_preamble](https://pub.dartlang.org/packages/node_preamble). The best I can think of at this point...

**Comment by mit-mit** [comment]
Discussion: Let's move ` dart:js` to the `other` category

**Comment by isoos** [comment]
We've replaced `server` with the `other` category, and expect to surface information about `dart:js` and Node.js in a different way.
