### ISSUE TITLE
periodic 503 Server error

### ISSUE THREAD

**Issue by patefacio** [dart-lang/pub-dartlang-dart#71]
I use pub to access documentation on packages. Periodically it hangs up. Then I try to go to pub and get:

-----------------------------------------------------------------------------------------------
Error: Server Error

The service you requested is not available yet.
Please try again in 30 seconds.

-----------------------------------------------------------------------------------------------

Natalie W. said it is issues with AppEngine. Kevin M requested me to open this and include http response headers. I hope this is what he wants:

-----------------------------------------------------------------------------------------------

Request URL:http://pub.dartlang.org/
Request Method:GET
Status Code:503 Service Unavailable
Remote Address:72.14.249.27:80
Response Headers
view source
Content-Length:302
Content-Type:text/html; charset=UTF-8
Date:Sat, 28 Jan 2017 03:04:17 GMT
Server:Google Frontend
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Cookie:_ga=GA1.2.1275874948.1465591297; __utmt=1; __utma=168521888.1457866598.1465573460.1485472865.1485572496.99; __utmb=168521888.1.10.1485572496; __utmc=168521888; __utmz=168521888.1484780674.95.35.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)
Host:pub.dartlang.org
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by mkustermann** [comment]
We have switched to a newer, hopefully more stable, AppEngine stack.

@patefacio Do you still see this issue?

**Comment by mkustermann** [comment]
Closing the issue for now. Please re-open if this happens again.
