### ISSUE TITLE
Page overflow on Chrome for Android

### ISSUE THREAD

**Issue by kirbyfan64** [dart-lang/pub-dartlang-dart#710]
URL: https://pub.dartlang.org/experimental/packages/vue2

The table listing the dependencies overflows without scrolling. Same thing for the navbar on the home page.

FWIW I'm using a Nexus 5. I guess the dev team just largely uses bigger phones?

**Comment by kevmoo** [comment]
Not a super-critical use case, but we'll take a look.

**Comment by kirbyfan64** [comment]
Off the top of my head, the table being too big should be fixable just using `overflow-x: auto` in the table's CSS.

**Comment by isoos** [comment]
@kirbyfan64: could you please specify a bit more what's wrong with the layout?

I'm using a Nexus 5, and the table looks ok to me. It is a bit wider and I needed to zoom out a bit, but otherwise not weird.

**Comment by kirbyfan64** [comment]
The table's too big, but nothing else adjusts, so you end up with this giant empty gap on the side:

![](https://s5.postimg.org/jb9uglprr/Screenshot_20171205-103410.png)
