### ISSUE TITLE
Indicators as to what to fix are too subtle

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/pub-dartlang-dart#711]
URL: https://pub.dartlang.org/experimental/packages/bot_test

In the analysis sections, the indicator that they can be hovered over is too subtle. Consider adding  a question mark in an icon next to them to.

**Comment by kevmoo** [comment]
@lukechurch – can you link to an example of the little '?' icons that you like?

**Comment by mit-mit** [comment]
Closing, we now have explicit suggestions under analysis
