### ISSUE TITLE
Feature: Group packages by unique name/project

### ISSUE THREAD

**Issue by supermuka** [dart-lang/pub-dartlang-dart#715]
Just a suggest. I think that would be interesting agroup packages related into a unique group name/project. Could be easier to find all packages related and understand the purpose as a whole.

Example:

Group name/project: Shelf
Packages related: shelf, shelf_auth, shelf_route, etc.

Group name/project: Angular
Packages related: angular, angular_components, angular_form, etc.

**Comment by mit-mit** [comment]
Closing as a duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/367
