### ISSUE TITLE
Markdown hyperlinks with newlines don't render correctly on pub.dartlang.org

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub-dartlang-dart#72]
I don't know if you'd consider this a bug or not, but on this page:

https://pub.dartlang.org/packages/built_value

The links to examples aren't rendering correctly

![examples](https://cloud.githubusercontent.com/assets/1078012/22863605/396294c4-f13b-11e6-8a5d-d5cc039d770d.png)

The source file in https://github.com/google/built_value.dart seems to have newlines between the link text in square brackets and the url in parens.

I raised https://github.com/google/built_value.dart/issues/117 over there in case @davidmorgan wants to update the readme; but since it renders correctly on GitHub I think it would be best if dartlang worked the same (otherwise there will just be lots of broken docs because people don't check the pub website).

**Comment by isoos** [comment]
I think this is not a bug, the behavior is consistent across different markdown implementations (and pub is not doing anything special about it):

- `[label](link)` renders as a correct [label with link](the-link)

- `[label]\n(link)` (note the newline) renders a [label] (link)

- `[label]\n(http://url-like.link/)` renders as [label] (http://url-like.link/)

This issue should be closed.

**Comment by davidmorgan** [comment]
Agreed. Fixed the links now. (I guess pub.dartlang.org will update when I publish the package.)

**Comment by DanTup** [comment]
Yeah, I can't repro on GH now so I'm not sure why I believed they rendered correctly when posting this. I agree, doesn't seem there's anything to do here so closing.
