### ISSUE TITLE
Show package dependencies on package details

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#721]
This is a request to show all packages that a package depends on under package details. I.e., something like this:

**Uploader**
zarah@google.com
goderbauer@google.com

**License**
unknown (LICENSE)

**Dependencies**
[flutter](https://pub.dartlang.org/experimental/packages/flutter), [url_launcher](https://pub.dartlang.org/experimental/packages/url_launcher) 

**More**

**Comment by mit-mit** [comment]
Yup, only the direct ones.

**Comment by kevmoo** [comment]
It'll be tough to pick "good ones" here. I'd like to avoid too much noise in the sidebar.

**Comment by mit-mit** [comment]
I don't think we should be "picking", we should be showing them all. If there are too many and it becomes noise, just show the first x characters and then add a 'more' link to expand the list.

**Comment by kevmoo** [comment]
@mit-mit – what's wrong w/ the details in the analysis tab?

I'd like to keep the sidebar ~clean.

**Comment by isoos** [comment]
The way I think of it, the sidebar is a nicely formatted pubspec.yaml, and the direct dependencies may have place there. The analysis has much more (dev and transitive deps, constraint, resolution)...

**Comment by mit-mit** [comment]
@kevmoo I think knowing the dependencies is a key piece of information to a consumer of a package. A consumer needs to understand the license, health, completeness, etc. not just of the package they are consuming directly, but also those same characteristics of it's dependencies. That's why I think it's important to put them "front and center"
