### ISSUE TITLE
Please add touch support

### ISSUE THREAD

**Issue by jolleekin** [dart-lang/pub-dartlang-dart#725]
URL: https://pub.dartlang.org/experimental/web/packages

1. Add touch support
    The new site doesn't support touch well. For example, I cannot tap the top two dropdown menus.

2. More sort options
    It would be nice to add _sort by updated date_ to improve package discoverability.

**Comment by kevmoo** [comment]
Sort options is covered here: https://github.com/dart-lang/pub-dartlang-dart/issues/693

**Comment by isoos** [comment]
We've added both and it is not deployed. Please open new issues if the touch support is not working on your device.
