### ISSUE TITLE
Graph of package score over time

### ISSUE THREAD

**Issue by robbecker-wf** [dart-lang/pub-dartlang-dart#727]
# Idea
I like that pub shows a package score, but it only shows the score for the latest version. As a convenience to maintainers and for additional information for consumers, I'd like to see a graph of a package's score over time as it changes. 

As a bonus, pub could also include a badge (up or down arrow for instance) on the top level score if the score is trending up or down since the previous release.

**Comment by isoos** [comment]
We've discussed this previously, and there are fundamental issues with that. Let me explain in details:

The package's **health** score is affected not only the package itself, but its dependencies (1), the SDK we are running the analysis on (2), and the latest set of rules and adjustments we are making in the weighting (3).

- (1): e.g. dependency ranges maybe too broad, and a new release breaks the package
- (2): e.g. a new SDK release changes language rules or de- or re-classifies something from/to an error
- (3): e.g. we see that we are too harsh on something and give it less penalty

With that, you cannot really compare even the health scores for `package/1.0.0` a year ago and `package/2.0.0` right now. We could store such scores, but it would be misleading in too many ways, and would not really represent neither progress, nor regression.

The **maintenance** score is also bound to dependencies, but it is also affected by the release date of the latest stable version. If that was more than a year ago, we degrade that score.

And I have no idea how we would compare **popularity** and what it would mean.

All of these  contribute to the **overall score**, at that given time.

While we could track and display the history of all, I couldn't assign any meaningful conclusion in their trend, and I believe it would mislead visitors looking at a package. I'd rather stick with the ever-green approach, which is: this is the assessment of the package right now. Does that make sense?

**Comment by robbecker-wf** [comment]
Thanks for the detailed explanation of why that wouldn't be easy or very helpful. You've convinced me.
