### ISSUE TITLE
Resetting main filter to ALL does not work on landing page

### ISSUE THREAD

**Issue by mravn-google** [dart-lang/pub-dartlang-dart#736]
URL: https://20171206t105357-dot-dartlang-pub.appspot.com/server

Click FLUTTER (page updates)
Click ALL (nothing appears to happen)

Once I enter a search term, things appear to work.

**Comment by kevmoo** [comment]
Great catch, @mravn-google !

**Comment by kevmoo** [comment]
Still not fixed...investigating...

**Comment by kevmoo** [comment]
Caching issue. It is fixed.
