### ISSUE TITLE
[gde review] platform buttons flow outside page and cause scrolling on mobile

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub-dartlang-dart#738]
On my mobile (Moto X Play, Chrome) the platform buttons are slightly wider than fit, so they cause horizontal scrolling and fall out of the container slightly.

**Comment by DanTup** [comment]
I'll attach a screenshot when I can figure out how to do from mobile ...

**Comment by DanTup** [comment]
![screenshot_20171206-202115](https://user-images.githubusercontent.com/1078012/33683620-63f9af0c-dac3-11e7-8c89-7e2db9e60ce7.png)

**Comment by mit-mit** [comment]
Design discussion: just allow these buttons to line break

**Comment by DanTup** [comment]
If the size of my devices is fairly common, maybe it's also worth shaving a few px off the left/right padding inside the buttons (it wouldn't take much) to avoid the wrap (I think it should still wrap, but this may reduce the number of people seeing it wrapped).

If my device is narrower than most typical these days (it's over two years old) then it might not be worth the effort!

**Comment by mit-mit** [comment]
Yes, the platform button padding does seem a bit excessive in the mobile view.

**Comment by DanTup** [comment]
Slight tangent (and nit-picking) but "Top Flutter Packages" could probably be unwrapped and the "sort" text underneath it here.

I don't know if optimising for mobile is a priority though, possibly it's not a common way to browse the pub site!

**Comment by DanTup** [comment]
The wrap works, but it looks a bit weird because of the contains border that used to sit against the buttons:

![screenshot_20180119-150427](https://user-images.githubusercontent.com/1078012/35156915-3a2e9c6c-fd2a-11e7-9684-39d69c169a95.png)
