### ISSUE TITLE
Copy edit needed

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub-dartlang-dart#739]
URL: https://pub.dartlang.org/help

This page and others need a bit of a copy edit. I'd be happy to do it.

**Comment by kevmoo** [comment]
@kwalrath – pull requests welcome! https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/views/v2/help.mustache

**Comment by kwalrath** [comment]
Working on it now...

**Comment by isoos** [comment]
The change was merged and deployed.
