### ISSUE TITLE
Title for the Flutter landing page does not mention Flutter

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#742]
Going to pub.dartlang.org/flutter has a title of "Pub: Dart Package Manager"

Maybe instead: "Packages for Flutter: Homepage" or similar?

**Comment by sethladd** [comment]
This is important because when you share the URL via social media, sites like twitter and G+ grab the title, and use the title.

**Comment by isoos** [comment]
I've prepared a PR with "Packages for Flutter", because I like the shorter version better, but it is easy to add the "Homepage" part too if you'd prefer that.

**Comment by sethladd** [comment]
works for me! thanks for the fast response.

**Comment by isoos** [comment]
This has been deployed, the title is "Flutter Packages"
