### ISSUE TITLE
404 page has different template

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub-dartlang-dart#747]
URL: https://pub.dartlang.org/blah

The header and footer of the 404 page have a different format from those in the other site pages. Two differences I especially noticed:

* There's no "Report an issue" link in the footer.
* Clicking the Dart logo in the header takes you to www.dartlang.org, instead of pub.dartlang.org.

**Comment by isoos** [comment]
Fixed in #743 and #744, awaiting deploy.
