### ISSUE TITLE
Copy editing suggestion for analysis tab

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#751]
URL: https://pub.dartlang.org/packages/share

On the analysis tab, it current says "We are analyzing each uploaded package and provide its scores, details and our suggestions here."

which implies that _right now_, the server is analyzing.

I'm not a copy editor, but I think it's more accurate (and shorter) to say: "We analyzed this package, and provided a score, details, and suggestions below."

I think we can also remove "You can see the overall score in a colored circle, and the results below." and it's redundant with "provided a score, details, and suggestions below"

**Comment by sethladd** [comment]
Is this something I can provide a PR for?

**Comment by kevmoo** [comment]
Have at it! https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/views/pkg/analysis_tab.mustache
