### ISSUE TITLE
Unclear what "pubspec reference with no conflicts" means on analysis tab

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#752]
URL: https://pub.dartlang.org/packages/share (the analysis tab)

I see "pubspec reference with no conflicts", which I guess is good :) but unclear what this means.

If everything is "good", then I might suggest just saying "no issues detected", or, don't say anything at all.

**Comment by isoos** [comment]
The new `pana` emits better messages.
