### ISSUE TITLE
Show Installs and Downloads stats in analysis-tab (or any other place)

### ISSUE THREAD

**Issue by yeradis** [dart-lang/pub-dartlang-dart#757]
The Overall score is nice, but to help in the decision process would be nice to also have the Installs and Downloads number visible, like for example Cocoapods:

<img width="769" alt="screen shot 2017-12-07 at 07 08 48" src="https://user-images.githubusercontent.com/666944/33701492-4270c22e-db1f-11e7-8ff0-c8cc54d76b78.png">

**Comment by isoos** [comment]
Install and download counts are easily swayed by a continuous integration framework that installs and downloads all of the packages on each new commit. We compensate against those in the popularity score, and I think it provides a better metric, than the raw counts.

**Comment by escamoteur** [comment]
@isoos I disagree. The Nuget package system of .net shows download counts and its a great help for package authors to see if the package is in constant use. For package authors its an important metric. even if it's not exact.

**Comment by mit-mit** [comment]
We've reconsidered this, and are looking into options for supporting this. The current tracking issue is https://github.com/dart-lang/pub-dev/issues/2714.
