### ISSUE TITLE
Add more Sort options(like latest updated) not only sorted by overall score

### ISSUE THREAD

**Issue by yeradis** [dart-lang/pub-dartlang-dart#758]
Rigth now there is only one and fixed sort option: sort by overall score
Making "imposible" to sort by latest updated

The only option rigth now is to do a manual access like: https://pub.dartlang.org/packages?sort=updated

Adding more options  should also include the Ascending and Descending options

So we can have something like , for example github issues options:

<img width="360" alt="screen shot 2017-12-07 at 07 26 06" src="https://user-images.githubusercontent.com/666944/33701780-a4248644-db20-11e7-98a0-06a29c9be7e6.png">

pd: this one can be considered related with #724

**Comment by zoechi** [comment]
💯  for "recently updated" (order by date)

**Comment by isoos** [comment]
This is a duplicate of #635, we will have something like that.
