### ISSUE TITLE
How to filter flutter only packages in the new UI?

### ISSUE THREAD

**Issue by sgon00** [dart-lang/pub-dartlang-dart#764]
URL: https://pub.dartlang.org/flutter/packages

I find out the webpage was updated in recent two days. The new UI is pretty cool. I just have one question what if I want to filter and check flutter only packages? Is there a way to achieve that?

I remembered it was like 7 or 8 pages of flutter packages in the old days, but with the new UI now, nearly all packages will have the `Flutter` tag. I know the packages worked in the web and server will also work in flutter. But I just want to check a list of flutter only packages so that I can understand what flutter can provide now, for example: camera, bluetooth access, sqlite, shared references etc.. They are related to flutter only. 

Thanks a lot.

**Comment by isoos** [comment]
At the moment that feature is not on the UI, but we are planning to add a checkbox for 'Flutter-only' searches.

Until then: do you have a specific search where the ranking on the search gives you unrelated packages? Right now, if you search under `/flutter/packages`, the results should be heavily biased towards Flutter-only, and relevant packages should go to the top of the list.

**Comment by sgon00** [comment]
@isoos thanks a lot for your reply. I don't have a specific search. I am new to flutter and would like to see a list of all flutter-only packages so that I can understand what flutter can provide (flutter supported features).
 
For example, I read 7 pages (https://pub.dartlang.org/flutter/packages?page=7) and understand that flutter supports image_picker (camera access), shared_preferences, sqlite, path_provider, bluetooth, location (gps) etc... Some are from official flutter team and some are from the community. For contact access, it only has a contact picker package which uses system's contact UI so I can not access all the contacts directly in flutter so far. To go through all the flutter-only packages is the way I can understand the flutter's supported features. I am not sure if I am the first person who does this kind of stupid lookup.

So I am not doing any search here and just want to get a list of all flutter-only packages. I am looking forward to seeing `Flutter-only` tag on the UI. 

Thank you very much.

**Comment by mit-mit** [comment]
Actually, you can just search for packages that depend on flutter:
https://pub.dartlang.org/packages?q=dependency%3Aflutter

@sgon00 does that satisfy what you are looking for. If so, we could consider making that more discoverable.

**Comment by mit-mit** [comment]
Design idea: Just add another link at the bottom of the Flutter landing page ('All Flutter-specific packages...') next to 'All Flutter packages'.
