### ISSUE TITLE
Create some model to selectively skip memcache

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#768]
So we can validate a deployment...

**Comment by isoos** [comment]
An idea: let's put the `reqestedUri.host` inside the cache key, we'll have a nice separation between the live site and some deploy candidate. Cache invalidations won't work across instances, but actions on the live site will trigger invalidations on the live site, and I think that covers most of our worries.

**Comment by kevmoo** [comment]
Or just do that if the host != `pub.dartlang.org`

Then all invalidations will affect only the "production" key.

...right?
