### ISSUE TITLE
If maintenance is < 100, there should be a reason given

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#771]
https://pub.dartlang.org/packages/pana#-analysis-tab- : pre-v1 is the only thing that I can see.

Let's get rid of any guessing here.

**Comment by kevmoo** [comment]
@isoos – I think this is a lot better now, right?

**Comment by isoos** [comment]
Yeah, it still has a lot of room for improvements, but maybe we can tick this box?
