### ISSUE TITLE
[analysis] Update scores more regularly

### ISSUE THREAD

**Issue by brianegan** [dart-lang/pub-dartlang-dart#779]
URL: https://pub.dartlang.org/packages/chewie#-analysis-tab-

Last calculations were run on December 6th (today is December 11th). Would be cool to see how package popularity changes over time after shipping something new!

**Comment by kevmoo** [comment]
Just updated! You have some popularity!

**Comment by isoos** [comment]
Generic auto-update tracking in #300, closing the issue for now.

**Comment by brianegan** [comment]
Thanks all!
