### ISSUE TITLE
Update readme for current flex environment directions

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#78]
Needed so we folks can help us with the site

Include info on the Docker file, running tests, etc

It'd also be nice to understand how to test against dev/test (non-production) services

**Comment by mkustermann** [comment]
I have updated the readme file with instructions about: running locally with/without docker, running tests, deploying and using custom packages (though first a [cleanup cl](https://codereview.chromium.org/2772053002/) needs to land).

Once we have a staging project we can adjust the instructions to describe how to run there.
