### ISSUE TITLE
Explain the interaction between PannerRunner.hasCompletedRecently and AnalysisBackend.isValidTarget

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#785]
I just updated https://pub.dartlang.org/packages/bot_io which is used by https://pub.dartlang.org/packages/hop

I'd assume that updating bot_io would start another analysis of hop – but the log just lists a bunch of 'skips'.

Maybe `isValidTarget` could log more?
Maybe it could return something "richer" than `bool` – something `PannerRunner.hasCompletedRecently` could use to log it's decision.

etc etc

**Comment by isoos** [comment]
I haven't found much in the logs, but opened #796 for more logging.

**Comment by kevmoo** [comment]
Closed by https://github.com/dart-lang/pub-dartlang-dart/commit/156e66c4f1bcdcb2c604d9455de6fe2165836b2d
