### ISSUE TITLE
Better indication when a task is aborted

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#786]
See https://pub.dartlang.org/packages/stream/versions/0.7.3+1#-analysis-tab-
and https://analyzer-dot-dartlang-pub.appspot.com/packages/stream/0.7.3+1

Status is still 'awaiting' on the site...

**Comment by kevmoo** [comment]
@isoos – thoughts on this?

**Comment by isoos** [comment]
agreed :)
