### ISSUE TITLE
Brand new high-quality package has low score

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#787]
URL: https://pub.dartlang.org/packages/side_header_list_view#-analysis-tab-

side_header_list_view seems like a great package, with high health and maintenance scores. However, it's brand new so it's popularity is zero. Unfortunately, that brings its overall score to under 50 :(

I wonder if there's a difference between popularity and health, and if so, if that difference is especially important for brand-new packages.

Suggestion: Accommodate "newness" in the popularity score or overall score, and don't penalize brand new packages in their overall score.

The older the package is, the more important popularity is. The newer the package, the less important popularity is.

**Comment by isoos** [comment]
Boost its score, because it is new? I fail to see the provided value in that. It would gain a short term feel-good score for the author, but other than that, how should it help the users?

We already factor age into maintenance: we start to decrease that score if the last release is over a years old.

**Comment by matanlurey** [comment]
@sethladd how much of this is just due to not being able to see "new" packages on the front page?

**Comment by sethladd** [comment]
A score of 45 for this package sounds like "crappy package". But, it's a useful, high-quality package that's simply new. I don't think it warrants a low score of 45 in this case, because it's brand new.

I'm not worried about making the author feel good, I'm worried about giving a misleading message to our developers. I think we need a clearer way to say "this package is new and it's high quality so go ahead and give it a shot".

@matanlurey I think it's unrelated. People find packages in many ways (social media, searching) and often bypass the homepage.

**Comment by matanlurey** [comment]
FWIW, I agree then. Maybe popularity shouldn't matter for packages < [%AGE].

**Comment by isoos** [comment]
What's the difference from the end-user perspective between these?
- `Package A`: health: 98, maintenance: 75, popularity: 0, overall: 45, *published 1 week ago*.
- `Package B`: health: 98, maintenance: 75, popularity: 0, overall: 45, *published 2 months ago*.
- `Package C`: health: 98, maintenance: 75, popularity: 0, overall: 45, *published 10 months ago*.

In either case: nobody is using the package, for whatever reason e.g. nobody has found it yet or it doesn't provide enough value.

I could publish a short dart file as a package, it will get 100 health, 100 maintenance. Should we display it as 100, in the same league as `angular` or other really popular packages?

I think as people get used to the numbers, the calibration will happen automatically, and 45 will be considered as good. Not as stellar as angular's 100, but good. We help with color coding.

We could add labels or an additional little icon for fresh packages, but I think that will be more like a distraction than useful. But unless we can uniformly say about the new packages's provided value, I wouldn't inflate the scores.

**Comment by kevmoo** [comment]
I think this is heavily related to https://github.com/dart-lang/pub-dartlang-dart/issues/300

We need to get a system in place where popularity is regularly updated.

**Comment by sethladd** [comment]
> What's the difference from the end-user perspective between these?

Package A might be amazing, but it appears as mediocre as Package C. That's misleading.

> I wouldn't inflate the scores

Ack. That was just a proposed solution.

Restating the problem: A brand-new package, which followed all the rules and is otherwise healthy and quality, has a low score simply because it's new. This may impede a user from choosing this package, if they don't know how to drill into a score and determine "oh, it's just because it's new"

Another proposed solution would be to add a visual hint/indicator next to the score, indicating that the package is "new".

**Comment by isoos** [comment]
> Package A might be amazing, but it appears as mediocre as Package C. That's misleading.

I think this is a wrong notion right now, which may fade later.

> Another proposed solution would be to add a visual hint/indicator next to the score, indicating that the package is "new".

Any suggestion on what the indicator should look like?

**Comment by sethladd** [comment]
I am not a designer, but maybe a "sunburst" around the score? Like rays coming out of the circle.

Something like this, but actually good:

![screen shot 2017-12-12 at 3 22 16 pm](https://user-images.githubusercontent.com/5479/33913851-6253bc74-df50-11e7-8182-2da71e053f6b.png)

**Comment by isoos** [comment]
After a bit of experimenting, I am working towards this:

<img width="58" alt="screen shot 2017-12-13 at 3 19 09 pm" src="https://user-images.githubusercontent.com/4778111/33943420-575d3d58-e019-11e7-9230-08bc6fb2c00b.png">

What do you think @sethladd, @kevmoo, @matanlurey ?

**Comment by sethladd** [comment]
Thanks! But it's really tiny. I can barely read that word. :/

**Comment by isoos** [comment]
How about this one?

<img width="53" alt="screen shot 2017-12-13 at 10 14 24 pm" src="https://user-images.githubusercontent.com/4778111/33962768-e86292b0-e052-11e7-8486-d281b9e5c486.png">

I think the question is really: is this something we can make work (by tuning the style) or it is the wrong line of design?

**Comment by sethladd** [comment]
that's easier to read, and is sufficient for testing! :) thank you!
