### ISSUE TITLE
Title of package page says "Instance of 'Package' 1.1.0"

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#8]
Compare path

https://dartlang-pub.appspot.com/packages/path - `path 1.3.5 | Pub Package Manager`

https://buildbot-dart-2015-04-21-dot-dartlang-pub.appspot.com/packages/path - `Instance of 'Package' 1.1.0`

**Comment by sgjesse** [comment]
Fixed in dc471ab21d340a65efc6b0a95c302275a9867bff.
