### ISSUE TITLE
Cannot run outside docker: "GrpcNetworkException: Endpoint https://datastore.googleapis.com does not support http/2 via ALPN"

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#80]
Dart VM version: 1.23.0-dev.10.0
Repo at 4bdb68eb7e9ed1eff52402e2d525cf658e9b9318

```
GrpcNetworkException: Endpoint https://datastore.googleapis.com does not support http/2 via ALPN
#0      Client.invoke (package:appengine/src/grpc_api_impl/grpc.dart:113:21)
<asynchronous suspension>
#1      Channel.invoke (package:appengine/src/grpc_api_impl/grpc.dart:45:19)
<asynchronous suspension>
#2      DatastoreApi.lookup (package:appengine/src/grpc_api/dart/google/datastore/v1/datastore.pb.dart:576:20)
#3      GrpcDatastoreImpl.lookup (package:appengine/src/grpc_api_impl/datastore_impl.dart:142:32)
<asynchronous suspension>
#4      _lookupHelper (package:gcloud/src/db/db.dart:408:23)
#5      DatastoreDB.lookup (package:gcloud/src/db/db.dart:342:12)
#6      cloudStorageKeyFromDB (package:pub_dartlang_org/keys.dart:19:33)
<asynchronous suspension>
#7      setupServices (file:///Users/kevmoo/source/github/pub-dartlang-dart/app/bin/server.dart:79:33)
<asynchronous suspension>
#8      main.<anonymous closure>.<anonymous closure> (file:///Users/kevmoo/source/github/pub-dartlang-dart/app/bin/server.dart:35:46)
<asynchronous suspension>
#9      _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:207:19)
#10     _rootRun (dart:async/zone.dart:1120)
#11     _CustomZone.run (dart:async/zone.dart:1001)
#12     runZoned (dart:async/zone.dart:1465)
#13     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
#14     fork (package:gcloud/service_scope.dart:103:30)
#15     main.<anonymous closure> (file:///Users/kevmoo/source/github/pub-dartlang-dart/app/bin/server.dart:34:12)
<
```

**Comment by mkustermann** [comment]
Just guessing: You are running on MacOS? The DartVM does not support ALPN on MacOS to the best of my knowledge.

Since this appears not to be an issue of the pub server app (and neither of `package:appengine`) I'll close this issue.

Try using linux!

**Comment by kevmoo** [comment]
If we want folks sending us pull requests and helping, we can/could/should be more helpful

It'd be easy to check for this error and check for Mac and stderr.out something helpful here

**Comment by mkustermann** [comment]
The exception comes from `package:appengine`, so if we want to change the exception message at all, then that's where the issue should move to.

But generally speaking it would be much more beneficial adding `dart:io` support for ALPN on MacOS **again** (when I've [implemented ALPN](https://codereview.chromium.org//625953002) it worked on mac IIRC, seems like the switch to different SSL implementations by others broke it (the alpn test functionality is now skipped on mac)).

**Comment by kevmoo** [comment]
Maybe update the readme about running w/ docker – that you can only do it on Linux – and include the link to the bug about enabling ALPN on mac?

**Comment by anders-sandholm** [comment]
@zanderso - just wondering what it would take to get back ALPN support on Mac?

For now, this is blocking us from running AppEngine Flex locally on Mac. But generally, it'll be a blocker for getting http2/gRPC to work on Macs.

My understanding from talking to Martin is that the [replacement](https://codereview.chromium.org/1721283002/) of Boring SSL with Apple's Secure Transport API means there is no official support for ALPN on Mac. Can we get unofficial support? Can we use Boring SSL? Other options? 

@kevmoo - can't find the bug about enabling ALPN on mac. Do you have the number? We should file one if it isn't there already.

**Comment by zanderso** [comment]
AFAIK, there is no support, neither official nor unofficial, for ALPN in the SecureTransport API.

Unfortunately, we can't simply switch back to BoringSSL on MacOS. Due to security concerns, we have a hard requirement from Fuchsia not to use the compiled-in trusted root certificates that we use on e.g. Windows (which we shouldn't be using there either). When evaluating the switch to SecureTransport, it wasn't clear to me that there was any way to use the MacOS system keychain certs with BoringSSL. It looked like the only way to get at them was through the SecureTransport API. Hence the need to switch.

Having said that though, I would like to understand the severity of this issue a bit better. Is this impacting a core piece of functionality of pub, or is this just an optimization? Why can't MacOS fall back on a normal https connection. Which customer is this issue affecting?

**Comment by mkustermann** [comment]
@kevmoo I've sent Istvan a [CL](https://codereview.chromium.org/2780373003) he can patch in to work around this issue on MacOS (switches from gRPC -> json based api).

**Comment by mkustermann** [comment]
Closing this issue. The workaround for mac has landed for this particular app (though its of course still an issue for others).
