### ISSUE TITLE
More logging in service handlers

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dartlang-dart#801]
![image](https://user-images.githubusercontent.com/405837/34036282-fc8a8044-e184-11e7-9e93-1cfa29a792e7.png)

**Comment by zoechi** [comment]
up again

**Comment by isoos** [comment]
I was able to catch part of it. Looks like it lasted from 09:41:18 to 09:47:33 UTC.

- The frontend was not able to reach the `search` service with `Exception: Service returned status code 502`.
- There is nothing in the `search` logs to indicate an error. (Related but we don't seem to log the requested URLs.)
- Appengine restarted at least one `search` instance around 09:47:20 UTC, which eventually resolved the issue.

**Comment by isoos** [comment]
(re-using the issue for tracking the logging of requests)
