### ISSUE TITLE
Update pana to 0.8.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#809]
Do we have to be careful about how we deploy to handle different contents in the analysis output?

**Comment by isoos** [comment]
> Do we have to be careful about how we deploy to handle different contents in the analysis output?

Only [this](https://github.com/dart-lang/pub-dartlang-dart/blob/master/README.md#version-upgrade-with-breaking-changes-pana).

**Comment by kevmoo** [comment]
Yay for docs!

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/pub-dartlang-dart/commit/509327e703e7e029f1f4132a0ebcd59a60b344f9
