### ISSUE TITLE
flutter_iap (exact package match) doesn't show up in the first page of results

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#813]
URL: https://pub.dartlang.org/packages?q=flutter_iap&page=1

Maybe we need to put in a bit more weight to exact package matches?

**Comment by isoos** [comment]
The root cause here is the underscore: we treat it as it were space, which is beneficial in many cases, but not this one. Should be easy to fix though...

**Comment by isoos** [comment]
^ The other way around: the bug was we didn't treat the underscore as space at the time of search, only at the time of indexing.
