### ISSUE TITLE
Can't filter recently updated or recently created package lists

### ISSUE THREAD

**Issue by MarkOSullivan94** [dart-lang/pub-dartlang-dart#817]
URL: https://pub.dartlang.org/packages?sort=updated or https://pub.dartlang.org/packages?sort=created

If you go to either of the above URLs and type in something to filter the recently updated list, the list doesn't update. 

Edit: Seems to be happening with recently created filter too.

**Comment by isoos** [comment]
Good catch, thanks for reporting it!

**Comment by MarkOSullivan94** [comment]
@isoos noticed it's also happening on the recently created filtered list as well
