### ISSUE TITLE
Do much less analysis for historical package versions

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#828]
Wasting so much CPU for very little gain. It also means we have to wait around to deploy.

An idea:

If
* no popularity data for package (no use in last ~60 days)
* and last publish was > 2 years ago

then
* Only analyze the last published version

Reasonable? @isoos @mit-mit @mkustermann ?

**Comment by isoos** [comment]
>  It also means we have to wait around to deploy.

- No need for wait in case we don't have breaking changes.
- No need for wait for everything (only the latest versions) if the breaking changes are subtle.
- Only big breaking changes require full wait, but those are rare so far.

> If [...] then ... Only analyze the last published version

I'd remove the popularity requirement. Even if the package is popular, is there a need to analyze http/0.11.0, published on May 5, 2014?

**Comment by kevmoo** [comment]
> I'd remove the popularity requirement. Even if the package is popular, is there a need to analyze http/0.11.0, published on May 5, 2014?

Sure. Only analyze last published for versions > Jan 1, 2016?

Then we can just put a note on the analysis tab for everything else – saying it was skipped because it was old...

**Comment by isoos** [comment]
> Only analyze last published for versions > Jan 1, 2016?

I'd keep it consistent with the maintenance score: if it is older than 2 years: maintenance score = 0, no analysis (only if it is the latest stable).

**Comment by kevmoo** [comment]
Sure...
