### ISSUE TITLE
Separate homepage and repository fields for a package

### ISSUE THREAD

**Issue by tejainece** [dart-lang/pub-dartlang-dart#842]
Right now, Dart only supports specifying homepage field.

Right now, people are using their homepage URL in that field. This makes it harder to reach the actual project repository.

Would be nice if this homepage field is split into two:

+ Repository
+ Homepage

Here is an example of one of my projects:

![image](https://user-images.githubusercontent.com/2513673/34222521-21d0616c-e5bc-11e7-8d17-9230c17ff009.png)

I would like to have:

+ Repository: https://github.com/Jaguar-dart/jaguar
+ Homepage: https://jaguar-dart.github.io/

**Comment by isoos** [comment]
@kevmoo @mkustermann

**Comment by kevmoo** [comment]
Interesting idea!

**Comment by xqwzts** [comment]
Fortuitous timing, I was trying to see how one might implement links to source files in dartdoc [for https://github.com/dart-lang/dartdoc/issues/73], this would definitely help.

**Comment by kevmoo** [comment]
Nice! We'd want to align w/ the right commit, etc etc.

We'll take small steps...

**Comment by isoos** [comment]
Closing this, as the use case is considered too rare.

My personal suggestion is that you fill the `homepage:` field with the github repo URL, and in the settings of that repo you can add the URL of the "traditional" homepage.
