### ISSUE TITLE
How to handle README/CHANGELOG files w/ relative links

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#850]
See https://pub.dartlang.org/packages/video_player/versions/0.0.7

Works great here: https://github.com/flutter/plugins/blob/8f8d0ae1d6d026bb287ceb14770c263a4ec20b8a/packages/video_player/README.md

Because this link is relative to assets on github
```markdown
![The example app running in iOS](doc/demo_ipod.gif)
```

Solution ideas:

1. Warn in pana if README/CHANGELOG items use relative links – encourage absolute links
2. Get clever about the homepage URL and try to figure out the best thing?

**Comment by isoos** [comment]
On github, the relative link requires a blob/master path part.
Example: https://pub.dartlang.org/packages/leveldb/versions/5.0.0 look for the example/main.dart reference.

(closing https://github.com/dart-lang/pub-dartlang-dart/issues/537)

**Comment by isoos** [comment]
I think warning is not enough, we shall be smart about URLs. Maybe the split of `homepage` and `repository` URL in pubspec would help this?

**Comment by isoos** [comment]
Part of this is now handled with the pana 0.9 upgrade, but we don't rewrite the urls of the images yet.
