### ISSUE TITLE
Undetected license

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#862]
https://pub.dartlang.org/packages/uuid has an 'unknown' license. However, github is able to detect it as MIT: https://github.com/Daegalus/dart-uuid/blob/master/LICENSE.

Are we not using the same detection algorithm?

cc @isoos

**Comment by isoos** [comment]
Closing this, instead tracking it on `pana`: https://github.com/dart-lang/pana/issues/200

> Are we not using the same detection algorithm?

We are using our own code to detect the license. I'd like to merge that with flutter's license detection, but it was not a priority yet.
