### ISSUE TITLE
Plugin published under my name.

### ISSUE THREAD

**Issue by theobouwman** [dart-lang/pub-dartlang-dart#867]
URL: https://pub.dartlang.org/packages/jaguar_http

I got notified by the owner of the Github repo the plugin was published under my email.
Since I did not published it myself I'd like to hand the published plugin over to hadrien.lejard@gmail.com or be removed.

Thanks in advance.

**Comment by isoos** [comment]
@theobouwman: I'm a bit at loss here: the package in question has now hadrien.lejard@gmail.com as both author and uploader. (Or maybe somebody updated it and has not closed this issue. In that case, can we close it?)

**Comment by mit-mit** [comment]
Closing as it's not clear what the issue is.

**Comment by theobouwman** [comment]
Sorry, I created the issue before I discovered that I could change the owner.
