### ISSUE TITLE
Standardize on GitHub CSS – at least for markdown?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#871]
Github open sources there markdown CSS - https://github.com/primer/primer/tree/master/modules/primer-markdown

We could just use it?

Example

https://pub.dartlang.org/packages/flutter_blue
![screen shot 2018-01-03 at 2 55 51 pm](https://user-images.githubusercontent.com/17034/34543570-661e3efe-f096-11e7-8596-2d209253461d.png)

Github - https://github.com/pauldemarco/flutter_blue
![screen shot 2018-01-03 at 2 55 57 pm](https://user-images.githubusercontent.com/17034/34543578-6bb88734-f096-11e7-9323-a7736466eb54.png)

**Comment by kevmoo** [comment]
CC @jcollins-g RE https://github.com/dart-lang/dartdoc
CC  @srawlins RE  https://github.com/dart-lang/markdown
And @isoos RE pub site

I hate to create another package – but maybe we need another package.

Or we could include a helper/asset in https://github.com/dart-lang/markdown that includes some default styles?

**Comment by srawlins** [comment]
What motivated this? The alternating table backgrounds, and borders, popped out to me.

Can pub-dartlang-dart include a build step that git clones [primer-markdown](https://github.com/primer/primer/tree/master/modules/primer-markdown), builds it using [dart-sass](https://github.com/sass/dart-sass), and ships the resulting single CSS file as part of pub.dartlang.org?

Or, checkin the CSS file into git, and have an update script that does the thing I said?

```sh
git clone primer-markdown
cd primer-markdown
pub global run sass .
cp whatever.css something-else.css
git add something-else.css
```

**Comment by kevmoo** [comment]
> What motivated this? The alternating table backgrounds, and borders, popped out to me.

Yup. Also, I've done a number of tweaks to the css on both the package site and dartdoc. It'd be good to find a source of truth we all like and then just tweak one set of styles.

**Comment by kevmoo** [comment]
CC @kwalrath @chalin – FYI. We might ponder more consistency w/ *.dartlang.org, too!

**Comment by chalin** [comment]
FYI *.dartlang.org currently use Bootstrap 3. Bootstrap 4 should be released soon (it is in its [final beta](http://blog.getbootstrap.com)).

**Comment by kevmoo** [comment]
> FYI *.dartlang.org currently use Bootstrap 3. Bootstrap 4 should be released soon (it is in its final beta).

At least for styling the content of markdown/code, sticking w/ GitHub would be a good idea, I think

**Comment by srawlins** [comment]
Do we compile bootstrap from Sass? Or just take the CSS? Seems like
primer-markdown might fit into a build system quite snugly...

**Comment by jcollins-g** [comment]
If we want to have consistent formatting with the SDK documentation it's probably better for dartdoc to include it.  We'll have to be sure that it doesn't conflict with any of flutter's custom styles but that shouldn't be too hard.

**Comment by isoos** [comment]
I'm closing this, because our side is done for now. When `dartdoc` includes the style, we'll detect it through our tests, and will update the customization to remove the extra style we are adding in #1638.
