### ISSUE TITLE
Should add OpenGraph items to pages, too

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#885]
I hate duplicating content, but it seems folks like Twitter want it

https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

**Comment by kevmoo** [comment]
Still missing `og:image` – required to show cards pretty on twitter https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

**Comment by kevmoo** [comment]
...make sure it's an absolute URI cc @isoos

**Comment by isoos** [comment]
> ...make sure it's an absolute URI

The plan is to use (1) absolute URL or (2) the output of https://github.com/dart-lang/pana/pull/221 on relative urls. The later will return null if we don't have a proper repository URL, and we never use relative ones in the output.

**Comment by kevmoo** [comment]
I thought we'd just go w/ the Dart logo for now – since figuring out the right image may be tough

CC @mit-mit

**Comment by isoos** [comment]
The heuristics is not too hard to implement, e.g.:
- the first image, or
- the first large-enough image, or
- the largest image.

The first method doesn't even require us to fetch the images e.g. during analysis, although a badge-provider blacklist may be needed. The other two is not that hard either.

**Comment by kevmoo** [comment]
What about badges?

https://github.com/dart-lang/fixnum/blob/2d95f7d21690be6f077128f6bd5c29d875f71fee/README.md

**Comment by isoos** [comment]
> What about badges?

They have easy-to-blacklist patterns.

**Comment by kevmoo** [comment]
Or maybe only allow images from the homepage URL?

I'm nervous about guessing here...

**Comment by isoos** [comment]
> I'm nervous about guessing here...

We can also have an additional `logo:` property in `pubspec.yaml` which overrides our guessing.

**Comment by kevmoo** [comment]
But then we need to document it :-)

I'd love to just fix the missing image using the default logo. Just so
sharing looks a bit better.

Then ya'll can design the right solution for custom images. :-)

**Comment by isoos** [comment]
> I'd love to just fix the missing image using the default logo. Just so sharing looks a bit better.

That is already the case with Facebook:
<img width="488" alt="screen shot 2018-01-12 at 10 57 48 pm" src="https://user-images.githubusercontent.com/4778111/34896986-294e2bee-f7ec-11e7-8edc-1527981d2f76.png">

Although Google+ is weirdly white.

**Comment by kevmoo** [comment]
Twitter as well...
