### ISSUE TITLE
analyzer invalidating memcache keys even when no work is done

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#887]
<img width="1637" alt="screen shot 2018-01-05 at 4 01 03 pm" src="https://user-images.githubusercontent.com/17034/34633540-9e0664f8-f231-11e7-953f-4470f7f1b649.png">

**Comment by isoos** [comment]
#898 handles one part of this, but I'm not sure how the skipped task could trigger the invalidation. I suspect this may be related to #896 too, and the additional logging should reveal it.

**Comment by isoos** [comment]
This looks fixed with the latest deployment.
