### ISSUE TITLE
packages that depend on a packge web page broken for all packages

### ISSUE THREAD

**Issue by gedw99** [dart-lang/pub-dartlang-dart#891]
for example:

https://pub.dartlang.org/packages/web_socket_channel

then choose the hyperlinekd text: "Packages that depend on web_socket_channel", which navigates to:
https://pub.dartlang.org/packages?q=dependency%3Aweb_socket_channel

**Comment by isoos** [comment]
Thanks for reporting it, looks like we have a NPE in the rendering of that page, fix will be coming shortly.
