### ISSUE TITLE
Pub server should enforce dependencies by hosted

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#908]
URL: https://pub.dartlang.org/packages/twitter/versions/0.4.0

This version has a dependency on a git repo.

It seems that the pub client only excludes path deps, not git.

Should the site require all packages (well, everything in `dependencies:`) also be hosted on pub.dartlang.org?

**Comment by kevmoo** [comment]
Thoughts, @nex3 ?

**Comment by nex3** [comment]
We intentionally allow Git dependencies during `pub lish`, although we do produce a warning about them. We don't want to artificially restrict what people can do—as long as a dependency is portable from machine to machine, users should be able to publish packages that use that dependency. Especially now that we have mechanisms for rating packages, I think it makes sense to be liberal in what we allow people to publish and rely on usability ratings to sort out the good from the bad.

**Comment by isoos** [comment]
`pana` could detect it and (1) reduce the maintenance score (2) add a suggestion about the dependency.

**Comment by mit-mit** [comment]
Closing as won't fix under the assumption that this happens very infrequently.
