### ISSUE TITLE
Getting the Package built_value problem.

### ISSUE THREAD

**Issue by diabolus** [dart-lang/pub-dartlang-dart#909]
URL: https://pub.dartlang.org/packages/built_value#-versions-tab-

I tried to add the library to my project by adding following line to dependencies 
`built_value: "^4.6.0"`
but got an error;
`Package built_value has no versions that match >=4.6.0 <5.0.0 derived from:`

**Comment by kevmoo** [comment]
@diabolus – figure it out?

**Comment by diabolus** [comment]
@kevmoo Yes, it is a dependency conflict between packages.
`dependency_overrides` solved it for now. 

Thanks.

**Comment by kevmoo** [comment]
Awesome
