### ISSUE TITLE
Request: Set a 'flutter-plugin' tag when publishing a Flutter Plugin package

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#91]
Flutter plugins are special Dart package that also contain Android and iOS platform-specific code.

Flutter plugins can be identified by having the following value in their `pubspec.yaml` file:
```
flutter:
  plugin:
```

When these packages are published, we request that a tag `flutter-tag` is set in their metadata. This tag needs to be easily queryable so that we can for example at some point restrict specific searches on pub.dartlang.org to only display packages that have this tag.

**Comment by isoos** [comment]
This is already done, and the issue can be closed: the `detectedTypes` field contains `flutter_plugin` if the pubspec contains the two entries mentioned above.

**Comment by mit-mit** [comment]
@isoos any way testing this; I mean, is there some way to see (either on the plugin page, by searching, etc.) packages that have this field set?

**Comment by isoos** [comment]
@mit-mit this is work in progress, but couple of pointers (not sure when the release happens):
- flutter icon on the package page: https://github.com/dart-lang/pub-dartlang-dart/pull/122
- list of flutter packages: https://github.com/dart-lang/pub-dartlang-dart/pull/117

Search is harder/tricky, will update the other opened issue when it is ready.

**Comment by mkustermann** [comment]
The original issue has been resolved: Published packages will get detected as flutter plugins and the information is surfaced on the web ui.
