### ISSUE TITLE
new Versions page: add a anchor link to dev releases at the top

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#913]
For `packages/<pkg>/versions`

If there are dev releases, provide a anchor link to navigate there – aid discovery...

Even better: put in text like "latest dev release was 1.0.0-dev on Jan 6" or something?

**Comment by mit-mit** [comment]
I'm not sure I follow, can you elaborate?

**Comment by mit-mit** [comment]
cc @kevmoo can you elaborate?

**Comment by kevmoo** [comment]
if the dev releases for a package are "below the fold" on a page, knowing there are dev releases and being able to jump to them might be nice.
