### ISSUE TITLE
Search support for filtering by package platform support

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#92]
In https://github.com/dart-lang/pub-dartlang-dart/issues/91 we requested support for a `flutter-plugin` tag.

With that added, we request support for a new query parameter in search that restricts the search to only packages having the `flutter-plugin` tag, e.g.:

https://pub.dartlang.org/search?q=foo&tag=flutter-plugin

It should also be allowed to only specify this tag to see all plugins (as initially there will be quite few):
https://pub.dartlang.org/search?tag=flutter-plugin

**Comment by mit-mit** [comment]
@isoos what is the status of this?

**Comment by isoos** [comment]
I've sent a mail about this on May 15, I guess it was lost in the ramp-up of I/O, in short:
- URLs like this work: https://pub.dartlang.org/search?q=url&type=flutter_plugin
- we don't expose it because:
  - (a) there are only a few flutter packages at the moment
  - (b) the flutter icon is visible in the normal search results
  - (c) I believe we shall first have a few more type classification (e.g. for angular, dart:html, dart:io), so that a checkbox or dropdown makes sense on the UI.

**Comment by mit-mit** [comment]
The search results appear to be missing entries. For example https://pub.dartlang.org/search?q=firebase&type=flutter_plugin shows just three plugins while we have at least five: https://pub.dartlang.org/flutter/plugins

**Comment by isoos** [comment]
This is a limitation of the search backend we are using: Google Custom Search may not index all of the packages we have :(
I'll write a script to check whether only the recent ones are missing or we have a few ones that are not in the index at all.

**Comment by isoos** [comment]
8.16% of the packages are not easily found and probably missing from the search index. AFAICT the recency of the package doesn't matter too much, my random sampling showed the full range.

**Comment by mit-mit** [comment]
Great analysis @isoos, thanks!

**Comment by mit-mit** [comment]
Updating title. As per https://github.com/dart-lang/pub-dartlang-dart/issues/143#issuecomment-305508387, this should search for both `flutter_package` or `flutter_plugin`.

**Comment by kevmoo** [comment]
Related to https://github.com/dart-lang/pub-dartlang-dart/issues/39

**Comment by mit-mit** [comment]
@kevmoo did you mention earlier this week that this is now supported?

**Comment by isoos** [comment]
> this is now supported?

The capability is there, the question is: which definition of 'platform' are we going to use? (e.g. What's up with packages that support multiple ones, but not in all of their libraries? Are we going to use the superset or the subset of the files?)

**Comment by isoos** [comment]
Status update.

Most of it is implemented and deployed end-to-end now:
- packages are analyzed with `pana`, creating (among other things) the platform classification
- search index is populated with this data
- web frontend queries and displays it

However, the end-user search form does not uses it yet, soon to be done when we'll get the new design.

**Comment by kevmoo** [comment]
@isoos – how close are we here?

**Comment by isoos** [comment]
V2 design already works on this, we can close.
