### ISSUE TITLE
Consider increasing max_num_instances for analyzer

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/pub-dartlang-dart#927]
Currently set to 8. When we deploy a new version of pana, and need to re-analyze all packages, it currently takes 2-3 days (estimated). We could consider increasing max_num_instances to finish this processing faster.

**Comment by mit-mit** [comment]
Back to on-deck, we resolved a few issues and are much faster now

**Comment by isoos** [comment]
I believe this is no longer necessary.
