### ISSUE TITLE
Prevent punctuation variations of package names

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub-dartlang-dart#929]
Prior art is NPM: https://twitter.com/jawache/status/953794118483922944

i.e. you could not publish `package:codebuilder` if there is already a `package:code_builder`.

**Comment by isoos** [comment]
Packages from the same author:
- [LoadingBox](https://pub.dartlang.org/packages/LoadingBox), [loading_box](https://pub.dartlang.org/packages/loading_box)
- [ViAuthClient](https://pub.dartlang.org/packages/ViAuthClient), [vi_auth_client](https://pub.dartlang.org/packages/vi_auth_client)
- [_test_](https://pub.dartlang.org/packages/_test_), [test](https://pub.dartlang.org/packages/test)
- [fast_chemail](https://pub.dartlang.org/packages/fast_chemail), [fastchemail](https://pub.dartlang.org/packages/fastchemail)
- [google_freebase_v1_sandbox_api](https://pub.dartlang.org/packages/google_freebase_v1_sandbox_api), [google_freebase_v1sandbox_api](https://pub.dartlang.org/packages/google_freebase_v1sandbox_api)

Packages with **different authors**:
- [bulls_eye](https://pub.dartlang.org/packages/bulls_eye), [bullseye](https://pub.dartlang.org/packages/bullseye)
- [event_source](https://pub.dartlang.org/packages/event_source), [eventsource](https://pub.dartlang.org/packages/eventsource)
- [google_cloud_datastore](https://pub.dartlang.org/packages/google_cloud_datastore), [googleclouddatastore](https://pub.dartlang.org/packages/googleclouddatastore)
- [js_proxy](https://pub.dartlang.org/packages/js_proxy), [jsproxy](https://pub.dartlang.org/packages/jsproxy)
- [json_rpc_2](https://pub.dartlang.org/packages/json_rpc_2), [jsonrpc2](https://pub.dartlang.org/packages/jsonrpc2)
- [mimetypes](https://pub.dartlang.org/packages/mimetypes), [mime_types](https://pub.dartlang.org/packages/mime_types)
- [pathfinding](https://pub.dartlang.org/packages/pathfinding), [path_finding](https://pub.dartlang.org/packages/path_finding)
- [polymer_date_picker](https://pub.dartlang.org/packages/polymer_date_picker), [polymer_datepicker](https://pub.dartlang.org/packages/polymer_datepicker)
- [pubsub](https://pub.dartlang.org/packages/pubsub), [pub_sub](https://pub.dartlang.org/packages/pub_sub)
- [state_machine](https://pub.dartlang.org/packages/state_machine), [statemachine](https://pub.dartlang.org/packages/statemachine)
- [telegram_bot](https://pub.dartlang.org/packages/telegram_bot), [telegrambot](https://pub.dartlang.org/packages/telegrambot)
- [u_til](https://pub.dartlang.org/packages/u_til), [util](https://pub.dartlang.org/packages/util)
- [xmlrpc](https://pub.dartlang.org/packages/xmlrpc), [xml_rpc](https://pub.dartlang.org/packages/xml_rpc)

**Comment by isoos** [comment]
While we have these conflicts, I believe we could move ahead of restricting **new** packages and not allow them if there is any name collision.

The key would be to have a specialized class (NameTracker?) that polls the Datastore for new uploads, and keeps track of the package names. When there is a new upload, we shall quickly check against this list, and allow only when (a) it already exists or (b) it has no collision. 

We have a similar setup in the [dependency graph](https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/shared/deps_graph.dart), where we build it on upload, and also poll the Datastore in every 10 seconds (?). I wouldn't put extra features in that, rather go with the class of the separate concern.

While this wouldn't prevent every race scenario (e.g. packages being uploaded in a short window of a minute at most), it would do a decent job to prevent typosquatting.

@jakobr-google: sounds acceptable?

**Comment by matanlurey** [comment]
_Excited!_
