### ISSUE TITLE
Don't show path deps in dev_dependencies

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#933]
URL: https://pub.dartlang.org/packages/build_web_compilers#-analysis-tab-

![screen shot 2018-01-18 at 3 50 15 pm](https://user-images.githubusercontent.com/17034/35127523-5692b4b0-fc67-11e7-8b79-029b4ae2c709.png)

**Comment by isoos** [comment]
I think here we need to link only the hosted packages here, but still show both git and path dependencies.

**Comment by kevmoo** [comment]
> I think here we need to link only the hosted packages here, but still show both git and path dependencies.

Reasonable
