### ISSUE TITLE
Tooltips for package category tags

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#936]
Before we publish the 'server'->'other' change, I think we need to add tooltips on the package category tags to explain what 'other' is. I suggest:

  * Flutter: "Compatible with the Flutter framework'
  * Web: "Compatible with web frameworks"
  * Other: "Compatible with other platforms (terminal, server, etc.)"

**Comment by mit-mit** [comment]
cc @isoos this would be a really small change, right? cc @jakobr-google

**Comment by isoos** [comment]
I've updated https://github.com/dart-lang/pub-dartlang-dart/pull/934 with a commit that does this. (cc @jakobr-google), also available on [staging](https://dartlang-pub-dev.appspot.com/)

**Comment by mit-mit** [comment]
Thanks much @isoos !

**Comment by isoos** [comment]
Implemented and deployed.
