### ISSUE TITLE
Search isn't finding text inside READMEs, or, too literal with hyphens

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#962]
I searched for "in app payments" and it found nothing:

![screen shot 2018-02-05 at 1 16 18 pm](https://user-images.githubusercontent.com/5479/35829172-d750fc98-0a76-11e8-94a9-51868918e983.png)

Then I tried IAP and found this:

![screen shot 2018-02-05 at 1 16 24 pm](https://user-images.githubusercontent.com/5479/35829183-e0568056-0a76-11e8-826d-cd26037e29f4.png)

And then I clicked the top link, and "in-app payments" is in the README:

![screen shot 2018-02-05 at 1 16 28 pm](https://user-images.githubusercontent.com/5479/35829198-ed4e6134-0a76-11e8-8126-c3c51936374c.png)

**Comment by isoos** [comment]
After a bit of investigation (e.g. searching for `app payments` works), I realised that we remove bigrams and unigrams, while we should only skip them if they are inside of a larger word. #984 fixes this, also adding test specifically for this use-case.
