### ISSUE TITLE
Search box isn't platform specific when on a package for a single platform

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#974]
The search box works confusingly in the following interaction:

1. Go to the front page of Pub
1. Click Flutter as you are Flutter developers
1. Click one of the packages in top-20
1. Decide that was the wrong one, and enter a search term in the search box

This turns into a general search, not a Flutter search. I would think the user would expect the latter.

**Comment by mit-mit** [comment]
Suggestion: If on a package page, and if that package page supports just one of our specialized platforms (Flutter, and Web), and change the search field into a Flutter/Web specific search field (like the one on the flutter/web landing pages)

**Comment by mit-mit** [comment]
cc @isoos WDUT?

**Comment by isoos** [comment]
Sounds reasonable and not too hard to do.

**Comment by isoos** [comment]
A demo on staging: https://20180212t171521-dot-dartlang-pub-dev.appspot.com/packages/webdriver
