### ISSUE TITLE
Expose release time through https://pub.dartlang.org/api

### ISSUE THREAD

**Issue by grouma** [dart-lang/pub-dartlang-dart#979]
We currently expose the various versions through the API. It would also be useful to have the date and time the version was released.

**Comment by isoos** [comment]
AFAICT these should be modified in the `pub_server` project. We delegate these API calls to `ShelfPubServer`, and timestamp could be added probably in the following locations:
- https://github.com/dart-lang/pub_server/blob/master/lib/shelf_pubserver.dart#L282
- https://github.com/dart-lang/pub_server/blob/master/lib/shelf_pubserver.dart#L236

**Comment by isoos** [comment]
This issue was moved to dart-lang/pub_server#14
