### ISSUE TITLE
Skip generation of dartdocs for flutter

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#986]
We currently have dartdocs for flutter: https://www.dartdocs.org/documentation/flutter/0.0.6/index.html. However, for flutter we would like to just have docs on https://docs.flutter.io/

Can we have a blacklist or something like that for packages that should not have dartdocs?

**Comment by isoos** [comment]
On top of blacklisting, I think it would be worth to redirect `www.dartdocs.org/documentation/flutter/[version]/*` to `docs.flutter.io/*`.

**Comment by mit-mit** [comment]
Agreed

**Comment by mit-mit** [comment]
After discussion, we won't do a blacklist now, but rather just redirect all requests to ` https://www.dartdocs.org/documentation/flutter/*` to `https://docs.flutter.io/`
