### ISSUE TITLE
Discontinue stale dart-lang packages

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#991]
With the new support from https://github.com/dart-lang/pub-dartlang-dart/issues/289, we should determine what ww actually want to mark discontinued.

**Comment by mit-mit** [comment]
Sample test package marked deprecated: https://dartlang-pub-dev.appspot.com/packages/owl_example

**Comment by devoncarew** [comment]
`compiler_unsupported`

**Comment by srawlins** [comment]
Shouldn't this be a one-to-one mapping with all the projects in [dart-archive](https://github.com/dart-archive)?

Although, additionally, [typed_mock](https://pub.dartlang.org/packages/typed_mock).

**Comment by mit-mit** [comment]
> Shouldn't this be a one-to-one mapping with all the projects in dart-archive?

I'd rather have individual that know the individual packages comment on that.

**Comment by srawlins** [comment]
Ah, ok. I'd like to add [mock](https://pub.dartlang.org/packages/mock), [route](https://pub.dartlang.org/packages/route), [route_hierarchical](https://pub.dartlang.org/packages/route_hierarchical), [unittest](https://pub.dartlang.org/packages/unittest).

**Comment by matanlurey** [comment]
+1 Sam's suggestion: anything in dart-archive/**. 

I'd go further and add the following packages:

* `benchmark_harness` (last updated 2015)
* `shelf_rpc` (last updated 2015)
* `instrumentation_client` (last updated 2015)

Others not mentioned above yet:

* `di`
* `scheduled_test`
* `template_binding`
* `initialize`
* `polymer_elements`
* `polymer_interop`
* `web_components`
* `polymer`
* `core_elements`
* `polymer_expressions`

I'd also like to see all of the barback-related packages:

(These aren't archived, yet, but they should be, or at least deprecated)

* `barback`
* `transformer_test`

**Comment by mit-mit** [comment]
@kevmoo I believe you moved things to https://github.com/dart-archive, can you confirm that everything there can be marked discontinued in Pub?

**Comment by nshahan** [comment]
Please discontinue [angular2_components](https://pub.dartlang.org/packages/angular2_components) and [angular2_material](https://pub.dartlang.org/packages/angular2_material).

**Comment by kevmoo** [comment]
@devoncarew @srawlins @nshahan @matanlurey – all of your suggestions were moved into the tracking sheet. Clearing out here to minimize duplication and confusion.

**Comment by mit-mit** [comment]
From discussion, the following are ready to be discontinued:

angular2
angular2_components
angular2_material
core_elements
custom_element_apigen
dev_compiler
di
func
html5lib
initialize
json
metatest
mock
ng2soyc
observe?
paper_elements
polymer
polymer_elements
polymer_expressions
polymer_interop
route
route_hierarchical
scheduled_test
shelf_rpc
smoke
template_binding
test_runner
tracing
typed_mock
unittest

**Comment by mit-mit** [comment]
This bug has been handed over to engineering. For additional 'discontinue' requests, please file new bugs!

**Comment by jakobr-google** [comment]
The listed packages have all been marked discontinued.
