### ISSUE TITLE
Static front page for new dartdoc.org landing page

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#994]

**Comment by mit-mit** [comment]
Let's do something super basic similar to:
http://download.dartlang.org/

Quick mockup:

---------------------------------

`<Dart logo>`
### Dart package API docs
API documentation for a package published on the [Pub package manager](https://pub.dartlang.org/), is available via the **Documentation** link located on any individual package page on Pub.

**Comment by mit-mit** [comment]
cc @jakobr-google @isoos WDYT?

**Comment by isoos** [comment]
SGTM
